import { expansionBank } from "../expansion-helpers";
import type { ItemFigure } from "@/lib/content/types";
const { mc: M, written: W } = expansionBank("u2-kinematics", "u2");
const L = String.raw;
const vectorFigure: ItemFigure = {
  type: "svg", title: "Two measured displacement vectors",
  description: "A and B start at the origin on equally scaled metre axes. A ends at (3,2), B at (-2,3).",
  svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 560 360" role="img">
  <rect width="560" height="360" fill="white"/>
  <defs><marker id="vector-tip" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="context-stroke"/></marker></defs>
  <g font-family="Arial, sans-serif" font-size="18" fill="#172033">
  ${[-4,-3,-2,-1,0,1,2,3,4].map(n => `<line x1="${260+40*n}" x2="${260+40*n}" y1="100" y2="300" stroke="#dce3ec"/><text x="${260+40*n}" y="325" text-anchor="middle">${n}</text>`).join("")}
  ${[-1,0,1,2,3,4].map(n => `<line x1="100" x2="420" y1="${260-40*n}" y2="${260-40*n}" stroke="#dce3ec"/><text x="86" y="${266-40*n}" text-anchor="end">${n}</text>`).join("")}
  <line x1="100" x2="432" y1="260" y2="260" stroke="#334155" stroke-width="2"/>
  <line x1="260" x2="260" y1="300" y2="80" stroke="#334155" stroke-width="2"/>
  <text x="444" y="266">x (m)</text><text x="269" y="80">y (m)</text>
  <line x1="260" y1="260" x2="380" y2="180" stroke="#2563eb" stroke-width="3" marker-end="url(#vector-tip)"/>
  <line x1="260" y1="260" x2="180" y2="140" stroke="#16803a" stroke-width="3" marker-end="url(#vector-tip)"/>
  <text x="393" y="174">A</text><text x="156" y="131">B</text>
  </g></svg>`,
};

export const planeExpansion = [
  M("2.3",101,2,L`Displacements are $\vec a=(2\hat i-\hat j)\,\mathrm{m}$ and $\vec b=(-5\hat i+3\hat j)\,\mathrm{m}$. Their resultant magnitude is`,L`$\sqrt{13}\,\mathrm{m}$`,[
    [L`$\sqrt{65}\,\mathrm{m}$`,"This comes from subtracting the vectors rather than adding them."],[L`$5\,\mathrm{m}$`,"Add signed rectangular components before finding magnitude."],[L`$\sqrt5+\sqrt{34}\,\mathrm{m}$`,"Adding magnitudes is valid only for parallel vectors in the same direction."]],
    L`$\vec a+\vec b=(-3\hat i+2\hat j)\,\mathrm{m}$, whose magnitude is $\sqrt{(-3)^2+2^2}=\sqrt{13}\,\mathrm{m}$.`,["Add x components and y components separately.","Keep the negative x component.","Use the sum of squared components."]),
  M("2.3",102,2,L`A unit vector along $8\hat i-15\hat j$ is`,L`$\dfrac{8\hat i-15\hat j}{17}$`,[
    [L`$\dfrac{8\hat i-15\hat j}{23}$`,"The vector's magnitude is not the sum of component magnitudes."],[L`$\dfrac{8\hat i+15\hat j}{17}$`,"This changes the direction by changing a component's sign."],[L`$17(8\hat i-15\hat j)$`,"Normalising requires division by the magnitude."]],
    L`The magnitude is $\sqrt{64+225}=17$. Dividing the vector by 17 preserves direction and gives magnitude one.`,["Find the original vector's magnitude.","Divide both components by that magnitude.","Check that the squared components of the unit vector sum to one."]),
  M("2.3",103,2,"Two non-zero vectors add to zero. Which statement is necessary?","They have equal magnitudes and opposite directions.",[
    ["They are perpendicular.","Perpendicular non-zero vectors cannot cancel."],["They have equal magnitudes, irrespective of direction.","Equal magnitudes alone are not sufficient."],["Their magnitudes must both be zero.","Non-zero opposite vectors can cancel."]],
    L`$\vec a+\vec b=0$ implies $\vec b=-\vec a$, which fixes both equal magnitudes and opposite directions.`,["Rearrange the vector equation.","Interpret a negative vector.","Magnitude and direction are both relevant."]),
  M("2.3",104,2,"Two vectors have magnitudes 5 and 7 in the same units. Which resultant magnitude is impossible?","13",[
    ["2","Opposite directions give the minimum magnitude 7-5=2."],["7","This lies between the minimum and maximum and is attainable."],["12","Parallel vectors in the same direction give 5+7=12."]],
    "The possible resultant magnitude lies between |7-5|=2 and 7+5=12 inclusive. Therefore 13 is impossible.",["Find the smallest resultant for opposite directions.","Find the largest for equal directions.","Test each proposed value against this interval."]),
  M("2.3",105,3,L`Two non-zero vectors each have magnitude A. Their sum also has magnitude A. The angle between them is`,L`$120^\circ$`,[
    [L`$60^\circ$`,L`This gives resultant magnitude $\sqrt3 A$.`],[L`$90^\circ$`,L`This gives resultant magnitude $\sqrt2 A$.`],[L`$180^\circ$`,"This gives zero resultant."]],
    L`$A^2=A^2+A^2+2A^2\cos\theta$ gives $\cos\theta=-1/2$, so $\theta=120^\circ$.`,["Use the cosine formula for a vector sum.","Divide by A squared, which is non-zero.","Find the angle with cosine negative one-half."]),
  M("2.3",106,2,L`A vector of magnitude $6\,\mathrm{m}$ makes an angle $150^\circ$ anticlockwise from the positive x-axis. Its components are`,L`$(-3\sqrt3,\ 3)\,\mathrm{m}$`,[
    [L`$(3\sqrt3,\ 3)\,\mathrm{m}$`,"The vector lies in the second quadrant, so x must be negative."],[L`$(-3,\ 3\sqrt3)\,\mathrm{m}$`,"This exchanges the sine and cosine components."],[L`$(-3\sqrt3,\ -3)\,\mathrm{m}$`,"The y component is positive in the second quadrant."]],
    L`$a_x=6\cos150^\circ=-3\sqrt3\,\mathrm{m}$ and $a_y=6\sin150^\circ=3\,\mathrm{m}$.`,["Identify the quadrant before calculating.","Use cosine for the x component.","Use sine for the y component."]),
  M("2.3",107,2,L`A displacement has components $(-4,7)\,\mathrm{m}$ in stationary rectangular axes. If the coordinate origin is translated but the axes keep their directions, these components`,"remain unchanged",[
    ["both increase by the origin shift","Individual position coordinates shift; differences between them do not."],["become positive","Changing origin does not change axis orientation."],["cannot be found without the new origin","The constant origin shift cancels from a displacement."]],
    L`A displacement is $\vec r_2-\vec r_1$. Subtracting the same origin-shift vector from both positions leaves this difference unchanged.`,["Write displacement as the difference of two positions.","Shift both positions by the same vector.","Cancel the common shift."]),
  M("2.3",108,2,L`Assertion (A): Multiplying a non-zero vector by $-2$ reverses its direction. Reason (R): The magnitude of the new vector is negative.`,"A is true, but R is false.",[
    ["Both are true and R explains A.","A vector magnitude cannot be negative."],["Both are true but R does not explain A.","The reason is false, not just an incorrect explanation."],["A is false, but R is true.","A negative scalar reverses direction while the magnitude stays non-negative."]],
    L`The new magnitude is $|-2|\,|\vec a|=2|\vec a|$. The sign of the scalar reverses direction, not the sign of the magnitude.`,["A magnitude is a non-negative scalar.","Use the absolute value of the multiplier for magnitude.","The negative sign acts on direction."]),
  M("2.4",101,2,L`A projectile is launched at $20\,\mathrm{m\,s^{-1}}$ at $60^\circ$ to the horizontal. Ignoring air resistance, its speed at the highest point is`,L`$10\,\mathrm{m\,s^{-1}}$`,[
    [L`$0\,\mathrm{m\,s^{-1}}$`,"Only the vertical component vanishes at the highest point."],[L`$10\sqrt3\,\mathrm{m\,s^{-1}}$`,"This is its initial vertical component."],[L`$20\,\mathrm{m\,s^{-1}}$`,"The vertical component changes under gravity."]],
    L`At the top $v_y=0$ but $v_x=20\cos60^\circ=10\,\mathrm{m\,s^{-1}}$ is unchanged.`,["Resolve the launch velocity.","At the top only the vertical component is zero.","The remaining speed equals the horizontal component."]),
  M("2.4",102,3,L`A projectile has initial components $(15,20)\,\mathrm{m\,s^{-1}}$. With upward positive and $g=10\,\mathrm{m\,s^{-2}}$, its speed at $t=3\,\mathrm{s}$ is`,L`$5\sqrt{13}\,\mathrm{m\,s^{-1}}$`,[
    [L`$25\,\mathrm{m\,s^{-1}}$`,"This is the initial speed, not the speed at 3 s."],[L`$5\,\mathrm{m\,s^{-1}}$`,"Do not add the perpendicular signed components as scalars."],[L`$35\,\mathrm{m\,s^{-1}}$`,"Gravity changes only the vertical component, with a negative sign here."]],
    L`$v_x=15$, $v_y=20-10(3)=-10\,\mathrm{m\,s^{-1}}$. Speed $=\sqrt{15^2+(-10)^2}=5\sqrt{13}\,\mathrm{m\,s^{-1}}$.`,["Keep horizontal velocity unchanged.","Update vertical velocity with gravity.","Take the magnitude of the velocity vector."]),
  M("2.4",103,3,L`A projectile is launched obliquely above horizontal ground and lands at its launch level. Its maximum height is $H$ and range is $R$. If $R=4H$, the launch angle is`,L`$45^\circ$`,[
    [L`$30^\circ$`,L`This gives $4H/R=1/\sqrt3$, not 1.`],[L`$60^\circ$`,L`This gives $4H/R=\sqrt3$.`],[L`$90^\circ$`,"A vertical launch has zero horizontal range."]],
    L`$4H/R=4[u^2\sin^2\theta/(2g)]/[u^2\sin2\theta/g]=\tan\theta$. Thus $\tan\theta=1$, giving $45^\circ$.`,["Write the height and range formulae.","Form their ratio so speed and g cancel.","Use the double-angle identity for sine."]),
  M("2.4",104,2,"For level-ground projectile motion without air resistance, the launch speed is doubled at the same angle and g. Both range and maximum height are multiplied by","4",[
    ["2","Time of flight doubles, but range and height depend on speed squared."],["8","Neither range nor maximum height contains speed cubed."],["1","Both quantities depend on launch speed."]],
    L`At fixed angle and $g$, both $R=u^2\sin2\theta/g$ and $H=u^2\sin^2\theta/(2g)$ are proportional to $u^2$.`,["Hold the angle constant.","Inspect the speed dependence in both formulae.","Square the speed-change factor."]),
  M("2.4",105,2,"A ball is dropped and another projected horizontally from the same height at the same instant. Neglect air resistance. Before either hits the ground, they have the same","vertical displacement at every elapsed time",[
    ["total speed at every elapsed time","The horizontally launched ball has an additional horizontal velocity component."],["horizontal displacement","Only one ball has horizontal motion."],["velocity vector","Their horizontal velocity components are different."]],
    L`Both start with $u_y=0$ and have the same $a_y=-g$, so their vertical displacement is $-gt^2/2$ at the same elapsed time.`,["Compare only the vertical initial conditions.","Horizontal motion does not change vertical acceleration.","Equal vertical displacement does not imply equal velocity vectors."]),
  M("2.4",106,3,L`A ball is thrown horizontally at $6\,\mathrm{m\,s^{-1}}$ from a height of $45\,\mathrm{m}$. For $g=10\,\mathrm{m\,s^{-2}}$, its impact speed is`,L`$6\sqrt{26}\,\mathrm{m\,s^{-1}}$`,[
    [L`$30\,\mathrm{m\,s^{-1}}$`,"This omits the horizontal component."],[L`$36\,\mathrm{m\,s^{-1}}$`,"Perpendicular components are not added arithmetically."],[L`$18\,\mathrm{m\,s^{-1}}$`,"This is the horizontal range numerically, not a speed."]],
    L`Fall time is $3\,\mathrm{s}$, giving downward speed $30\,\mathrm{m\,s^{-1}}$. Impact speed $=\sqrt{6^2+30^2}=6\sqrt{26}\,\mathrm{m\,s^{-1}}$.`,["Find time from the vertical fall.","Determine vertical velocity at impact.","Combine perpendicular velocity components by Pythagoras."]),
  M("2.4",107,2,L`A boat moves due north relative to the water at $8\,\mathrm{m\,s^{-1}}$, while the river flows east at $6\,\mathrm{m\,s^{-1}}$. Its direction relative to the ground makes an angle $\theta$ east of north satisfying`,L`$\tan\theta=3/4$`,[
    [L`$\tan\theta=4/3$`,"This ratio corresponds to an angle measured north of east, not east of north."],[L`$\tan\theta=7$`,"Add velocities as vectors, not as scalar components along the same line."],[L`$\tan\theta=0$`,"The current supplies a non-zero eastward component."]],
    L`Relative to the northward direction, opposite component is eastward 6 and adjacent is northward 8. Thus $\tan\theta=6/8=3/4$.`,["Write the north and east ground-velocity components.","Identify the direction from which the angle is measured.","Use east component divided by north component."]),
  M("2.4",108,3,L`A swimmer's speed relative to water is $4\,\mathrm{m\,s^{-1}}$ and the river current is $5\,\mathrm{m\,s^{-1}}$. Can the swimmer reach the directly opposite bank point by choosing a fixed heading?`,"No; the maximum upstream component is smaller than the current.",[
    ["Yes, by aiming straight across.","This leaves the full downstream current uncompensated."],["Yes, by pointing directly upstream.","The swimmer still drifts downstream and has no across-river component."],["Yes, because perpendicular speeds always cancel.","Cancellation requires equal opposite components, not perpendicular velocities."]],
    "Zero downstream ground velocity requires an upstream swimming component of 5 m/s. No component of a 4 m/s velocity can reach that value, so direct-opposite landing is impossible under this model.",["A direct-opposite landing requires zero net along-river motion.","An individual component cannot exceed the velocity magnitude.","Compare maximum upstream swimming speed with current speed."]),
  M("2.4",109,2,L`Two vehicles move at $9\,\mathrm{m\,s^{-1}}$ east and $12\,\mathrm{m\,s^{-1}}$ north. The magnitude of the first vehicle's velocity relative to the second is`,L`$15\,\mathrm{m\,s^{-1}}$`,[
    [L`$3\,\mathrm{m\,s^{-1}}$`,"Subtracting magnitudes is not valid for perpendicular velocities."],[L`$21\,\mathrm{m\,s^{-1}}$`,"Adding magnitudes assumes opposite collinear velocities."],[L`$108\,\mathrm{m\,s^{-1}}$`,"The product of speeds is not relative speed."]],
    L`$\vec v_{A/B}=9\hat i-12\hat j$, whose magnitude is $\sqrt{81+144}=15\,\mathrm{m\,s^{-1}}$.`,["Subtract velocity vectors.","Use east and north axes.","Take the magnitude after subtraction."]),
  M("2.4",110,2,L`Assertion (A): A projectile's acceleration is parallel to its velocity throughout its flight. Reason (R): Its acceleration is vertically downward throughout ideal flight near the Earth's surface.`,"A is false, but R is true.",[
    ["Both are true and R explains A.","For an oblique projectile the horizontal velocity component prevents parallelism throughout."],["Both are true but R does not explain A.","The assertion is false, not merely unrelated."],["A is true, but R is false.","The ideal acceleration is downward; the velocity direction varies."]],
    "Gravity keeps acceleration downward. An obliquely launched projectile has non-zero horizontal velocity, so its velocity need not align with gravity, including at the top where they are perpendicular.",["Consider an oblique projectile at its top.","Its velocity there is horizontal.","Its acceleration is still vertically downward."]),
  M("2.4",111,3,L`A projectile has horizontal velocity $10\,\mathrm{m\,s^{-1}}$ and initial vertical velocity $15\,\mathrm{m\,s^{-1}}$. For $g=10\,\mathrm{m\,s^{-2}}$, its trajectory, with launch at the origin, is`,L`$y=1.5x-0.05x^2$ in SI units`,[
    [L`$y=1.5x-0.5x^2$ in SI units`,"The quadratic coefficient contains the square of horizontal velocity."],[L`$y=15x-5x^2$ in SI units`,"This substitutes horizontal distance directly for time."],[L`$y=1.5x+0.05x^2$ in SI units`,"Gravity curves the trajectory downward, not upward."]],
    L`$x=10t$ gives $t=x/10$. Substitute into $y=15t-5t^2$ to obtain $y=1.5x-0.05x^2$.`,["Eliminate time using horizontal motion.","Substitute t=x/10 into the vertical equation.","Square the whole x/10 in the acceleration term."]),
  M("2.5",101,2,"Two points fixed on a uniformly rotating disc are at radii r and 3r. Their linear speeds are in the ratio","1:3",[
    ["1:1","Their angular speeds are equal, not their linear speeds."],["1:9","Linear speed is proportional to radius, not radius squared, at fixed angular speed."],["3:1","The outer point covers more distance in each revolution."]],
    L`Both points have the same $\omega$. Since $v=\omega r$, the speed ratio is $r:3r=1:3$.`,["A rigid disc gives both points the same revolution time.","Use v=omega times radius.","Compare radii directly."]),
  M("2.5",102,2,L`A particle moves uniformly around a circle. If speed triples while radius doubles, the centripetal acceleration changes by a factor of`,"9/2",[
    ["3/2","Acceleration contains speed squared."],["9/4","Radius appears to the first power in the denominator."],["6","The radius belongs in the denominator, not numerator."]],
    L`$a'_c/a_c=(3v)^2/(2r)\div(v^2/r)=9/2$.`,["Start from v squared divided by r.","Square the speed multiplier.","Divide by the radius multiplier."]),
  M("2.5",103,2,L`A particle moves anticlockwise at speed v on a circle. Its velocity changes from northward at the rightmost point to southward at the leftmost point after half a revolution. The magnitude of its velocity change is`,"2v",[
    ["0","The speeds match but the velocity directions are opposite."],[L`$\sqrt2 v$`,"This corresponds to perpendicular, not opposite, velocities."],["v","Subtracting two opposite equal vectors doubles their magnitude."]],
    L`Taking north positive, $\Delta\vec v=(-v)\hat j-v\hat j=-2v\hat j$, so its magnitude is $2v$.`,["Write the initial and final vectors.","Subtract the initial from the final.","Do not subtract speed magnitudes."]),
  M("2.5",104,2,L`A particle moves at constant speed on a circular path. Over one complete revolution its average velocity is`,"zero",[
    ["equal to its non-zero speed","Average velocity uses net displacement, which vanishes after a revolution."],["directed towards the centre","This describes instantaneous centripetal acceleration, not average velocity."],["tangent at the final point","That is the direction of instantaneous velocity, not the full-cycle average."]],
    "The final and initial positions coincide, so displacement is zero and average velocity over the non-zero period is zero.",["Compare starting and ending positions.","Average velocity uses displacement.","The path length is not the displacement."]),
  M("2.5",105,2,L`A particle at the northernmost point of a horizontal circular track moves clockwise when viewed from above. Its velocity and acceleration point respectively`,"east and south",[
    ["west and south","West is the tangent direction for anticlockwise motion at this point."],["east and north","Centripetal acceleration points inward, not outward."],["south and east","Velocity is tangential while acceleration is radial."]],
    "At the northernmost point clockwise motion is eastward. The centre lies south of that point, so acceleration is southward.",["Trace clockwise motion from the top point.","Velocity follows the tangent.","Acceleration points from the particle towards the centre."]),
  M("2.5",106,2,L`Assertion (A): In uniform circular motion the acceleration vector is constant. Reason (R): Its magnitude $v^2/r$ remains constant.`,"A is false, but R is true.",[
    ["Both are true and R explains A.","A constant vector needs constant direction as well as magnitude."],["Both are true but R does not explain A.","The acceleration direction rotates, so A is false."],["A is true, but R is false.","The magnitude does stay constant when v and r are constant."]],
    "The centripetal acceleration magnitude is fixed, but its inward direction changes continuously as the particle moves around the circle. Therefore the vector is not constant.",["Check both magnitude and direction.","The inward direction depends on the particle's location.","Constant magnitude does not imply a constant vector."]),
  W("2.3",101,"vsaq",2,L`A vector is $\vec p=-6\hat i+8\hat j$.`,[
    {prompt:"Find the vector of magnitude 5 pointing in the same direction.",answer:L`$|\vec p|=10$. The required vector is $(5/10)\vec p=-3\hat i+4\hat j$.`,marking:[L`Obtains $-3\hat i+4\hat j$.`]}],
    ["Find the magnitude of the given vector.","Normalise to obtain its direction.","Multiply the unit vector by five."],["Changing component signs while rescaling."]),
  W("2.3",102,"vsaq",2,L`A displacement vector has magnitude $10\,\mathrm{m}$ and x-component $-6\,\mathrm{m}$. Its y-component is positive.`,[
    {prompt:"Find its y-component.",answer:L`$a_y=+\sqrt{10^2-(-6)^2}=+8\,\mathrm{m}$.`,marking:["Gives +8 m using the specified sign."]}],
    ["Use magnitude squared as the sum of squared components.","Solve for the missing component squared.","Choose the positive square root as stated."],["Losing the sign condition when taking a square root."]),
  W("2.3",103,"vsaq",2,L`Two vectors have components $\vec a=(1,4)$ and $\vec b=(3,-2)$.`,[
    {prompt:L`Find $2\vec a-\vec b$.`,answer:L`$2\vec a-\vec b=(2,8)-(3,-2)=(-1,10)$.`,marking:["Gives components (-1,10)."]}],
    ["Multiply both components of a by two.","Subtract each component of b.","Subtracting its negative y-component adds two."],["Applying the factor two to only one component."]),
  W("2.3",104,"saq",2,L`A hiker walks $4\,\mathrm{km}$ east, $3\,\mathrm{km}$ north, and $4\,\mathrm{km}$ west.`,[
    {prompt:"Find the distance travelled and the resultant displacement.",answer:L`Distance is $4+3+4=11\,\mathrm{km}$. The east and west displacements cancel, leaving $3\,\mathrm{km}$ north.`,marking:["Gives distance 11 km.","Gives displacement 3 km north."]}],
    ["Distance adds all path lengths.","Combine east-west components with signs.","The remaining component determines displacement direction."],["Calling total path length the resultant displacement."]),
  W("2.3",105,"saq",3,L`Two vectors have equal magnitude $8\,\mathrm{N}$ and an included angle of $60^\circ$.`,[
    {prompt:"Find the magnitude and direction of their sum relative to either vector.",answer:L`$R=\sqrt{8^2+8^2+2(8)(8)\cos60^\circ}=8\sqrt3\,\mathrm{N}$. Equal magnitudes make the resultant bisect the angle, so it is $30^\circ$ from either vector.`,marking:[L`Obtains $8\sqrt3\,\mathrm{N}$.`,"Gives the internal angle-bisector direction, 30 degrees from either."]}],
    ["Use the cosine formula for the magnitude.","Exploit symmetry for direction.","The equal vectors contribute equally on either side of the bisector."],["Adding magnitudes as though the vectors were parallel."]),
  W("2.3",106,"laq",3,L`A drone's three successive displacements are $(6\hat i+2\hat j)$, $(-4\hat i+5\hat j)$ and $(\hat i-3\hat j)$ metres.`,[
    {prompt:"Find the resultant displacement, its magnitude, and a unit vector along it.",answer:L`Adding gives $(3\hat i+4\hat j)\,\mathrm{m}$, with magnitude $5\,\mathrm{m}$ and unit vector $(3\hat i+4\hat j)/5$.`,marking:["Obtains components (3,4) m.","Obtains magnitude 5 m.","Obtains the correct unit vector."]},
    {prompt:"Find the displacement required to return directly to the starting point, and distinguish its length from total distance already flown.",answer:L`Return displacement is $(-3\hat i-4\hat j)\,\mathrm{m}$ with length 5 m. Distance already flown is $\sqrt{40}+\sqrt{41}+\sqrt{10}\,\mathrm{m}$, the sum of individual leg lengths, not 5 m.`,marking:["Gives opposite return displacement.","Expresses total flown distance as the sum of the three magnitudes."]}],
    ["Add corresponding signed components.","Normalise the resultant for a unit vector.","For distance, find each leg's magnitude before adding."],["Taking the magnitude only after adding when calculating distance."]),
  W("2.3",107,"case",3,"The figure shows two displacement vectors A and B measured on equally scaled metre axes.",[
    {prompt:"Read the components of both vectors and obtain their sum.",answer:L`$\vec A=(3\hat i+2\hat j)\,\mathrm{m}$ and $\vec B=(-2\hat i+3\hat j)\,\mathrm{m}$. Their sum is $(\hat i+5\hat j)\,\mathrm{m}$.`,marking:["Reads both endpoint component pairs correctly.","Obtains the sum (1,5) m."]},
    {prompt:"Find the resultant magnitude and the displacement that would cancel this sum.",answer:L`Magnitude is $\sqrt{1^2+5^2}=\sqrt{26}\,\mathrm{m}$. The cancelling displacement is $(-\hat i-5\hat j)\,\mathrm{m}$.`,marking:[L`Obtains $\sqrt{26}\,\mathrm{m}$.`,"Gives the opposite vector, not just its magnitude."]}],
    ["Read signed coordinates of arrow tips.","Add components rather than arrow lengths.","A cancelling vector is the negative of the resultant."],["Reading negative x as a positive component."],vectorFigure),
  W("2.3",108,"case",3,L`A surveyor records two displacements: $10\,\mathrm{m}$ at $30^\circ$ north of east, followed by $10\,\mathrm{m}$ at $30^\circ$ south of east.`,[
    {prompt:"Resolve the two displacements and find the resultant.",answer:L`Their components are $(5\sqrt3,5)$ and $(5\sqrt3,-5)\,\mathrm{m}$. The sum is $(10\sqrt3,0)\,\mathrm{m}$, due east.`,marking:["Obtains both signed component pairs.",L`Obtains $10\sqrt3\,\mathrm{m}$ east.`]},
    {prompt:"Compare the distance travelled with displacement magnitude and explain the difference.",answer:L`Distance is 20 m, greater than $10\sqrt3\,\mathrm{m}$. The north-south components cancel in displacement, but both slanting path lengths contribute to distance.`,marking:["Gives total path length 20 m.","Explains cancellation of components versus addition of path lengths."]}],
    ["The two directions are symmetric about east.","The y components have opposite signs.","Equal leg lengths do not mean the path is straight."],["Adding the two magnitudes to get the resultant."]),
  W("2.4",101,"vsaq",2,L`A projectile has initial horizontal and vertical velocities $18$ and $12\,\mathrm{m\,s^{-1}}$. Ignore air resistance.`,[
    {prompt:"What is its velocity at the highest point?",answer:L`Its velocity is $18\,\mathrm{m\,s^{-1}}$ horizontally in the launch direction; its vertical component is zero.`,marking:["Gives 18 m/s horizontally, not zero total velocity."]}],
    ["Horizontal acceleration is zero.","Vertical velocity vanishes at the top.","State direction as well as magnitude."],["Setting the whole velocity vector to zero."]),
  W("2.4",102,"vsaq",2,L`A ball rolls off a horizontal ledge at $7\,\mathrm{m\,s^{-1}}$ and lands after $2\,\mathrm{s}$. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Find the ledge height.",answer:L`Initial vertical velocity is zero, so $h=\tfrac12gt^2=20\,\mathrm{m}$. Horizontal speed is not needed for height.`,marking:["Obtains 20 m using vertical motion."]}],
    ["Separate vertical from horizontal motion.","Initial vertical velocity is zero.","Use the fall time to determine height."],["Using horizontal speed as initial vertical speed."]),
  W("2.4",103,"vsaq",2,L`A stone is projected at $10\sqrt2\,\mathrm{m\,s^{-1}}$ at $45^\circ$ above the horizontal. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Find the time to reach its highest point.",answer:L`$u_y=10\,\mathrm{m\,s^{-1}}$ and $t_{\mathrm{top}}=u_y/g=1\,\mathrm{s}$.`,marking:["Obtains 1 s from the vertical component."]}],
    ["Resolve the launch speed vertically.","At the top vertical velocity is zero.","Divide initial vertical velocity by g."],["Using total launch speed instead of its vertical component."]),
  W("2.4",104,"vsaq",2,L`Rain moves vertically downward at $9\,\mathrm{m\,s^{-1}}$ relative to the ground. A pedestrian walks east at $3\,\mathrm{m\,s^{-1}}$.`,[
    {prompt:"Write the rain velocity relative to the pedestrian, taking east and upward as positive axes.",answer:L`$\vec v_{R/P}=(-3\hat i-9\hat j)\,\mathrm{m\,s^{-1}}$.`,marking:["Gives the relative vector with both negative components."]}],
    ["Subtract the observer's velocity from rain velocity.","Ground-frame rain has zero east component.","Keep downward velocity negative."],["Adding the pedestrian's velocity instead of subtracting it."]),
  W("2.4",105,"vsaq",2,L`A river flows east at $2\,\mathrm{m\,s^{-1}}$. A boat is to travel due north relative to the ground.`,[
    {prompt:"What east-west component must its velocity relative to water have?",answer:L`It must have $2\,\mathrm{m\,s^{-1}}$ westward relative to water, cancelling the eastward current.`,marking:["Gives 2 m/s westward relative to water."]}],
    ["Add boat-relative-water and water-relative-ground velocities.","For due north, the ground east-west component must vanish.","Use equal and opposite components."],["Aiming directly north and assuming there is no drift."]),
  W("2.4",106,"saq",3,L`A ball is projected horizontally from a $5\,\mathrm{m}$ high platform. It must land $12\,\mathrm{m}$ from the platform base. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Find the required horizontal launch speed.",answer:L`$t=\sqrt{2h/g}=1\,\mathrm{s}$. Hence $u_x=12/t=12\,\mathrm{m\,s^{-1}}$.`,marking:["Finds fall time 1 s.","Obtains required horizontal speed 12 m/s."]}],
    ["The height fixes the flight time.","Horizontal speed does not change that fall time.","Divide target range by flight time."],["Using a level-ground oblique-projectile range formula."]),
  W("2.4",107,"saq",3,L`A swimmer moves north relative to water at $1.5\,\mathrm{m\,s^{-1}}$ across a river $60\,\mathrm{m}$ wide. The current is $0.5\,\mathrm{m\,s^{-1}}$ eastward.`,[
    {prompt:"Find crossing time and downstream drift.",answer:L`Across-river speed is $1.5\,\mathrm{m\,s^{-1}}$, so crossing time is $60/1.5=40\,\mathrm{s}$. Drift is $0.5(40)=20\,\mathrm{m}$ east.`,marking:["Obtains crossing time 40 s from the north component.","Obtains downstream drift 20 m."]}],
    ["Only the north component crosses the width.","Use this time for the current's motion.","Do not divide width by the resultant speed."],["Using total ground speed for the across-river distance."]),
  W("2.4",108,"laq",3,L`A ball is launched with components $u_x=12$ and $u_y=16\,\mathrm{m\,s^{-1}}$ from level ground. Take $g=10\,\mathrm{m\,s^{-2}}$ and neglect air resistance.`,[
    {prompt:"Find launch speed, time of flight and maximum height.",answer:L`$u=\sqrt{12^2+16^2}=20\,\mathrm{m\,s^{-1}}$, $T=2u_y/g=3.2\,\mathrm{s}$ and $H=u_y^2/(2g)=12.8\,\mathrm{m}$.`,marking:["Obtains launch speed 20 m/s.","Obtains flight time 3.2 s.","Obtains maximum height 12.8 m."]},
    {prompt:"Find range and explain why replacing horizontal speed by total launch speed gives an incorrect range.",answer:L`$R=u_xT=12(3.2)=38.4\,\mathrm{m}$. Only the horizontal component contributes to horizontal displacement; the vertical component determines time aloft.`,marking:["Obtains range 38.4 m.","Explains the component distinction."]}],
    ["Treat components independently.","For same-level landing, vertical motion is symmetric.","Use the horizontal component with the whole flight time."],["Using the launch-speed magnitude as the horizontal component."]),
  W("2.4",109,"laq",3,L`Two projectiles are launched at speed $20\,\mathrm{m\,s^{-1}}$ from level ground at $30^\circ$ and $60^\circ$. Take $g=10\,\mathrm{m\,s^{-2}}$ and neglect air resistance.`,[
    {prompt:"Compare their times of flight and maximum heights as ratios, second projectile to first.",answer:L`$T\propto\sin\theta$, so $T_{60}/T_{30}=\sqrt3$. Since $H\propto\sin^2\theta$, $H_{60}/H_{30}=3$.`,marking:["Obtains time ratio square root of 3.","Obtains height ratio 3."]},
    {prompt:"Find their common range and compare their speeds at their respective highest points.",answer:L`Both ranges are $400\sin60^\circ/10=20\sqrt3\,\mathrm{m}$. Top speeds are $20\cos30^\circ=10\sqrt3$ and $20\cos60^\circ=10\,\mathrm{m\,s^{-1}}$, so the 30-degree projectile is faster there.`,marking:[L`Obtains common range $20\sqrt3\,\mathrm{m}$.`,"Obtains both top speeds correctly.","Correctly identifies the 30-degree projectile as faster at its top."]}],
    ["Write the angle dependence of time and height.","Complementary launch angles have the same sine of twice the angle.","At a highest point only horizontal speed remains."],["Assuming equal ranges imply equal flight times or maximum heights."]),
  W("2.4",110,"case",3,L`A ball has initial velocity $(8\hat i+15\hat j)\,\mathrm{m\,s^{-1}}$ from the origin. A horizontal opening in a wall lies $16\,\mathrm{m}$ away at height $10\,\mathrm{m}$. Take $g=10\,\mathrm{m\,s^{-2}}$ and ignore the ball's size and air resistance.`,[
    {prompt:"Determine whether the ball reaches the opening.",answer:L`At the wall, $t=16/8=2\,\mathrm{s}$. Height is $15(2)-5(2^2)=10\,\mathrm{m}$, so it passes through the opening under the point-particle model.`,marking:["Finds arrival time 2 s.","Finds height 10 m and compares it with the opening."]},
    {prompt:"Is it rising or falling at the opening? Give its velocity there.",answer:L`$v_y=15-10(2)=-5\,\mathrm{m\,s^{-1}}$ while $v_x=8\,\mathrm{m\,s^{-1}}$. It is falling, with velocity $(8\hat i-5\hat j)\,\mathrm{m\,s^{-1}}$.`,marking:["Computes vertical velocity -5 m/s.","Gives the full velocity vector and identifies descent."]}],
    ["Horizontal motion gives arrival time at the wall.","Evaluate vertical position at that time.","Evaluate vertical velocity separately to identify ascent or descent."],["Inferring direction of vertical motion from positive height."]),
  W("2.4",111,"case",3,L`A boat can move at $13\,\mathrm{m\,s^{-1}}$ relative to still water. A river flows east at $5\,\mathrm{m\,s^{-1}}$ and is $120\,\mathrm{m}$ wide from south to north.`,[
    {prompt:"For landing directly opposite, find the west and north components of boat velocity relative to water, and the crossing time.",answer:L`The west component must be 5 m/s. The north component is $\sqrt{13^2-5^2}=12\,\mathrm{m\,s^{-1}}$, so crossing time is $120/12=10\,\mathrm{s}$.`,marking:["Sets the upstream component to 5 m/s.","Obtains north component 12 m/s and time 10 s."]},
    {prompt:"If instead the boat points due north, does it cross sooner? Find its downstream drift.",answer:L`The crossing time is $120/13\,\mathrm{s}<10\,\mathrm{s}$. The drift is $5(120/13)=600/13\,\mathrm{m}$ east. Minimum time is not the same requirement as directly opposite landing.`,marking:["Obtains 120/13 s and correctly compares the times.","Obtains drift 600/13 m east."]}],
    ["Cancel the current only for the directly opposite target.","Use the fixed boat-speed magnitude to find its north component.","For minimum time, maximise the across-river component."],["Confusing shortest crossing time with zero downstream drift."]),
  W("2.5",101,"vsaq",2,L`A particle completes 5 revolutions in $20\,\mathrm{s}$ at uniform angular speed.`,[
    {prompt:"Find its angular speed in radians per second.",answer:L`$\omega=5(2\pi)/20=\pi/2\,\mathrm{rad\,s^{-1}}$.`,marking:[L`Obtains $\pi/2\,\mathrm{rad\,s^{-1}}$.`]}],
    ["Convert revolutions into radians.","Divide total angle by total time.","Each revolution contributes two pi radians."],["Treating one revolution as one radian."]),
  W("2.5",102,"vsaq",2,L`Two particles move uniformly on circles of radii $2r$ and $r$, with the same linear speed.`,[
    {prompt:"Find the ratio of their centripetal accelerations, first to second.",answer:L`At fixed speed, $a_c=v^2/r$, so $a_1/a_2=r/(2r)=1/2$.`,marking:["Gives 1:2, with the larger-radius acceleration smaller."]}],
    ["Use the same speed in both expressions.","Acceleration is inversely proportional to radius here.","Keep the requested ordering of the ratio."],["Using the fixed-angular-speed rule when linear speed is fixed."]),
  W("2.5",103,"saq",2,L`A point moves uniformly around a circle of radius $0.20\,\mathrm{m}$ with angular speed $5\,\mathrm{rad\,s^{-1}}$.`,[
    {prompt:"Find its linear speed and centripetal acceleration.",answer:L`$v=\omega r=1.0\,\mathrm{m\,s^{-1}}$ and $a_c=\omega^2r=5.0\,\mathrm{m\,s^{-2}}$, directed inward.`,marking:["Obtains linear speed 1.0 m/s.","Obtains acceleration 5.0 m/s squared towards the centre."]}],
    ["Use v=omega r.","Acceleration contains omega squared.","State the inward direction."],["Confusing angular speed and linear speed."]),
  W("2.5",104,"laq",3,L`A particle moves uniformly anticlockwise at speed $4\,\mathrm{m\,s^{-1}}$ on a circle of radius $2\,\mathrm{m}$. At t=0 it is at the rightmost point.`,[
    {prompt:"Write its velocity at t=0 and after a quarter revolution, using right and upward as positive axes.",answer:L`Initially velocity is $4\hat j\,\mathrm{m\,s^{-1}}$. At the top after a quarter turn it is $-4\hat i\,\mathrm{m\,s^{-1}}$.`,marking:["Gives the initial upward velocity.","Gives the final leftward velocity."]},
    {prompt:"Find the magnitude of average acceleration over that quarter revolution and compare it with instantaneous centripetal acceleration.",answer:L`Velocity-change magnitude is $4\sqrt2\,\mathrm{m\,s^{-1}}$. Quarter-turn duration is $(\pi r/2)/v=\pi/4\,\mathrm{s}$, so $|\vec a_{\mathrm{av}}|=16\sqrt2/\pi\,\mathrm{m\,s^{-2}}$. Instantaneous magnitude is $v^2/r=8\,\mathrm{m\,s^{-2}}$, which is larger.`,marking:["Obtains velocity-change magnitude and interval correctly.",L`Obtains average magnitude $16\sqrt2/\pi\,\mathrm{m\,s^{-2}}$.`,"Obtains instantaneous magnitude 8 m/s squared and compares correctly."]}],
    ["Draw the two velocity directions mentally or on paper.","Use vector change, not speed change.","Average acceleration over a finite arc differs from its instantaneous value."],["Concluding acceleration is zero because speed is constant."]),
  W("2.5",105,"laq",3,L`A particle completes a semicircle of radius $3\,\mathrm{m}$ at uniform speed $2\,\mathrm{m\,s^{-1}}$, moving from the rightmost to the leftmost point.`,[
    {prompt:"Find the time taken, distance and displacement magnitude.",answer:L`Distance is $\pi r=3\pi\,\mathrm{m}$. Time is $3\pi/2\,\mathrm{s}$. Displacement is the diameter, magnitude $6\,\mathrm{m}$, leftwards.`,marking:[L`Gives distance $3\pi\,\mathrm{m}$.`,L`Gives time $3\pi/2\,\mathrm{s}$.`,"Gives displacement 6 m leftwards."]},
    {prompt:"Find average speed and average velocity magnitude.",answer:L`Average speed remains $2\,\mathrm{m\,s^{-1}}$. Average velocity magnitude is $6/(3\pi/2)=4/\pi\,\mathrm{m\,s^{-1}}$, less than the speed.`,marking:["Gives average speed 2 m/s.",L`Gives average-velocity magnitude $4/\pi\,\mathrm{m\,s^{-1}}$.`]}],
    ["Use arc length for distance and chord for displacement.","Find the time using constant speed.","Use the appropriate numerator for each average."],["Using semicircular arc length as displacement magnitude."]),
  W("2.5",106,"case",3,L`Two markers are fixed on a disc at radii $0.10$ and $0.30\,\mathrm{m}$. The disc rotates uniformly with period $2\,\mathrm{s}$.`,[
    {prompt:"Find their common angular speed and their linear speeds.",answer:L`$\omega=2\pi/T=\pi\,\mathrm{rad\,s^{-1}}$. Linear speeds are $0.10\pi$ and $0.30\pi\,\mathrm{m\,s^{-1}}$.`,marking:[L`Obtains angular speed $\pi\,\mathrm{rad\,s^{-1}}$.`,"Obtains both linear speeds with the correct radii."]},
    {prompt:"Compare their centripetal accelerations and explain why the outer marker has the larger value despite a larger radius.",answer:L`Accelerations are $0.10\pi^2$ and $0.30\pi^2\,\mathrm{m\,s^{-2}}$, ratio 1:3. Angular speed, not linear speed, is fixed; $a_c=\omega^2r$ increases with radius.`,marking:["Obtains acceleration ratio 1:3.","Explains the fixed-angular-speed condition."]}],
    ["Both markers complete each revolution together.","Use the shared period to find omega.","At fixed omega, acceleration is directly proportional to radius."],["Applying inverse-radius scaling while overlooking changing linear speed."]),
];
