import { expansionBank } from "../expansion-helpers";
import { kinematicsGraph } from "../kinematics-graph";
const { mc: M, written: W } = expansionBank("u2-kinematics", "u2");
const L = String.raw;
const positionGraph = kinematicsGraph("Position of a cart", "x (m)", [[0,-4],[2,4],[4,4],[6,-2]], [0,2,4,6], [-4,-2,0,2,4]);
const reversalGraph = kinematicsGraph("Velocity of a particle", "v (m/s)", [[0,-4],[2,0],[6,8]], [0,2,4,6], [-4,0,4,8]);
const cruiseGraph = kinematicsGraph("Velocity of a trolley", "v (m/s)", [[0,2],[2,6],[5,6],[7,0]], [0,1,2,3,4,5,6,7], [0,2,4,6]);
const signedGraph = kinematicsGraph("Velocity on a straight track", "v (m/s)", [[0,6],[3,0],[5,-4]], [0,1,2,3,4,5], [-4,-2,0,2,4,6]);

export const straightLineExpansion = [
  M("2.1",101,2,L`A runner completes equal distances at speeds $3\,\mathrm{m\,s^{-1}}$ and $6\,\mathrm{m\,s^{-1}}$. The average speed for both stages is`,
    L`$4\,\mathrm{m\,s^{-1}}$`,[[L`$4.5\,\mathrm{m\,s^{-1}}$`,"The arithmetic mean applies to equal times, not equal distances."],[L`$9\,\mathrm{m\,s^{-1}}$`,"Adding speeds does not give total distance divided by total time."],[L`$2\,\mathrm{m\,s^{-1}}$`,"This omits one of the two equal distances in the numerator."]],
    L`For each distance $d$, total time is $d/3+d/6=d/2$. Hence average speed $=2d/(d/2)=4\,\mathrm{m\,s^{-1}}$.`,["Assign distance d to each stage.","Add the two travel times.","Divide total distance 2d by total time."]),
  M("2.1",102,2,L`A conveyor moves a parcel at $2\,\mathrm{m\,s^{-1}}$ for $4\,\mathrm{s}$ and then at $5\,\mathrm{m\,s^{-1}}$ for $2\,\mathrm{s}$, in the same direction. Its average speed is`,
    L`$3\,\mathrm{m\,s^{-1}}$`,[[L`$3.5\,\mathrm{m\,s^{-1}}$`,"The stages last different times."],[L`$7\,\mathrm{m\,s^{-1}}$`,"The speeds must be weighted by their durations."],[L`$1.5\,\mathrm{m\,s^{-1}}$`,"The total distance is 18 m, not 9 m."]],
    L`Distance is $2(4)+5(2)=18\,\mathrm{m}$ and time is $6\,\mathrm{s}$, giving $3\,\mathrm{m\,s^{-1}}$.`,["Calculate each stage's distance.","Add the durations.","Use total distance divided by total time."]),
  M("2.1",103,2,L`A particle moves from $x=8\,\mathrm{m}$ to $x=-4\,\mathrm{m}$, without turning. Which pair gives its distance and displacement?`,
    L`$12\,\mathrm{m},\ -12\,\mathrm{m}$`,[[L`$-12\,\mathrm{m},\ -12\,\mathrm{m}$`,"Distance cannot be negative."],[L`$4\,\mathrm{m},\ 4\,\mathrm{m}$`,"Subtract initial position from final position."],[L`$12\,\mathrm{m},\ 12\,\mathrm{m}$`,"The displacement points in the negative direction."]],
    L`$\Delta x=-4-8=-12\,\mathrm{m}$. With no reversal, distance is $|\Delta x|=12\,\mathrm{m}$.`,["Use final minus initial position.","Keep the sign for displacement.","Take the magnitude for this no-turn path's distance."]),
  M("2.1",104,2,L`Two observers use coordinate origins $10\,\mathrm{m}$ apart, but equally oriented axes and the same stationary reference frame. They will necessarily assign the same`,
    "displacement over a given time interval",[["position at every instant","Position changes by the offset between origins."],["distance from the coordinate origin","That distance depends on where the origin is placed."],["sign of position at every instant","A point can lie on different sides of the two origins."]],
    L`If $x'=x-10$, then $x'_2-x'_1=(x_2-10)-(x_1-10)=x_2-x_1$. The origin offset cancels.`,["Represent the origin shift by a constant.","Form a difference of positions.","The constant cancels in displacement."]),
  M("2.1",105,2,L`A particle's position is $x=7-2t$ in SI units. During the interval $0\leq t\leq5\,\mathrm{s}$ it`,
    "moves with constant velocity in the negative direction",[["remains at rest when it crosses the origin","Zero position does not imply zero velocity."],["has positive acceleration","The position-time slope is constant, so acceleration is zero."],["moves more slowly as x decreases","The slope is -2 throughout; its magnitude does not decrease."]],
    L`$v=dx/dt=-2\,\mathrm{m\,s^{-1}}$ and $a=0$. Passing through $x=0$ does not change this velocity.`,["Read the coefficient of time.","It is the position-time slope.","Do not confuse position with velocity."]),
  M("2.1",106,2,L`At one instant a particle has $v=-4\,\mathrm{m\,s^{-1}}$ and $a=+2\,\mathrm{m\,s^{-2}}$. At that instant its speed is`,
    "decreasing",[["increasing because acceleration is positive","Acceleration opposite to velocity reduces speed."],["zero because the signs differ","Opposite signs do not cancel different physical quantities."],["constant because the motion is one-dimensional","One-dimensional motion can have changing speed."]],
    "The acceleration opposes the current velocity, so the magnitude of velocity decreases locally. Positive acceleration need not mean speeding up.",["Compare velocity and acceleration directions.","Opposite directions reduce the magnitude of velocity.","Use speed as the magnitude, not the signed velocity."]),
  M("2.1",107,2,L`A car's speedometer reads $40\,\mathrm{km\,h^{-1}}$ at an instant. This reading alone determines`,
    "the magnitude of instantaneous velocity",[["the car's displacement during the previous hour","One instant does not describe the whole previous hour."],["the direction of instantaneous velocity","A speedometer reports magnitude, not direction."],["the car's acceleration","Acceleration requires information about velocity change."]],
    "The speedometer measures instantaneous speed. It does not supply direction, acceleration or the earlier history of the motion.",["Distinguish speed from velocity.","The reading is instantaneous.","Decide what additional information would be needed for acceleration."]),
  M("2.1",108,2,L`The positions of two cars are $x_A=4t+5$ and $x_B=4t-7$ in SI units. Their separation is`,
    L`constant at $12\,\mathrm{m}$`,[[L`increasing at $8\,\mathrm{m\,s^{-1}}$`,"Both velocities have the same sign; subtract them for relative motion."],[L`constant at $2\,\mathrm{m}$`,"Subtract the two intercepts with their signs."],["zero after three seconds","Equal slopes mean the position-time lines never intersect here."]],
    L`$x_A-x_B=(4t+5)-(4t-7)=12\,\mathrm{m}$ at every time.`,["Subtract the position expressions.","The time-dependent terms cancel.","Interpret the remaining constant."]),
  M("2.1",109,2,L`Assertion (A): Zero displacement over an interval implies zero average velocity over that interval. Reason (R): Zero displacement implies that the particle was at rest throughout the interval.`,
    "A is true, but R is false.",[["Both are true and R explains A.","A particle can move and return to its starting position."],["Both are true but R does not explain A.","The reason is false for a return journey."],["A is false, but R is true.","Average velocity is displacement divided by elapsed time."]],
    "For a non-zero elapsed time, zero displacement gives zero average velocity. It does not imply that the intervening distance travelled was zero.",["Use the definition of average velocity.","Consider an out-and-back journey.","Evaluate A and R independently."]),
  M("2.1",110,2,L`A particle moves in the positive direction without stopping, but its position-time graph becomes progressively less steep. Its velocity and acceleration are respectively`,
    "positive and negative",[["positive and positive","Decreasing positive slope indicates decreasing velocity."],["negative and positive","The slope is positive, so velocity is positive."],["negative and negative","Moving in the positive direction excludes negative velocity."]],
    "A positive slope means positive velocity. As this slope decreases with time, the acceleration is negative.",["Velocity is the graph's slope.","Acceleration describes how this slope changes.","Separate the sign of a quantity from the sign of its rate of change."]),
  M("2.1",111,3,L`A particle has position $x=t^2-6t+8$ in SI units. Its distance travelled from $t=0$ to $t=4\,\mathrm{s}$ is`,
    L`$10\,\mathrm{m}$`,[[L`$8\,\mathrm{m}$`,"This is the displacement magnitude; it misses the reversal at 3 s."],[L`$4\,\mathrm{m}$`,"Evaluate positions at the endpoints and at the turning instant."],[L`$16\,\mathrm{m}$`,"Distance is the sum of absolute changes between turning points, not the sum of endpoint magnitudes."]],
    L`$v=2t-6$ vanishes at $t=3$. Positions are $x(0)=8$, $x(3)=-1$, $x(4)=0\,\mathrm{m}$. Distance is $9+1=10\,\mathrm{m}$.`,["Find when velocity is zero.","Evaluate position at the turning point as well as both endpoints.","Add absolute changes over the two monotonic stages."]),
  M("2.1",112,2,L`An object's velocity is $v=3t^2$ in SI units. Its average acceleration between $t=1$ and $t=3\,\mathrm{s}$ is`,
    L`$12\,\mathrm{m\,s^{-2}}$`,[[L`$18\,\mathrm{m\,s^{-2}}$`,"This is the instantaneous acceleration at the final time."],[L`$9\,\mathrm{m\,s^{-2}}$`,"Use the change of velocity, not final velocity divided by final time."],[L`$24\,\mathrm{m\,s^{-2}}$`,"This is the velocity change before division by the 2 s interval."]],
    L`$a_{\mathrm{av}}=[v(3)-v(1)]/(3-1)=(27-3)/2=12\,\mathrm{m\,s^{-2}}$.`,["Calculate the two endpoint velocities.","Use the duration 3 minus 1.","Divide velocity change by that duration."]),
  M("2.1",113,2,L`A bus covers $200\,\mathrm{m}$ in $20\,\mathrm{s}$, waits $10\,\mathrm{s}$, then covers another $100\,\mathrm{m}$ in $20\,\mathrm{s}$. Its average speed over the complete journey is`,
    L`$6\,\mathrm{m\,s^{-1}}$`,[[L`$7.5\,\mathrm{m\,s^{-1}}$`,"This excludes the waiting time."],[L`$10\,\mathrm{m\,s^{-1}}$`,"This describes only the first stage."],[L`$5\,\mathrm{m\,s^{-1}}$`,"This describes only the final moving stage."]],
    L`Total distance is $300\,\mathrm{m}$ and total elapsed time, including the stop, is $50\,\mathrm{s}$. Thus average speed is $6\,\mathrm{m\,s^{-1}}$.`,["Include every part of elapsed time.","The stop adds time but no distance.","Divide 300 by the full duration."]),
  M("2.1",114,2,L`A particle moves from $x=2$ to $x=11\,\mathrm{m}$ and returns to $x=5\,\mathrm{m}$. The ratio of distance to displacement magnitude is`,
    "$5$",[["$3$","The total path is 9+6, while the net change is 3."],["$1$","The particle reverses direction, so distance exceeds displacement magnitude."],["$15$","This gives the distance, not the required dimensionless ratio."]],
    L`Distance $=|11-2|+|5-11|=15\,\mathrm{m}$. Displacement magnitude $=|5-2|=3\,\mathrm{m}$, so the ratio is 5.`,["Break the path at the turning point.","Use only final minus initial for displacement.","Form the ratio, with units cancelling."]),
  M("2.1",115,2,L`Assertion (A): A horizontal segment of a position-time graph represents rest. Reason (R): A horizontal segment of a velocity-time graph always represents rest.`,
    "A is true, but R is false.",[["Both are true and R explains A.","A horizontal velocity-time segment may lie at a non-zero velocity."],["Both are true but R does not explain A.","R is false unless that horizontal segment is at zero velocity."],["A is false, but R is true.","A constant position does mean rest in the chosen frame."]],
    "Constant position means zero velocity. Constant velocity need not be zero; the graph's vertical coordinate matters.",["Read the vertical variable before interpreting a graph.","A position-time horizontal line has zero slope.","A velocity-time horizontal line specifies a constant value, possibly non-zero."]),
  M("2.1",116,2,L`Two successive equal time intervals have displacements $+8\,\mathrm{m}$ and $-2\,\mathrm{m}$. No direction reversal occurs within either interval. The ratio of average speed to average velocity magnitude over both intervals is`,
    "$5/3$",[["$1$","The opposite signs show that the motion is not one-way."],["$4$","The ratio of individual displacement magnitudes is not the requested ratio."],["$3/5$","This reverses distance and displacement in the ratio."]],
    L`The same total time cancels. Distance is $8+2=10\,\mathrm{m}$; displacement magnitude is $|8-2|=6\,\mathrm{m}$. The ratio is $10/6=5/3$.`,["Compute total path length.","Compute signed net displacement.","The common total time cancels from the ratio."]),
  M("2.1",117,2,L`A particle's position changes by $+5\,\mathrm{m}$ in the first second, by $+5\,\mathrm{m}$ in the next second, and by $+5\,\mathrm{m}$ in the third. These data alone establish`,
    "equal average velocities over the three intervals",[["constant instantaneous velocity throughout","Within each second the motion could vary while yielding the same displacement."],["zero instantaneous acceleration everywhere","Interval displacements do not determine all instantaneous accelerations."],["that the particle never reverses within an interval","Short reversals cannot be excluded by endpoints alone."]],
    "Each interval has average velocity 5 m/s. Endpoint data alone do not determine the detailed motion between observations.",["Ask what an interval displacement measures.","Distinguish average from instantaneous velocity.","Many within-interval motions can share the same endpoints."]),

  M("2.2",101,2,L`A vehicle accelerates uniformly from $5$ to $17\,\mathrm{m\,s^{-1}}$ over $66\,\mathrm{m}$. The acceleration is`,
    L`$2\,\mathrm{m\,s^{-2}}$`,[[L`$4\,\mathrm{m\,s^{-2}}$`,"This misses the factor 2 in the displacement equation."],[L`$1\,\mathrm{m\,s^{-2}}$`,"Use the difference of squared speeds, not their difference."],[L`$12\,\mathrm{m\,s^{-2}}$`,"This is a velocity change, not acceleration."]],
    L`$a=(v^2-u^2)/(2s)=(289-25)/132=2\,\mathrm{m\,s^{-2}}$.`,["Choose the equation without time.","Square both speeds separately.","Divide their squared difference by twice the displacement."]),
  M("2.2",102,2,L`A ball is thrown vertically upwards at $24\,\mathrm{m\,s^{-1}}$. Take $g=10\,\mathrm{m\,s^{-2}}$ and ignore air resistance. Its velocity after $3\,\mathrm{s}$, upwards positive, is`,
    L`$-6\,\mathrm{m\,s^{-1}}$`,[[L`$+6\,\mathrm{m\,s^{-1}}$`,"The ball has passed its highest point and is descending."],[L`$0\,\mathrm{m\,s^{-1}}$`,"It is momentarily at rest at 2.4 s, not 3 s."],[L`$54\,\mathrm{m\,s^{-1}}$`,"Gravity has negative sign when upwards is positive."]],
    L`$v=u-gt=24-10(3)=-6\,\mathrm{m\,s^{-1}}$.`,["Fix the positive direction.","Use negative acceleration for gravity.","Retain the negative sign of the final velocity."]),
  M("2.2",103,2,L`Under a fixed braking deceleration, doubling a car's initial speed changes its braking distance by a factor of`,
    "$4$",[["$2$","Braking distance depends on the square of initial speed."],["$1/2$","Greater initial speed cannot reduce braking distance under the same deceleration."],["$8$","There is no cube of speed in the stopping-distance relation."]],
    L`Putting $v=0$ in $v^2=u^2+2as$ gives $s=u^2/(2|a|)$. At fixed deceleration, doubling $u$ multiplies $s$ by four.`,["Set the final speed to zero.","Solve for stopping distance.","Inspect the power of initial speed."]),
  M("2.2",104,3,L`The velocity-time graph shown describes a reversal of direction. What is the total distance travelled from $0$ to $6\,\mathrm{s}$?`,
    L`$20\,\mathrm{m}$`,[[L`$12\,\mathrm{m}$`,"This is signed displacement; distance adds the magnitudes of both areas."],[L`$24\,\mathrm{m}$`,"The positive part is a triangle, not a rectangle."],[L`$16\,\mathrm{m}$`,"This omits the distance before the reversal."]],
    L`The negative triangle has magnitude $\tfrac12(2)(4)=4\,\mathrm{m}$ and the positive triangle $\tfrac12(4)(8)=16\,\mathrm{m}$. Distance is $20\,\mathrm{m}$.`,["Find where velocity changes sign.","Calculate each triangular area separately.","Add absolute areas for distance."],reversalGraph),
  M("2.2",105,2,L`An object starts from rest with uniform acceleration. Distances travelled during the first, second and third individual seconds are in the ratio`,
    "$1:3:5$",[["$1:4:9$","These are cumulative distances at 1, 2 and 3 seconds."],["$1:2:3$","Velocity, not distance in each second, follows that ratio here."],["$1:1:1$","That would describe constant speed."]],
    L`Using $s(t)=\tfrac12at^2$, the successive increments are $a/2,3a/2,5a/2$. Their ratio is $1:3:5$.`,["Write cumulative displacement at whole-second times.","Subtract adjacent cumulative values.","Compare the individual increments."]),
  M("2.2",106,2,L`Assertion (A): At the highest point of a vertical throw, the ball has zero acceleration. Reason (R): At the highest point, its instantaneous velocity is zero. Ignore air resistance.`,
    "A is false, but R is true.",[["Both are true and R explains A.","Gravity still acts when the instantaneous velocity is zero."],["Both are true but R does not explain A.","The assertion is false, not merely unexplained."],["A is true, but R is false.","The velocity is zero at the top but the acceleration is not."]],
    L`The ball has $v=0$ at the top but $a=-g$ throughout the flight when upward is positive.`,["Is gravity absent at the top?","Distinguish the value of velocity from its rate of change.","Acceleration remains downward during ascent and descent."]),
  M("2.2",107,3,L`A driver travelling at $15\,\mathrm{m\,s^{-1}}$ reacts for $0.8\,\mathrm{s}$ before braking uniformly at $5\,\mathrm{m\,s^{-2}}$. The total stopping distance is`,
    L`$34.5\,\mathrm{m}$`,[[L`$22.5\,\mathrm{m}$`,"This is braking distance only."],[L`$12\,\mathrm{m}$`,"This is reaction distance only."],[L`$45\,\mathrm{m}$`,"Do not use initial speed times braking duration for the uniformly slowing stage."]],
    L`Reaction distance is $15(0.8)=12\,\mathrm{m}$. Braking distance is $15^2/(2\times5)=22.5\,\mathrm{m}$. Total $=34.5\,\mathrm{m}$.`,["Separate reaction and braking stages.","During reaction, speed is unchanged.","Add reaction distance to braking distance."]),
  M("2.2",108,2,L`A body moving at $8\,\mathrm{m\,s^{-1}}$ experiences acceleration $-2\,\mathrm{m\,s^{-2}}$ for $6\,\mathrm{s}$. Its displacement in this interval is`,
    L`$12\,\mathrm{m}$`,[[L`$20\,\mathrm{m}$`,"That is distance, including motion after reversal."],[L`$48\,\mathrm{m}$`,"This ignores acceleration."],[L`$-12\,\mathrm{m}$`,"The final velocity is negative, but the net displacement remains positive."]],
    L`$s=ut+\tfrac12at^2=8(6)-6^2=12\,\mathrm{m}$. The equation remains valid across the reversal because acceleration stays constant.`,["Use signed acceleration.","The question asks displacement, not path length.","Evaluate the complete constant-acceleration expression."]),
  M("2.2",109,2,L`A stone falls freely from rest on a planet with $g=8\,\mathrm{m\,s^{-2}}$. The distance it falls in its fourth second is`,
    L`$28\,\mathrm{m}$`,[[L`$64\,\mathrm{m}$`,"This is total distance after four seconds."],[L`$32\,\mathrm{m}$`,"This is the final speed numerically, not the distance in the fourth second."],[L`$16\,\mathrm{m}$`,"Subtract cumulative distances at 4 and 3 s."]],
    L`$s(4)-s(3)=\tfrac12(8)(16-9)=28\,\mathrm{m}$.`,["The fourth second runs from 3 to 4 s.","Find both cumulative distances.","Take their difference."]),
  M("2.2",110,3,L`A ball is projected upwards at $20\,\mathrm{m\,s^{-1}}$. At what two times is it $15\,\mathrm{m}$ above the launch point? Take $g=10\,\mathrm{m\,s^{-2}}$.`,
    L`$1\,\mathrm{s}$ and $3\,\mathrm{s}$`,[[L`$1\,\mathrm{s}$ and $2\,\mathrm{s}$`,"At 2 s it is at the highest point, 20 m above launch."],[L`$2\,\mathrm{s}$ and $3\,\mathrm{s}$`,"Substitute both times into the position equation."],[L`$3\,\mathrm{s}$ and $4\,\mathrm{s}$`,"At 4 s it returns to launch height."]],
    L`$15=20t-5t^2$ gives $t^2-4t+3=0$, hence $t=1$ or $3\,\mathrm{s}$.`,["Use height as signed displacement.","Rearrange to a quadratic.","Both roots are physical: ascent and descent."]),
  M("2.2",111,2,L`A vehicle's speed changes uniformly from $18$ to $6\,\mathrm{m\,s^{-1}}$ in $4\,\mathrm{s}$. Its displacement in that time is`,
    L`$48\,\mathrm{m}$`,[[L`$72\,\mathrm{m}$`,"This assumes the initial speed lasts throughout."],[L`$24\,\mathrm{m}$`,"This assumes the final speed lasts throughout."],[L`$12\,\mathrm{m}$`,"This is the average velocity numerically, before multiplication by time."]],
    L`For uniform acceleration, $s=(u+v)t/2=(18+6)(4)/2=48\,\mathrm{m}$.`,["Uniform acceleration makes velocity vary linearly.","Average the endpoint velocities.","Multiply by four seconds."]),
  M("2.2",112,2,L`An object in free fall descends $45\,\mathrm{m}$ during a $3\,\mathrm{s}$ interval. Its initial downward speed for that interval is what, for $g=10\,\mathrm{m\,s^{-2}}$?`,
    L`$0\,\mathrm{m\,s^{-1}}$`,[[L`$15\,\mathrm{m\,s^{-1}}$`,"This is the average speed over the interval."],[L`$30\,\mathrm{m\,s^{-1}}$`,"This is the speed at the lower point."],[L`$5\,\mathrm{m\,s^{-1}}$`,"Use the acceleration contribution over the full three seconds."]],
    L`$45=3u+\tfrac12(10)(3^2)=3u+45$, so $u=0$. The upper point is the release point.`,["Use the upper point as the interval's starting point.","Do not assume a non-zero initial speed.","Solve the displacement equation for u."]),
  M("2.2",113,2,L`A constant acceleration changes velocity from $-6$ to $+10\,\mathrm{m\,s^{-1}}$ in $4\,\mathrm{s}$. Its value is`,
    L`$+4\,\mathrm{m\,s^{-2}}$`,[[L`$+1\,\mathrm{m\,s^{-2}}$`,"This subtracts speed magnitudes and loses the initial negative sign."],[L`$-4\,\mathrm{m\,s^{-2}}$`,"Velocity changes in the positive direction."],[L`$+16\,\mathrm{m\,s^{-2}}$`,"This omits division by the time interval."]],
    L`$a=[10-(-6)]/4=4\,\mathrm{m\,s^{-2}}$.`,["Retain signed velocities.","Subtract the initial velocity from the final velocity.","Divide by four seconds."]),
  M("2.2",114,3,L`A train starts from rest with uniform acceleration $1\,\mathrm{m\,s^{-2}}$. A cyclist passes its starting point at that instant at constant speed $6\,\mathrm{m\,s^{-1}}$, in the same direction. The train next catches the cyclist after`,
    L`$12\,\mathrm{s}$`,[[L`$6\,\mathrm{s}$`,"This is when their velocities match, not their positions."],[L`$3\,\mathrm{s}$`,"Equate displacements, not acceleration and speed."],[L`$18\,\mathrm{s}$`,"At this time the train has already overtaken the cyclist."]],
    L`Equate $t^2/2=6t$. Besides $t=0$, the solution is $t=12\,\mathrm{s}$.`,["Write one position function for each traveller.","Meeting requires equal position.","Exclude the initial meeting at t=0."]),
  M("2.2",115,2,L`Which condition is required for using $s=ut+\tfrac12at^2$ with a single value of a throughout an interval?`,
    "The acceleration must remain constant over that interval.",[["The initial velocity must be zero.","The equation includes a non-zero initial velocity term."],["The velocity must remain positive.","Signed displacement permits negative velocities and reversal."],["The motion must always be speeding up.","Constant negative acceleration can slow a body or cause reversal."]],
    "The equation follows by integrating a constant acceleration. It does not require rest initially, positive velocity, or continuously increasing speed.",["Recall how the equation is derived.","Which quantity is treated as a constant in the integration?","Velocity may still change sign."]),
  M("2.2",116,2,L`A ball is thrown vertically downwards at $5\,\mathrm{m\,s^{-1}}$ from a ledge. Ignoring air resistance, how far does it fall in $2\,\mathrm{s}$? Take $g=10\,\mathrm{m\,s^{-2}}$.`,
    L`$30\,\mathrm{m}$`,[[L`$20\,\mathrm{m}$`,"This omits the initial downward velocity."],[L`$10\,\mathrm{m}$`,"This omits the gravitational acceleration term."],[L`$50\,\mathrm{m}$`,"This uses the final velocity for the entire interval."]],
    L`Taking downward as positive, $s=5(2)+\tfrac12(10)(2^2)=30\,\mathrm{m}$.`,["Choose downward as positive.","Include both initial motion and acceleration.","Add the two displacement contributions."]),
  M("2.2",117,2,L`A particle's velocity is $v=4+3t$ in SI units. Its displacement between $t=2$ and $t=4\,\mathrm{s}$ is`,
    L`$26\,\mathrm{m}$`,[[L`$40\,\mathrm{m}$`,"This is displacement from 0 to 4 s, not from 2 to 4 s."],[L`$20\,\mathrm{m}$`,"This uses the velocity at 2 s as constant."],[L`$32\,\mathrm{m}$`,"This uses the velocity at 4 s as constant."]],
    L`Velocities are $10$ and $16\,\mathrm{m\,s^{-1}}$. Their mean over the 2 s linear segment is $13\,\mathrm{m\,s^{-1}}$, giving $26\,\mathrm{m}$.`,["Reset the interval to start at 2 s.","Find the two endpoint velocities.","Use their mean times the interval length."]),
  M("2.2",118,2,L`Assertion (A): Two bodies released from rest simultaneously from different heights have equal speeds after the same elapsed time, while both are still falling freely. Reason (R): Their acceleration is the same constant g and their initial velocities are equal. Neglect air resistance and variation of g.`,
    "Both are true and R explains A.",[["Both are true but R does not explain A.","Equal u, a and elapsed t directly imply equal v."],["A is true, but R is false.","Under the stated model both accelerations are g."],["A is false, but R is true.","Starting height does not enter v=u+gt while both bodies remain in free fall."]],
    L`For each body, $v=gt$ downwards. Different remaining heights do not change this result before either strikes the ground.`,["Use velocity as a function of elapsed time.","Check the initial velocities.","The comparison ends if one body hits the ground."]),
  W("2.1",101,"vsaq",2,L`A lift moves from a floor at $x=18\,\mathrm{m}$ to one at $x=3\,\mathrm{m}$ in $5\,\mathrm{s}$. Upward is positive.`,[
    {prompt:"Find its average velocity.",answer:L`$v_{\mathrm{av}}=(3-18)/5=-3\,\mathrm{m\,s^{-1}}$, or 3 m/s downward.`,marking:["Gives -3 m/s with the stated sign convention."]}],
    ["Use final minus initial coordinate.","Retain the direction sign.","Divide the displacement by five seconds."],["Reporting speed instead of signed velocity."]),
  W("2.1",102,"vsaq",1,L`A particle is at $x=-7\,\mathrm{m}$. A new origin is placed at the old coordinate $x=-10\,\mathrm{m}$, with the positive direction unchanged.`,[
    {prompt:"Find the particle's new coordinate.",answer:L`$x'=x-(-10)=-7+10=+3\,\mathrm{m}$.`,marking:["Gives +3 m."]}],
    ["Measure from the new origin.","The particle lies to its positive side.","Subtract the coordinate of the new origin."],["Changing the axis direction along with the origin."]),
  W("2.1",103,"vsaq",2,L`The position is $x=t^3+2$ in SI units.`,[
    {prompt:L`Find the instantaneous velocity at $t=2\,\mathrm{s}$.`,answer:L`$v=dx/dt=3t^2$, so $v(2)=12\,\mathrm{m\,s^{-1}}$.`,marking:["Differentiates position and obtains 12 m/s."]}],
    ["Instantaneous velocity is a derivative.","The constant position offset has zero derivative.","Evaluate 3t squared at t=2."],["Dividing position by time."]),
  W("2.1",104,"vsaq",2,L`During a trip along a straight corridor, a student's displacement is $-9\,\mathrm{m}$.`,[
    {prompt:"What is the minimum possible distance travelled? State when this minimum occurs.",answer:L`The minimum is $9\,\mathrm{m}$. It occurs if the student travels only in the negative direction, without retracing any part of the path.`,marking:["Gives 9 m with the no-reversal condition."]}],
    ["Distance cannot be less than displacement magnitude.","A detour or reversal adds path length.","Use a one-direction path for the minimum."],["Making distance negative."]),
  W("2.1",105,"vsaq",2,L`A robot covers $36\,\mathrm{m}$ at $3\,\mathrm{m\,s^{-1}}$, then waits $6\,\mathrm{s}$.`,[
    {prompt:"Find its average speed including the wait.",answer:L`Travel time $=36/3=12\,\mathrm{s}$. Average speed $=36/(12+6)=2\,\mathrm{m\,s^{-1}}$.`,marking:["Includes waiting time and obtains 2 m/s."]}],
    ["Find the moving duration from distance and speed.","Add the wait.","The numerator remains 36 m."],["Excluding a stop from total elapsed time."]),
  W("2.1",106,"vsaq",2,L`At an instant, a moving particle has negative velocity and negative acceleration.`,[
    {prompt:"Is its speed increasing or decreasing? Justify.",answer:"Its speed is increasing because acceleration points in the same direction as velocity, increasing its magnitude.",marking:["States increasing speed and explains the same-direction condition."]}],
    ["Speed is the magnitude of velocity.","Compare the directions of v and a.","Two negative signs mean they point the same way."],["Equating negative acceleration with decreasing speed in every case."]),
  W("2.1",107,"vsaq",2,L`Two position-time lines intersect at one point but have unequal slopes there.`,[
    {prompt:"What do the objects share at the intersection, and what need not be equal?",answer:"They share the same position at the same time. Their velocities differ because their position-time slopes are unequal.",marking:["Identifies equal position and time but unequal velocities."]}],
    ["Read both coordinates at the intersection.","Velocity comes from slope, not graph height.","Compare the slopes at the shared point."],["Concluding that meeting implies equal velocity."]),
  W("2.1",108,"vsaq",2,L`A cart's velocity changes from $+3$ to $-5\,\mathrm{m\,s^{-1}}$ over $2\,\mathrm{s}$.`,[
    {prompt:"Find the average acceleration.",answer:L`$a_{\mathrm{av}}=[-5-(+3)]/2=-4\,\mathrm{m\,s^{-2}}$.`,marking:["Gives -4 m/s squared."]}],
    ["Use a signed velocity change.","Subtract positive three from negative five.","Divide by two seconds."],["Subtracting speed magnitudes."]),
  W("2.1",109,"saq",2,L`A particle has position $x=2t^2$ in SI units.`,[
    {prompt:L`Find its average velocity between $1$ and $3\,\mathrm{s}$ and its instantaneous velocity at $3\,\mathrm{s}$.`,answer:L`$v_{\mathrm{av}}=(18-2)/(3-1)=8\,\mathrm{m\,s^{-1}}$. Since $v=4t$, $v(3)=12\,\mathrm{m\,s^{-1}}$.`,marking:["Obtains average velocity 8 m/s.","Differentiates and obtains instantaneous velocity 12 m/s."]}],
    ["For the average, use endpoint positions.","For the instantaneous value, differentiate.","Do not use the final velocity as the interval average."],["Confusing average and final instantaneous velocity."]),
  W("2.1",110,"saq",3,L`A cyclist uses speeds $4$ and $12\,\mathrm{m\,s^{-1}}$ on two stages.`,[
    {prompt:"Compare the average speeds if the stages have (i) equal durations and (ii) equal distances.",answer:L`Equal durations give $(4+12)/2=8\,\mathrm{m\,s^{-1}}$. Equal distances give $2/(1/4+1/12)=6\,\mathrm{m\,s^{-1}}$.`,marking:["Obtains 8 m/s for equal times.","Obtains 6 m/s for equal distances with correct time weighting."]}],
    ["Assign a common time in the first situation.","Assign a common distance in the second.","Compute total distance over total time in each situation."],["Using an arithmetic mean for both cases."]),
  W("2.1",111,"saq",2,L`Two cyclists are $180\,\mathrm{m}$ apart and ride towards one another at constant speeds $18$ and $12\,\mathrm{m\,s^{-1}}$.`,[
    {prompt:"Find the meeting time and distance travelled by the faster cyclist.",answer:L`Closing speed is $18+12=30\,\mathrm{m\,s^{-1}}$. They meet after $180/30=6\,\mathrm{s}$; the faster cyclist covers $18(6)=108\,\mathrm{m}$.`,marking:["Obtains 6 s using closing speed.","Obtains 108 m for the faster cyclist."]}],
    ["The gap shrinks due to both motions.","Divide the initial gap by closing speed.","Use the resulting time for the faster cyclist."],["Subtracting speeds for an approaching pair."]),
  W("2.1",112,"saq",2,L`A train moves east at $7\,\mathrm{m\,s^{-1}}$. An observer walks east beside the track at $3\,\mathrm{m\,s^{-1}}$.`,[
    {prompt:"Find the train's velocity relative to the observer. If the observer reverses direction while keeping the same speed, what does it become?",answer:L`Taking east as positive, $v_{T/O}=7-3=4\,\mathrm{m\,s^{-1}}$. After reversal it is $7-(-3)=10\,\mathrm{m\,s^{-1}}$, both eastward.`,marking:["Obtains 4 m/s east initially.","Obtains 10 m/s east after the observer reverses."]}],
    ["Use train velocity minus observer velocity.","Choose one positive direction.","Change the sign of the observer's velocity, not its speed."],["Adding speeds even when both move the same way."]),
  W("2.1",113,"laq",3,L`A particle moves along a line with $x=t^3-6t^2+9t$ in SI units for $0\leq t\leq4\,\mathrm{s}$.`,[
    {prompt:"Find the instants at which the particle reverses direction.",answer:L`$v=3t^2-12t+9=3(t-1)(t-3)$. Its sign changes at $t=1$ and $3\,\mathrm{s}$, so both are reversals.`,marking:["Obtains the velocity by differentiation.","Finds 1 s and 3 s and checks sign changes."]},
    {prompt:"Find total distance, displacement and average velocity over the stated interval.",answer:L`The successive positions at $t=0,1,3,4$ are $0,4,0,4\,\mathrm{m}$. Distance $=4+4+4=12\,\mathrm{m}$, displacement $=4\,\mathrm{m}$, and average velocity $=4/4=1\,\mathrm{m\,s^{-1}}$.`,marking:["Uses the turning positions and obtains distance 12 m.","Obtains displacement 4 m.","Obtains average velocity 1 m/s."]}],
    ["Differentiate and locate zeros of velocity.","Check for direction changes around each zero.","Split distance at both turning points, but use endpoints for displacement."],["Using displacement magnitude as distance despite two reversals."]),
  W("2.1",114,"laq",3,L`A student walks $90\,\mathrm{m}$ east in $60\,\mathrm{s}$, waits $30\,\mathrm{s}$, and then walks $30\,\mathrm{m}$ west in $20\,\mathrm{s}$.`,[
    {prompt:"Find the total distance and signed displacement, taking east as positive.",answer:L`Distance is $90+30=120\,\mathrm{m}$ and displacement is $90-30=60\,\mathrm{m}$.`,marking:["Obtains distance 120 m.","Obtains displacement +60 m."]},
    {prompt:"Find average speed and average velocity for the whole journey. Explain their inequality.",answer:L`Elapsed time $=110\,\mathrm{s}$. Average speed $=120/110=12/11\,\mathrm{m\,s^{-1}}$; average velocity $=60/110=6/11\,\mathrm{m\,s^{-1}}$ east. Retracing part of the path adds distance while reducing displacement.`,marking:["Obtains average speed 12/11 m/s including the stop.","Obtains average velocity 6/11 m/s east.","Explains the effect of reversing direction."]}],
    ["Include waiting time.","Add path lengths but add displacements with signs.","Use the same total time in both averages."],["Omitting the waiting interval."]),
  W("2.1",115,"laq",3,L`A bus starts at $x=0$ and moves at $4\,\mathrm{m\,s^{-1}}$. A motorcycle starts at $x=-30\,\mathrm{m}$ at the same instant and moves at $10\,\mathrm{m\,s^{-1}}$. Both maintain constant velocity.`,[
    {prompt:"Write their position functions and determine the meeting time and coordinate.",answer:L`$x_B=4t$ and $x_M=-30+10t$. Equating them gives $6t=30$, hence $t=5\,\mathrm{s}$ and $x=20\,\mathrm{m}$.`,marking:["Writes both signed position functions.","Obtains meeting time 5 s.","Obtains meeting position 20 m."]},
    {prompt:"Describe their position-time lines and explain why equal positions at the meeting do not imply equal velocities.",answer:"Both graphs are straight. The motorcycle starts lower but has larger slope. They intersect at (5 s, 20 m), yet their slopes remain 10 and 4 m/s respectively.",marking:["Describes intercepts and relative slopes correctly.","Distinguishes an intersection from equal slopes."]}],
    ["Include the motorcycle's negative starting coordinate.","Set positions equal, not velocities.","Slopes remain unchanged at a crossing."],["Ignoring the motorcycle's initial offset."]),
  W("2.1",116,"case",3,"A cart's motion along a straight track is shown in the position-time graph.",[
    {prompt:"Find its velocities during 0-2 s and 4-6 s.",answer:L`The slopes give $(4-(-4))/2=4\,\mathrm{m\,s^{-1}}$ and $(-2-4)/2=-3\,\mathrm{m\,s^{-1}}$.`,marking:["Obtains +4 m/s in the first segment.","Obtains -3 m/s in the final segment."]},
    {prompt:"Find the total distance and explain the flat middle segment.",answer:L`Distance $=8+0+6=14\,\mathrm{m}$. From 2 to 4 s the position stays at 4 m, so the cart is at rest.`,marking:["Obtains total distance 14 m.","Interprets the flat segment as rest, not zero position."]}],
    ["Read positions at the segment endpoints.","Divide each signed position change by its duration.","For distance add magnitudes, including zero for the wait."],["Reading the height of a position graph as velocity."],positionGraph),
  W("2.1",117,"case",3,L`A camera records a trolley at positions $0$, $3$ and $8\,\mathrm{m}$ at times $0$, $1$ and $2\,\mathrm{s}$ respectively. A student says the data prove that acceleration was constant throughout.`,[
    {prompt:"Find the average velocity in each one-second interval.",answer:L`The interval averages are $(3-0)/1=3\,\mathrm{m\,s^{-1}}$ and $(8-3)/1=5\,\mathrm{m\,s^{-1}}$.`,marking:["Obtains 3 m/s and 5 m/s."]},
    {prompt:"If uniform acceleration is assumed, find initial velocity and acceleration.",answer:L`$u+a/2=3$ and $u+3a/2=5$, so $a=2\,\mathrm{m\,s^{-2}}$ and $u=2\,\mathrm{m\,s^{-1}}$.`,marking:["Sets up the two constant-acceleration displacement equations.","Obtains u=2 m/s and a=2 m/s squared."]},
    {prompt:"Is the student's claim proved by these three positions alone?",answer:"No. A uniformly accelerated model fits the observations, but non-uniform motion between camera frames can fit the same three positions.",marking:["Distinguishes a consistent model from proof of constant acceleration."]}],
    ["Start with what the discrete observations directly establish.","For the conditional calculation, use a single u and a.","Ask whether unobserved between-frame motion is uniquely known."],["Confusing a fitted model with uniquely determined motion."]),
  W("2.1",118,"case",3,L`A delivery vehicle must cover $120\,\mathrm{km}$ in $3\,\mathrm{h}$. It covers the first $60\,\mathrm{km}$ at $30\,\mathrm{km\,h^{-1}}$, without stops.`,[
    {prompt:"Find the time left and required average speed for the remaining distance.",answer:L`The first half takes $60/30=2\,\mathrm{h}$. One hour remains, requiring $60/1=60\,\mathrm{km\,h^{-1}}$.`,marking:["Finds 1 h remaining.","Obtains required remaining average speed 60 km/h."]},
    {prompt:L`The vehicle instead stops for $0.25\,\mathrm{h}$ before resuming. What average moving speed is then required, and why is the whole-trip average not the mean of 30 and this speed?`,answer:L`Only $0.75\,\mathrm{h}$ remains for motion, so the required speed is $60/0.75=80\,\mathrm{km\,h^{-1}}$. Stage durations differ and the stop adds elapsed time; the whole-trip average remains $120/3=40\,\mathrm{km\,h^{-1}}$.`,marking:["Obtains 80 km/h after allowing for the stop.","Explains elapsed-time weighting rather than an arithmetic mean."]}],
    ["Budget the full three-hour duration.","Subtract the first-stage time and then the stop.","The required average uses all elapsed time, including waiting."],["Averaging speeds without their durations."]),
  W("2.2",101,"vsaq",2,L`A trolley increases speed uniformly from $2$ to $14\,\mathrm{m\,s^{-1}}$ in $3\,\mathrm{s}$.`,[
    {prompt:"Find its displacement during these three seconds.",answer:L`$s=(u+v)t/2=(2+14)(3)/2=24\,\mathrm{m}$.`,marking:["Uses the mean velocity and obtains 24 m."]}],
    ["Velocity changes linearly.","Average the initial and final velocities.","Multiply by the duration."],["Using final speed for the entire motion."]),
  W("2.2",102,"vsaq",2,L`A body moving at $21\,\mathrm{m\,s^{-1}}$ slows uniformly at $3\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Find the time to first come to rest.",answer:L`$0=21-3t$ gives $t=7\,\mathrm{s}$.`,marking:["Obtains 7 s with the deceleration sign handled correctly."]}],
    ["Use v=u+at.","Final velocity is zero.","Use a negative acceleration in the direction convention of the initial motion."],["Adding the deceleration to initial velocity."]),
  W("2.2",103,"vsaq",2,L`A pebble is released from rest and falls through $20\,\mathrm{m}$. Take $g=10\,\mathrm{m\,s^{-2}}$ and neglect air resistance.`,[
    {prompt:"Find the fall time.",answer:L`$20=\tfrac12(10)t^2$, so $t=2\,\mathrm{s}$, taking the positive root.`,marking:["Obtains the physical root t=2 s."]}],
    ["Initial velocity is zero.","Use distance equals half g times time squared.","Elapsed time cannot be negative."],["Using distance divided by g as a time."]),
  W("2.2",104,"vsaq",2,L`A ball is thrown vertically upwards at $12\,\mathrm{m\,s^{-1}}$. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Find its maximum rise above the launch point.",answer:L`At the top, $v=0$, so $h=u^2/(2g)=144/20=7.2\,\mathrm{m}$.`,marking:["Obtains 7.2 m."]}],
    ["Velocity vanishes at the top.","Use the equation that eliminates time.","Solve for the upward displacement."],["Setting acceleration to zero at the top."]),
  W("2.2",105,"vsaq",2,L`A car's acceleration remains zero for $5\,\mathrm{s}$ while it has initial velocity $-3\,\mathrm{m\,s^{-1}}$.`,[
    {prompt:"Find the displacement in this interval.",answer:L`Velocity remains $-3\,\mathrm{m\,s^{-1}}$, so displacement is $(-3)(5)=-15\,\mathrm{m}$.`,marking:["Gives -15 m, not zero."]}],
    ["Zero acceleration means constant velocity.","The given constant velocity is not zero.","Multiply signed velocity by time."],["Treating zero acceleration as rest."]),
  W("2.2",106,"vsaq",2,L`A particle has $v=5-2t$ in SI units.`,[
    {prompt:"When does it first reverse direction after t=0?",answer:L`$v=0$ at $t=2.5\,\mathrm{s}$. The velocity changes from positive to negative there, so it reverses at 2.5 s.`,marking:["Finds 2.5 s and recognises the sign change."]}],
    ["Locate zero velocity.","Check the velocity sign just before and after.","A sign change confirms reversal."],["Assuming every zero of velocity necessarily implies a reversal."]),
  W("2.2",107,"saq",3,L`A car at $10\,\mathrm{m\,s^{-1}}$ accelerates at $2\,\mathrm{m\,s^{-2}}$ for $3\,\mathrm{s}$, then continues at the attained speed for $4\,\mathrm{s}$.`,[
    {prompt:"Find the distance travelled during the complete seven seconds.",answer:L`First-stage final speed is $16\,\mathrm{m\,s^{-1}}$ and distance $=10(3)+\tfrac12(2)(9)=39\,\mathrm{m}$. Cruise distance $=16(4)=64\,\mathrm{m}$. Total $=103\,\mathrm{m}$.`,marking:["Obtains 16 m/s and first-stage distance 39 m.","Adds the 64 m cruise distance to obtain 103 m."]}],
    ["Treat the stages separately.","Carry final velocity from stage one into stage two.","Only the first stage has acceleration."],["Applying the first acceleration over all seven seconds."]),
  W("2.2",108,"saq",3,L`A lift moving upwards at $4\,\mathrm{m\,s^{-1}}$ has constant downward acceleration $2\,\mathrm{m\,s^{-2}}$ for $3\,\mathrm{s}$.`,[
    {prompt:"Find its displacement and total distance travelled.",answer:L`It stops after $2\,\mathrm{s}$, rising $4(2)-2^2=4\,\mathrm{m}$. In the final second it descends $1\,\mathrm{m}$. Displacement is $3\,\mathrm{m}$ upwards and distance is $5\,\mathrm{m}$.`,marking:["Locates reversal at 2 s and obtains 4 m up followed by 1 m down.","Gives displacement +3 m and distance 5 m."]}],
    ["Find the stopping instant first.","Split the path there for distance.","For displacement, combine the signed changes."],["Assuming downward acceleration means downward motion from the start."]),
  W("2.2",109,"saq",3,L`A train moving at $9\,\mathrm{m\,s^{-1}}$ must stop within $27\,\mathrm{m}$ with uniform braking and no reaction delay.`,[
    {prompt:"Find the minimum deceleration magnitude and the corresponding stopping time.",answer:L`$|a|=u^2/(2s)=81/54=1.5\,\mathrm{m\,s^{-2}}$. Then $t=u/|a|=9/1.5=6\,\mathrm{s}$.`,marking:["Obtains minimum deceleration 1.5 m/s squared.","Obtains stopping time 6 s."]}],
    ["A smaller deceleration gives a longer stopping distance.","Set the maximum allowed distance equal to 27 m.","Use the resulting deceleration to determine time."],["Calling the signed negative acceleration a negative magnitude."]),
  W("2.2",110,"laq",3,L`A ball is thrown upwards from a $25\,\mathrm{m}$ high platform at $20\,\mathrm{m\,s^{-1}}$. Take $g=10\,\mathrm{m\,s^{-2}}$ and ground level as y=0.`,[
    {prompt:"Write y(t) and find the greatest height above the ground.",answer:L`$y=25+20t-5t^2$. The top occurs at $t=2\,\mathrm{s}$, where $y=45\,\mathrm{m}$.`,marking:["Writes the position equation with initial height 25 m.","Obtains greatest height 45 m."]},
    {prompt:"Find when and with what velocity it reaches the ground.",answer:L`$0=25+20t-5t^2$ gives $t=5$ or $-1\,\mathrm{s}$. The physical time is $5\,\mathrm{s}$; $v=20-10(5)=-30\,\mathrm{m\,s^{-1}}$, downward.`,marking:["Solves the quadratic and selects 5 s.","Obtains 30 m/s downwards.","Rejects the negative-time root for this flight."]}],
    ["Include the starting height.","The highest point has zero velocity.","Ground impact is y=0, not return to launch level."],["Using the symmetric return-to-launch time as ground-impact time."]),
  W("2.2",111,"laq",3,L`A car travels at $20\,\mathrm{m\,s^{-1}}$. The driver reacts for $0.5\,\mathrm{s}$ and then brakes at constant deceleration $4\,\mathrm{m\,s^{-2}}$. An obstacle is $55\,\mathrm{m}$ ahead at the initial instant.`,[
    {prompt:"Determine whether the car stops before the obstacle.",answer:L`Reaction distance $=20(0.5)=10\,\mathrm{m}$. Braking distance $=20^2/(2\times4)=50\,\mathrm{m}$. Total stopping distance $=60\,\mathrm{m}>55\,\mathrm{m}$, so it does not stop in time.`,marking:["Obtains reaction distance 10 m.","Obtains braking distance 50 m.","Concludes stopping requires 60 m, exceeding the available distance."]},
    {prompt:"Find the speed at the obstacle under this model.",answer:L`After reaction, the remaining distance is $45\,\mathrm{m}$. Thus $v^2=400-2(4)(45)=40$, giving $v=2\sqrt{10}\,\mathrm{m\,s^{-1}}$.`,marking:["Uses 45 m as braking distance before the obstacle.",L`Obtains $2\sqrt{10}\,\mathrm{m\,s^{-1}}$.`]}],
    ["Compute reaction distance before applying braking.","Compare total stopping distance with the obstacle gap.","For impact speed use only the distance over which braking acts."],["Applying braking throughout the reaction interval."]),
  W("2.2",112,"laq",3,L`A particle initially at rest accelerates at $3\,\mathrm{m\,s^{-2}}$ for $4\,\mathrm{s}$ and then at $-2\,\mathrm{m\,s^{-2}}$ for $8\,\mathrm{s}$.`,[
    {prompt:"Find the velocity after each stage and the net displacement.",answer:L`After stage one, $v_1=12\,\mathrm{m\,s^{-1}}$ and $s_1=24\,\mathrm{m}$. After stage two, $v_2=12-16=-4\,\mathrm{m\,s^{-1}}$ and $s_2=12(8)-8^2=32\,\mathrm{m}$. Net displacement is $56\,\mathrm{m}$.`,marking:["Obtains intermediate velocity +12 m/s and final velocity -4 m/s.","Obtains stage displacements 24 m and 32 m.","Obtains net displacement 56 m."]},
    {prompt:"Find total distance travelled, allowing for any reversal.",answer:L`In stage two, stopping takes $12/2=6\,\mathrm{s}$ and adds $36\,\mathrm{m}$ forward. The last 2 s add $4\,\mathrm{m}$ backwards. Total distance is $24+36+4=64\,\mathrm{m}$.`,marking:["Locates the reversal 6 s into stage two.","Obtains total distance 64 m."]}],
    ["Carry velocity continuously across the stage boundary.","Find whether velocity changes sign during the second stage.","Split only the distance calculation at that reversal."],["Using signed net displacement for total distance."]),
  W("2.2",113,"laq",3,L`Two balls are released from rest from the same high point, the second $1\,\mathrm{s}$ after the first. Take $g=10\,\mathrm{m\,s^{-2}}$; neither ball has reached the ground during the times considered.`,[
    {prompt:"Find their separation 3 s after the first release.",answer:L`The first has fallen $5(3^2)=45\,\mathrm{m}$ and the second $5(2^2)=20\,\mathrm{m}$. Separation is $25\,\mathrm{m}$.`,marking:["Uses elapsed fall times 3 s and 2 s.","Obtains separation 25 m."]},
    {prompt:"Show that their relative speed is constant after the second release, and obtain the separation as a function of time t measured from the first release.",answer:L`For $t\geq1$, $v_1-v_2=10t-10(t-1)=10\,\mathrm{m\,s^{-1}}$. Separation is $5[t^2-(t-1)^2]=10t-5\,\mathrm{m}$ before impact.`,marking:["Shows relative speed is 10 m/s.","Obtains separation 10t-5 m.","States the domain t>=1 while both remain in free fall."]}],
    ["Give each ball its own elapsed fall time.","Subtract the velocities after both are falling.","Their equal accelerations cancel in relative motion."],["Using t instead of t-1 for the second ball."]),
  W("2.2",114,"case",3,"A laboratory trolley follows the velocity-time graph shown.",[
    {prompt:"Find the acceleration in the first and final sloping segments.",answer:L`First segment: $(6-2)/2=2\,\mathrm{m\,s^{-2}}$. Final segment: $(0-6)/(7-5)=-3\,\mathrm{m\,s^{-2}}$.`,marking:["Obtains +2 m/s squared initially.","Obtains -3 m/s squared finally."]},
    {prompt:"Find the total distance travelled.",answer:L`The three positive areas are a trapezium $\tfrac12(2+6)(2)=8\,\mathrm{m}$, rectangle $6(3)=18\,\mathrm{m}$, and triangle $\tfrac12(2)(6)=6\,\mathrm{m}$. Total is $32\,\mathrm{m}$.`,marking:["Calculates the three areas as 8, 18 and 6 m.","Obtains 32 m; velocity never becomes negative."]}],
    ["Read segment boundaries from the time scale.","Slopes give acceleration.","Add areas below all three positive-velocity segments."],["Treating the initial segment as a triangle despite non-zero initial velocity."],cruiseGraph),
  W("2.2",115,"case",3,"A particle's velocity-time graph is shown. It starts at the coordinate origin.",[
    {prompt:"Find the time of reversal and its position then.",answer:L`It reverses at $3\,\mathrm{s}$ where v crosses zero. Its position then is the positive triangular area $\tfrac12(3)(6)=9\,\mathrm{m}$.`,marking:["Identifies reversal at 3 s.","Obtains x=9 m at reversal."]},
    {prompt:"Find its final position and total distance at 5 s.",answer:L`The later signed area is $-\tfrac12(2)(4)=-4\,\mathrm{m}$. Final position $=9-4=5\,\mathrm{m}$; distance $=9+4=13\,\mathrm{m}$.`,marking:["Obtains final position +5 m.","Obtains distance 13 m."]}],
    ["Velocity sign gives direction.","Use signed area for coordinate changes.","Add magnitudes for the distance."],["Assuming negative final velocity means negative final position."],signedGraph),
  W("2.2",116,"case",3,L`A car is initially stationary at a traffic light. It accelerates uniformly at $2\,\mathrm{m\,s^{-2}}$ for $5\,\mathrm{s}$, then travels at constant speed. At t=0 a second vehicle passes the light at constant speed $6\,\mathrm{m\,s^{-1}}$. Both move in the same direction.`,[
    {prompt:"Find each vehicle's position at 5 s and state which is ahead.",answer:L`The accelerating car is at $\tfrac12(2)(25)=25\,\mathrm{m}$; the second vehicle is at $6(5)=30\,\mathrm{m}$. The second is 5 m ahead.`,marking:["Obtains positions 25 m and 30 m.","Identifies the 5 m gap."]},
    {prompt:"Find when the car catches the other vehicle, measured from t=0.",answer:L`After 5 s the car travels at 10 m/s, so the gap closes at $10-6=4\,\mathrm{m\,s^{-1}}$. Catch-up takes an additional $5/4=1.25\,\mathrm{s}$, hence $6.25\,\mathrm{s}$ from t=0.`,marking:["Uses the post-acceleration closing speed 4 m/s.","Obtains total time 6.25 s."]}],
    ["Check whether catch-up occurs before the acceleration ends.","Carry the gap and final speed into the constant-speed stage.","Add the extra catch-up time to five seconds."],["Extending the 2 m/s squared acceleration beyond five seconds."]),
  W("2.2",117,"case",3,L`A ball is thrown upwards at $30\,\mathrm{m\,s^{-1}}$ from ground level. A camera takes a frame every $1\,\mathrm{s}$. Take $g=10\,\mathrm{m\,s^{-2}}$ and ignore air resistance.`,[
    {prompt:"Find its heights at 2 s and 4 s, and velocities at those instants.",answer:L`$y=30t-5t^2$ gives $y(2)=40\,\mathrm{m}$ and $y(4)=40\,\mathrm{m}$. $v=30-10t$ gives $+10$ and $-10\,\mathrm{m\,s^{-1}}$.`,marking:["Obtains equal heights of 40 m.","Obtains signed velocities +10 and -10 m/s."]},
    {prompt:"Find the distance travelled between these frames and explain why it is not zero.",answer:L`The maximum height at 3 s is 45 m. The ball rises 5 m and falls 5 m between the frames, so distance is 10 m even though displacement is zero.`,marking:["Uses the intervening maximum height 45 m.","Obtains distance 10 m and distinguishes it from zero displacement."]}],
    ["Equal heights may occur during ascent and descent.","Locate the highest point between the frames.","Add both parts of the path, not just the endpoint difference."],["Inferring zero distance from two equal-height observations."]),
];
