import { expansionBank } from "../expansion-helpers";
import { kinematicsGraph } from "../kinematics-graph";
const { mc: M, written: W } = expansionBank("u4-work-energy-power", "u4");
const L = String.raw;
const workGraph = kinematicsGraph("Position-dependent net force", "F (N)", [[0,4],[2,4],[4,-4],[6,-4]], [0,2,3,4,6], [-4,0,4], "x (m)");

export const energyExpansion = [
  M("4.1",101,2,L`A constant force $(3\hat i-4\hat j)\,\mathrm{N}$ acts during displacement $(2\hat i+\hat j)\,\mathrm{m}$. The work done is`,L`$2\,\mathrm{J}$`,[
    [L`$10\,\mathrm{J}$`,"The y contribution is negative, not positive."],[L`$5\sqrt5\,\mathrm{J}$`,"Multiplying magnitudes assumes force and displacement are parallel."],[L`$-2\,\mathrm{J}$`,"The positive x contribution is 6 J and exceeds the 4 J negative contribution."]],
    L`$W=\vec F\cdot\vec s=3(2)+(-4)(1)=2\,\mathrm{J}$.`,["Use the scalar product.","Multiply corresponding components.","Keep the negative sign in the y force." ]),
  M("4.1",102,3,L`A force along the x-axis is $F_x=6-2x$ in SI units. Its work as a particle moves from x=1 m to x=4 m is`,L`$3\,\mathrm{J}$`,[
    [L`$9\,\mathrm{J}$`,"The force changes sign; not all the work contributions are positive."],[L`$12\,\mathrm{J}$`,"The force at the starting point does not remain constant."],[L`$-6\,\mathrm{J}$`,"Using only the final force ignores its variation along the path."]],
    L`$W=\int_1^4(6-2x)\,dx=[6x-x^2]_1^4=8-5=3\,\mathrm{J}$.`,["Integrate the position-dependent force.","Evaluate at both stated endpoints.","The force becomes negative beyond x=3 m." ]),
  M("4.1",103,2,"Assertion (A): If a force does zero work on a moving particle, that force must be zero. Reason (R): A force perpendicular to instantaneous velocity has zero instantaneous power.","A is false, but R is true.",[
    ["Both A and R are true, and R explains A.","A non-zero perpendicular force is a counterexample to A."],["Both A and R are true, but R does not explain A.","A is false, not merely unexplained."],["A is true, but R is false.","The scalar product of perpendicular force and velocity vanishes."]],
    L`Power is $\vec F\cdot\vec v$. A non-zero force can stay perpendicular to motion and do no work, as the inward force does in uniform circular motion.`,["Recall the angle in the work or power expression.","Consider uniform circular motion.","Zero scalar product does not require either vector to vanish." ]),
  W("4.1",101,"vsaq",2,L`A constant force does $-24\,\mathrm{J}$ of work over a displacement of $6\,\mathrm{m}$.`,[
    {prompt:"Find its component along the displacement.",answer:L`$F_{\parallel}=W/s=-24/6=-4\,\mathrm{N}$, opposite to the displacement.`,marking:["Obtains a -4 N component, with direction interpreted."]}],
    ["Only the parallel component contributes to work.","Divide signed work by displacement magnitude.","Interpret the negative sign."],["Treating negative work as a negative force magnitude."]),
  W("4.1",102,"saq",2,L`A person carries a $6\,\mathrm{kg}$ bag up a staircase with vertical rise $4\,\mathrm{m}$. The bag moves at constant speed, and the person's support force is vertical. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Find work done on the bag by the person and by gravity, and the net work.",answer:L`The support force equals mg. Its work is $+mgh=+240\,\mathrm{J}$; gravity does $-240\,\mathrm{J}$. Net work is zero, consistent with constant kinetic energy.`,marking:["Gives signed works +240 J and -240 J.","Gives zero net work and connects it to unchanged speed."]}],
    ["Only vertical displacement contributes to each vertical force's work.","The two forces act in opposite directions.","Use constant speed as an energy check."],["Concluding that each individual work must vanish because net work is zero."]),
  W("4.1",103,"case",3,L`The graph shows the net force on a particle moving along the positive x-axis from x=0 to x=6 m. Its initial kinetic energy is 9 J.`,[
    {prompt:"Find the work from 0 to 4 m and from 0 to 6 m.",answer:L`From 0 to 2 m the area is 8 J. From 2 to 4 m equal positive and negative triangles cancel. Thus $W_{0\to4}=8\,\mathrm{J}$. From 4 to 6 m the work is -8 J, so $W_{0\to6}=0$.`,marking:["Obtains 8 J to x=4 m using signed areas.","Includes the final negative area to obtain zero total work."]},
    {prompt:"Where is kinetic energy greatest, and what is its value?",answer:L`Kinetic energy increases while F is positive and decreases while F is negative, so its maximum occurs at x=3 m. Work up to there is $8+\tfrac12(1)(4)=10\,\mathrm{J}$, giving $K_{\max}=9+10=19\,\mathrm{J}$.`,marking:["Identifies x=3 m from the force sign change.","Obtains maximum kinetic energy 19 J."]}],
    ["Use signed force-displacement areas.","Kinetic-energy change equals net work.","Locate where accumulating work stops increasing."],["Using the magnitude of all areas or identifying largest force with largest kinetic energy."],workGraph),
  M("4.2",101,2,"Two bodies have the same non-zero momentum. The first has three times the mass of the second. Their kinetic energies, first to second, are in the ratio","1:3",[
    ["3:1","At fixed momentum, kinetic energy is inversely proportional to mass."],["1:9","The mass appears to the first power in p squared over 2m."],["1:1","Equal momentum does not require equal kinetic energy."]],
    L`$K=p^2/(2m)$. Equal p gives $K_1/K_2=m_2/m_1=1/3$.`,["Express kinetic energy using momentum.","Hold momentum, not speed, constant.","Compare the masses in the denominator." ]),
  M("4.2",102,3,L`A $2\,\mathrm{kg}$ block enters a rough horizontal strip at $4\,\mathrm{m\,s^{-1}}$. Friction has constant magnitude $5\,\mathrm{N}$ and the strip is $4\,\mathrm{m}$ long. The block`,L`stops $3.2\,\mathrm{m}$ into the strip`,[
    [L`leaves with kinetic energy $-4\,\mathrm{J}$`,"Negative kinetic energy means the assumed exit cannot be reached."],[L`leaves with speed $2\,\mathrm{m\,s^{-1}}$`,"The strip can remove more than the available 16 J."],[L`stops exactly at the far end`,"The stopping distance is initial kinetic energy divided by friction."]],
    L`Initial energy is $\tfrac12(2)(4^2)=16\,\mathrm{J}$. It is exhausted after $s=16/5=3.2\,\mathrm{m}<4\,\mathrm{m}$.`,["Calculate available initial kinetic energy.","Compare with work needed to cross the whole strip.","If that is too large, solve for stopping distance instead." ]),
  M("4.2",103,2,"A body's speed increases by 50% while its mass remains constant. Its kinetic energy increases by","125%",[
    ["50%","Kinetic energy is quadratic in speed."],["225%","225% is the final energy as a percentage of the original, not the increase."],["25%","Square the full factor 1.5, then subtract one."]],
    L`$K_f/K_i=(1.5)^2=2.25$. The increase is $(2.25-1)\times100\%=125\%$.`,["Convert the speed change to a factor.","Square that factor.","Subtract the original 100% to obtain the increase." ]),
  W("4.2",101,"vsaq",2,"A particle's momentum reverses direction without changing magnitude, and its mass remains constant.",[
    {prompt:"What is the net work done during this change?",answer:L`Zero, because $K=p^2/(2m)$ is unchanged. The impulse is not zero, since momentum is a vector.`,marking:["Gives zero net work using unchanged kinetic energy."]}],
    ["Work changes kinetic energy.","Kinetic energy depends on momentum magnitude squared.","Do not equate non-zero impulse with non-zero work."],["Using momentum change directly as work."]),
  W("4.2",102,"saq",3,L`A $1\,\mathrm{kg}$ particle moves along x with speed satisfying $v^2=9+4x$ in SI units.`,[
    {prompt:"Use work-energy reasoning to find the net force along x.",answer:L`$K=\tfrac12(9+4x)=4.5+2x$ joules. Since $F_x=dK/dx$, the net force is $2\,\mathrm{N}$ along positive x.`,marking:["Obtains kinetic energy as a function of position.","Uses its position derivative to obtain +2 N."]}],
    ["Express kinetic energy as a function of x.","A small displacement gives dK=F dx.","Differentiate with respect to position, not time."],["Differentiating v squared and forgetting the mass-over-two factor."]),
  W("4.2",103,"laq",4,L`A $2\,\mathrm{kg}$ block is projected up a rough $30^\circ$ incline at $6\,\mathrm{m\,s^{-1}}$. The coefficient of kinetic friction is $1/(2\sqrt3)$; take $g=10\,\mathrm{m\,s^{-2}}$. At the turning point it begins sliding down immediately.`,[
    {prompt:"Find how far the block travels up the slope.",answer:L`Initial energy is 36 J. Gravity's opposing component is 10 N and friction is $\mu_kmg\cos30^\circ=5\,\mathrm{N}$. Thus $36=(10+5)s$, giving $s=2.4\,\mathrm{m}$.`,marking:["Obtains gravity component 10 N and friction 5 N.","Uses the 36 J initial energy.","Obtains upward distance 2.4 m."]},
    {prompt:"Find its speed on returning to the launch point and explain the energy loss over the round trip.",answer:L`On descent gravity does 24 J while friction does -12 J. Return kinetic energy is 12 J, so $v=\sqrt{12}=2\sqrt3\,\mathrm{m\,s^{-1}}$. Friction dissipates $5(2\times2.4)=24\,\mathrm{J}$ over the full path; gravity's net work is zero.`,marking:["Obtains return kinetic energy 12 J and speed 2 square root of 3 m/s.","Accounts for total frictional loss 24 J and zero net gravity work."]}],
    ["Friction opposes motion on both legs.","Its direction reverses at the turn; gravity's slope component does not.","Use each stage's signed work rather than reversing the entire ascent equation."],["Making friction do positive work on the descent."]),
  M("4.3",101,2,L`A force $(4\hat i-3\hat j)\,\mathrm{N}$ acts on a particle with velocity $(2\hat i+\hat j)\,\mathrm{m\,s^{-1}}$. Its instantaneous power is`,L`$5\,\mathrm{W}$`,[
    [L`$11\,\mathrm{W}$`,"The y contribution is negative."],[L`$5\sqrt5\,\mathrm{W}$`,"Force and velocity are not parallel, so multiplying magnitudes is incorrect."],[L`$-5\,\mathrm{W}$`,"The positive x contribution exceeds the negative y contribution."]],
    L`$P=\vec F\cdot\vec v=4(2)-3(1)=5\,\mathrm{W}$.`,["Use a dot product for power.","Multiply corresponding components.","Preserve their signs." ]),
  M("4.3",102,3,L`A vehicle's engine delivers constant useful power while it moves on a level road with negligible resistance. If speed doubles, the driving force becomes`,"half its previous value",[
    ["twice its previous value","At fixed power, P=Fv makes force inversely proportional to speed."],["unchanged","That would double the power."],["one-quarter its previous value","Force depends on inverse speed, not inverse speed squared, here."]],
    L`For force along the velocity, $F=P/v$. Constant P and doubled v imply force $F/2$. This idealisation applies at non-zero speeds.`,["Relate power to force and speed.","Hold power constant.","Solve for force before scaling." ]),
  M("4.3",103,2,L`A motor draws $800\,\mathrm{W}$ and has efficiency 75%. Its useful output in 5 s is`,L`$3000\,\mathrm{J}$`,[
    [L`$4000\,\mathrm{J}$`,"This is total input energy."],[L`$600\,\mathrm{J}$`,"600 is useful power in watts, not energy over five seconds."],[L`$1000\,\mathrm{J}$`,"This is the lost energy, not the useful output."]],
    L`Useful power is $0.75(800)=600\,\mathrm{W}$. Useful energy is $600(5)=3000\,\mathrm{J}$.`,["Apply efficiency to input power.","Multiply useful power by the duration.","Keep energy and power units distinct." ]),
  W("4.3",101,"vsaq",2,"A force is perpendicular to a particle's velocity at an instant.",[
    {prompt:"Find the instantaneous power supplied by that force, even if the force is non-zero.",answer:L`$P=Fv\cos90^\circ=0$.`,marking:["Gives zero power using perpendicular force and velocity."]}],
    ["Use the force-velocity scalar product.","Insert the angle between them.","Non-zero force does not by itself imply non-zero power."],["Multiplying magnitudes without the angle factor."]),
  W("4.3",102,"vsaq",2,L`A motor delivers $1.2\,\mathrm{kW}$ of useful power while its input is $1.5\,\mathrm{kW}$.`,[
    {prompt:"Find its efficiency.",answer:L`$\eta=P_{\mathrm{out}}/P_{\mathrm{in}}=1.2/1.5=0.80=80\%$.`,marking:["Gives 80% as output divided by input."]}],
    ["Identify input and useful output separately.","Use output divided by input.","Equal units cancel before converting to percent."],["Reversing the power ratio and obtaining efficiency above 100%."]),
  W("4.3",103,"case",3,L`A $100\,\mathrm{kg}$ load is raised vertically from rest with constant upward acceleration $0.5\,\mathrm{m\,s^{-2}}$ for 4 s. Ignore losses and take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Find the lifting force and instantaneous power at 4 s.",answer:L`$F=m(g+a)=1050\,\mathrm{N}$. Speed at 4 s is 2 m/s, so $P=Fv=2100\,\mathrm{W}$.`,marking:["Includes both weight and acceleration in the 1050 N lifting force.","Obtains final instantaneous power 2100 W."]},
    {prompt:"Find average power over the four seconds and explain why it differs from the final value.",answer:L`Rise is $\tfrac12(0.5)(4^2)=4\,\mathrm{m}$. Work is $1050(4)=4200\,\mathrm{J}$, so average power is 1050 W. Force is constant but speed and instantaneous power rise from zero; the final power is not the interval average.`,marking:["Obtains average power 1050 W from total work.","Explains the changing speed and therefore changing instantaneous power."]}],
    ["The lifting force must accelerate the load as well as support it.","Use final velocity for final instantaneous power.","Use total work divided by time for average power."],["Taking the final power as constant throughout the lift."]),
  M("4.4",101,2,L`A spring stores energy U when stretched by x within its elastic limit. To store 9U, the extension must be`,"3x",[
    ["9x","Spring energy is proportional to extension squared."],["x/3","Reducing extension cannot increase stored energy."],["81x","Take the square root of the energy ratio."]],
    L`$U=\tfrac12kx^2$. Therefore $x'/x=\sqrt{U'/U}=3$.`,["Keep the same spring constant.","Energy varies as extension squared.","Take the square root to infer extension." ]),
  M("4.4",102,3,L`A one-dimensional potential is $U(x)=2x^2-8x+10$ joules, with x in metres. At x=1 m the force is`,L`$+4\,\mathrm{N}$`,[
    [L`$-4\,\mathrm{N}$`,"Force is minus the potential derivative."],[L`$+2\,\mathrm{N}$`,"2 J is the minimum potential, not the force at this point."],[L`$0\,\mathrm{N}$`,"Force vanishes at x=2 m, not x=1 m."]],
    L`$F_x=-dU/dx=8-4x$. At x=1 m this is +4 N.`,["Differentiate potential with respect to position.","Include the minus sign.","Then substitute the stated position." ]),
  M("4.4",103,2,"Adding a constant C to a gravitational potential-energy function changes","neither the force nor potential-energy differences",[
    ["the force but not the differences","The derivative of a constant vanishes."],["the differences but not the force","The same constant cancels when energies at two points are subtracted."],["both force and differences","Neither differentiation nor endpoint subtraction retains the added constant."]],
    L`$F=-d(U+C)/dx=-dU/dx$ and $(U_2+C)-(U_1+C)=U_2-U_1$. The zero of potential energy is a reference choice.`,["Consider the derivative of a constant.","Also subtract values at two positions.","Absolute reference and measurable differences are distinct." ]),
  W("4.4",101,"vsaq",2,"Gravity does +45 J of work on an object between two points.",[
    {prompt:"What is the change in gravitational potential energy?",answer:L`For a conservative force, $\Delta U=-W_g=-45\,\mathrm{J}$.`,marking:["Gives a decrease of 45 J."]}],
    ["Use work by the conservative force, not work against it.","Potential-energy change has the opposite sign.","Positive gravity work corresponds to decreasing potential energy."],["Assigning the same sign to gravity work and potential-energy change."]),
  W("4.4",102,"saq",3,L`A horizontal spring has force constant $300\,\mathrm{N\,m^{-1}}$. It is stretched slowly from 0.10 m to 0.20 m beyond its natural length.`,[
    {prompt:"Find the additional work done by the external stretching force.",answer:L`Slow stretching gives $W_{\mathrm{ext}}=\Delta U=\tfrac12(300)(0.20^2-0.10^2)=4.5\,\mathrm{J}$. This is the difference of two stored energies, not the energy of a 0.10 m extension from natural length.`,marking:["Uses the difference of squared extensions.","Obtains positive additional work 4.5 J."]}],
    ["The initial spring already stores energy.","Subtract initial energy from final energy.","Do not square only the extension change."],["Using one-half k times the square of the extension increment."]),
  W("4.4",103,"laq",4,L`A $1\,\mathrm{kg}$ block moving at $4\,\mathrm{m\,s^{-1}}$ contacts an uncompressed horizontal spring of constant $200\,\mathrm{N\,m^{-1}}$. During compression, a constant $20\,\mathrm{N}$ friction force opposes the block.`,[
    {prompt:"Find the maximum compression.",answer:L`At the first stop, $8=100x^2+20x$. This gives $100x^2+20x-8=0$, with positive root $x=0.20\,\mathrm{m}$; the negative root is not a compression length.`,marking:["Includes both elastic energy and frictional loss.","Forms the correct quadratic.","Selects physical root 0.20 m."]},
    {prompt:"How is the initial kinetic energy distributed at this instant? Can the block's first zero speed alone prove it stays at rest?",answer:L`The spring stores $100(0.20)^2=4\,\mathrm{J}$ and friction has dissipated $20(0.20)=4\,\mathrm{J}$. Zero instantaneous speed does not establish equilibrium; whether it remains at rest requires the available static-friction limit, which is not given.`,marking:["Accounts for 4 J stored and 4 J dissipated.","Distinguishes a turning point from equilibrium and identifies the missing static-friction information."]}],
    ["Apply work-energy only through the first stopping point.","Friction acts throughout the compression distance.","Do not use kinetic friction to decide a later static equilibrium."],["Ignoring frictional work or assuming every zero-speed state is permanent rest."]),
  M("4.5",101,2,L`Two equal masses approach one another at speeds $3\,\mathrm{m\,s^{-1}}$ and stick together. What fraction of their initial kinetic energy is lost?`,"All of it",[
    ["One-half","Equal opposite momenta make the final body stationary."],["None","Momentum conservation does not require kinetic-energy conservation."],["One-quarter","The final kinetic energy is zero, not three-quarters of the original."]],
    "Initial total momentum is zero, so the joined body is at rest. Its final kinetic energy is zero and all initial kinetic energy has changed into other forms.",["Assign opposite signs to the initial velocities.","Find the common final velocity from momentum.","Compare kinetic energies before and after." ]),
  M("4.5",102,3,L`A light rigid rod of length r keeps a particle in a vertical circle about a fixed pivot. Unlike a string, it can push as well as pull. For a limiting complete revolution with vanishingly small speed at the top, the bottom speed approaches`,L`$\sqrt{4gr}$`,[
    [L`$\sqrt{5gr}$`,"That extra top-speed constraint applies to a flexible string, which cannot push."],[L`$\sqrt{gr}$`,"This is insufficient to gain gravitational potential energy 2mgr."],[L`$\sqrt{2gr}$`,"The top is 2r above the bottom, not r."]],
    L`The rod can supply an outward force at the top, so the string condition $v_{\mathrm{top}}^2\geq gr$ is unnecessary. In the limit, $\tfrac12mv_b^2\to mg(2r)$, giving $v_b\to\sqrt{4gr}$. Exact equality is a limiting case, not a finite-speed passage through the top.`,["Ask whether the constraint can push.","Use the 2r vertical rise.","Treat zero top speed as a limit rather than a normal crossing." ]),
  M("4.5",103,3,L`A particle completes a vertical circle on a light string, with gravity as the only force doing work. Tensions at the bottom and top are $T_b$ and $T_t$. Their difference is`,L`$6mg$`,[
    [L`$2mg$`,"This omits the difference in radial-force requirements caused by changing speed."],[L`$4mg$`,"This accounts for speed change but omits the weight signs in the radial equations."],[L`$0$`,"Neither tension nor speed remains constant in this motion."]],
    L`Energy gives $v_b^2-v_t^2=4gr$. Radial equations are $T_b-mg=mv_b^2/r$ and $T_t+mg=mv_t^2/r$. Subtracting gives $T_b-T_t=4mg+2mg=6mg$.`,["Relate top and bottom speeds by energy.","Write radial equations with inward directions separately.","Subtract the equations and use the speed-square difference." ]),
  W("4.5",101,"vsaq",2,"Two isolated carts stick together after a collision.",[
    {prompt:"State which of total momentum and total kinetic energy must be conserved, and which need not be.",answer:"Total momentum is conserved because net external impulse is zero. Total kinetic energy need not be conserved; some generally becomes internal energy in a sticking collision.",marking:["Distinguishes conserved momentum from non-conserved kinetic energy."]}],
    ["Isolation controls momentum conservation.","Sticking describes the collision type.","Total energy conservation is not the same as kinetic-energy conservation."],["Claiming conservation of kinetic energy merely because the system is isolated."]),
  W("4.5",102,"laq",3,L`A $1\,\mathrm{kg}$ cart moving at $6\,\mathrm{m\,s^{-1}}$ collides elastically in one dimension with a stationary $2\,\mathrm{kg}$ cart. The track is smooth.`,[
    {prompt:"Write momentum and kinetic-energy conservation equations and find both final velocities for the actual collision.",answer:L`With initial direction positive, $v_1+2v_2=6$ and $v_1^2+2v_2^2=36$. Substitution gives the unchanged-motion root and the collision root $v_2=4$, $v_1=-2\,\mathrm{m\,s^{-1}}$. Thus the first cart rebounds.`,marking:["Writes momentum conservation.","Writes kinetic-energy conservation.","Selects collision velocities -2 and +4 m/s, not the unchanged-motion root."]},
    {prompt:"Find the kinetic energy transferred to the second cart and its fraction of the initial energy.",answer:L`The second cart gains $\tfrac12(2)(4^2)=16\,\mathrm{J}$. Initial energy is 18 J, so the transferred fraction is $16/18=8/9$.`,marking:["Obtains transferred energy 16 J.","Obtains fraction 8/9."]}],
    ["Keep signs in the momentum equation.","Elastic means kinetic energy is conserved as well.","The algebraic unchanged-motion solution is not the post-impact collision state."],["Treating the rebound speed as a positive velocity in momentum conservation."]),
  W("4.5",103,"case",4,L`A $0.5\,\mathrm{kg}$ ball on a light string of length $1\,\mathrm{m}$ passes the bottom of a vertical circle at $8\,\mathrm{m\,s^{-1}}$. Take $g=10\,\mathrm{m\,s^{-2}}$. The string can withstand $40\,\mathrm{N}$, and air resistance is negligible.`,[
    {prompt:"Find the bottom tension and determine whether the string survives there.",answer:L`$T_b=mg+mv_b^2/r=5+0.5(64)=37\,\mathrm{N}<40\,\mathrm{N}$, so it survives the bottom.`,marking:["Uses the correct bottom radial equation.","Obtains 37 N and checks against the breaking limit."]},
    {prompt:"Check whether it can remain taut at the top. Explain why both the top and bottom checks matter.",answer:L`Energy gives $v_t^2=64-4(10)(1)=24$. Then $T_t=0.5(24)-5=7\,\mathrm{N}>0$. The top checks for slackness; the bottom has the greatest tension and checks breakage. Both conditions are satisfied.`,marking:["Obtains top speed squared 24 and tension 7 N.","Distinguishes non-negative top tension from the maximum bottom tension limit."]}],
    ["At the bottom tension must support weight and provide inward acceleration.","The rise to the top is twice the radius.","Tension must neither become negative nor exceed its breaking value."],["Checking only the minimum completion speed while ignoring string strength."]),
];
