import { expansionBank } from "../expansion-helpers";
const { mc: M, written: W } = expansionBank("u5-system-particles-rigid-body", "u5");
const L = String.raw;
export const rotationExpansion = [
  M("5.1",101,2,L`Masses m and 3m are fixed 8 m apart. Their centre of mass is`,"2 m from the heavier mass, between the masses",[
    ["2 m from the lighter mass, between the masses","The centre of mass lies nearer the heavier mass."],["4 m from each mass","The midpoint applies to equal masses."],["2 m beyond the heavier mass","Positive masses have their centre of mass between their two positions."]],
    L`Put m at x=0 and 3m at x=8. Then $x_{\mathrm{CM}}=(0+24m)/(4m)=6\,\mathrm{m}$, which is 2 m from the heavier mass.`,["Choose the lighter mass as the origin.","Take a mass-weighted average of positions.","Translate the coordinate into distance from the heavier mass." ]),
  M("5.1",102,3,"A projectile breaks into fragments during flight. Neglect air resistance, and assume no fragment has reached the ground. The centre of mass of the fragments","continues on the original projectile trajectory",[
    ["stops at the explosion point","Internal explosion forces do not remove the original total momentum."],["moves along the path of the heaviest fragment","The centre of mass depends on all fragments."],["moves horizontally because the explosion forces cancel","Gravity remains an external force after the explosion."]],
    "The internal impulses cancel in the total momentum. The centre of mass retains the original instantaneous velocity at breakup and continues to accelerate downward at g under gravity.",["Separate internal explosion forces from external gravity.","Use total external force for centre-of-mass acceleration.","The breakup does not change its position or velocity discontinuously." ]),
  W("5.1",101,"vsaq",2,"A uniform thin circular ring has its centre at the origin.",[
    {prompt:"Can its centre of mass lie at a point where no material is present? Locate it.",answer:"Yes. Symmetry places the centre of mass at the geometric centre, the origin, even though the thin ring has no material there.",marking:["Locates the centre of mass at the empty geometric centre using symmetry."]}],
    ["Pair every small mass element with the opposite element.","Their position contributions cancel.","A centre of mass is a weighted location, not necessarily a material point."],["Requiring the centre of mass to be on the ring itself."]),
  W("5.1",102,"case",3,L`Three small masses are fixed at the vertices of a right triangle: 1 kg at (0,0), 2 kg at (6,0) and 3 kg at (0,4), with coordinates in metres.`,[
    {prompt:"Find the centre-of-mass coordinates.",answer:L`Total mass is 6 kg. $x_{\mathrm{CM}}=[1(0)+2(6)+3(0)]/6=2\,\mathrm{m}$ and $y_{\mathrm{CM}}=[1(0)+2(0)+3(4)]/6=2\,\mathrm{m}$.`,marking:["Finds x coordinate 2 m.","Finds y coordinate 2 m."]},
    {prompt:"Where should an additional 2 kg point mass be placed so that the new centre of mass is (2,1.5) m?",answer:L`The existing mass-weighted coordinate sums are (12,12). With new total mass 8 kg, $12+2x=8(2)$ and $12+2y=8(1.5)$ give $(x,y)=(2,0)\,\mathrm{m}$.`,marking:["Uses the new total mass and correct target coordinate sums.","Obtains added position (2,0) m."]}],
    ["Compute each coordinate with mass weighting.","For the added mass, use total mass 8 kg.","Solve the target centre-of-mass equations backwards."],["Using the geometric centroid despite unequal masses."]),
  M("5.2",101,2,"Two equal opposite parallel forces act on a rigid body along different lines of action. This pair can produce","zero net force but a non-zero net torque",[
    ["zero net force and necessarily zero net torque","Separated lines of action form a couple."],["non-zero net force but zero torque","The equal opposite forces cancel in their vector sum."],["a net force twice either force","Their directions are opposite, not the same."]],
    L`The resultant force is zero, but the couple has torque magnitude $Fd$, where d is the perpendicular separation of the lines of action.`,["Add the two force vectors.","Take their moments about a point on either line of action.","Separate force balance from torque balance." ]),
  M("5.2",102,2,L`A force $\vec F=(3\hat i+4\hat j)\,\mathrm{N}$ acts at position $\vec r=(2\hat i-\hat j)\,\mathrm{m}$ from a pivot. Its torque is`,L`$11\hat k\,\mathrm{N\,m}$`,[
    [L`$5\hat k\,\mathrm{N\,m}$`,"The negative y coordinate contributes +3 to the z torque."],[L`$-11\hat k\,\mathrm{N\,m}$`,"Torque is r cross F, not F cross r."],[L`$2\,\mathrm{N\,m}$`,"This is the scalar product, not the torque."]],
    L`$\tau_z=r_xF_y-r_yF_x=2(4)-(-1)(3)=11\,\mathrm{N\,m}$. The direction is positive z.`,["Use the vector product in the correct order.","Calculate the z component with signed coordinates.","Apply the right-hand rule for its direction." ]),
  W("5.2",101,"saq",3,L`A uniform horizontal beam of length 3 m and weight 120 N is hinged at its left end. A vertical support at its right end holds it in equilibrium, and a 180 N load acts 1 m from the hinge.`,[
    {prompt:"Find the vertical forces from the right support and the hinge.",answer:L`Taking torque about the hinge, $3R=120(1.5)+180(1)=360$, so $R=120\,\mathrm{N}$ upward. Vertical balance gives $H=120+180-120=180\,\mathrm{N}$ upward.`,marking:["Uses torque balance to find right support 120 N.","Uses vertical balance to find hinge force 180 N."]}],
    ["Choose the hinge as the torque origin.","The beam's weight acts at its midpoint.","Use force balance after obtaining the other support force."],["Splitting the total weight equally despite the off-centre load."]),
  W("5.2",102,"laq",4,L`A uniform ladder of length 5 m and weight 200 N rests against a smooth vertical wall. Its foot is 3 m from the wall on rough horizontal ground. No person stands on it.`,[
    {prompt:"Find the wall reaction and the ground's normal and friction forces in equilibrium.",answer:L`The upper end is 4 m high. The weight's horizontal moment arm about the foot is 1.5 m. Torque balance gives $R_w(4)=200(1.5)$, so $R_w=75\,\mathrm{N}$. Horizontal balance requires ground friction 75 N towards the wall. Vertical balance gives ground normal force 200 N.`,marking:["Finds the 4 m height and 1.5 m weight moment arm.","Obtains wall reaction 75 N.","Obtains ground normal 200 N and friction 75 N towards the wall."]},
    {prompt:"Find the minimum coefficient of static friction at the ground and state whether 0.30 is sufficient.",answer:L`$\mu_{s,\min}=75/200=0.375$. A coefficient of 0.30 permits only 60 N of friction, below the required 75 N, so it is insufficient.`,marking:["Obtains minimum coefficient 0.375.","Rejects 0.30 by comparing friction demand with its limit."]}],
    ["The smooth wall supplies a horizontal normal force only.","Take torque about the foot to eliminate ground forces.","After force balance, compare friction demand with mu times normal force."],["Assigning an upward friction force at the smooth wall."]),
  M("5.3",101,2,"A particle moves along a straight line with constant momentum. About a fixed point lying off that line, its angular momentum","is constant and can be non-zero",[
    ["must be zero because its path is straight","The line need not pass through the chosen origin."],["increases with distance travelled","The perpendicular distance from the origin to the line remains constant."],["changes direction every instant","The plane of r and p and the signed perpendicular offset remain unchanged."]],
    L`The angular-momentum magnitude is $pb$, with b the perpendicular distance from the fixed point to the line. Both p and b stay constant, as does the direction of $\vec r\times\vec p$.`,["Use perpendicular distance to the momentum's line of action.","Straight-line motion need not pass through the origin.","The changing parallel part of r contributes no cross product." ]),
  M("5.3",102,3,L`A freely rotating system changes its moment of inertia from I to 3I without external torque. Its rotational kinetic energy changes from K to`,L`$K/3$`,[
    [L`$3K$`,"This assumes constant angular speed, whereas angular momentum is fixed."],[L`$K/9$`,"Angular speed is divided by three, but the new moment of inertia is tripled."],[L`$K$`,"No external torque does not require constant rotational kinetic energy."]],
    L`With angular momentum L fixed, $K=L^2/(2I)$. Therefore tripling I reduces K to one-third.`,["Identify the conserved quantity first.","Express rotational energy in terms of angular momentum.","Internal work can change rotational energy." ]),
  W("5.3",101,"vsaq",2,L`A constant torque of $-0.8\,\mathrm{N\,m}$ acts about a fixed axis for 5 s. Initial angular momentum about that axis is $+6\,\mathrm{kg\,m^2\,s^{-1}}$.`,[
    {prompt:"Find the final angular momentum.",answer:L`$L_f=L_i+\tau\Delta t=6-0.8(5)=+2\,\mathrm{kg\,m^2\,s^{-1}}$.`,marking:["Gives signed final angular momentum +2 kg m squared per second."]}],
    ["Torque-time product gives angular-momentum change.","Keep its negative sign.","Add the change to the initial value."],["Reporting the change -4 as the final angular momentum."]),
  W("5.3",102,"laq",3,L`Two coaxial rotors with moments of inertia $0.20$ and $0.30\,\mathrm{kg\,m^2}$ rotate at $+10$ and $-4\,\mathrm{rad\,s^{-1}}$. They are coupled and reach a common angular velocity. External torque is negligible.`,[
    {prompt:"Find the common angular velocity and its direction.",answer:L`Initial angular momentum is $0.20(10)+0.30(-4)=0.8\,\mathrm{kg\,m^2\,s^{-1}}$. Hence $\omega=0.8/(0.20+0.30)=+1.6\,\mathrm{rad\,s^{-1}}$, in the first rotor's initial direction.`,marking:["Adds signed angular momenta to obtain 0.8.","Obtains common angular velocity +1.6 rad/s."]},
    {prompt:"Calculate the loss of rotational kinetic energy and explain how this is compatible with angular-momentum conservation.",answer:L`$K_i=\tfrac12(0.20)(10^2)+\tfrac12(0.30)(4^2)=12.4\,\mathrm{J}$. $K_f=\tfrac12(0.50)(1.6^2)=0.64\,\mathrm{J}$. Loss is 11.76 J. Internal friction converts mechanical energy into internal energy while its equal opposite torques do not change total angular momentum.`,marking:["Obtains initial and final energies 12.4 J and 0.64 J.","Obtains loss 11.76 J.","Explains internal dissipation without external torque."]}],
    ["Use opposite signs for the initial angular velocities.","After coupling, add both moments of inertia.","Kinetic energy uses squared speeds even for opposite rotation."],["Subtracting one rotor's kinetic energy because its rotation is negative."]),
  M("5.4",101,2,L`A wheel initially turns at $12\,\mathrm{rad\,s^{-1}}$. A constant angular deceleration of magnitude $3\,\mathrm{rad\,s^{-2}}$ acts until it stops. Its angular displacement before stopping is`,L`$24\,\mathrm{rad}$`,[
    [L`$48\,\mathrm{rad}$`,"The wheel does not keep its initial angular speed during braking."],[L`$4\,\mathrm{rad}$`,"4 is the stopping time in seconds."],[L`$6\,\mathrm{rad}$`,"Use the complete rotational kinematics relation with speed squared."]],
    L`$0=12^2+2(-3)\theta$ gives $\theta=24\,\mathrm{rad}$. Equivalently, average angular speed 6 times stopping time 4 gives 24.`,["The angular acceleration is negative in the initial rotation direction.","Use the relation eliminating time.","Check with mean angular speed times duration." ]),
  M("5.4",102,2,L`A motor supplies torque $5\,\mathrm{N\,m}$ to a rotor while a bearing exerts an opposing torque of $1\,\mathrm{N\,m}$. The moment of inertia is $2\,\mathrm{kg\,m^2}$. Its angular acceleration is`,L`$2\,\mathrm{rad\,s^{-2}}$`,[
    [L`$2.5\,\mathrm{rad\,s^{-2}}$`,"This ignores the opposing torque."],[L`$3\,\mathrm{rad\,s^{-2}}$`,"Opposing torques must be subtracted, not added."],[L`$8\,\mathrm{rad\,s^{-2}}$`,"Divide net torque by moment of inertia, rather than multiplying."]],
    L`The net torque is $5-1=4\,\mathrm{N\,m}$. Therefore $\alpha=4/2=2\,\mathrm{rad\,s^{-2}}$.`,["Form the signed net torque.","Apply net torque equals I alpha.","Check the angular-acceleration units." ]),
  W("5.4",101,"vsaq",2,L`A wheel rotates at $120\,\mathrm{rpm}$ while a motor exerts a torque of $3\,\mathrm{N\,m}$ in the rotation direction.`,[
    {prompt:"Find the instantaneous mechanical power supplied.",answer:L`$120\,\mathrm{rpm}=4\pi\,\mathrm{rad\,s^{-1}}$. Hence $P=\tau\omega=12\pi\,\mathrm{W}$.`,marking:[L`Converts angular speed and obtains $12\pi\,\mathrm{W}$.`]}],
    ["Convert revolutions per minute to radians per second.","Use torque times angular speed.","Do not use rpm directly in the SI power formula."],["Leaving the angular speed in revolutions per minute."]),
  W("5.4",102,"case",3,L`A rotor of moment of inertia $0.4\,\mathrm{kg\,m^2}$ starts from rest. A motor torque of 3 N m acts against a constant friction torque of 1 N m for 2 s. The motor is then switched off, while the same friction torque continues until rest.`,[
    {prompt:"Find the angular speed and displacement during the driven stage.",answer:L`Net torque is 2 N m, so $\alpha=2/0.4=5\,\mathrm{rad\,s^{-2}}$. After 2 s, $\omega=10\,\mathrm{rad\,s^{-1}}$ and $\theta=\tfrac12(5)(2^2)=10\,\mathrm{rad}$.`,marking:["Uses net torque and obtains angular speed 10 rad/s.","Obtains angular displacement 10 rad."]},
    {prompt:"Find the extra rotation before stopping after switch-off, and check it using energy.",answer:L`Friction alone gives deceleration $1/0.4=2.5\,\mathrm{rad\,s^{-2}}$, so extra angle is $10^2/(2\times2.5)=20\,\mathrm{rad}$. Initial coast-down energy is $\tfrac12(0.4)(10^2)=20\,\mathrm{J}$, equal to friction work magnitude $1(20)=20\,\mathrm{J}$.`,marking:["Obtains coast-down angle 20 rad.","Checks 20 J kinetic energy against 20 J frictional work."]}],
    ["Subtract friction during the motor-driven stage.","After switch-off only the friction torque remains.","Use the end speed from the first stage as the next initial speed."],["Keeping motor torque in the equation after switch-off."]),
  M("5.5",101,3,L`Two equal point masses m are fixed at the ends of a light rod of length L. The moment of inertia about an axis through one end perpendicular to the rod is how many times that about a parallel axis through its midpoint?`,"2",[
    ["1","The perpendicular distances to the axis change."],["4","The midpoint inertia includes both masses, not just one."],["1/2","Moving the axis to one end increases the moment of inertia in this system."]],
    L`About the midpoint, $I_c=2m(L/2)^2=mL^2/2$. About the end, $I_e=0+mL^2$. Thus $I_e/I_c=2$.`,["Use each mass's perpendicular distance to each axis.","Include both masses for the midpoint axis.","The mass lying on the end axis contributes zero." ]),
  M("5.5",102,3,"A ring and a solid disc have equal mass and radius. Starting from rest, each receives the same net work about its symmetry axis. The disc's final angular speed divided by the ring's is",L`$\sqrt2$`,[
    ["2","Angular speed depends on the square root of inverse inertia for fixed energy."],["1","Equal rotational energy need not imply equal angular speed."],[L`$1/\sqrt2$`,"The disc has the smaller moment of inertia, so it spins faster."]],
    L`Equal work gives equal $\tfrac12I\omega^2$. Since $I_r=MR^2$ and $I_d=MR^2/2$, $\omega_d/\omega_r=\sqrt{I_r/I_d}=\sqrt2$.`,["Translate equal net work into equal rotational energy.","Use the two standard moments of inertia.","Take a square root when solving for angular speed." ]),
  W("5.5",101,"vsaq",2,"A body keeps the same mass but its radius of gyration about a chosen axis increases by 20% after redistribution of its mass.",[
    {prompt:"By what percentage does its moment of inertia increase?",answer:L`$I=Mk^2$, so $I_f/I_i=1.2^2=1.44$. The increase is 44%.`,marking:["Obtains a 44% increase by squaring the radius-of-gyration factor."]}],
    ["Hold total mass constant.","Moment of inertia depends on k squared.","Subtract one from the final-to-initial ratio."],["Treating the inertia change as linear in radius of gyration."]),
  W("5.5",102,"saq",3,L`Two point masses of 1 kg and 3 kg are fixed 2 m apart on a light rod.`,[
    {prompt:"Find the moment of inertia about an axis through their centre of mass perpendicular to the rod.",answer:L`The centre of mass is 1.5 m from the 1 kg mass and 0.5 m from the 3 kg mass. Thus $I=1(1.5)^2+3(0.5)^2=3\,\mathrm{kg\,m^2}$.`,marking:["Finds the unequal distances 1.5 m and 0.5 m from the centre of mass.","Obtains moment of inertia 3 kg m squared."]}],
    ["Locate the mass-weighted centre first.","Use distances from that centre, not from a rod end.","Add each mass times its distance squared."],["Taking the geometric midpoint as the centre of mass."]),
];
