import { expansionBank } from "../expansion-helpers";
const { mc: M, written: W } = expansionBank("u1-physical-world-measurement", "u1");
const L = String.raw;

export const measurementExpansion = [
  M("1.1",101,2,L`A pump transfers $1.5\,\mathrm{L}$ of water in $30\,\mathrm{s}$. Its volume flow rate in SI units is`,
    L`$5.0\times10^{-5}\,\mathrm{m^3\,s^{-1}}$`,[
      [L`$0.050\,\mathrm{m^3\,s^{-1}}$`,"This treats one litre as one cubic metre."],
      [L`$5.0\times10^{-2}\,\mathrm{m^2\,s^{-1}}$`,"Volume flow has a cubic-length unit, not an area unit."],
      [L`$45\,\mathrm{m^3\,s^{-1}}$`,"Divide volume by time and convert litres before reporting SI units."]],
    L`Since $1\,\mathrm{L}=10^{-3}\,\mathrm{m^3}$, $Q=(1.5\times10^{-3})/30=5.0\times10^{-5}\,\mathrm{m^3\,s^{-1}}$.`,
    ["Identify the quantity transferred per second.",L`Convert litres using $1\,\mathrm{L}=10^{-3}\,\mathrm{m^3}$.`,"Divide the converted volume by 30."]),
  M("1.1",102,2,L`A force of $1\,\mathrm{N}$ is expressed in a new system whose mass, length and time units are $2\,\mathrm{kg}$, $0.5\,\mathrm{m}$ and $2\,\mathrm{s}$. Its numerical value is`,
    "$4$",[["$1/4$","This reverses the ratio of old and new unit sizes."],["$1$","The time unit must be squared in a force unit."],["$2$","Both mass and length, as well as squared time, enter the force unit."]],
    L`One new force unit is $2(0.5)/2^2=0.25\,\mathrm{N}$. Therefore $1\,\mathrm{N}$ is four new force units.`,
    [L`Force has unit $MLT^{-2}$.`,"Calculate the size of one new force unit in newtons.","Divide one newton by that unit size."]),
  M("1.1",103,2,L`Two labels describe a spring constant: $0.80\,\mathrm{N\,cm^{-1}}$ and $80\,\mathrm{N\,m^{-1}}$. Which assessment is correct?`,
    "Both labels describe the same spring constant.",[["The first is 100 times larger.","A centimetre in the denominator makes its unit 100 times larger, but the numerical values already compensate."],["The second is 100 times larger.","Convert both denominators to the same length unit before comparing."],["Neither can describe a spring constant.","Force per extension is the unit of spring constant."]],
    L`Because $1\,\mathrm{cm}=0.01\,\mathrm{m}$, $0.80\,\mathrm{N\,cm^{-1}}=0.80/0.01=80\,\mathrm{N\,m^{-1}}$.`,
    ["Compare in one system of units.","Length is in the denominator.","Replacing centimetres with metres multiplies the numerical value by 100."]),
  M("1.1",104,2,L`Assertion (A): The kelvin is an SI base unit. Reason (R): The joule is an SI derived unit.`,
    "Both A and R are true, but R does not explain A.",[["Both A and R are true, and R explains A.","The classification of joule does not explain why temperature is a base quantity."],["A is true, but R is false.","Joule is a derived unit, expressible using kilogram, metre and second."],["A is false, but R is true.","Kelvin is the SI base unit of thermodynamic temperature."]],
    L`Kelvin is the base unit for thermodynamic temperature, while $1\,\mathrm{J}=1\,\mathrm{kg\,m^2\,s^{-2}}$. Both classifications are true, but the second does not explain the first.`,
    ["Recall the SI base quantities.","Express a joule in base units.","Evaluate the explanatory link separately from the truth of each statement."]),
  W("1.1",101,"vsaq",2,L`A material has density $7.8\,\mathrm{g\,cm^{-3}}$.`,[
    {prompt:"Express the density in SI units.",answer:L`$\rho=7.8\times10^{-3}/10^{-6}=7.8\times10^3\,\mathrm{kg\,m^{-3}}$.`,marking:[L`Correctly converts to $7.8\times10^3\,\mathrm{kg\,m^{-3}}$.`]}],
    ["Convert both mass and volume.",L`$1\,\mathrm{g}=10^{-3}\,\mathrm{kg}$ and $1\,\mathrm{cm^3}=10^{-6}\,\mathrm{m^3}$.`,"Divide the two conversion factors."],["Converting the numerator alone."]),
  W("1.1",102,"saq",2,L`A pressure gauge reads $2.4\,\mathrm{kPa}$ and acts on a piston of area $5.0\,\mathrm{cm^2}$.`,[
    {prompt:"Find the force on the piston, showing the SI conversions.",answer:L`$P=2.4\times10^3\,\mathrm{Pa}$ and $A=5.0\times10^{-4}\,\mathrm{m^2}$. Thus $F=PA=1.2\,\mathrm{N}$.`,marking:["Converts pressure and area correctly.",L`Uses $F=PA$ to obtain $1.2\,\mathrm{N}$.`]}],
    ["Pressure is force per area.","Square the centimetre-to-metre conversion for area.","Multiply pressure in pascals by area in square metres."],["Using a linear conversion for area."]),
  W("1.1",103,"laq",3,L`A laboratory defines a mass unit of $5\,\mathrm{kg}$, a length unit of $2\,\mathrm{m}$ and a time unit of $4\,\mathrm{s}$.`,[
    {prompt:"Determine its units of speed and energy in SI units.",answer:L`One speed unit is $2/4=0.5\,\mathrm{m\,s^{-1}}$. One energy unit is $5(2)^2/(4)^2=1.25\,\mathrm{J}$.`,marking:[L`Obtains $0.5\,\mathrm{m\,s^{-1}}$.`,L`Uses $ML^2T^{-2}$ and obtains $1.25\,\mathrm{J}$.`]},
    {prompt:L`Express an energy of $15\,\mathrm{J}$ in this system and explain why changing units does not change the physical energy.`,answer:L`Its numerical value is $15/1.25=12$. The energy is unchanged because the product of numerical value and unit size remains $15\,\mathrm{J}$.`,marking:["Obtains numerical value 12.","Explains numerical value times unit size is invariant."]}],
    ["Derive each unit from the base units.","Energy is mass times speed squared.","Divide the physical energy by the size of the new energy unit."],["Multiplying the energy by the new unit size."]),
  W("1.1",104,"case",3,L`An irrigation pipe delivers $600\,\mathrm{mL}$ in $20\,\mathrm{s}$. The water density is $1000\,\mathrm{kg\,m^{-3}}$ and the pipe's internal area is $2.0\,\mathrm{cm^2}$. Flow is steady.`,[
    {prompt:"Find the volume flow rate in SI units.",answer:L`$Q=600\times10^{-6}/20=3.0\times10^{-5}\,\mathrm{m^3\,s^{-1}}$.`,marking:[L`Obtains $3.0\times10^{-5}\,\mathrm{m^3\,s^{-1}}$.`]},
    {prompt:"Find the mass delivered per second.",answer:L`$\dot m=\rho Q=1000(3.0\times10^{-5})=0.030\,\mathrm{kg\,s^{-1}}$.`,marking:[L`Obtains $0.030\,\mathrm{kg\,s^{-1}}$.`]},
    {prompt:"Use volume = area times length to find the mean water speed.",answer:L`$Q=Av$ and $A=2.0\times10^{-4}\,\mathrm{m^2}$, so $v=0.15\,\mathrm{m\,s^{-1}}$.`,marking:[L`Uses $v=Q/A$ with the correct area.`,L`Obtains $0.15\,\mathrm{m\,s^{-1}}$.`]}],
    ["Convert millilitres to cubic metres.","Multiply volume per second by density for mass per second.","Divide volume per second by the cross-sectional area for speed."],["Confusing millilitres with litres."]),
  M("1.2",101,2,L`A balance has a constant zero error of $+0.20\,\mathrm{g}$. Empty and loaded containers read $12.40\,\mathrm{g}$ and $18.65\,\mathrm{g}$. The mass of the contents is`,
    L`$6.25\,\mathrm{g}$`,[[L`$6.05\,\mathrm{g}$`,"The same zero error occurs in both readings and cancels in their difference."],[L`$6.45\,\mathrm{g}$`,"Adding a zero correction to the difference counts an error that already cancelled."],[L`$31.05\,\mathrm{g}$`,"The contents' mass is a difference, not a sum."]],
    L`Corrected readings are $12.20\,\mathrm{g}$ and $18.45\,\mathrm{g}$. Their difference is $6.25\,\mathrm{g}$, also equal to $18.65-12.40$.`,
    ["Apply the same correction to both readings.","Expand the difference of the corrected readings.","The two constant corrections cancel."]),
  M("1.2",102,2,L`A rod length is $(25.0\pm0.1)\,\mathrm{cm}$. Which is the maximum percentage uncertainty in its length?`,
    L`$0.4\%$`,[[L`$4\%$`,"This misplaces a decimal in the relative uncertainty."],[L`$0.1\%$`,"Absolute uncertainty and percentage uncertainty are different quantities."],[L`$2.5\%$`,"Divide uncertainty by measured value, not measured value by 100."]],
    L`The maximum percentage uncertainty is $(0.1/25.0)\times100=0.4\%$.`,
    ["Form uncertainty divided by value.","The centimetres cancel.","Multiply the relative uncertainty by 100." ]),
  M("1.2",103,3,L`The measured resistance is calculated as $R=V/I$. The maximum fractional uncertainties in $V$ and $I$ are $0.02$ and $0.03$. For worst-case uncertainty, which conclusion is justified?`,
    L`The maximum fractional uncertainty in $R$ is approximately $0.05$.`,[[L`It is approximately $-0.01$.`,"Worst-case uncertainty magnitudes add for a quotient; they are not subtracted."],[L`It is approximately $0.0006$.`,"Multiplying the uncertainties is not first-order propagation."],["It is zero if the same observer reads both meters.","Using the same observer does not eliminate measurement uncertainty."]],
    L`To first order, $\Delta R/R\leq\Delta V/V+\Delta I/I=0.05$. This is a worst-case bound, not a statistical root-sum-square estimate.`,
    ["Distinguish worst-case from statistical uncertainty.","For a quotient, add the fractional uncertainty magnitudes.","Use the approximation valid for small uncertainties."]),
  M("1.2",104,2,L`Assertion (A): Repeating measurements removes a fixed zero error. Reason (R): Averaging repeated measurements can reduce the effect of random fluctuations.`,
    "A is false, but R is true.",[["Both A and R are true, and R explains A.","A fixed zero shift remains in every repetition."],["Both A and R are true, but R does not explain A.","The assertion is false, not merely unexplained."],["A is true, but R is false.","This reverses the roles of systematic and random error."]],
    "Averaging can reduce random scatter, but each reading retains the same systematic zero shift. Calibration or a zero correction is needed to remove that shift.",
    ["Separate systematic error from random scatter.","Ask whether the offset changes between readings.","A constant offset survives an average."]),
  W("1.2",101,"vsaq",2,L`A stopwatch reads $0.3\,\mathrm{s}$ before timing begins and $8.7\,\mathrm{s}$ when timing ends.`,[
    {prompt:"Find the elapsed time if the zero offset remains fixed.",answer:L`Elapsed time is $8.7-0.3=8.4\,\mathrm{s}$. The fixed offset cancels.`,marking:[L`Obtains $8.4\,\mathrm{s}$.`]}],
    ["Elapsed time is a difference.","Use both readings, not only the final display.","Subtract the initial reading from the final reading."],["Treating the final display as the interval."]),
  W("1.2",102,"saq",2,L`Four diameter measurements are $2.42$, $2.44$, $2.46$ and $2.44\,\mathrm{mm}$.`,[
    {prompt:"Find their mean and the mean absolute deviation from the mean.",answer:L`The mean is $9.76/4=2.44\,\mathrm{mm}$. Absolute deviations are $0.02,0,0.02,0\,\mathrm{mm}$, whose mean is $0.01\,\mathrm{mm}$.`,marking:[L`Obtains mean $2.44\,\mathrm{mm}$.`,L`Obtains mean absolute deviation $0.01\,\mathrm{mm}$.`]}],
    ["Calculate the arithmetic mean first.","Take absolute values of the deviations.","Average all four deviations, including zeros."],["Averaging signed deviations and obtaining zero."]),
  W("1.2",103,"laq",3,L`A rectangular plate has length $(12.0\pm0.1)\,\mathrm{cm}$ and breadth $(5.0\pm0.1)\,\mathrm{cm}$. Use first-order worst-case uncertainty propagation.`,[
    {prompt:"Calculate its area and maximum fractional uncertainty.",answer:L`$A=60.0\,\mathrm{cm^2}$. The fractional uncertainty is $0.1/12.0+0.1/5.0=0.02833\ldots$, about $2.8\%$.`,marking:[L`Obtains area $60.0\,\mathrm{cm^2}$.`,"Adds fractional uncertainties and obtains about 0.0283."]},
    {prompt:"Report the area with absolute uncertainty, then identify which dimension contributes more uncertainty.",answer:L`$\Delta A=60.0(0.02833\ldots)=1.7\,\mathrm{cm^2}$, so $A=(60.0\pm1.7)\,\mathrm{cm^2}$. Breadth contributes $2\%$, greater than the length's $0.83\%$.`,marking:[L`Reports $(60.0\pm1.7)\,\mathrm{cm^2}$.`,"Identifies breadth using relative uncertainties, not just equal absolute errors."]}],
    ["For a product, add fractional uncertainties.","Convert the resulting fractional uncertainty to absolute uncertainty in area.","Compare uncertainty divided by value for each dimension."],["Adding centimetre uncertainties directly to an area."]),
  W("1.2",104,"case",3,L`A pendulum experiment gives $T=2\pi\sqrt{l/g}$. Length has maximum uncertainty $1\%$ and the measured period has maximum uncertainty $2\%$. Treat $\pi$ as exact and use first-order worst-case propagation.`,[
    {prompt:"Rearrange for g and find its maximum percentage uncertainty.",answer:L`$g=4\pi^2l/T^2$, so $\Delta g/g$ is at most $1\%+2(2\%)=5\%$.`,marking:[L`Rearranges to $g=4\pi^2l/T^2$.`,"Obtains 5%."]},
    {prompt:"Only one improvement is possible: halve the length uncertainty or halve the period uncertainty. Which yields the smaller uncertainty in g? Justify numerically.",answer:L`Halving length uncertainty gives $0.5+4=4.5\%$. Halving period uncertainty gives $1+2(1)=3\%$. Improve period measurement.`,marking:["Calculates both revised bounds, 4.5% and 3%.","Selects the period improvement because its uncertainty carries a factor of two."]}],
    ["Rearrange before propagating uncertainty.","Powers multiply relative uncertainty contributions.","Compare the two proposed changes separately."],["Forgetting the square on period."]),
  M("1.3",101,2,L`A digital instrument reports $0.004070\,\mathrm{m}$. How many significant figures does this reading contain?`,
    "$4$",[["$3$","The final zero after the decimal is significant."],["$6$","Leading zeros only locate the decimal point."],["$2$","Zeros between non-zero digits are significant too."]],
    "The leading zeros are placeholders. The significant digits are 4, 0, 7 and the final 0: four significant figures.",
    ["Find the first non-zero digit.","Retain zeros within the significant digits.","Retain the final decimal zero."]),
  M("1.3",102,2,L`A wire of measured length $18.76\,\mathrm{cm}$ has a piece of measured length $2.3\,\mathrm{cm}$ removed. The correctly reported remaining length is`,
    L`$16.5\,\mathrm{cm}$`,[[L`$16.46\,\mathrm{cm}$`,"The tenths-place measurement does not support hundredths in the difference."],[L`$16\,\mathrm{cm}$`,"For subtraction, use decimal-place precision, not the fewest significant figures."],[L`$16.4\,\mathrm{cm}$`,"The unrounded difference is 16.46, which rounds up at the tenths place."]],
    L`The unrounded difference is $16.46\,\mathrm{cm}$. The least precise input is reported to $0.1\,\mathrm{cm}$, so the result is $16.5\,\mathrm{cm}$.`,
    ["Use the subtraction rule, not the multiplication rule.","Identify the least precise decimal place.","Round the difference to tenths."]),
  M("1.3",103,2,L`A mass of $8.4\,\mathrm{g}$ occupies $2.00\,\mathrm{cm^3}$. The density should be reported as`,
    L`$4.2\,\mathrm{g\,cm^{-3}}$`,[[L`$4.200\,\mathrm{g\,cm^{-3}}$`,"This claims more precision than the mass measurement supports."],[L`$4\,\mathrm{g\,cm^{-3}}$`,"Two significant figures are justified; rounding to one discards valid information."],[L`$16.8\,\mathrm{g\,cm^{-3}}$`,"Density is mass divided by volume, not their product."]],
    L`$\rho=8.4/2.00=4.2\,\mathrm{g\,cm^{-3}}$. The mass limits the quotient to two significant figures.`,
    ["Use mass divided by volume.","Count significant figures in both measurements.","Use the smaller count for the quotient."]),
  M("1.3",104,2,L`Assertion (A): Multiplying a measured length by an exact count of 3 limits the result to one significant figure. Reason (R): An exact count has no measurement uncertainty.`,
    "A is false, but R is true.",[["Both A and R are true, and R explains A.","An exact count does not limit measurement precision."],["Both A and R are true, but R does not explain A.","The assertion is false because the factor is exact."],["A is true, but R is false.","Exact counts do not have rounding uncertainty from a measuring instrument."]],
    "An exact count is not a one-significant-figure measurement. The measured length, not the exact multiplier, controls the precision of the product.",
    ["Distinguish a measured value from a count.","Does the exact multiplier carry experimental uncertainty?","Only uncertain inputs restrict reported precision."]),
  W("1.3",101,"vsaq",1,L`A measured time is written as $0.00650\,\mathrm{s}$.`,[
    {prompt:"Rewrite it in scientific notation without changing its precision.",answer:L`$6.50\times10^{-3}\,\mathrm{s}$ preserves all three significant figures.`,marking:[L`Gives $6.50\times10^{-3}\,\mathrm{s}$, retaining the final zero.`]}],
    ["Move the decimal until the coefficient lies between 1 and 10.","Count the decimal places moved.","Do not discard the trailing zero."],["Writing 6.5 and losing the indicated precision."]),
  W("1.3",102,"saq",2,L`A student calculates $(2.35\,\mathrm{m})(1.2\,\mathrm{m})$ and reports $2.820\,\mathrm{m^2}$.`,[
    {prompt:"Correct the report and explain the rule used.",answer:L`The product before rounding is $2.82\,\mathrm{m^2}$. Since $1.2$ has two significant figures, report $2.8\,\mathrm{m^2}$. The original report overstates precision.`,marking:[L`Gives $2.8\,\mathrm{m^2}$.`,"Explains the least-significant-figures rule for products."]}],
    ["Compute before rounding.","Count significant figures in the two factors.","Keep two significant figures in the final product."],["Using the number of decimal places for a product."]),
  W("1.3",103,"laq",3,L`A tank initially contains $12.6\,\mathrm{L}$. A further $3.24\,\mathrm{L}$ is added, then the entire liquid is divided into exactly four equal portions.`,[
    {prompt:"Determine the supported decimal-place precision and report the total volume.",answer:L`The sum before rounding is $15.84\,\mathrm{L}$. It is limited to tenths by $12.6\,\mathrm{L}$ and is reported as $15.8\,\mathrm{L}$.`,marking:["Identifies tenths as the limiting decimal place.",L`Reports $15.8\,\mathrm{L}$.`]},
    {prompt:"Calculate the volume of one portion, retaining guard digits until the end. Explain the role of the exact divisor.",answer:L`Using the unrounded intermediate value, $15.84/4=3.96\,\mathrm{L}$, reported to three significant figures. The exact count four does not impose a one-significant-figure limit.`,marking:[L`Obtains $3.96\,\mathrm{L}$ using guard digits.`,"Explains that an exact divisor does not limit significant figures."]}],
    ["Apply the addition rule to the total.","Keep extra digits internally during the next calculation.","The count of portions is exact."],["Rounding intermediate values prematurely."]),
  W("1.3",104,"case",2,L`Three students record the same nominal distance as $2.5\,\mathrm{m}$, $2.50\,\mathrm{m}$ and $2.500\,\mathrm{m}$. Assume each report correctly reflects its instrument's resolution.`,[
    {prompt:"State the significant-figure count of each report.",answer:"The counts are two, three and four respectively.",marking:["Gives 2, 3 and 4."]},
    {prompt:"Which report indicates the finest resolution? Does it prove the smallest systematic error?",answer:L`$2.500\,\mathrm{m}$ indicates the finest reported resolution. It does not establish accuracy: an instrument can resolve small changes while retaining a calibration offset.`,marking:["Selects 2.500 m for finest resolution.","Distinguishes resolution/precision from accuracy or systematic error."]},
    {prompt:"Convert the second report to centimetres without changing its significant-figure count.",answer:L`$2.50\,\mathrm{m}=2.50\times10^2\,\mathrm{cm}$ retains three significant figures unambiguously.`,marking:["Gives an unambiguous three-significant-figure form in centimetres."]}],
    ["Trailing decimal zeros convey precision.","Resolution does not establish calibration accuracy.","Use scientific notation to avoid ambiguous trailing zeros in centimetres."],["Equating more digits with freedom from systematic error."]),
  M("1.4",101,2,L`A machine's power loss is modelled as $P=cv^3$, where $v$ is speed. The dimensions of $c$ are`,
    "$[ML^{-1}]$",[["$[ML^2T^{-3}]$","These are power dimensions before division by speed cubed."],["$[ML^{-1}T^{-1}]$","The time powers cancel completely in this quotient."],["$[ML^{-2}T]$","This uses the wrong power of speed."]],
    L`$[c]=[P]/[v]^3=(ML^2T^{-3})/(L^3T^{-3})=ML^{-1}$.`,
    ["Isolate the coefficient.","Power is energy per time.","Divide by the cube of speed dimensions."]),
  M("1.4",102,2,L`Pressure multiplied by volume has the same dimensions as`,
    "energy",[["force","Volume contributes three length powers, not two."],["momentum","The time exponent remains -2, not -1."],["power","Power needs one additional inverse-time factor."]],
    L`$[PV]=(ML^{-1}T^{-2})(L^3)=ML^2T^{-2}$, the dimensions of energy.`,
    ["Write pressure as force per area.","Multiply by volume dimensions.","Compare with work = force times distance."]),
  M("1.4",103,2,L`In $x=A\sin(\omega t+\phi)$, $x$ is displacement and $t$ is time. Which dimensional assignment is valid?`,
    L`$[A]=L,\ [\omega]=T^{-1},\ [\phi]=1$`,[[L`$[A]=L,\ [\omega]=T,\ [\phi]=1$`,"The product of angular frequency and time must be dimensionless."],[L`$[A]=1,\ [\omega]=T^{-1},\ [\phi]=L$`,"The amplitude supplies the length dimension; phase cannot carry length."],[L`$[A]=L,\ [\omega]=1,\ [\phi]=T$`,"A trigonometric argument must be dimensionless."]],
    L`The sine is dimensionless, so $[A]=[x]=L$. Its argument requires $[\omega t]=1$ and $[\phi]=1$, hence $[\omega]=T^{-1}$.`,
    ["Check the trigonometric argument first.","Both terms added in the argument must be dimensionless.","The prefactor supplies displacement dimensions."]),
  M("1.4",104,2,L`Assertion (A): Torque and work have identical dimensions. Reason (R): Two quantities with identical dimensions must represent the same physical quantity.`,
    "A is true, but R is false.",[["Both A and R are true, and R explains A.","Equal dimensions do not imply identical physical meanings."],["Both A and R are true, but R does not explain A.","The reason itself is false."],["A is false, but R is true.","Both torque and work contain force times length, so A is true."]],
    L`Both have dimensions $ML^2T^{-2}$, but work is a scalar and torque is an axial vector. Dimensional equality is not physical identity.`,
    ["Write dimensions of force times distance.","Recall the scalar or vector character of each quantity.","A dimensional test cannot distinguish every physical quantity."]),
  W("1.4",101,"vsaq",2,L`Energy $E$ and frequency $f$ are related by $E=hf$.`,[
    {prompt:"Find the dimensions of h.",answer:L`$[h]=[E]/[f]=(ML^2T^{-2})/(T^{-1})=ML^2T^{-1}$.`,marking:[L`Gives $[ML^2T^{-1}]$.`]}],
    ["Isolate h.","Frequency is inverse time.","Divide energy dimensions by inverse-time dimensions."],["Multiplying by frequency rather than dividing."]),
  W("1.4",102,"saq",2,L`The acceleration of a particle is written as $a=p+qt^2$, with time $t$.`,[
    {prompt:"Determine the dimensions and SI units of p and q.",answer:L`$[p]=LT^{-2}$ with unit $\mathrm{m\,s^{-2}}$. Since $[qt^2]=LT^{-2}$, $[q]=LT^{-4}$ with unit $\mathrm{m\,s^{-4}}$.`,marking:["Correct dimensions and unit of p.","Correct dimensions and unit of q."]}],
    ["Every added term must have acceleration dimensions.","For q, divide by time squared.","Translate length and time dimensions into metre and second."],["Giving p and q the same dimensions."]),
  W("1.4",103,"laq",3,L`A force law is proposed as $F=av+bv^2$, where $v$ is speed.`,[
    {prompt:"Find dimensions of a and b, explaining the use of homogeneity.",answer:L`Each term must be a force: $[a]=[F]/[v]=MT^{-1}$ and $[b]=[F]/[v]^2=ML^{-1}$.`,marking:["States that both added terms must have force dimensions.",L`Finds $[a]=MT^{-1}$.`,L`Finds $[b]=ML^{-1}$.`]},
    {prompt:"When the two terms have equal magnitudes, express the non-zero crossover speed and check its dimensions.",answer:L`$av=bv^2$ gives $v=a/b$ for positive coefficients and non-zero speed. Its dimensions are $(MT^{-1})/(ML^{-1})=LT^{-1}$.`,marking:[L`Obtains $v=a/b$.`,"Checks the quotient has speed dimensions."]}],
    ["Treat the two terms separately.","Divide force dimensions by the relevant power of speed.","Cancel a non-zero speed when equating the terms."],["Assuming coefficients of different speed powers have the same units."]),
  W("1.4",104,"case",3,L`A proposed energy expression is $E=\alpha v^2+\beta x$, where $v$ is speed and $x$ is displacement. The same student writes $E=\alpha(v^2+x)$ on the next line.`,[
    {prompt:"Determine the dimensions of both coefficients in the first expression.",answer:L`$[\alpha]=[E]/[v]^2=M$ and $[\beta]=[E]/[x]=MLT^{-2}$.`,marking:[L`Obtains $[\alpha]=M$.`,L`Obtains $[\beta]=MLT^{-2}$.`]},
    {prompt:"Explain why the rewritten expression is invalid and give the algebraically correct factorisation when alpha is non-zero.",answer:L`$v^2$ and $x$ have different dimensions and cannot be added. The valid factorisation is $E=\alpha[v^2+(\beta/\alpha)x]$; $(\beta/\alpha)x$ has dimensions $L^2T^{-2}$.`,marking:["Identifies addition of unlike dimensions.",L`Gives $\alpha[v^2+(\beta/\alpha)x]$ and checks the terms match.`]}],
    ["Find each coefficient by division.","Compare the dimensions inside the proposed bracket.","Factoring out alpha must also divide the second coefficient by alpha."],["Treating dimensionful coefficients as interchangeable numbers."]),
  M("1.5",101,3,L`Assume the speed $v$ of a disturbance depends only on pressure $P$ and density $\rho$, as $v=kP^a\rho^b$, with dimensionless $k$. The exponents are`,
    L`$a=\tfrac12,\ b=-\tfrac12$`,[[L`$a=1,\ b=-1$`,"This produces speed squared rather than speed."],[L`$a=-\tfrac12,\ b=\tfrac12$`,"This has inverse-speed dimensions."],[L`$a=\tfrac12,\ b=\tfrac12$`,"Mass dimensions would not cancel."]],
    L`Comparing $LT^{-1}=(ML^{-1}T^{-2})^a(ML^{-3})^b$ gives $-2a=-1$ and $a+b=0$, hence $a=1/2$, $b=-1/2$.`,
    ["Write pressure and density dimensions.","Match the time exponent first.","Use cancellation of the mass exponent to obtain b."]),
  M("1.5",102,2,L`A student proposes $s=ut+at^2$ for displacement under constant acceleration. What can dimensional analysis alone establish?`,
    "The equation is dimensionally consistent, but its numerical coefficient cannot be checked.",[["The equation must be physically correct.","Homogeneity is necessary but cannot establish the coefficient of the acceleration term."],["The equation is invalid because acceleration cannot be added to velocity.","The terms are acceleration times time squared and velocity times time, both lengths."],["The equation must contain a factor of one-half by dimensional analysis.","A dimensionless numerical factor is invisible to dimensional analysis."]],
    L`Both $ut$ and $at^2$ have length dimensions. The correct coefficient $1/2$ in the acceleration term requires kinematics, not dimensions alone.`,
    ["Check the dimensions of complete terms.","Does multiplying a term by a pure number change its dimensions?","Separate consistency from physical correctness."]),
  M("1.5",103,3,L`An orbital time scale is assumed to have the form $T=C r^a\mu^b$, where $[\mu]=L^3T^{-2}$ and $C$ is dimensionless. The exponents are`,
    L`$a=\tfrac32,\ b=-\tfrac12$`,[[L`$a=\tfrac12,\ b=-\tfrac12$`,"The net length exponent would not vanish."],[L`$a=3,\ b=-1$`,"This produces time squared."],[L`$a=\tfrac32,\ b=\tfrac12$`,"The time exponent would be negative."]],
    L`Matching $T=L^{a+3b}T^{-2b}$ gives $-2b=1$ and $a+3b=0$. Thus $b=-1/2$, $a=3/2$.`,
    ["Write the dimensions of the assumed power law.","Match the time exponent first.","Set the total length exponent to zero."]),
  M("1.5",104,2,L`Assertion (A): Dimensional analysis cannot determine an unknown dependence on a dimensionless launch angle. Reason (R): Different functions of an angle can have identical dimensions.`,
    "Both A and R are true, and R explains A.",[["Both A and R are true, but R does not explain A.","The indistinguishable dimensions of angle functions directly cause the limitation."],["A is true, but R is false.","Sine, cosine and many other functions of an angle are dimensionless."],["A is false, but R is true.","Dimensions alone cannot select the correct angle function."]],
    L`For example, $\sin\theta$ and $\sin2\theta$ are both dimensionless. Homogeneity cannot distinguish them, so dynamical reasoning is needed.`,
    ["An angle in radians is dimensionless.","Compare dimensions of different trigonometric functions.","Ask what information survives a dimensions-only calculation."]),
  W("1.5",101,"vsaq",2,L`A proposed expression for a time is $\sqrt{h/g}$, where $h$ is height and $g$ is acceleration.`,[
    {prompt:"Check its dimensions. Does the check prove it is the exact fall time from rest?",answer:L`$[\sqrt{h/g}]=\sqrt{L/(LT^{-2})}=T$. It is dimensionally a time, but the actual free-fall result contains $\sqrt2$, which dimensions cannot determine.`,marking:["Shows time dimensions and states that the exact numerical factor is not determined."]}],
    ["Divide height dimensions by acceleration dimensions.","Take the square root.","A numerical factor does not affect dimensions."],["Treating a dimensionally valid formula as a proven motion law."]),
  W("1.5",102,"saq",3,L`Assume the energy stored in a stretched spring depends only on its spring constant $k$ and extension $x$: $E=Ck^a x^b$.`,[
    {prompt:"Find a and b by dimensions. State one quantity this method leaves undetermined.",answer:L`$[k]=MT^{-2}$, so $ML^2T^{-2}=M^aT^{-2a}L^b$ gives $a=1,b=2$. The dimensionless constant $C$ remains undetermined.`,marking:["Obtains a=1 and b=2 by matching dimensions.","States that C cannot be determined."]}],
    ["Use force per extension for k.","Match mass and length powers.","A pure number is not fixed by homogeneity."],["Claiming that dimensional analysis determines the factor one-half."]),
  W("1.5",103,"laq",3,L`The drag force on a body is assumed to depend only on fluid density $\rho$, frontal area $A$ and speed $v$: $F=C\rho^a A^b v^c$.`,[
    {prompt:"Determine the exponents using dimensional analysis.",answer:L`$MLT^{-2}=M^aL^{-3a+2b+c}T^{-c}$. Thus $a=1,c=2$, and $-3+2b+2=1$ gives $b=1$. Therefore $F=C\rho Av^2$.`,marking:["Writes the correct dimensions equation.","Obtains a=1 and c=2.","Obtains b=1 and the force scaling."]},
    {prompt:"Predict the change in drag if area is halved and speed doubled, assuming the same C. Explain why the same C must be specified.",answer:L`$F'/F=(1/2)(2^2)=2$. The dimensionless coefficient can depend on shape and flow conditions; dimensions alone do not fix it.`,marking:["Obtains a factor of two.","Identifies that C is not fixed by dimensional analysis."]}],
    ["Match mass, time and then length powers.","Use area dimensions L squared.","Compare the products of the area and speed-squared factors."],["Using length dimensions for area."]),
  W("1.5",104,"case",3,L`A student suggests that a liquid drop's oscillation time depends only on density $\rho$, radius $r$ and surface tension $\sigma$, whose SI unit is $\mathrm{N\,m^{-1}}$. Let $T=C\rho^a r^b\sigma^c$.`,[
    {prompt:"Find the exponents and the resulting time scaling.",answer:L`$[\sigma]=MT^{-2}$. Equating dimensions gives $a+c=0$, $-3a+b=0$, and $-2c=1$. Hence $a=1/2,b=3/2,c=-1/2$, so $T=C\sqrt{\rho r^3/\sigma}$.`,marking:["Uses the dimensions of surface tension correctly.","Obtains all three exponents and the scaling."]},
    {prompt:"For drops of the same liquid under the same conditions, compare periods when one radius is four times the other.",answer:L`With unchanged density, surface tension and C, $T_2/T_1=4^{3/2}=8$.`,marking:["Uses the radius power three-halves.","Obtains a factor of eight."]}],
    ["Convert N per metre to base dimensions.","Write one equation for each base-dimension exponent.","Use the derived radius exponent rather than assuming proportionality to radius."],["Treating surface tension as pressure."]),
];
