import type { VideoMetadata } from "@/lib/video-lessons";

// Generated by scripts/check-video-lessons.mjs --refresh; no student-side metadata requests.
export const VIDEO_METADATA: Record<string, VideoMetadata> = {
  xZELQc11ACY: {
    title: "Intersection of Sets, Union of Sets and Venn Diagrams",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  bAHqiEESWgs: {
    title:
      "Sets Class 11 One Shot 🔥 | Complete Chapter | Maths Chapter 1 by Uday Sir",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  PlrvWjFoDz4: {
    title:
      "TRIGONOMETRIC FUNCTIONS in 1 Shot || FULL Chapter Coverage (Concepts+PYQs) || Class 11th Maths",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  OQz1ydBcQSA: {
    title: "Complex Numbers - Basic Operations",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  X6pqgXzfNDQ: {
    title:
      "Complex Numbers Class 11 One Shot | Class 11 Maths Chapter 5 | Vedantu Math | Harsh Priyam Sir",
    channel: "Vedantu JEE Made Ejee",
    checkedOn: "2026-09-19",
  },
  fyJAOD3X5tw: {
    title:
      "How To Find The Slope and Y Intercept of a Line | Linear Equations - Algebra",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  guYhVnACdTk: {
    title:
      "STRAIGHT LINES in 1 Shot || FULL Chapter Coverage (Concepts+PYQs) || Class 11th MATHS",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  l2yuDvwYq5g: {
    title: "Significant Figures - A Fast Review!",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "bin4OCO-LSc": {
    title: "Units & Measurements in ONE SHOT 🔥 | Class 11 Physics Chapter 1",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  dHjWVlfNraM: {
    title: "Kinematics In One Dimension - Physics",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  m8dx27hc5Q0: {
    title:
      "MOTION IN A STRAIGHT LINE in 1 Shot || FULL Chapter Coverage (Concepts+PYQs) || Class 11th Physics",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  WM_H3b6wOKc: {
    title:
      "MOTION IN A PLANE in 1 Shot || FULL Chapter Coverage (Concepts+PYQs) || Class 11th Physics",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  g550H4e5FCY: {
    title: "Newton's Law of Motion - First, Second & Third - Physics",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  OpfWImlMeq0: {
    title: "Laws of Motion Class 11 - Newton's Laws of Motion | Physics",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  irYPta9G_sw: {
    title: "How To Convert Grams To Moles - VERY EASY!",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  sZBq2x8ArAM: {
    title:
      "Some Basic Concepts of Chemistry Class 11 | Chemistry Class 11 | Full Revision in 30 Minutes",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  NIwcDnFjj98: {
    title: "Electron Configuration - Basic introduction",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  R0dDOK2twpI: {
    title: "Structure of Atom Class 11 Chemistry | Marks Booster One Shot",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  kFvEo1qZdNw: {
    title: "Ionic and Atomic Radius - Periodic Trends",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  wXtQXh03GYE: {
    title:
      "Classification of Elements and Periodicity in Properties Class 11 Chemistry Chapter 3 | 2026-27",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  "YqT-DAmvi3I": {
    title:
      "One to one and onto functions | Relations and Functions | Class XII | Mathematics | Khan Academy",
    channel: "Khan Academy India",
    checkedOn: "2026-09-19",
  },
  _VGodfB7zpM: {
    title:
      "Relations & Functions, One shot video for Class 12 Maths NCERT for CBSE Boards 2023",
    channel: "Arvind Academy",
    checkedOn: "2026-09-19",
  },
  vzt9c7iWPxs: {
    title: "Multiplying Matrices",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "4e4xqoYdylo": {
    title:
      "Matrices Class 12 One Shot 🔥 | Maths Chapter 3 | Full NCERT + Board 2026 | VIJETA 2026",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  xuAiQOzIkWY: {
    title:
      "Differentiability and continuity | Derivatives introduction | AP Calculus AB | Khan Academy",
    channel: "Khan Academy",
    checkedOn: "2026-09-19",
  },
  "2TWRSvJUqVs": {
    title:
      "Continuity & Differentiability, One shot video for Class 12 Maths NCERT for CBSE Boards 2023",
    channel: "Arvind Academy",
    checkedOn: "2026-09-19",
  },
  j_Cy891cmIY: {
    title:
      "Equipotential Lines & Surfaces, Electric Field, Work & Voltage - Physics",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "9nU2YZ2HVPA": {
    title:
      "Electric Charges And Fields Class 12 One Shot | Physics Chapter 1 | VIJETA 2026 🔥",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  wejz5s31Cts: {
    title:
      "Series and Parallel Circuits Explained - Voltage Current Resistance Physics - AC vs DC & Ohm's Law",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "7Wh42oHg0JY": {
    title: "Current Electricity One Shot | Physics | Class 12th Boards",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  csMqfwJRjCs: {
    title:
      "Magnetism, Magnetic Field Force, Right Hand Rule, Ampere's Law, Torque, Solenoid, Physics Problems",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  lYqCUYI9D7Y: {
    title:
      "Moving Charges And Magnetism Class 12 One Shot | NCERT Revision | Physics Chapter 4 | VIJETA 2026 🔥",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  O_nyEj_hZzg: {
    title:
      "Molarity, Molality, Volume & Mass Percent, Mole Fraction & Density - Solution Concentration Problems",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "0M3kJJid0Rc": {
    title:
      "Solutions in One Shot | Chemistry Class 12 | Chapter 02 | CBSE NEET JEE CUET",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  vLCf4_NKjGU: {
    title: "How To Draw Galvanic Cells and Voltaic Cells - Electrochemistry",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  hCBQTg64MfQ: {
    title:
      "Electrochemistry | Chemistry Class 12 One Shot 🔥| Bharat Panchal |  Boards 2024 | NEET | JEE",
    channel: "Class 12 by Unacademy",
    checkedOn: "2026-09-19",
  },
  e4qci9b2d3U: {
    title:
      "Half-life of a first-order reaction | Kinetics | AP Chemistry | Khan Academy",
    channel: "Khan Academy Organic Chemistry",
    checkedOn: "2026-09-19",
  },
  d2GGCSc0VMU: {
    title:
      "Chemical Kinetics in One Shot | Class 12 Chemistry | Chapter 04 | CBSE JEE NEET CUET",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  FQX48a7SGB8: {
    title:
      "CBSE Class 12 Chemistry - 2 | Solutions |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  DC7cFdUawBc: {
    title:
      "CBSE Class 12 Chemistry - 3 | Electrochemistry |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  RVDKighUnBY: {
    title:
      "CBSE Class 12 Chemistry - 4 | Chemical Kinetics |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  MXM7G3EJrdQ: {
    title:
      "CBSE Class 12 Chemistry - 8 | The d & f Block Elements | Part 1 |  Full Chapter | NCERT Animation |",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  BRZSD0RKgKo: {
    title:
      "CBSE Class 12 Chemistry - 8 | The d & f Block Elements | Part 2 |  Full Chapter | NCERT Animation |",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  TYe7SJZKOYg: {
    title:
      "CBSE Class 12 Chemistry - 9 | Coordination Compounds |  Full Chapter | NCERT Animation | JEE NEET CB",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  LIS9HVYJHeI: {
    title:
      "CBSE Class 12 Chemistry - 10 | Haloalkanes and Haloarenes |  Full Chapter | NCERT Animation | JEE NE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "TNsSr0l-T6g": {
    title:
      "CBSE Class 12 Chemistry - 11 | Alcohols, Phenols and Ethers |  Full Chapter | NCERT Animation | JEE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  jrW8BfVbsFU: {
    title:
      "CBSE Class 12 Chemistry - 12 | Aldehydes, Ketones & Carboxylic Acids |  Full Chapter | NCERT Animati",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "4heMA_R3zN8": {
    title:
      "CBSE Class 12 Chemistry - 13 | Amines |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  f_0H5yxxjlU: {
    title:
      "CBSE Class 12 Chemistry - 14 | Biomolecules |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  zZ3kpW3XiqQ: {
    title:
      "d and f Block Elements One Shot | Class 12 Chemistry | Bharat Panchal Sir",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  W7v7yc40zo0: {
    title:
      "Coordination Compound in One Shot | Class 12 Chemistry Boards 2026 | Bharat Panchal Sir",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  yDYnKBc4akQ: {
    title:
      "Haloalkanes and Haloarenes in One Shot | Class 12 | Boards 2025 - 26 | Bharat Panchal",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  KbeDVZDISbo: {
    title:
      "Alcohol, Phenol and Ethers  in One Shot | Class 12 | Boards 2025 - 26 | Bharat Panchal",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  Yr0QFOw0NCI: {
    title: "Aldehyde Ketones and Carboxylic Acid in One Shot",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  PCdKnJvbd1A: {
    title: "Class 12 Chemistry | Amines in One Shot | Bharat Panchal Sir",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  P4VtiTmzTSM: {
    title: "Class 12 Chemistry I Biomolecules in One Shot | bharat Panchal Sir",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  xHZREcntcY8: {
    title:
      "CBSE Class 12 Chemistry - 5 | Surface Chemistry | Part 1 |  Full Chapter | NCERT Animation | JEE NEE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  F8CtJ5xSk54: {
    title:
      "CBSE Class 12 Chemistry - 5 | Surface Chemistry | Part 2 |  Full Chapter | NCERT Animation | JEE NEE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  QNLwFXijkd8: {
    title:
      "CBSE Class 12 Chemistry - 6 | General Principles & Process of Isolation |  Full Chapter | NCERT Anim",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  q9gXiFfnCZw: {
    title:
      "CBSE Class 12 Chemistry - 16 | Polymers |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "e9R-jwdcDQU": {
    title:
      "CBSE Class 12 Chemistry - 15 | Chemistry in Everyday Life |  Full Chapter | NCERT Animation | JEE NE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  k6M7sdtDvD0: {
    title:
      "Class 12 Chemistry | Surface Chemistry in 30 Minutes | CUET | NEET Bharat Panchal Sir",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  JX7O3Xv5HFQ: {
    title:
      "GENERAL PRINCIPLES & PROCESSES OF ISOLATION in 1 Shot : Chemistry - All Concepts & Imp. Questions",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  "eM15MG-3j_s": {
    title:
      "Class 12 Chemistry - Polymers in 30 Minutes | CUET 2023 | Chemistry by Bharat Panchal",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  "1-R6hhhG51Y": {
    title:
      "CHEMISTRY IN EVERYDAY LIFE in 1 Shot: Chemistry - All Concepts & Imp. Questions | CUET Crash Course",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  LzQpbfU7DLo: {
    title:
      "Determination of Concentration of KMnO4 Soution using Ferrous Ammonium Sulphate - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  rp8VtU74DlU: {
    title:
      "Class 12 Chemistry Practical | Volumetric titration of unknown KMnO4 with Mohr Salt |",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  n4esSHxz_J8: {
    title:
      "Tests for the Functional Group Present in the Organic Compounds - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  AHqjvsaYAxo: {
    title:
      "Class 12 Chemistry Practicals || Best Trick for Salt Analysis 01 || Analysis of Acidic Radicals ||",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  PUrevC1bBd4: {
    title:
      "Class 12 Chemistry Practicals || Best Trick for Salt Analysis 02 || Analysis of Basic Radicals ||",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  "lT-K-XvIdeI": {
    title: "Preparation of Lyophilic and Lyophobic Sols - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  QacQmS3aaTI: {
    title: "Test for Carbohydrates, Proteins and Fats - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  jVXQtXK7Jqo: {
    title:
      "Prepare Pure sample of potash alum || class12th chemistry practical #experiment @a2zpractical991",
    channel: "A2Z practical",
    checkedOn: "2026-09-19",
  },
  j6vaRrT_EcI: {
    title: "Detection of Adulterant in Dal - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  KY4t3z_6HaA: {
    title: "Score 30/30 in Chemistry Practical Boards 2026 with These Secrets",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  rvqLff_eJR8: {
    title:
      "CBSE Class 11 Chemistry - 1 | Some Basic Concept of Chemistry |  Full Chapter | NCERT Animation | JE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  wCunYTntVJo: {
    title:
      "Some Basic Concepts of Chemistry | Class 11 Chemistry | Full Chapter  in 44 Minutes | One Shot",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  "-Qf8IdfFcvk": {
    title:
      "CBSE Class 11 Chemistry - 2 | Structure of Atom | Part 1 |  Full Chapter | NCERT Animation | JEE NEE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  gWJeO6tTf9U: {
    title:
      "CBSE Class 11 Chemistry - 2 | Structure of Atom | Part 2 |  Full Chapter | NCERT Animation | JEE NEE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  TfppDsXOLlY: {
    title:
      "Structure of Atom Chemistry Class 11 One Shot | Complete Chapter in 44 Minutes |",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  "2_gEGKGDuDc": {
    title:
      "CBSE Class 11 Chemistry   4 | Chemical Bonding and Molecular Structure | Part 1 |  Full Chapter | NC",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  pGFd43BJGNc: {
    title:
      "CBSE Class 11 Chemistry - 4 | Chemical Bonding and Molecular Structure | Part 2 |  Full Chapter | NC",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  mibviwHOveM: {
    title:
      "CBSE Class 11 Chemistry - 6 | Thermodynamics | Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "lSmIi-MSZgg": {
    title:
      "Thermodynamics Chemistry Class 11 One Shot | Complete Chapter in 44 Minutes |",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  qi6h6Regqak: {
    title:
      "Class 11 Chemistry | Thermodynamics in 15 Minutes  | Rapid Revision of Chemistry",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  xqUZTDkYUVI: {
    title:
      "CBSE Class 11 Chemistry - 7 | Equilibrium | Part 1 |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "NOO7mjlq-Xs": {
    title:
      "CBSE Class 11 Chemistry - 7 | Equilibrium | Part 2 |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "0MY0ZfdUs5Q": {
    title: "Equilibrium in One Shot | Class 11 Chemistry |",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  lp23KN03JrY: {
    title:
      "Class 11 Chemistry | Equilibrium in 15 Minutes  | Rapid Revision of Chemistry",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  thuIw8GLhzM: {
    title:
      "CBSE Class 11 Chemistry - 8 | Redox Reactions |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  HN0xaDXCftg: {
    title:
      "Redox Reaction in one Shot | Class 11 Chemistry | Full Chapter Revision in 44 Minutes |",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  "soz-THA0luM": {
    title:
      "Class 11 Chemistry | Redox Reaction in 15 Minutes | Rapid Revision of Chemistry",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  "v-XxOyVPmlg": {
    title:
      "CBSE Class 11 Chemistry - 12 | Organic Chemistry | Part 1 |  Full Chapter | NCERT Animation | JEE NE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  xXdvpmvFSfU: {
    title:
      "CBSE Class 11 Chemistry - 12 | Organic Chemistry | Part 2 |  Full Chapter | NCERT Animation | JEE NE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  _x7ZtdYWnSE: {
    title: "Class 11 Organic Chemistry in One Shot",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  CtDQxvp5mcw: {
    title:
      "Class 11 Chemistry | Organic Chemistry in 15 Minutes | Rapid Revision of Chemistry",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  "VF-Lp6IpClM": {
    title:
      "CBSE Class 11 Chemistry - 13 | Hydrocarbons | Part 1 |  Full Chapter | NCERT Animation | JEE NEET CB",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  U2DzcHUgdwI: {
    title:
      "CBSE Class 11 Chemistry - 13 | Hydrocarbons | Part 2 |  Full Chapter | NCERT Animation | JEE NEET CB",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  k7pqxuBK8Jo: {
    title:
      "Hydrocarbons in One Shot | Class 11 Chemistry | Full Chapter Revision | ",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  "w-7kM3xupl4": {
    title:
      "Class 11 Chemistry | Hydrocarbons in 15 Minutes | Rapid Revision of Chemistry",
    channel: "Bharat Panchal - Chemistry Guruji 2.0",
    checkedOn: "2026-09-19",
  },
  aM0UMpyCnbo: {
    title:
      "CBSE Class 11 Chemistry - 5 | States Of Matter |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  ABYNG_ZrXRU: {
    title:
      "CBSE Class 11 Chemistry - 10 | The s Block Elements |  Full Chapter | NCERT Animation | JEE NEET CBS",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  UebSo5CvYDI: {
    title:
      "CBSE Class 11 Chemistry - 11 | The p Block Elements |  Full Chapter | NCERT Animation | JEE NEET CBS",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  FggvNDlkJxo: {
    title: "Purification of Benzoic Acid by Crystallization - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  DboO6_eF5cE: {
    title:
      "Class 11 | Chemistry | CBSE | Classification of elements and periodicity in properties",
    channel: "instyn education",
    checkedOn: "2026-09-19",
  },
  uRTLY3p1VUE: {
    title:
      "Class 11th Chemistry | Redox Reactions and Electrode Processes | Chapter 7 | NCERT",
    channel: "Ignited Minds",
    checkedOn: "2026-09-19",
  },
  AXhOVhqXRXQ: {
    title:
      "Electrodes and voltage of Galvanic cell [Hindi] | Redox reactions | Class 11 | Chemistry",
    channel: "Khan Academy India - Hindi medium",
    checkedOn: "2026-09-19",
  },
  AJiOL1ZgZng: {
    title:
      "States of Matter । Class11 (L1) I Boyles | Charles | Gaylussac's | Avogadros | Ideal gas Equation",
    channel: "Pankaj Sir Chemistry",
    checkedOn: "2026-09-19",
  },
  MKo0d51Udxs: {
    title:
      "11 chap 5 | Gaseous State 07 | Real Gas and Ideal Gas IIT JEE /NEET | Compressibility Factor Z ||",
    channel: "Physics Wallah - Alakh Pandey",
    checkedOn: "2026-09-19",
  },
  "1uJk4K_irP8": {
    title:
      "S block elements class 11 one shot |  Chapter 11 - CBSE JEE NEET NCERT Hindi",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  "6Ojqg1tzdRw": {
    title:
      "CBSE Class 11 Chemistry The p-Block Elements Anomalous behavior of Boron & Important |Extraminds",
    channel: "Extraminds",
    checkedOn: "2026-09-19",
  },
  "22ZB0ZwvOsQ": {
    title: "Basic Laboratory Techniques - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  nQNaTfqXECk: {
    title: "Melting Point of an Organic Compound - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  J9Zmjs1EAWc: {
    title: "Boiling Point of an Organic compound - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  c7g0c59ZxH4: {
    title: "pH Determination - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  XqDchNzLNsY: {
    title:
      "To study the variation in pH by common ion effect in the case of weak acids and weak bases",
    channel: "LabInApp",
    checkedOn: "2026-09-19",
  },
  zCeciBrBhMU: {
    title:
      "Study the Shift in Equilibrium between Ferric ions and Thiocyanate ions",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  rZX_Hv2LNQg: {
    title: "NCERT | CBSE | RBSE | Class-11 | प्रायोगिक रसायन | PH ज्ञात करना",
    channel: "Ekaksha",
    checkedOn: "2026-09-19",
  },
  O3d_NKyhIwg: {
    title: "Chemical Tests for Chloride - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  GTZBs3iZgg0: {
    title: "Tests for Ammonium Ion - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  wI_X8xRnh9E: {
    title:
      "Salt Analysis Complete Theory + Practical | Boards & NEET 2026 | Rohit Saini Sir",
    channel: "ALLEN NEET",
    checkedOn: "2026-09-19",
  },
  FUo428guKt0: {
    title: "Detection of Elements: Lassaigne’s Test - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  slC3G0XVenU: {
    title:
      "Lassaigne's Test I Sodium Fusion Extract I Nitrogen, Sulphur, Halogen I 200K Views #jee #neet",
    channel: "Dr. Yadav D.K.",
    checkedOn: "2026-09-19",
  },
  "6oabC6KaUpQ": {
    title:
      "Class 11 Experiment Chemistry | Cutting, Bending Drawing jet from glass tube | Theory and Practical",
    channel: "Bhatia Mam Classes",
    checkedOn: "2026-09-19",
  },
  "8q5HN1Pef9Q": {
    title:
      "➡️ Titration Experiment for Board Class | Complete Video to Understand Chemistry Practical | ALLEN",
    channel: "ALLEN Career Institute",
    checkedOn: "2026-09-19",
  },
  "5ZhNmKb-dqk": {
    title: "Set Theory | All-in-One Video",
    channel: "Dr. Will Wood",
    checkedOn: "2026-09-19",
  },
  wbBY2tTqXDA: {
    title: "Relations and Functions | Algebra",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  KyOQhC8ctxc: {
    title:
      "Domain and Range Functions & Graphs - Linear, Quadratic, Rational, Logarithmic & Square Root",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  QPAbml1pQ0Q: {
    title:
      "Relations and Functions Class 11 Maths Chapter 2 | Full Chapter One Shot New NCERT 2026-27 JEE CBSE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  m1OitPmkydY: {
    title: "Trig Identities",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "Vw-RwPBWS8g": {
    title:
      "Graphing Sine and Cosine Trig Functions With Transformations, Phase Shifts, Period - Domain & Range",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  sU2pyMR8GZ4: {
    title:
      "Sum and Difference Identities & Formulas - Sine, Cosine, Tangent - Degrees & Radians, Trigonometry",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  SE5SBTgrwH8: {
    title:
      "Double Angle Identities & Formulas of Sin, Cos & Tan - Trigonometry",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  FS3L1k6lHXQ: {
    title:
      "Trigonometric Functions Class 11 Maths Chapter 3 | Full Chapter One Shot New NCERT 2026-27 CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  "1r6yLUKc8yc": {
    title:
      "Linear Inequalities Class 11 Maths Chapter 5 | Full Chapter 2026-27 | New NCERT - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  DrZJKdXlZ3I: {
    title: "How To Solve Linear Inequalities, Basic Introduction, Algebra",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  XJnIdRXUi7A: {
    title: "Permutations and Combinations Tutorial",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  s19dWIHficY: {
    title:
      "Binomial Theorem Expansion, Pascal's Triangle, Finding Terms & Coefficients, Combinations, Algebra 2",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  XZJdyPkCxuE: {
    title: "Arithmetic Sequences and Arithmetic Series - Basic Introduction",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "Tr-TVt5JAWY": {
    title:
      "Permutations and Combinations Class 11 Maths Chapter 7 | New NCERT | 2026-27 Session - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  j9GohkxkjGk: {
    title:
      "Binomial Theorem Class 11 Maths Chapter 8 | New NCERT | 2026-27 Session - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  "CCWhTwyx-rc": {
    title:
      "Sequences and Series Class 11 Maths Chapter 9 | New NCERT | 2026-27 Session - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  ceORkyzh6pA: {
    title:
      "06 - Equations & Definition of Conic Sections - Circle, Ellipse, Parabola & Hyperbola",
    channel: "Math and Science",
    checkedOn: "2026-09-19",
  },
  EzJP9uwV3ms: {
    title: "Plotting Points In a Three Dimensional Coordinate System",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "5BDrdI3rdQY": {
    title: "Distance Between a Point and a Line In 2D & 3D - Geometry",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  kS2ydDhLaVw: {
    title:
      "Conic Sections Class 11 Maths Chapter 11 | New NCERT | 2026-27 Session - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  bnah8aIb7CU: {
    title:
      "Introduction to Three Dimensional Geometry 3D Class 11 Maths Chapter 12 | NCERT | 2026-27 CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  "xGibYZiT5-U": {
    title: "Limits and Derivatives",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  lvJUmabJhLE: {
    title:
      "Derivative as a Rate of Change | Tangent Line & Velocity Problems (Calc 1)",
    channel: "Understand The Math",
    checkedOn: "2026-09-19",
  },
  HbtuSC_WOW0: {
    title: "Limits of Trigonometric Functions",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  PEqCa0U77mc: {
    title: "Derivatives of Trigonometric Functions",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  rXRN_8Wz5kk: {
    title:
      "Limits and Derivatives Class 11 Maths Chapter 12 | New NCERT | 2026-27 Session - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  TePZBh0y9TI: {
    title:
      "SET, RELATIONS AND FUNCTIONS Class 11 & 12 | Complete JEE Maths One Shot in Pure English",
    channel: "PW JEE English",
    checkedOn: "2026-09-19",
  },
  j9UeuYDob8Y: {
    title: "Relation & Function  Class 12 | JEE Main & Advanced",
    channel: "JEE Nexus by Unacademy ",
    checkedOn: "2026-09-19",
  },
  "8EKy2Hxprrg": {
    title:
      "Complex Numbers Class 11 | One Shot in English | JEE Main & Advanced",
    channel: "Unacademy JEE English",
    checkedOn: "2026-09-19",
  },
  sKwCHRS8zqA: {
    title: "Complex Numbers Class 11 | JEE Main & Advanced",
    channel: "JEE Nexus by Unacademy ",
    checkedOn: "2026-09-19",
  },
  reMEOAcJi7U: {
    title:
      "Quadratic Equations Class 11 | One Shot in English | JEE Main & Advanced",
    channel: "Unacademy JEE English",
    checkedOn: "2026-09-19",
  },
  xMFg07mCutk: {
    title: "Quadratic Equation Class 11 | JEE Main & Advanced",
    channel: "JEE Nexus by Unacademy ",
    checkedOn: "2026-09-19",
  },
  _dn3yUfNZKU: {
    title:
      "Statistics Class 11 Maths Chapter 15 | Full Chapter One Shot | New NCERT 2026-27 - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  Uk98hiMQgN0: {
    title:
      "Standard Deviation Formula, Statistics, Variance, Sample and Population Mean",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  x6Pnf57wRAs: {
    title: "How To Calculate The Standard Deviation of Grouped Data",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "0T-CaQCiSf4": {
    title: "Probability of Complementary Events & Sample Space",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  qYqS5Ib7TxA: {
    title:
      "Probability Class 11 Maths | Chapter 16 Full Chapter One Shot | New NCERT 2026-27 - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  "nf2id-6PrQY": {
    title:
      "Inverse Trigonometric Functions Class 12 Maths | New NCERT 2026-27 | Chapter 2 One Shot - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  hrumNRQwTV8: {
    title: "Equivalence Classes and Partitions",
    channel: "Neso Academy",
    checkedOn: "2026-09-19",
  },
  "jt7p-mCC0ng": {
    title: "Evaluating Inverse Trigonometric Functions",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  waDbbpib9cM: {
    title:
      "Inverse Trig Functions With Double Angle Formulas and Half Angle Identities - Trigonometry",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  hyhktV5pxrE: {
    title:
      "Matrices Class 12 Maths | New NCERT 2026-27 | Chapter 3 One Shot | Full Chapter - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  "5zIK-D1DVgo": {
    title:
      "Symmetric and skew symmetric matrices | Matrices | Grade 12 | Math | Khan Academy",
    channel: "Khan Academy India - English",
    checkedOn: "2026-09-19",
  },
  UHhvcj0doaA: {
    title: "Solving Matrix Equations",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "3ROzG6n4yMc": {
    title:
      "Determinant of 3x3 Matrices, 2x2 Matrix, Precalculus Video Tutorial",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  _jHGxcX0C10: {
    title: "Minors and Cofactors of a Matrix | Linear Algebra",
    channel: "Wrath of Math",
    checkedOn: "2026-09-19",
  },
  Fg7_mv3izR0: {
    title: "Inverse of a 3x3 Matrix",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "6Nk8YoHgnss": {
    title:
      "Application of Derivatives Class 12 Maths | NCERT Chapter 6 | CBSE JEE | One Shot |हिंदी में",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  A9CR6XOuQkk: {
    title:
      "Implicit Differentiation Second Derivative Trig Functions & Examples- Calculus",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  WiOdQQYLMU4: {
    title:
      "Application of Derivatives - Formulas and Notes - Calculus Study Guide Review",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  o75AqTInKDU: {
    title:
      "Indefinite Integral - Basic Integration Rules, Problems, Formulas, Trig Functions, Calculus",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "6rXByMcuAyI": {
    title: "Integration By Partial Fractions",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  aeB5BWY0RlE: {
    title: "Fundamental Theorem of Calculus Part 1",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  kgg5Rspf1Js: {
    title: "Area Between Two Curves",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  C7nuJcJriWM: {
    title: "Separable First Order Differential Equations - Basic Introduction",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  hXOrQ0Ao4UE: {
    title:
      "Integration Class 12 Maths | NCERT Chapter 7 | CBSE JEE | One Shot |हिंदी में",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  qEU2oKUNosA: {
    title:
      "Application of Integrals Class 12 Maths | NCERT Chapter 8 | CBSE JEE | One Shot |हिंदी में",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  HzUPPCfcw64: {
    title:
      "Differential Equations Class 12 Maths | NCERT Chapter 9 | CBSE JEE | One Shot |हिंदी में",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  uZHMmMeNySo: {
    title:
      "VECTOR ALGEBRA Class 12 in One Shot | Class 12 Maths | Class 12 BOARDS/JEE Mains | Class 12 TERM 2",
    channel: "Apni Kaksha Official",
    checkedOn: "2026-09-19",
  },
  QgBLda_lXhU: {
    title: "Class 12 Maths Chapter 11: ONE SHOT | Three Dimensional Geometry",
    channel: "Skill Ark",
    checkedOn: "2026-09-19",
  },
  NEj70xMyRIk: {
    title:
      "Vector Algebra Class 12 Maths | NCERT Chapter 10 | CBSE JEE | One Shot |हिंदी में",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  ZoCxUV893fo: {
    title: "Calculus 3 - Direction Cosines & Direction Angles of a Vector",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "xS-gdFgZel0": {
    title: "Addition of Vectors By Means of Components - Physics",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  VzX8KJKFhlM: {
    title: "Dot Product of Two Vectors",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  pWbOisq1MJU: {
    title: "Cross Product of Two Vectors Explained!",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  jCluGlqH70M: {
    title:
      "3d Geometry Class 12 Maths | NCERT Chapter 11 | CBSE JEE | One Shot |हिंदी में",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  wEkEihCorHw: {
    title:
      "Linear Programming Class 12 Maths One Shot | NCERT Chapter 12 CBSE JEE NEET",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  Bzzqx1F23a8: {
    title: "Linear Programming",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  OByl4RJxnKA: {
    title: "Bayes' Theorem of Probability With Tree Diagrams & Venn Diagrams",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  "94AmzeR9n2w": {
    title:
      "Multiplication & Addition Rule - Probability - Mutually Exclusive & Independent Events",
    channel: "The Organic Chemistry Tutor",
    checkedOn: "2026-09-19",
  },
  vO9zVl0fXZA: {
    title:
      "Probability Class 12 Maths | NCERT Chapter 13 | CBSE JEE | One Shot |हिंदी में",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  U4j8Pw4hV5U: {
    title:
      "Determinants Class 12 Maths One Shot | Chapter 4 | 2026-27 New NCERT - CBSE JEE",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  "K-thBCPDqaY": {
    title: "MATRICES Class 12 | Complete JEE Maths One Shot in Pure English",
    channel: "PW JEE English",
    checkedOn: "2026-09-19",
  },
  fsmiRRcj_nw: {
    title:
      "DETERMINANTS Class 12 | Complete JEE Maths One Shot in Pure English",
    channel: "PW JEE English",
    checkedOn: "2026-09-19",
  },
  jr_DqbNC_dI: {
    title:
      "Matrices And Determinants One Shot | JEE Main 2024 | RRR | Arvind Kalia Sir",
    channel: "JEE Nexus by Unacademy ",
    checkedOn: "2026-09-19",
  },
  v1_PvRIykCs: {
    title:
      "CBSE Class 11 Physics   2 ¦ Units and Measurements ¦  Full Chapter ¦ NCERT Animation ¦ JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  hzIP3ECrGJo: {
    title:
      "CBSE Class 11 Physics - 3 | Motion In A Straight Line |  Full Chapter | NCERT Animation | JEE NEET C",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  DLjgka69URU: {
    title:
      "CBSE Class 11 Physics - 4 | Motion in a Plane |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  RX1B67J88NQ: {
    title:
      "CBSE Class 11 Physics - 5 | Laws of Motion |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  vqVAOthL8f0: {
    title:
      "CBSE Class 11 Physics - 6 | Work Energy and Power |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  mR_6KPV2Zjk: {
    title:
      "CBSE Class 11 Physics - 7 | System Of Particles and Rotational Motion |  Full Chapter | NCERT Animat",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "J2-PpzuaacE": {
    title:
      "CBSE Class 11 Physics - 8 | Gravitation |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "5wHjxNSPouQ": {
    title:
      "CBSE Class 11 Physics - 9 |  Mechanical Properties of Solids |  Full Chapter | NCERT Animation | JEE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  Tdn_NkQFF3M: {
    title:
      "CBSE Class 11 Physics - 10 |  Mechanical Properties of Fluids |  Full Chapter | NCERT Animation | JE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  hz22apRERW0: {
    title:
      "CBSE Class 11 Physics - 11 |  Thermal Properties of Matter |  Full Chapter | NCERT Animation | JEE N",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  Wg6kTB3yYjM: {
    title:
      "CBSE Class 11 Physics - 12 |  Thermodynamics |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "3yTCXDYGSpI": {
    title:
      "CBSE Class 11 Physics - 13 | Kinetic Theory |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  JH7kBhlHNoE: {
    title:
      "CBSE Class 11 Physics - 14 | Oscillations  |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "8F4c62h4Xkg": {
    title:
      "CBSE Class 12 Physics - 1 | Electric Charges and Fields | Part 1 |  Full Chapter | NCERT Animation |",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  UEXEHi42_kg: {
    title:
      "CBSE Class 12 Physics - 1 | Electric Charges and Fields | Part 2 |  Full Chapter | NCERT Animation |",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  Bfl7sfmNYeo: {
    title:
      "CBSE Class 12 Physics - 2 | Electrostatic Potential & Capacitance | Part 1 |  Full Chapter | NCERT A",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  qz5RRFT23Qk: {
    title:
      "CBSE Class 12 Physics - 2 | Electrostatic Potential & Capacitance | Part 2 |  Full Chapter | NCERT A",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  m4N8CPjHN3Q: {
    title:
      "CBSE Class 12 Physics - 3 | Current Electricity |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  K2OYkQqZ01Q: {
    title:
      "CBSE Class 12 Physics - 4 | Moving Charges and Magnetism |  Full Chapter | NCERT Animation | JEE NEE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  RL0p9vXbdYI: {
    title:
      "CBSE Class 12 Physics - 5 | Magnetism and Matter |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  LlUqU81NnIs: {
    title:
      "CBSE Class 12 Physics - 6 | Electromagnetic Induction |  Full Chapter | NCERT Animation | JEE NEET C",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  PnnFhvjJ7Xw: {
    title:
      "CBSE Class 12 Physics - 7 | Alternating Current |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  PDRKP4b7tJE: {
    title:
      "CBSE Class 12 Physics - 8 | Electromagnetic Waves |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  ALC0WDdbnsk: {
    title:
      "CBSE Class 12 Physics - 9 | Ray Optics and Optical Instruments | Part 1 |  Full Chapter | NCERT Anim",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  RNgPpwfVYM4: {
    title:
      "CBSE Class 12 Physics - 9 | Ray Optics and Optical Instruments | Part 2 |  Full Chapter | NCERT Anim",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  u30W5ipiQL8: {
    title:
      "CBSE Class 12 Physics - 10 | Wave Optics |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "3RoTS5DM-fk": {
    title:
      "CBSE Class 12 Physics - 11 | Dual Nature of Radiation and Matter |  Full Chapter | NCERT Animation |",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  mIqlLELb_dA: {
    title:
      "CBSE Class 12 Physics - 12 | Atoms |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  H_1Au9yVl1M: {
    title:
      "CBSE Class 12 Physics - 13 | Nuclei |  Full Chapter | NCERT Animation | JEE NEET CBSE",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  FdjTjiKiGkE: {
    title:
      "CBSE Class 12 Physics - 14 | Semiconductor Electronics | Part 1 |  Full Chapter | NCERT Animation |",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "2C0WLYlYxmA": {
    title:
      "CBSE Class 12 Physics - 14 | Semiconductor Electronics | Part 2 |  Full Chapter | NCERT Animation |",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "-t7wCNnJATc": {
    title:
      "LAWS OF MOTION in 1 Shot || FULL Chapter Coverage (Concepts+PYQs) || Class 11th Physics",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  _Yp0Jq_b3kM: {
    title: "Thermodynamics, One shot video for Class 11 Physics NCERT",
    channel: "Arvind Academy",
    checkedOn: "2026-09-19",
  },
  "5ppdT-dsC4Y": {
    title:
      "POTENTIAL & CAPACITANCE in Just 10 mins 🔥 Physics Class 12 Boards 2025 🎯 Arvind Academy",
    channel: "Arvind Academy",
    checkedOn: "2026-09-19",
  },
  j5wR8pfqyh4: {
    title:
      "Alternating Current Class 12 One Shot 🔥 | NCERT + Derivations + PYQs | Physics Chapter 7",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  "V3JXWwBXv-4": {
    title:
      "Ray Optics And Optical Instruments Class 12 One Shot 🔥 | NCERT Revision | Physics Chapter 7",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  yY6ChKn7thM: {
    title:
      "Wave Optics Class 12 One Shot 🔥 | NCERT + Derivations + PYQ | Physics Chapter 10",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  "7naR68Z6xEs": {
    title:
      "Dual Nature Of Matter And Radiation Class 12 One Shot 🔥 | NCERT Revision | VIJETA 2026",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  v16hdgJ9rag: {
    title:
      "Resonance Tube Experiment Class 11 Physics | Resonance Class 11 | Practical XI:  Resonance Tube",
    channel: "Notes4Boards",
    checkedOn: "2026-09-19",
  },
  "0WeXmbdYsyY": {
    title:
      "Meter Bridge Practical Explained Step-by-Step | Readings, Formula & Viva | Class 12 Physics",
    channel: "Puneet's Physics",
    checkedOn: "2026-09-19",
  },
  FXF1iW7ntig: {
    title: "Waves In One Shot - JEE/NEET/Class 11th Boards | Victory Batch",
    channel: "PW English Medium ",
    checkedOn: "2026-09-19",
  },
  dhNhg9t3Lhw: {
    title:
      "Work Energy And Power class 11 One Shot 🔥 | NCERT + PYQs + Derivations | Physics Chapter 6",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  nwV_ADaD1Dk: {
    title:
      "Rotational Motion Physics Class 11 One Shot 🔥 | NCERT + PYQs + Derivations | Physics Chapter 7",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  "-jJgjcF3TVI": {
    title:
      "Gravitation Class 11 One Shot 🔥 | NCERT + PYQs + Derivations | Physics Chapter 7",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  ZwD4CoXKEUk: {
    title:
      "Mechanical Properties of Solids Class 11 One Shot 🔥 | NCERT + PYQs + Derivations | Physics Chapter 8",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  "6aS6LcLU8hM": {
    title:
      "Mechanical Properties of Fluids Class11 🔥  | NCERT + PYQs + Derivations | Physics Chapter 9",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  "43KARHMMW_w": {
    title:
      "Thermal Properties Of Matter Class 11 One Shot 🔥 | NCERT + PYQs + Derivations | Physics Chapter 11",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  k4FvOpHU0jo: {
    title:
      "Kinetic Theory Of Gases Class 11 Physics One Shot  🔥 | NCERT + Derivations | Physics Chapter 13",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  n0cEcXWPFCU: {
    title:
      "Oscillations Class 11 One Shot 🔥 | NCERT + Derivations | Physics Chapter 14  by Akshay Tyagi Sir",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  p3vMfyGjfcM: {
    title:
      "Waves | Full Chapter in ONE SHOT | Chapter 14 | Class 11 Physics 🔥",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  lWbUXCr3FOk: {
    title:
      "Magnetism And Matter Class 12 One Shot | NCERT Revision | Physics Chapter 5 | VIJETA 2026 🔥",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  GaLQhuyaUNg: {
    title:
      "Electromagnetic Induction Class 12 One Shot | NCERT Revision | Physics Chapter 6 | VIJETA 2026 🔥",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  NsO6M28xPTs: {
    title:
      "Electromagnetic Waves Class Class 12 One Shot 🔥 | NCERT Revision | Physics Chapter 9 By Akshay sir",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  YuU3gaY34dI: {
    title:
      "Atoms and Nuclei Class 12 Physics One Shot 🔥 | NCERT Revision | VIJETA 2026",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  XGc2OCsjIdk: {
    title:
      "Semiconductor 12 Physics One Shot 🔥 | NCERT Revision | VIJETA 2026",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  "11EM0nZUdqE": {
    title:
      "Physics Practical: Edunovus _ Physics _ Screw gauge principle and description (Introduction)",
    channel: "Edunovus",
    checkedOn: "2026-09-19",
  },
  fowRMegIFvw: {
    title: "Parallelogram Law of Vectors - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  WMQZWBi7fbE: {
    title: "Young's Modulus - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  "pH-72pQDsWA": {
    title:
      "CLASS 11 PHYSICS PRACTICAL EXAM ,CLASS 11 PHYSICS VIVA,CLASS 11 PHYSICS PRACTICAL EXPERIMENTs",
    channel: "Munil Sir",
    checkedOn: "2026-09-19",
  },
  "2_KrtHaqw-w": {
    title:
      "Vernier Caliper || How to use vernier caliper in hindi || How to read Vernier scale Class11th Physic",
    channel: "Abhishek Sahu",
    checkedOn: "2026-09-19",
  },
  "4nt6cYjJkzE": {
    title:
      "Parallelogram law of vectors || 11th physics practical #11thphysics @a2zpractical991",
    channel: "A2Z practical",
    checkedOn: "2026-09-19",
  },
  "50VYcOryCXo": {
    title: "Young's Modulus - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  cfRbAfOCkR4: {
    title:
      "Sonometer and Resonance Tube सोनोमीटर और अनुनाद नली Mathematical Calculation 11p2212 ✅",
    channel: "P C VERMA",
    checkedOn: "2026-09-19",
  },
  tbTjRlLIilo: {
    title:
      "Class 11 Physics Practical CBSE Viva Questions and Practical File Exp. | Practical Kaise hote h .",
    channel: "Blue Sky PCM",
    checkedOn: "2026-09-19",
  },
  JTvzP7HrMxU: {
    title: "Metre bridge-Resistance of a wire - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  pPQVH8s_UDU: {
    title: "Conversion of Galvanometer to Voltmeter - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  V6TaA1iLl9U: {
    title:
      "Focal length of convex lens by plotting a graph between u and v // physics experiment class12",
    channel: "Learn Physics with RK TOMAR",
    checkedOn: "2026-09-19",
  },
  h88jDycWFTk: {
    title: "Diode Characteristics - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  aQ0DLteewhM: {
    title:
      "How I Scored 30/30 in Physics Practical | Class 12 Physics Viva Full Guide",
    channel: "Alisha Bhatia",
    checkedOn: "2026-09-19",
  },
  IxjeH_svHak: {
    title:
      "REFRACTIVE INDEX OF LIQUID BY LENS & MIRROR #CBSE#GSEB#PhysicsPractical#Class12#ExperientialPhysics",
    channel: "Experiential Physics",
    checkedOn: "2026-09-19",
  },
  zHLqPRYQomY: {
    title:
      "Galvanometer into Voltmeter Apparatus | Voltmeter | How to convert Galvo to Voltmeter | OM LABS",
    channel: "OM LABS",
    checkedOn: "2026-09-19",
  },
  Kk2Q6TM1JT8: {
    title:
      "class-12 physics practical To find focal length of concave mirror in (Hindi)",
    channel: "One Cup Physics with Ashutosh Sir",
    checkedOn: "2026-09-19",
  },
  b3QY47NGwHw: {
    title:
      "Sure Shot Viva Question for PN Junction Diode | Physics Practical | Physics Baba 2.0",
    channel: "Rankplus",
    checkedOn: "2026-09-19",
  },
  StBdeErCQlc: {
    title:
      "Physics Viva, Physics Practical Class 12: All Experiments List & Viva Questions 2026 🔥",
    channel: "Arvind Academy",
    checkedOn: "2026-09-19",
  },
  lQFxbiQd6QE: {
    title:
      "Experiment CLASS XII - To find the focal length of a concave lens, using a convex lens",
    channel: "Sage Classes - Sachin & sakshi",
    checkedOn: "2026-09-19",
  },
  snlKFX8_q1o: {
    title:
      "CBSE 2020 Class 9 Maths - 1 | Number Systems | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  VQLWEVM0eWs: {
    title:
      "CBSE 2020 Class 9 Maths - 2 | Polynomials | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  qj9PGmoL6Mo: {
    title:
      "CBSE 2020 Class 9 Maths - 3 | Coordinate Geometry | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  B6rfaYAjrMU: {
    title:
      "CBSE 2020 Class 9 Maths - 7 | Triangles | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  JIsKAUERQyQ: {
    title:
      "CBSE 2020 Class 9 Maths - 12 | Heron’s Formula | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "35IP0ggmkjM": {
    title: "Complete Class 9th MATHS in 1 Shot | Final Marathon 🎯",
    channel: "Physics Wallah Foundation",
    checkedOn: "2026-09-19",
  },
  "mwaL-T3-ITQ": {
    title:
      "CBSE Class 9 Science - 5 | The Fundamental Unit of Life | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "PJ0Nl-kwHhA": {
    title:
      "CBSE Class 9 Science - 2 | Is Matter Around Us Pure | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  rRsefE4xoNs: {
    title:
      "CBSE Class 9 Science - 4 | Structure of The Atom | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "7FHrda_i2m8": {
    title: "CBSE Class 9 Science - 8 | Motion | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  BeI58I7lftw: {
    title: "Complete Class 9th SCIENCE in 1 Shot | Final Marathon 🎯",
    channel: "Physics Wallah Foundation",
    checkedOn: "2026-09-19",
  },
  OqIsi_4IkO0: {
    title:
      "CBSE Class 10 Science - 1 | Chemical Reactions and Equations | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  Q5rfzGmhVdQ: {
    title:
      "CBSE Class 10 Science   6 ¦ Life Processes ¦ Full Chapter ¦ NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  nSzg1FyjTBs: {
    title:
      "CBSE Class 10 Science - 10 | Light Reflation and Refraction | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  T8Mam6h_JY8: {
    title:
      "CBSE Class 10 Science - 12 | Electricity | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  KB3a2tNdJ8A: {
    title:
      "CBSE Class 10 Science - 15 | Our Environment | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  DigrHomWUkw: {
    title:
      "CBSE Class 10 Science   5 ¦ Periodic Classification of Elements ¦ Full Chapter ¦ NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  HPphkPll7Wg: {
    title:
      "Class 10th - Complete Science | NCERT Covered - For CBSE Board 2026 | By Alakh Pandey",
    channel: "Alakh Pandey - Class 9th & 10th",
    checkedOn: "2026-09-19",
  },
  ByF2q7TENLE: {
    title:
      "CBSE Class 10 Maths - 1 || Real Numbers || Full Chapter || By Shiksha House",
    channel: "Best for NEET",
    checkedOn: "2026-09-19",
  },
  "5wx-307BDco": {
    title:
      "CBSE Class 10 Maths - 2 || Polynomials || Full Chapter || By Shiksha House",
    channel: "Best for NEET",
    checkedOn: "2026-09-19",
  },
  n0YK4gJCLv0: {
    title:
      "COMPLETE Class 10 Maths 🔥 | Full NCERT Coverage | One Shot Revision | Board Exam 2026",
    channel: "PW Class 10 - UDAAN",
    checkedOn: "2026-09-19",
  },
  "54_XRjHhZzI": {
    title: "Calculus 1 Lecture 1.1:  An Introduction to Limits",
    channel: "Professor Leonard",
    checkedOn: "2026-09-19",
  },
  RUS4mKo9tBk: {
    title: "Calculus 1 Lecture 2.7:  Implicit Differentiation",
    channel: "Professor Leonard",
    checkedOn: "2026-09-19",
  },
  "sB6ZVg-8uJE": {
    title: "Calculus 1 Lecture 5.1 Part 1",
    channel: "Professor Leonard",
    checkedOn: "2026-09-19",
  },
  pUmXQ2926sQ: {
    title: "AP Calculus Units 1–5 Review AB & BC (2026): You Can Get a 5",
    channel: "turksvids",
    checkedOn: "2026-09-19",
  },
  QWuqkiaw_UE: {
    title: "AP Calculus Units 6–10 Review AB & BC (2026): You Can Get a 5",
    channel: "turksvids",
    checkedOn: "2026-09-19",
  },
  sIqVmuNfG3I: {
    title:
      "Reproduction: How Life Continues FULL CHAPTER | Class 9 Science 2026 New Syllabus by LAKSHMI MA'AM",
    channel: "Full Concepts  ",
    checkedOn: "2026-09-19",
  },
  MBTB3_2VHyo: {
    title:
      "Complete Class 9th BIOLOGY In One Shot | All CHAPTERS Rapid Revision 🔥",
    channel: "PW Class 9 - NEEV",
    checkedOn: "2026-09-19",
  },
  Z6alJFYLZ9I: {
    title:
      "Solar Radiation, Heat Balance and Temperature - Physical Geography | Class 6th to 12th NCERT",
    channel: "PW OnlyIAS English",
    checkedOn: "2026-09-19",
  },
  nCNjcmbf9Tc: {
    title: "Mission IAS 2021 | Ecology By Rohan Sir | Biogeochemical Cycles",
    channel: "Unacademy UPSC",
    checkedOn: "2026-09-19",
  },
  teERjw2A51M: {
    title: "Ecology; Biogeochemical Cycles",
    channel: "Mr. Farney's Classroom",
    checkedOn: "2026-09-19",
  },
  "4PP-bAlj2BU": {
    title:
      "Class 9th Science Activity 2.1 (Practical Video) | Heterogenous and Homogenous Mixtures",
    channel: "Educational Hix",
    checkedOn: "2026-09-19",
  },
  AKJyrRNG3is: {
    title:
      "To Prepare Stained Temporary Mount of Onion Peel | Science | Class 9 | Term 1 Practical |CBSE |NCERT",
    channel: "ChemXpert",
    checkedOn: "2026-09-19",
  },
  CHWhaAlo_ms: {
    title:
      "Limits and Derivatives | Full Chapter in ONE SHOT | Chapter 12 | Class 11 Maths 🔥",
    channel: "PW Class 11 Science",
    checkedOn: "2026-09-19",
  },
  KUu18_pkvbk: {
    title:
      "DIFFERENTIATION | BEGINNER'S COURSE JEE 2026 / 2027 FULL PREP FROM BASICS | MATHEMATICALLY INCLINED",
    channel: "Neha Agrawal Mathematically Inclined",
    checkedOn: "2026-09-19",
  },
  Kqmq47WOvdU: {
    title:
      "DIFFERENTIAL EQUATIONS in One Shot: All Concepts & PYQs Covered | JEE Main & Advanced",
    channel: "JEE Wallah",
    checkedOn: "2026-09-19",
  },
  "oixVk-jA3vM": {
    title:
      "Calculus - Indefinite Integration | Definite Integration | Areas | Differential Equations | JEE 2025",
    channel: "Vedantu Telugu JEE",
    checkedOn: "2026-09-19",
  },
  u9gWnGrWkVk: {
    title:
      "CBSE 2020 Class 9 Maths - 4 | Linear Equations in Two Variables | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "6LBC2FnsGEw": {
    title:
      "CBSE 2020 Class 9 Maths - 5 | Introduction to Euclid’s Geometry | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  QS48hkxsOz4: {
    title:
      "CBSE 2020 Class 9 Maths - 6 | Lines and Angles | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  g0osHz73n34: {
    title:
      "CBSE 2020 Class 9 Maths - 8 | Quadrilateral | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  hsqLBpD7hMY: {
    title:
      "CBSE 2020 Class 9 Maths - 10 | Circles | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  QQx5EFJH08s: {
    title:
      "CBSE 2020 Class 9 Maths - 13 | Surface Areas and Volumes Chapter | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "Ol-y2HO18Kg": {
    title: "STATISTICS ONE SHOT | Full Chapter | Class 9 Maths | Chapter 14",
    channel: "PW Class 9 - NEEV",
    checkedOn: "2026-09-19",
  },
  gaNXYPZXVAk: {
    title:
      "The Mathematics of Maybe: Introduction to Probability One Shot🔥| Class 9 Maths Chapter 7 New NCERT",
    channel: "Shobhit Nirwan - 9th",
    checkedOn: "2026-09-19",
  },
  "JNHjc1r-TJk": {
    title:
      "CBSE Class 9 Science - 6 | Tissues | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  fsiLGhWACTw: {
    title:
      "CBSE Class 9 Science - 7 | Diversity in Living Organisms | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "YNNoQkw0-cA": {
    title:
      "CBSE Class 9 Science - 3 | Atoms and Molecules | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "eIAne1UCz-E": {
    title:
      "CBSE Class 9 Science - 9 | Force and Laws of Motion | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "kS-wQsUSHsY": {
    title:
      "CBSE Class 9 Science - 11 | Work and Energy | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  hWkxTtIOsYw: {
    title: "CBSE Class 9 Science - 12 | Sound | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  TPphmsPe4sc: {
    title:
      "CBSE Class 10 Science - 2 | Acids Bases and Salts | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "3VsmMtQCaUw": {
    title:
      "CBSE Class 10 Science - 3 | Metals and Non Metals | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  y0NDtAjW6hc: {
    title:
      "CBSE Class 10 Science - 4 | Carbon and its compounds | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  irzfDYMUhRY: {
    title:
      "CBSE Class 10 Science - 7 | Control and Coordination | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "P-uHjiIiCCQ": {
    title:
      "CBSE Class 10 Science   8 ¦ How Organisms Reproduce ¦ Full Chapter ¦ NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  u0QrwrR7vcw: {
    title:
      "CBSE Class 10 Science - 9 | Heredity and Evolution | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  j8JtL9yisT0: {
    title:
      "CBSE Class 10 Science - 11 | Human Eye and Colourful World | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  "Ml-iZ_UNkwE": {
    title:
      "CBSE Class 10 Science - 13 | Magnetic Field and Electric Currents | Full Chapter | NCERT Animation",
    channel: "Shiksha House Official",
    checkedOn: "2026-09-19",
  },
  FpzlZq_wDL4: {
    title:
      "Electric generator (A.C. & D.C.) (Hindi) | Magnetic effects of current | Physics | Khan Academy",
    channel: "Khan Academy India",
    checkedOn: "2026-09-19",
  },
  FRx5LPCmpaw: {
    title:
      "Class 10th - Science All Important Activities🔥| Important Questions | Prashant Kirad",
    channel: "Exphub 9th &10th",
    checkedOn: "2026-09-19",
  },
  vwu8m0wI4Jw: {
    title:
      "ALL Chapters Maths SUMMARY in ONE Video 😱 | Class 10 Boards 2026 💯",
    channel: "Deeksha Vedantu CBSE English",
    checkedOn: "2026-09-19",
  },
  _0oeaaCKFy8: {
    title:
      "Chapter 8: Sequences and Progressions | Class 9 Maths | NCERT Explainer",
    channel: "EduRev Class 6 - 10",
    checkedOn: "2026-09-19",
  },
  g3MbdXuTdR0: {
    title:
      "Predicting What Comes Next: Exploring Sequences & Progressions One Shot 🔥| 9th Maths Ch-8 New NCERT",
    channel: "Shobhit Nirwan - 9th",
    checkedOn: "2026-09-19",
  },
  "6qJB9bfSMas": {
    title:
      "CBSE Class 10 Maths - 3 || Pair of Linear Equations in Two Variables || Full Chapter || By Shiksha",
    channel: "Best for NEET",
    checkedOn: "2026-09-19",
  },
  "3MIZUl6bWxY": {
    title:
      "Coordinate Geometry Class 9 in 12 Minutes 🔥 | Class 9 Maths Chapter 3 Complete Lecture",
    channel: "Shobhit Nirwan - 9th",
    checkedOn: "2026-09-19",
  },
  R6o_TVU65sI: {
    title: "What is the Distance Formula? | Don't Memorise",
    channel: "Sri Chaitanya Academy NEET",
    checkedOn: "2026-09-19",
  },
  WYVQjJsjhs8: {
    title: "Determine if 3 points are collinear using the distance formula",
    channel: "Mathbyfives",
    checkedOn: "2026-09-19",
  },
  g6SfGc9iKAc: {
    title:
      "Measuring Space: Perimeter and Area Class 9 in One Shot 🔥| Class 9 Maths Chapter 6 New NCERT",
    channel: "Shobhit Nirwan - 9th",
    checkedOn: "2026-09-19",
  },
  XcBHb3zPJxg: {
    title: "Area and Perimeter: Circles",
    channel: "Kevinmathscience",
    checkedOn: "2026-09-19",
  },
  casNoSzuma4: {
    title: "The Law of Conservation of Mass - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  xnh3GdKV7Pc: {
    title: "Verification of Newton's Second law - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  UW6PAdz5Ot8: {
    title:
      "Work, Energy & Simple Machines Full Chapter ONE SHOT | Class 9 Science",
    channel: "PW Class 9 - NEEV",
    checkedOn: "2026-09-19",
  },
  ife1FQtUrwU: {
    title:
      "PH PAPER TEST ON ACIDS, BASES & SALTS | GRADE 10 BOARD PRACTICAL | CHEMISTRY DEMONSTRATION",
    channel: "Make Me Scientific",
    checkedOn: "2026-09-19",
  },
  ZgKAxgyvycE: {
    title:
      "Electric motor (Hindi) | Magnetic effect of electric current | Physics | Khan Academy",
    channel: "Khan Academy India",
    checkedOn: "2026-09-19",
  },
  a0lFMwb6wms: {
    title:
      "Chemical Bonding and Molecular Structure Class 11 Chemistry Ch 4 | 2026-27 CBSE New NCERT One Shot",
    channel: "LearnoHub - Class 11, 12",
    checkedOn: "2026-09-19",
  },
  lZSL7Tm5ViA: {
    title: "Probability",
    channel: "Manocha Academy",
    checkedOn: "2026-09-19",
  },
  XTrxr2cxwsY: {
    title: "Reproduction One Shot | Biology For CBSE Class 9th | In English",
    channel: "PW Foundation English",
    checkedOn: "2026-09-19",
  },
  "7Q4uQ15PuWE": {
    title:
      "NCERT Class 9 Science COMPLETE ONE SHOT | All 15 Chapters Full Marathon | CBSE Class 9 Science",
    channel: "Backbenchers Hub",
    checkedOn: "2026-09-19",
  },
  HTGJ58AcHYI: {
    title: "Human Impacts on the Nitrogen Cycle",
    channel: "Mrs. Lynch",
    checkedOn: "2026-09-19",
  },
  WEhKjP4PUdE: {
    title:
      "Solar Radiation, Heat Balance and Temperature Class 11 Geography Chapter in Hindi OneShot Animation ",
    channel: "Ansh Simplifier ",
    checkedOn: "2026-09-19",
  },
  jBCiDNwjlkM: {
    title:
      "Separation of components of a  mixture | Part 1/1 | English | Class 9",
    channel: "TicTacLearn English",
    checkedOn: "2026-09-19",
  },
  "4sY1KoktMZo": {
    title:
      "⚡ Class 9 | Work, Energy & Simple Machines 🚀 | Science One Shot | Complete Chapter + PYQs 🔥 | NCERT",
    channel: "Deeksha Vedantu CBSE English",
    checkedOn: "2026-09-19",
  },
  kgjqMMj4V4g: {
    title:
      "Law Of Conservation Of Mass | Law Of Conservation Of Mass Class 9 In Hindi",
    channel: "Know Chemistry",
    checkedOn: "2026-09-19",
  },
  Jhtub_pPKEA: {
    title: 'To Prepare stained temporary mounts of Onion peel"....',
    channel: "PW Solutions",
    checkedOn: "2026-09-19",
  },
  VgbDPfnUyRc: {
    title: "second law of motion// laws of motion//Experiments in hindi",
    channel: "KEVAL JAIN☑️",
    checkedOn: "2026-09-19",
  },
  kmmWoLIzv1o: {
    title:
      "Electric Motor Working Principle, Electromagnetism Class 10 Physics",
    channel: "Digital Teacher",
    checkedOn: "2026-09-19",
  },
  Ylgb8FFMgd4: {
    title:
      "Electric generator (A.C. & D.C.) | Magnetic effects of current | Khan Academy",
    channel: "Khan Academy India - English",
    checkedOn: "2026-09-19",
  },
  OhvoiOYsyN0: {
    title:
      "Periodic Classification Of Elements Class 10 | Periodic Classification Of Elements One Shot",
    channel: "BaBa Bangali Ka Gyan",
    checkedOn: "2026-09-19",
  },
  m1vfHJaaf4E: {
    title:
      "Heredity and Evolution in 20 Minutes🔥| Class 10th | Rapid Revision | Prashant Kirad",
    channel: "Exphub 9th &10th",
    checkedOn: "2026-09-19",
  },
  "2PHrJKbykVI": {
    title:
      "Soaps and detergents | Carbon and its compounds | Class 10 | Chemistry | Khan Academy",
    channel: "Khan Academy India - English",
    checkedOn: "2026-09-19",
  },
  "9WB82CvGIa8": {
    title:
      "HOW TO CONNECT OHM'S LAW CIRCUIT IN 4 MINS | BOARD PRACTICAL | ELECTRICITY DEMO | STD 10-12 PHYSICS",
    channel: "Make Me Scientific",
    checkedOn: "2026-09-19",
  },
  FOLDv1JLzeE: {
    title: "To prepare a temporary mount of a leaf peel to show its stomata",
    channel: "Kadir Khan Learning",
    checkedOn: "2026-09-19",
  },
  qdN4y215c3c: {
    title:
      "Determining the Focal Length of a Concave Mirror | Physics Experiment | Grade 10",
    channel: "Periwinkle",
    checkedOn: "2026-09-19",
  },
  RVNfTqGeyjM: {
    title:
      "LIMIT, CONTINUITY AND DIFFERENTIABILITY in 1 Shot | सीमा, सांतत्य एवं अवकलनीयता | All Concept & PYQs",
    channel: "JEE Hindi Medium",
    checkedOn: "2026-09-19",
  },
  kBRP_oXwjxQ: {
    title:
      "Squeeze theorem (Sandwich theorem) for limits | Calculus 1 | Hindi/Urdu | Examples explained/solved",
    channel: "Tutor & Mentor",
    checkedOn: "2026-09-19",
  },
  vFg20NZiq7M: {
    title:
      "Intermediate Value Theorem | Continuity Class 12 | IIT JEE MATHS | ATP STAR KOTA",
    channel: "The Khatri Tribe",
    checkedOn: "2026-09-19",
  },
  PBg4P0XFtXo: {
    title:
      "Continuity And Differentiability Class 12 One Shot 🔥| NCERT Revision | Maths Chapter 5 | VIJETA 2026",
    channel: "NCERT Wallah",
    checkedOn: "2026-09-19",
  },
  jOVcucQLv38: {
    title:
      "APPLICATION OF DERIVATIVES in One Shot: All Concepts & PYQs Covered | JEE Main & Advanced",
    channel: "JEE Wallah",
    checkedOn: "2026-09-19",
  },
  _SfzOlpmxw4: {
    title:
      "Fundamental Theorem of calculus of Riemann integral in Urdu / Hindi | Real analysis | IIT JAM",
    channel: "MforMATHODOLOGY ",
    checkedOn: "2026-09-19",
  },
  drAYy4xUwwY: {
    title:
      "Calculus-Integration solve Using Long Division Method Easily-Hindi Part-4 #advancedcalculus#calculus",
    channel: "An era To success(AeTs) Physics,Math&English",
    checkedOn: "2026-09-19",
  },
  GGIrKkkbYbE: {
    title:
      "Direction Fields | Complete Differential Equation Series | Bsc 2nd Year Math - Classs 1",
    channel: "Palpali bharat",
    checkedOn: "2026-09-19",
  },
  NlvWOKs8mjk: {
    title:
      "Definite Integration 16 | Average Value of a Function | Non Integrable Functions | Class 12th",
    channel: "BHANNAT MATHS",
    checkedOn: "2026-09-19",
  },
  TP_25k8PHJg: {
    title:
      "Ep 10 | Application of Differentiation | Velocity and Acceleration | Calculus",
    channel: "Einstein’s Mechanics",
    checkedOn: "2026-09-19",
  },
  "9Q3U2lw4loM": {
    title:
      "Volume of solids of revolution in urdu hindi | Disk and washer method || Lec 10B",
    channel: "The Mathematics Outlet",
    checkedOn: "2026-09-19",
  },
  "1nqxPW9kL2M": {
    title: "Preparation of 250 mL of 0 1M standard solution of oxalic acid",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  kc0Nc77t5Ig: {
    title: "Quantitative Estimation - MeitY OLabs",
    channel: "amritacreate",
    checkedOn: "2026-09-19",
  },
  "WXsji-QVacI": {
    title:
      "Titration || determine molarity of sodium hydroxide(NaoH) by titrating it against 0.05M oxalic acid",
    channel: "A2Z practical",
    checkedOn: "2026-09-19",
  },
};
