import { expansionBank } from "../expansion-helpers";
import { kinematicsGraph } from "../kinematics-graph";
const { mc: M, written: W } = expansionBank("u3-laws-of-motion", "u3");
const L = String.raw;
const impulseGraph = kinematicsGraph("Net horizontal force on a trolley", "F (N)", [[0,0],[2,8],[4,0],[6,-4]], [0,2,4,6], [-4,0,4,8]);

export const lawsExpansion = [
  M("3.1",101,2,L`A $50\,\mathrm{kg}$ student stands on a weighing scale in a lift accelerating downward at $2\,\mathrm{m\,s^{-2}}$. For $g=10\,\mathrm{m\,s^{-2}}$, the normal force recorded by the scale is`,L`$400\,\mathrm{N}$`,[
    [L`$500\,\mathrm{N}$`,"This is the weight, not the normal force during downward acceleration."],[L`$600\,\mathrm{N}$`,"This would apply to upward acceleration of the same magnitude."],[L`$100\,\mathrm{N}$`,"This is the magnitude of the net force, not the scale force."]],
    L`Taking upward positive, $N-mg=-ma$. Hence $N=m(g-a)=50(10-2)=400\,\mathrm{N}$.`,["Draw weight downward and normal force upward.","The acceleration points downward.","The scale measures normal force, not net force."]),
  M("3.1",102,2,"A heavy truck and a light car exert forces on one another during a collision. Which comparison is correct?","The force magnitudes are equal, but the car has the larger acceleration magnitude due to this interaction.",[
    ["The truck exerts the larger force because it is heavier.","Interaction forces form a third-law pair with equal magnitudes."],["The car exerts the larger force because it accelerates more.","Larger acceleration can result from smaller mass under an equal force."],["Their accelerations must be equal because the forces are equal.","Acceleration also depends on mass."]],
    L`Newton's third law gives equal opposite interaction forces. For the acceleration due to this interaction, $|a|=|F|/m$, so the lighter car has the larger magnitude.`,["Apply the third law to the interaction forces.","Apply the second law separately to each vehicle.","Do not confuse equal forces with equal accelerations."]),
  M("3.1",103,3,L`Two blocks of masses $2$ and $4\,\mathrm{kg}$ touch on a smooth horizontal floor. A horizontal force of $18\,\mathrm{N}$ pushes the $2\,\mathrm{kg}$ block towards the other block. The contact force on the $4\,\mathrm{kg}$ block is`,L`$12\,\mathrm{N}$`,[
    [L`$18\,\mathrm{N}$`,"The applied force accelerates both blocks; it is not all transmitted as contact force."],[L`$6\,\mathrm{N}$`,"This is the net force on the 2 kg block."],[L`$3\,\mathrm{N}$`,"The common acceleration is 3 m/s squared, not a force."]],
    L`The common acceleration is $18/(2+4)=3\,\mathrm{m\,s^{-2}}$. The only horizontal force on the 4 kg block is contact, so $C=4(3)=12\,\mathrm{N}$.`,["Find acceleration using the two-block system.","Then isolate the block not directly pushed.","Its contact force equals its mass times acceleration."]),
  M("3.1",104,2,"Assertion (A): A body can have zero instantaneous velocity while its net force is non-zero. Reason (R): At the highest point of a vertical throw, gravity still acts on the body.","Both A and R are true, and R explains A.",[
    ["Both A and R are true, but R does not explain A.","The vertical throw directly provides the stated example."],["A is true, but R is false.","Gravity does not vanish at the turning point."],["A is false, but R is true.","Zero instantaneous velocity does not imply zero acceleration."]],
    "A thrown body's velocity is momentarily zero at its top, while its downward gravitational force remains non-zero. Force determines the rate of change of velocity, not velocity itself.",["Consider the instant at the top of a vertical throw.","Distinguish velocity from its rate of change.","Check whether weight disappears at that instant."]),
  W("3.1",101,"vsaq",2,L`An object moves west but accelerates east under a net force.`,[
    {prompt:"Is its speed initially increasing or decreasing? Explain.",answer:"Its speed is initially decreasing because acceleration is opposite to velocity. The force need not point in the direction of motion.",marking:["Identifies decreasing speed with opposite velocity and acceleration."]}],
    ["Compare directions of velocity and acceleration.","An opposite acceleration reduces speed before reversal.","Force direction follows acceleration."],["Assuming force must point along velocity."]),
  W("3.1",102,"saq",2,L`A $4\,\mathrm{kg}$ body has acceleration $(3\hat i-2\hat j)\,\mathrm{m\,s^{-2}}$. One of two forces on it is $(5\hat i+\hat j)\,\mathrm{N}$.`,[
    {prompt:"Find the other force.",answer:L`Net force is $m\vec a=(12\hat i-8\hat j)\,\mathrm{N}$. Thus $\vec F_2=(12,-8)-(5,1)=(7\hat i-9\hat j)\,\mathrm{N}$.`,marking:["Obtains net force (12,-8) N.","Subtracts to obtain the second force (7,-9) N."]}],
    ["First find the net force.","The given force is only one contribution.","Subtract component by component."],["Equating the single known force to the net force."]),
  W("3.1",103,"laq",3,L`Two masses $3$ and $5\,\mathrm{kg}$ hang from the ends of a light inextensible string passing over a smooth massless pulley. The system is released from rest. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Write the two equations of motion and find the common acceleration.",answer:L`For the descending 5 kg mass, $50-T=5a$. For the rising 3 kg mass, $T-30=3a$. Adding gives $20=8a$, so $a=2.5\,\mathrm{m\,s^{-2}}$.`,marking:["Writes correct opposite-direction equations for both masses.","Obtains acceleration 2.5 m/s squared."]},
    {prompt:"Find the tension and the distance each mass travels in the first 2 s, assuming neither reaches a support.",answer:L`$T=30+3(2.5)=37.5\,\mathrm{N}$. Each travels $s=\tfrac12(2.5)(2^2)=5\,\mathrm{m}$. The tension lies between the two weights, consistent with their accelerations.`,marking:["Obtains tension 37.5 N.","Uses common acceleration and initial rest.","Obtains distance 5 m."]}],
    ["Use a separate force equation for each mass.","The string gives equal acceleration magnitudes and equal tension.","Add equations to eliminate tension, then substitute back."],["Assuming tension equals either weight in an accelerating system."]),
  W("3.1",104,"case",3,L`A $60\,\mathrm{kg}$ passenger stands on a force-measuring scale in a lift. The lift starts upward, then moves upward at constant speed, and finally slows while still moving upward. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"During the start, the scale reads 720 N. Find acceleration and the scale reading during constant-speed travel.",answer:L`$N-mg=ma$ gives $a=(720-600)/60=2\,\mathrm{m\,s^{-2}}$ upward. During constant speed, $a=0$ and the scale reads 600 N.`,marking:["Obtains upward acceleration 2 m/s squared.","Gives 600 N during constant speed."]},
    {prompt:"While slowing, the upward speed falls by 3 m/s in 1.5 s at a constant rate. Find the scale reading and explain its relation to weight.",answer:L`Acceleration is $-3/1.5=-2\,\mathrm{m\,s^{-2}}$ with upward positive. Therefore $N=60(10-2)=480\,\mathrm{N}$, below weight because acceleration is downward despite upward motion.`,marking:["Finds downward acceleration 2 m/s squared.","Gives 480 N and distinguishes velocity from acceleration."]}],
    ["Scale force minus weight equals mass times upward acceleration.","Constant speed means zero acceleration.","Slowing while rising means downward acceleration."],["Using the direction of motion instead of acceleration to decide apparent weight."]),
  M("3.2",101,2,L`A force delivers an eastward impulse of $6\,\mathrm{N\,s}$ to a $2\,\mathrm{kg}$ body initially moving west at $4\,\mathrm{m\,s^{-1}}$. Its final velocity is`,L`$1\,\mathrm{m\,s^{-1}}$ west`,[
    [L`$7\,\mathrm{m\,s^{-1}}$ east`,"The initial momentum is westward and must be signed negative."],[L`$3\,\mathrm{m\,s^{-1}}$ east`,"This is the change in velocity, not the final velocity."],[L`$1\,\mathrm{m\,s^{-1}}$ east`,"The impulse is insufficient to reverse the initial momentum."]],
    L`East positive gives $p_i=-8\,\mathrm{kg\,m\,s^{-1}}$. Then $p_f=-8+6=-2$ and $v_f=-2/2=-1\,\mathrm{m\,s^{-1}}$.`,["Assign a sign to the initial velocity.","Add impulse to initial momentum.","Divide final momentum by mass."]),
  M("3.2",102,2,L`A particle's momentum is $p_x=4t^2-3t$ in SI units. The x-component of net force at $t=2\,\mathrm{s}$ is`,L`$13\,\mathrm{N}$`,[
    [L`$10\,\mathrm{N}$`,"This substitutes into momentum instead of differentiating it."],[L`$5\,\mathrm{N}$`,"This is p/t, not the instantaneous derivative."],[L`$16\,\mathrm{N}$`,"The derivative of the linear term is -3, not zero."]],
    L`$F_x=dp_x/dt=8t-3$. At 2 s, $F_x=16-3=13\,\mathrm{N}$.`,["Use the momentum form of the second law.","Differentiate before substituting time.","Keep the derivative of the linear term." ]),
  M("3.2",103,2,"The same impulse is delivered by a constant force in two trials. The second trial takes three times as long. Its force magnitude is","one-third of the first",[
    ["three times the first","For fixed impulse, force and duration are inversely related."],["the same as the first","Equal impulse need not mean equal force."],["nine times the first","Impulse contains duration to the first power."]],
    L`For a constant force, $J=F\Delta t$. With equal J and tripled duration, the force becomes $F/3$.`,["Write impulse as force times duration.","Hold impulse fixed.","Solve for the force ratio." ]),
  M("3.2",104,3,L`A $0.10\,\mathrm{kg}$ ball strikes a smooth vertical wall with velocity $(6\hat i+8\hat j)\,\mathrm{m\,s^{-1}}$. The x-axis is normal to the wall. It rebounds with only the x-component reversed. The impulse from the wall is`,L`$-1.2\hat i\,\mathrm{N\,s}$`,[
    [L`$-0.6\hat i\,\mathrm{N\,s}$`,"Reversing a component changes it by twice its initial magnitude."],[L`$-2\hat i\,\mathrm{N\,s}$`,"The full speed is not the normal component."],[L`$(-1.2\hat i-1.6\hat j)\,\mathrm{N\,s}$`,"The tangential component does not reverse at the smooth wall."]],
    L`$\vec v_f=(-6\hat i+8\hat j)$. Hence $\vec J=m(\vec v_f-\vec v_i)=0.10(-12\hat i)=-1.2\hat i\,\mathrm{N\,s}$.`,["Resolve motion normal and tangential to the wall.","Only the normal component reverses.","Use final minus initial velocity." ]),
  W("3.2",101,"vsaq",2,"Two constant-mass bodies receive equal non-zero impulses. One has twice the mass of the other.",[
    {prompt:"Compare the magnitudes of their velocity changes, heavier to lighter.",answer:L`Since $\Delta v=J/m$, the ratio is $1:2$. Equal impulses give equal momentum changes, not equal velocity changes.`,marking:["Gives 1:2 using impulse divided by mass."]}],
    ["Impulse equals momentum change.","Convert momentum change into velocity change.","The heavier body changes velocity less."],["Confusing momentum change with velocity change."]),
  W("3.2",102,"saq",3,L`A $0.25\,\mathrm{kg}$ ball moving downward at $12\,\mathrm{m\,s^{-1}}$ rebounds upward at $8\,\mathrm{m\,s^{-1}}$. Contact with the floor lasts $0.05\,\mathrm{s}$. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Find the average normal force of the floor on the ball, including its weight during contact.",answer:L`Upward momentum change is $0.25[8-(-12)]=5\,\mathrm{N\,s}$. Thus $N_{\mathrm{av}}-mg=5/0.05=100\,\mathrm{N}$, giving $N_{\mathrm{av}}=102.5\,\mathrm{N}$.`,marking:["Obtains net average force 100 N upward from signed momentum change.","Adds weight 2.5 N to obtain normal force 102.5 N."]}],
    ["Take upward positive for both velocities.","Momentum change gives net impulse.","The floor force must also overcome weight."],["Calling net average force the normal force without accounting for gravity."]),
  W("3.2",103,"laq",3,L`A $3\,\mathrm{kg}$ trolley initially moves at $2\,\mathrm{m\,s^{-1}}$ to the right. It experiences a net force of $+6\,\mathrm{N}$ for 2 s, followed immediately by $-3\,\mathrm{N}$ for 4 s.`,[
    {prompt:"Find the impulse of each stage and the velocity after each stage.",answer:L`The impulses are $+12$ and $-12\,\mathrm{N\,s}$. Initial momentum is 6; after the first stage it is 18, giving $6\,\mathrm{m\,s^{-1}}$. After the second it returns to 6, giving $2\,\mathrm{m\,s^{-1}}$.`,marking:["Gives both signed impulses.","Obtains the intermediate velocity 6 m/s.","Obtains final velocity 2 m/s."]},
    {prompt:"Does zero total impulse imply zero displacement? Calculate the displacement to support your answer.",answer:L`No. Each stage has constant acceleration and positive velocities. Displacements are $(2+6)2/2=8\,\mathrm{m}$ and $(6+2)4/2=16\,\mathrm{m}$, total 24 m rightward. Zero total impulse means zero net velocity change.`,marking:["Obtains total displacement 24 m.","Explains the distinction between displacement and velocity change."]}],
    ["Treat the two time intervals separately.","Momentum after stage one is the starting momentum for stage two.","Use mean endpoint velocity within each constant-acceleration interval."],["Concluding that zero net impulse means no motion occurred."]),
  W("3.2",104,"case",3,L`A $2\,\mathrm{kg}$ trolley starts from rest. The graph gives its net horizontal force; rightward force is positive.`,[
    {prompt:"Find the impulse from 0 to 4 s and the velocity at 4 s.",answer:L`The positive triangular area is $\tfrac12(4)(8)=16\,\mathrm{N\,s}$. Thus $v(4)=16/2=8\,\mathrm{m\,s^{-1}}$ rightward.`,marking:["Obtains positive impulse 16 N s.","Obtains velocity 8 m/s rightward."]},
    {prompt:"Find the velocity at 6 s. At what time is the speed largest in the displayed interval?",answer:L`The final negative triangle contributes $-\tfrac12(2)(4)=-4\,\mathrm{N\,s}$. Net impulse is 12, so $v(6)=6\,\mathrm{m\,s^{-1}}$ rightward. Velocity remains positive; speed grows until force changes sign at 4 s, where its maximum is 8 m/s.`,marking:["Uses signed negative area and obtains final velocity 6 m/s.","Identifies 4 s as maximum-speed time with a force-sign explanation."]}],
    ["Impulse is signed area under the force-time graph.","Subtract the below-axis area.","Check that velocity does not reverse when force becomes negative."],["Treating all graph areas as positive."],impulseGraph),
  M("3.3",101,2,L`Two carts of masses $3$ and $2\,\mathrm{kg}$ move at $+4$ and $-1\,\mathrm{m\,s^{-1}}$ on a smooth track. After collision the $3\,\mathrm{kg}$ cart moves at $+1\,\mathrm{m\,s^{-1}}$. The other cart's velocity is`,L`$+3.5\,\mathrm{m\,s^{-1}}$`,[
    [L`$+5.5\,\mathrm{m\,s^{-1}}$`,"The second cart initially has negative momentum."],[L`$-3.5\,\mathrm{m\,s^{-1}}$`,"Its final momentum must be positive to preserve the total."],[L`$+2\,\mathrm{m\,s^{-1}}$`,"The carts do not stick together, so they need not share velocity."]],
    L`Initial momentum is $3(4)+2(-1)=10$. Conservation gives $3(1)+2v=10$, hence $v=3.5\,\mathrm{m\,s^{-1}}$.`,["Find total signed initial momentum.","Use the given final velocity for only the 3 kg cart.","Solve for the other velocity." ]),
  M("3.3",102,2,L`A $2\,\mathrm{kg}$ object moving east at $6\,\mathrm{m\,s^{-1}}$ breaks into two equal fragments. One moves east at $10\,\mathrm{m\,s^{-1}}$. External impulse during the break is negligible. The other moves`,L`east at $2\,\mathrm{m\,s^{-1}}$`,[
    [L`west at $10\,\mathrm{m\,s^{-1}}$`,"Equal opposite momenta apply only when the initial total momentum is zero."],[L`west at $2\,\mathrm{m\,s^{-1}}$`,"The remaining momentum is 12-10=+2, not -2."],[L`east at $6\,\mathrm{m\,s^{-1}}$`,"The second fragment's velocity need not equal the original velocity."]],
    L`Initial momentum is $2(6)=12$. Each fragment has mass 1 kg, so $10+v=12$ and $v=2\,\mathrm{m\,s^{-1}}$ east.`,["The object was not initially at rest.","Conserve the non-zero initial momentum.","Each fragment has half the original mass." ]),
  M("3.3",103,2,"Assertion (A): The momentum of one cart can change while the total momentum of two colliding carts remains constant. Reason (R): Forces between the carts are external to each individual cart but internal to the two-cart system.","Both A and R are true, and R explains A.",[
    ["Both A and R are true, but R does not explain A.","The choice of system explains how individual changes coexist with conservation."],["A is true, but R is false.","Whether a force is internal depends on the selected system."],["A is false, but R is true.","Only the total momentum, not each individual momentum, must be constant when net external force is zero."]],
    "Equal opposite interaction impulses change the individual momenta and cancel in their sum. With negligible net external impulse, total momentum remains constant.",["Choose the system before classifying forces.","Compare one cart with both carts together.","Add the two equal opposite interaction impulses." ]),
  M("3.3",104,3,L`A $40\,\mathrm{kg}$ child and a $60\,\mathrm{kg}$ floating platform are initially at rest, with negligible horizontal external force. The child walks east at $1\,\mathrm{m\,s^{-1}}$ relative to the platform. The platform's velocity relative to the shore is`,L`$0.4\,\mathrm{m\,s^{-1}}$ west`,[
    [L`$2/3\,\mathrm{m\,s^{-1}}$ west`,"This incorrectly treats the child's relative speed as its shore-frame speed."],[L`$0.6\,\mathrm{m\,s^{-1}}$ west`,"This uses the platform mass as the moving-child mass in the numerator."],[L`$0.4\,\mathrm{m\,s^{-1}}$ east`,"The platform must move opposite to the child's walking direction."]],
    L`Let platform velocity be V east-positive. Child velocity is $V+1$. Then $40(V+1)+60V=0$, giving $V=-0.4\,\mathrm{m\,s^{-1}}$.`,["Express both velocities in the shore frame.","Child velocity equals platform velocity plus relative velocity.","Conserve zero total horizontal momentum." ]),
  W("3.3",101,"vsaq",2,"An isolated object initially at rest separates into two unequal fragments.",[
    {prompt:"Which fragment has the larger speed, and why?",answer:L`Their momenta are equal in magnitude and opposite. Since $m_1v_1=m_2v_2$, the smaller-mass fragment has the larger speed.`,marking:["Identifies the lighter fragment through equal opposite momenta."]}],
    ["Initial total momentum is zero.","Add the two final momenta.","Equal momentum magnitude does not mean equal speed."],["Giving equal speeds to unequal masses."]),
  W("3.3",102,"saq",3,L`A stationary $6\,\mathrm{kg}$ body bursts into three fragments. A $2\,\mathrm{kg}$ fragment moves east at $3\,\mathrm{m\,s^{-1}}$, and a $1\,\mathrm{kg}$ fragment moves north at $8\,\mathrm{m\,s^{-1}}$. Neglect external impulse.`,[
    {prompt:"Find the velocity vector of the third fragment, taking east and north positive.",answer:L`Its mass is 3 kg. Conservation gives $3\vec v=-(6\hat i+8\hat j)$, so $\vec v=(-2\hat i-\tfrac83\hat j)\,\mathrm{m\,s^{-1}}$.`,marking:["Finds third mass and the required opposite momentum components.","Divides by 3 kg to obtain both velocity components."]}],
    ["Find the remaining mass.","Conserve momentum along each perpendicular axis.","Divide the third momentum by its mass."],["Conserving speed magnitudes instead of vector momentum."]),
  W("3.3",103,"laq",3,L`A $10\,\mathrm{g}$ pellet moving at $200\,\mathrm{m\,s^{-1}}$ horizontally embeds in a stationary $0.99\,\mathrm{kg}$ block on a smooth horizontal surface. After the impact, a constant horizontal resisting force of $0.5\,\mathrm{N}$ is applied.`,[
    {prompt:"Find the speed immediately after impact. State why momentum conservation is used only for the short impact here.",answer:L`During impact external horizontal impulse is negligible: $0.01(200)=(0.01+0.99)V$, hence $V=2\,\mathrm{m\,s^{-1}}$. Afterwards the applied resisting force supplies a non-zero external impulse.`,marking:["Converts pellet mass and uses combined mass 1 kg.","Obtains speed 2 m/s.","Distinguishes impact from the later externally forced stage."]},
    {prompt:"Find the time until the combined body stops.",answer:L`The required momentum change has magnitude $1(2)=2\,\mathrm{N\,s}$. Thus $0.5t=2$, giving $t=4\,\mathrm{s}$.`,marking:["Uses the resisting impulse or constant deceleration 0.5 m/s squared.","Obtains stopping time 4 s."]}],
    ["Separate the collision and slowing stages.","Use the total mass after embedding.","The external force changes the previously conserved momentum."],["Applying constant total momentum after the resisting force begins."]),
  W("3.3",104,"case",3,L`A $2\,\mathrm{kg}$ trolley moving right at $3\,\mathrm{m\,s^{-1}}$ carries a $1\,\mathrm{kg}$ package with it. On a smooth horizontal track the package is released with zero horizontal velocity relative to the ground.`,[
    {prompt:"Find the trolley's speed immediately after release.",answer:L`Initial momentum is $(2+1)3=9\,\mathrm{kg\,m\,s^{-1}}$. The released package has zero horizontal momentum, so $2V=9$, giving $V=4.5\,\mathrm{m\,s^{-1}}$ rightward.`,marking:["Includes the package's initial momentum.","Obtains trolley speed 4.5 m/s."]},
    {prompt:"Compare this with releasing the package with zero horizontal velocity relative to the trolley.",answer:L`In that different release, both share final horizontal velocity V, so $3V=9$ and $V=3\,\mathrm{m\,s^{-1}}$. Ground-relative and trolley-relative zero velocity are different conditions.`,marking:["Correctly translates the alternate relative-velocity condition.","Obtains 3 m/s and explains the reference-frame distinction."]}],
    ["Use a single ground frame for all momenta.","The package initially shares the trolley's velocity.","Zero relative velocity depends on the named frame."],["Treating both forms of zero velocity as identical."]),
  M("3.4",101,3,L`A $5\,\mathrm{kg}$ box on a horizontal floor is pulled by $20\,\mathrm{N}$ at $30^\circ$ above the horizontal. It has no vertical acceleration. For $g=10\,\mathrm{m\,s^{-2}}$, its normal reaction is`,L`$40\,\mathrm{N}$`,[
    [L`$50\,\mathrm{N}$`,"The upward pull partly supports the weight."],[L`$60\,\mathrm{N}$`,"An upward pull reduces, rather than increases, normal reaction."],[L`$50-10\sqrt3\,\mathrm{N}$`,"Use the vertical sine component, not the horizontal cosine component."]],
    L`Vertical balance gives $N+20\sin30^\circ=50$. Hence $N=40\,\mathrm{N}$.`,["Resolve the inclined pull vertically.","Set vertical acceleration to zero.","Do not assume normal force always equals weight." ]),
  M("3.4",102,2,L`A block rests on a rough slope at $30^\circ$ to the horizontal. What is the smallest coefficient of static friction that can prevent slipping?`,L`$1/\sqrt3$`,[
    [L`$1/2$`,"The normal reaction is mg cos theta, not mg."],[L`$\sqrt3/2$`,"Cosine alone does not compare downhill force with normal reaction."],[L`$\sqrt3$`,"This is cotangent, the inverse of the required ratio."]],
    L`At the limiting condition $mg\sin\theta=\mu_s mg\cos\theta$, so $\mu_s=\tan30^\circ=1/\sqrt3$.`,["Resolve weight along and perpendicular to the slope.","At the minimum coefficient, friction is limiting.","Divide the two force components." ]),
  M("3.4",103,2,"A block is already sliding rightward on a fixed rough horizontal floor. A small leftward pull is then added. While it still slides rightward, kinetic friction acts","leftward",[
    ["rightward, opposite the pull","Friction opposes relative slipping, not necessarily the applied force."],["upward","The upward contact component is the normal reaction."],["in whichever direction keeps the net force zero","Kinetic friction does not adjust itself to ensure equilibrium."]],
    "The block's lower surface slips rightward relative to the floor. Kinetic friction on the block therefore remains leftward while that slipping direction persists.",["Identify the relative sliding direction.","Do not use the pull direction as the friction rule.","Distinguish kinetic friction from self-adjusting static friction." ]),
  M("3.4",104,2,"Assertion (A): Static friction on a resting block must always equal its limiting value. Reason (R): Static friction can take values from zero up to its limiting value.","A is false, but R is true.",[
    ["Both A and R are true, and R explains A.","The assertion wrongly replaces an upper bound with an equality."],["Both A and R are true, but R does not explain A.","The assertion is false."],["A is true, but R is false.","Static friction adjusts to the required balance until its limit."]],
    L`Static friction obeys $|f_s|\leq\mu_sN$. Equality holds only at impending slipping, not for every resting block.`,["Think of a block with no horizontal force.","Its friction can be zero.","The limiting value is a maximum." ]),
  W("3.4",101,"vsaq",2,L`A particle is in equilibrium under forces $(2\hat i-5\hat j)\,\mathrm{N}$, $(-7\hat i+\hat j)\,\mathrm{N}$ and a third force.`,[
    {prompt:"Find the third force.",answer:L`The first two sum to $(-5\hat i-4\hat j)\,\mathrm{N}$. The third must be $(5\hat i+4\hat j)\,\mathrm{N}$ for zero resultant.`,marking:["Gives the opposite of the sum, (5,4) N."]}],
    ["Add the two known forces.","Equilibrium requires zero vector sum.","Reverse both components of the known resultant."],["Giving the resultant instead of the equilibrant."]),
  W("3.4",102,"saq",3,L`A $4\,\mathrm{kg}$ block slides up a rough $30^\circ$ incline. The coefficient of kinetic friction is $1/(2\sqrt3)$ and $g=10\,\mathrm{m\,s^{-2}}$. No other force acts.`,[
    {prompt:"Find its acceleration while it is moving up the incline.",answer:L`Both gravity's component and friction act down the slope. $a=g(\sin30^\circ+\mu_k\cos30^\circ)=10(1/2+1/4)=7.5\,\mathrm{m\,s^{-2}}$ downhill.`,marking:["Adds the two downhill components with N=mg cos 30 degrees.","Obtains acceleration 7.5 m/s squared downhill."]}],
    ["Friction opposes the upward sliding.","The normal force is mg cos theta.","Both along-slope contributions point downhill."],["Subtracting friction from the downhill gravitational component."]),
  W("3.4",103,"laq",4,L`A $2\,\mathrm{kg}$ block rests on a $4\,\mathrm{kg}$ trolley. The floor under the trolley is smooth. The coefficient of static friction between block and trolley is 0.3. A horizontal force F pulls only the trolley. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Assuming no slipping, express the common acceleration and the friction on the upper block in terms of F.",answer:L`For the whole system $a=F/6$. Friction is the only horizontal force on the upper block, so $f=2a=F/3$, in the pull direction.`,marking:["Obtains common acceleration F/6.","Obtains friction F/3 and its direction."]},
    {prompt:"Find the maximum F for which the no-slip assumption holds. Check whether F=15 N meets it.",answer:L`The limit is $f_{\max}=0.3(2)(10)=6\,\mathrm{N}$. Thus $F/3\leq6$, giving $F_{\max}=18\,\mathrm{N}$. At 15 N, $f=5\,\mathrm{N}<6\,\mathrm{N}$, so no slipping is possible.`,marking:["Finds static friction limit 6 N.","Obtains threshold force 18 N.","Checks the 15 N case against the friction bound."]}],
    ["First assume a shared acceleration for both bodies.","Isolate the upper block to find the friction required.","Check that required friction does not exceed its limit."],["Applying the pull directly to the upper block or using total mass in its friction limit."]),
  W("3.4",104,"case",3,L`A $10\,\mathrm{kg}$ crate is on a horizontal floor with $\mu_s=0.4$ and $\mu_k=0.25$. A horizontal pull is increased slowly from zero. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Compare the friction forces when the pull is 18 N and when it is just sufficient to initiate slipping.",answer:L`At 18 N, static friction is 18 N opposite the pull. The limiting value is $0.4(100)=40\,\mathrm{N}$, reached at impending slipping.`,marking:["Gives 18 N in the first case.","Gives limiting static friction 40 N."]},
    {prompt:"Once the crate is sliding, the pull is maintained at 30 N. Find acceleration and explain why it need not stop even though 30 N is below 40 N.",answer:L`Kinetic friction is $0.25(100)=25\,\mathrm{N}$. Net force is 5 N forward, so $a=0.5\,\mathrm{m\,s^{-2}}$. The 40 N threshold concerns starting from rest; sliding friction is smaller.`,marking:["Uses kinetic friction 25 N and obtains acceleration 0.5 m/s squared.","Distinguishes starting threshold from friction during sliding."]}],
    ["Use static friction before slipping.","Change to the kinetic coefficient after slipping begins.","Compare the maintained pull with kinetic friction, not the static maximum."],["Continuing to use limiting static friction after sliding begins."]),
  M("3.5",101,2,"A string maintains uniform circular motion of a particle on a smooth horizontal table. If the string breaks, its immediate subsequent motion is","along the tangent at the release point",[
    ["radially outward","The inward force disappears, but no outward horizontal force is introduced."],["radially inward","The previous force direction is not the velocity direction."],["along the original circle","Continued circular motion requires an inward net force."]],
    "At release, the particle retains its instantaneous tangential velocity. With no horizontal force afterwards, it continues in that straight-line direction.",["Identify the velocity immediately before the break.","Remove the string force, not the existing velocity.","Apply the first law after release." ]),
  M("3.5",102,2,L`A bead of mass m moves in a horizontal circle as a conical pendulum. The supporting string makes angle $\theta$ with the vertical. The tension is`,L`$mg/\cos\theta$`,[
    [L`$mg$`,"Only the vertical component of tension balances weight."],[L`$mg\cos\theta$`,"This makes the vertical support too small."],[L`$mg/\sin\theta$`,"Sine gives the horizontal component when the angle is measured from vertical."]],
    L`Vertical acceleration is zero, so $T\cos\theta=mg$. Therefore $T=mg/\cos\theta$; the horizontal component supplies the radial acceleration.`,["Resolve tension relative to the stated vertical angle.","Use zero vertical acceleration.","The horizontal component is not needed to find this expression." ]),
  M("3.5",103,2,L`On a level bend, available tyre-road static friction is unchanged. If the bend radius is increased from r to 4r, the maximum safe speed changes by a factor of`,"2",[
    ["4","Maximum speed depends on the square root of radius."],["1/2","A larger radius needs less radial acceleration at a given speed."],["1","Radius affects the required inward force."]],
    L`At the limit $mv^2/r=\mu_smg$, so $v_{\max}=\sqrt{\mu_sgr}$. Increasing r fourfold doubles the maximum speed.`,["Equate required force with limiting static friction.","Cancel mass.","Take the square root of the radius factor." ]),
  M("3.5",104,2,"A car traverses a frictionless banked road at its design speed. If a second car has twice the mass, the design speed on the same curve is","unchanged",[
    ["twice as large","Mass cancels when the radial and vertical force equations are divided."],["half as large","Both weight and required radial force scale with mass."],["multiplied by the square root of two","The design-speed formula depends on radius, gravity and bank angle, not mass."]],
    L`The equations $N\cos\theta=mg$ and $N\sin\theta=mv^2/r$ give $v^2=rg\tan\theta$. Mass is absent from this condition.`,["Write vertical balance and radial acceleration equations.","Divide to eliminate the normal force.","Check whether mass remains." ]),
  W("3.5",101,"vsaq",2,"A student draws weight, tension and a separate 'centripetal force' on the free-body diagram of a ball on a string.",[
    {prompt:"What is wrong with treating centripetal force as an additional interaction?",answer:"Centripetal force names the inward resultant of actual forces; it is not an extra interaction to add alongside weight and tension.",marking:["Explains that the inward net component is supplied by existing physical forces."]}],
    ["List the actual agents exerting forces.","Centripetal describes the role of a resultant.","Avoid counting the same inward contribution twice."],["Adding mv squared over r as an extra force."]),
  W("3.5",102,"saq",3,L`A $0.5\,\mathrm{kg}$ mass moves in a horizontal circle of radius $0.6\,\mathrm{m}$ as a conical pendulum. The string makes $45^\circ$ with the vertical. Take $g=10\,\mathrm{m\,s^{-2}}$.`,[
    {prompt:"Find its speed and the tension.",answer:L`Dividing $T\sin\theta=mv^2/r$ by $T\cos\theta=mg$ gives $v^2=rg\tan45^\circ=6$, so $v=\sqrt6\,\mathrm{m\,s^{-1}}$. Also $T=5/\cos45^\circ=5\sqrt2\,\mathrm{N}$.`,marking:[L`Obtains speed $\sqrt6\,\mathrm{m\,s^{-1}}$ from the component equations.`,L`Obtains tension $5\sqrt2\,\mathrm{N}$.`]}],
    ["The bob has zero vertical acceleration.","The horizontal tension component supplies radial acceleration.","Divide component equations to remove tension."],["Equating the whole tension to either weight or radial force."]),
  W("3.5",103,"laq",3,L`A $0.20\,\mathrm{kg}$ puck is tied to a string and moves in a horizontal circle on a smooth table. The radius is $0.8\,\mathrm{m}$ and the string can sustain at most $10\,\mathrm{N}$.`,[
    {prompt:"Find the maximum permitted speed and the corresponding period.",answer:L`$mv^2/r\leq10$ gives $v_{\max}=\sqrt{10(0.8)/0.20}=\sqrt{40}=2\sqrt{10}\,\mathrm{m\,s^{-1}}$. The period is $2\pi r/v=0.8\pi/\sqrt{10}\,\mathrm{s}$.`,marking:["Sets required tension equal to the limiting value.",L`Obtains maximum speed $2\sqrt{10}\,\mathrm{m\,s^{-1}}$.`,L`Obtains period $0.8\pi/\sqrt{10}\,\mathrm{s}$.`]},
    {prompt:"If radius is halved while speed is held at that maximum, can the original string sustain the motion?",answer:"No. At fixed speed, halving radius doubles the required force from 10 N to 20 N, exceeding the specified limit.",marking:["Uses inverse-radius scaling at fixed speed.","Finds 20 N and compares with the 10 N limit."]}],
    ["The string supplies the entire horizontal inward force.","Use circumference divided by speed for period.","For the altered motion keep speed, not angular speed, fixed."],["Using the fixed-angular-speed scaling when speed is held constant."]),
  W("3.5",104,"case",4,L`A car follows a level circular track of radius $40\,\mathrm{m}$ at an instant when its speed is $12\,\mathrm{m\,s^{-1}}$. The coefficient of static friction is 0.5 and $g=10\,\mathrm{m\,s^{-2}}$. Tyre friction must supply both radial and tangential acceleration; ignore air resistance.`,[
    {prompt:"Find radial acceleration and the largest possible magnitude of total horizontal acceleration without slipping.",answer:L`$a_r=v^2/r=144/40=3.6\,\mathrm{m\,s^{-2}}$. The friction bound gives $a_{\mathrm{total}}\leq\mu_sg=5\,\mathrm{m\,s^{-2}}$.`,marking:["Obtains radial acceleration 3.6 m/s squared.","Obtains total horizontal acceleration limit 5 m/s squared."]},
    {prompt:"Find the greatest tangential acceleration magnitude at that instant. Would 4 m/s squared be possible?",answer:L`The components are perpendicular, so $a_{t,\max}=\sqrt{5^2-3.6^2}=\sqrt{12.04}\approx3.47\,\mathrm{m\,s^{-2}}$. A tangential acceleration of 4 would require total acceleration $\sqrt{3.6^2+4^2}\approx5.38>5$, so it is not possible without slipping.`,marking:["Combines perpendicular components and obtains about 3.47 m/s squared.","Rejects 4 m/s squared by comparing required total with the limit."]}],
    ["First reserve friction for the inward acceleration.","Tangential and radial force components are perpendicular.","Apply the limit to their vector magnitude, not each separately."],["Allowing the full friction limit independently in both directions."]),
];
