import { expansionBank } from "../expansion-helpers";
const { mc: M, written: W } = expansionBank("u6-gravitation", "u6");
const L = String.raw;
export const gravitationExpansion = [
  M("6.1",101,2,L`Two planets of negligible mass compared with their common star have orbital periods in the ratio 8:27. Their semi-major axes are in the ratio`,"4:9",[
    ["8:27","Kepler's third law relates squared periods to cubed semi-major axes."],["2:3","This uses a cube root without squaring it."],["64:729","This is the period-squared ratio, not the axis ratio."]],
    L`$a_1/a_2=(T_1/T_2)^{2/3}=(8/27)^{2/3}=4/9$.`,["Write the third law for the same central star.","Solve it for the axis ratio.","Take the cube root and then square." ]),
  M("6.1",102,2,"In an elliptical planetary orbit, equal areas are swept out in equal times. This directly means the planet's","areal velocity is constant",[
    ["linear speed is constant","The planet's distance from the focus and its linear speed vary."],["angular speed is constant","The angular sweep needed for a fixed area depends on distance from the focus."],["distance from the star is constant","That is true only for the circular special case."]],
    L`The law states that $dA/dt$ is constant. It does not require constant speed, angular speed or star-planet separation.`,["Identify exactly which quantity is divided by time.","An ellipse has changing distance from the focus.","Do not replace area swept by angle swept." ]),
  M("6.1",103,3,L`Three equal point masses m occupy A=(0,0), B=(a,0) and C=(a,a), with a positive. The magnitude of the net gravitational force on the mass at C is`,L`$\dfrac{Gm^2}{a^2}\sqrt{\dfrac54+\dfrac{1}{\sqrt2}}$`,[
    [L`$\dfrac{3Gm^2}{2a^2}$`,"This adds force magnitudes, although the directions differ by 45 degrees."],[L`$\dfrac{Gm^2}{a^2}\sqrt{\dfrac54}$`,"The force directions are not perpendicular."],[L`$\dfrac{Gm^2}{2a^2}$`,"This includes only the diagonal source."]],
    L`The separations are a and $a\sqrt2$, giving force magnitudes $F_0=Gm^2/a^2$ and $F_0/2$. Their included angle is $45^\circ$, so $F^2=F_0^2[1+1/4+\cos45^\circ]=F_0^2(5/4+1/\sqrt2)$.`,["Sketch the three occupied corners.","The diagonal distance is square root of two times a.","Add the two forces with their 45-degree included angle." ]),
  M("6.1",104,2,"Assertion (A): For two non-overlapping, spherically symmetric bodies, changing composition alone leaves gravitational force unchanged if their masses and centre separation remain fixed. Reason (R): The gravitational constant G depends on the materials used.","A is true, but R is false.",[
    ["Both A and R are true, and R explains A.","G is universal, not material-dependent."],["Both A and R are true, but R does not explain A.","The reason is false, not merely unrelated."],["A is false, but R is true.","The force is unchanged under these conditions, and G does not depend on material."]],
    L`For non-overlapping spherically symmetric bodies, $F=Gm_1m_2/r^2$. No material-specific constant appears, and G is universal.`,["List the variables in the inverse-square law.","Mass is held fixed in this comparison.","G is not a property of the bodies' composition." ]),
  W("6.1",101,"vsaq",2,"A planet's orbit is elliptical. A student places the star at the geometric centre of the ellipse.",[
    {prompt:"Correct the placement according to Kepler's first law.",answer:"The star is at one focus of the ellipse, not its geometric centre. These coincide only in the circular special case.",marking:["Places the star at one focus."]}],
    ["Distinguish an ellipse's centre from its foci.","Recall the location specified in the first law.","A circle is the limiting special case."],["Placing the attracting star at the centre for every ellipse."]),
  W("6.1",102,"saq",3,L`A planet's distance from its star is r at perihelion and 3r at aphelion. Its speed at perihelion is $30\,\mathrm{km\,s^{-1}}$.`,[
    {prompt:"Find its aphelion speed and the ratio of gravitational force magnitudes at perihelion and aphelion.",answer:L`At the two apsides velocity is perpendicular to radius, so $rv_p=3rv_a$ gives $v_a=10\,\mathrm{km\,s^{-1}}$. Inverse-square force gives $F_p/F_a=(3r/r)^2=9$.`,marking:["Uses angular-momentum conservation at the apsides to obtain 10 km/s.","Uses inverse-square scaling to obtain force ratio 9:1."]}],
    ["At the nearest and farthest points, velocity is transverse.","Conserve angular momentum, not linear speed.","Force obeys a different distance power from the endpoint speed relation."],["Using inverse-square scaling for the endpoint speed ratio."]),
  W("6.1",103,"laq",3,L`Small masses of 2 kg and 6 kg are separated by 4 m. They are replaced, without changing their positions, by masses of 4 kg and 3 kg.`,[
    {prompt:"Compare the mutual force before and after the replacement, and calculate each in terms of G.",answer:L`Initially $F=G(2)(6)/4^2=3G/4$ newtons. Afterwards $F'=G(4)(3)/4^2=3G/4$ newtons. Equal mass products give equal forces.`,marking:["Obtains original force 3G/4 N.","Obtains unchanged new force using the mass product."]},
    {prompt:"Compare the accelerations of the body at the first position before and after replacement. Explain why unchanged force does not imply unchanged acceleration.",answer:L`Initially $a=F/2=3G/8\,\mathrm{m\,s^{-2}}$. Afterwards $a'=F'/4=3G/16\,\mathrm{m\,s^{-2}}$, half the original. The mass being accelerated has doubled.`,marking:["Obtains the original acceleration 3G/8.","Obtains the new acceleration 3G/16.","Explains the changed inertial mass despite equal force."]}],
    ["Compare mass products first.","For acceleration, divide by the mass at the specified position.","Keep track of which body is being compared."],["Assuming equal force entails equal acceleration."]),
  W("6.1",104,"case",3,L`Two low-mass planets orbit the same star in ellipses. Planet A has semi-major axis a and period T. Planet B has semi-major axis 9a/4.`,[
    {prompt:"Find B's period in terms of T. Does the eccentricity need to be known for this comparison?",answer:L`$T_B/T=(9/4)^{3/2}=27/8$. Thus $T_B=27T/8$. For these Keplerian orbits about the same star, the period depends on semi-major axis, not eccentricity.`,marking:["Obtains period ratio 27/8.","States why eccentricity is not required."]},
    {prompt:"During one-eighth of A's period, what fraction of the total elliptical area is swept out by its star-planet line? Does this imply one-eighth of the orbit's perimeter is covered?",answer:"One-eighth of the total area is swept out. It does not generally imply one-eighth of the perimeter, because linear speed varies along an ellipse.",marking:["Gives one-eighth of the area.","Distinguishes equal swept area from equal path length."]}],
    ["Use semi-major axis in the third law for ellipses.","Use equal areas for equal times in the second law.","Area fraction is not arc-length fraction."],["Using the instantaneous star-planet distance in place of semi-major axis."]),
  M("6.2",101,3,L`Two fixed point masses M and 9M are separated by distance d. Between them, the gravitational field is zero at a distance from M equal to`,L`$d/4$`,[
    [L`$d/2$`,"The midpoint cancels fields only for equal source masses."],[L`$3d/4$`,"The zero-field point must lie closer to the smaller mass."],[L`$d/10$`,"The field depends on inverse distance squared, not inverse distance."]],
    L`Let the distance from M be x. Then $GM/x^2=9GM/(d-x)^2$. Positive distances give $d-x=3x$, so $x=d/4$.`,["Between the masses the two field directions oppose.","Equate their magnitudes.","Take the positive square root before solving." ]),
  M("6.2",102,2,"A spherically symmetric planet retains its mass while its radius decreases to 80% of the original value. Its new surface gravity divided by the old value is","25/16",[
    ["4/5","Surface gravity is not proportional to radius at fixed mass."],["16/25","This reverses the inverse-square radius factor."],["5/4","Square the radius ratio."]],
    L`At fixed M, $g\propto R^{-2}$. Thus $g'/g=1/(0.8)^2=25/16$.`,["Specify what stays fixed.","Use the surface inverse-square relation.","A smaller radius at fixed mass increases surface gravity." ]),
  M("6.2",103,2,"Two spherical planets have the same radius but densities in the ratio 2:5. Their surface gravities are in the ratio","2:5",[
    ["4:25","Gravity is linear, not quadratic, in mass at fixed radius."],["5:2","The denser planet has larger mass and larger surface gravity."],["1:1","Equal radius does not imply equal mass."]],
    L`$M=(4\pi/3)\rho R^3$ gives $g=(4\pi G/3)\rho R$. With equal R, gravity is proportional to density.`,["Express mass using density and volume.","Substitute into surface gravity.","Cancel the common radius." ]),
  M("6.2",104,2,"An astronaut floats freely inside a satellite in circular orbit. Which statement is correct?","Gravity is non-zero; astronaut and satellite share gravitational free fall.",[
    ["Gravity vanishes outside the atmosphere.","Earth's gravitational field extends far beyond the atmosphere."],["The astronaut has no mass in orbit.","Mass is unchanged; the supporting normal force is absent."],["The satellite shields the astronaut from gravity.","Ordinary satellite walls do not shield gravity."]],
    "The astronaut and satellite accelerate towards Earth together. With no supporting normal force in ideal free fall, apparent weight is zero although gravitational force is not.",["Orbital motion itself requires gravitational acceleration.","A scale measures support force.","Compare the astronaut's and satellite's free-fall motion." ]),
  W("6.2",101,"vsaq",2,L`At a point, a test mass of $0.5\,\mathrm{kg}$ experiences gravitational force $(-2\hat i+\hat j)\,\mathrm{N}$.`,[
    {prompt:"Find the gravitational field vector there.",answer:L`$\vec g=\vec F/m=(-4\hat i+2\hat j)\,\mathrm{N\,kg^{-1}}$.`,marking:["Divides both force components by 0.5 kg."]}],
    ["Field is force per unit test mass.","Divide each signed component.","Keep the field direction parallel to force."],["Multiplying force by test mass."]),
  W("6.2",102,"saq",3,L`Two equal fixed point masses M lie at x=-a and x=+a. Consider point P=(0,a).`,[
    {prompt:"Find the gravitational field vector at P, taking x and y as standard Cartesian axes.",answer:L`Each distance is $a\sqrt2$, so each field magnitude is $GM/(2a^2)$. Horizontal components cancel and downward components add, giving $\vec g=-GM/(\sqrt2a^2)\,\hat j$.`,marking:["Finds equal distances and cancels horizontal components.",L`Obtains $-GM\hat j/(\sqrt2a^2)$.`]}],
    ["Sketch the two attraction directions.","Both distances equal the diagonal of an a-by-a square.","Add components, not the full field magnitudes."],["Adding the two magnitudes without resolving them."]),
  W("6.2",103,"laq",3,L`A non-rotating spherical planet has radius half Earth's radius and average density three times Earth's average density. Let Earth's mass, radius and surface gravity be M, R and g.`,[
    {prompt:"Find the planet's mass and surface gravity in terms of Earth's values.",answer:L`The mass ratio is $3(1/2)^3=3/8$, so $M_p=3M/8$. Then $g_p/g=(3/8)/(1/2)^2=3/2$.`,marking:["Uses density times volume for mass ratio 3/8.","Obtains surface gravity 3g/2."]},
    {prompt:"An object weighs 80 N on Earth. Find its weight there and compare its inertial mass.",answer:"Its weight becomes 120 N, since gravity is multiplied by 3/2. Its inertial mass remains unchanged; changing location changes weight, not mass.",marking:["Scales the weight to 120 N.","States unchanged inertial mass.","Explains the distinction between mass and local gravitational force."]}],
    ["Volume scales as radius cubed.","Use the derived mass in the inverse-square surface formula.","Apply the gravity ratio only to weight."],["Using the density ratio directly as the mass ratio."]),
  W("6.2",104,"case",3,L`Two equal small masses M are held at x=-2a and x=+2a. A test particle is first at the midpoint, then displaced a small distance x to the right, where $0<x<2a$.`,[
    {prompt:"State the field at the midpoint and write the signed field at the displaced position.",answer:L`The midpoint field is zero by symmetry. At the new point, $g_x=GM/(2a-x)^2-GM/(2a+x)^2$, positive towards the nearer right-hand mass.`,marking:["Gives zero field at the midpoint.","Writes the correct difference of the two inverse-square fields."]},
    {prompt:"Is the midpoint a stable equilibrium for motion constrained along the line joining the sources? Explain without a series expansion.",answer:"No. A rightward displacement makes the rightward attraction stronger, so acceleration is further right rather than restoring. A leftward displacement similarly accelerates further left. The equilibrium is unstable along this line.",marking:["Compares the nearer and farther attractions correctly.","Concludes instability specifically along the line of the sources."]}],
    ["Equal fields cancel only at the symmetric point.","After displacement, identify the nearer mass.","Stable equilibrium requires a restoring, not reinforcing, force."],["Assuming every zero-field point is stable."]),
  M("6.3",101,2,L`At height h above a spherical planet of radius R, gravity is 64% of its surface value. The height is`,L`$R/4$`,[
    [L`$4R/5$`,"4/5 is R divided by the new centre distance, not the height."],[L`$R/5$`,"Solving R/(R+h)=4/5 gives h=R/4."],[L`$5R/4$`,"This is distance from the centre, not height above the surface."]],
    L`$[R/(R+h)]^2=0.64$ gives $R/(R+h)=0.8$, so $R+h=1.25R$ and $h=R/4$.`,["Use centre distance R+h.","Take the square root of the gravity ratio.","Subtract the surface radius at the end." ]),
  M("6.3",102,2,"Inside a uniformly dense, non-rotating spherical planet, the gravitational-field magnitude as a function of distance r from its centre is","proportional to r",[
    ["proportional to inverse r squared","Inside, the attracting enclosed mass decreases as r cubed."],["constant","The enclosed mass changes with position."],["proportional to r cubed","Divide enclosed mass, proportional to r cubed, by r squared."]],
    L`Enclosed mass is $M(r)=4\pi\rho r^3/3$. Then $g(r)=GM(r)/r^2=4\pi G\rho r/3$. Outer shells give no net field inside.`,["Use only enclosed mass for the field.","Express enclosed mass using uniform density.","Apply the inverse-square law to that enclosed mass." ]),
  M("6.3",103,3,L`For a small altitude h and small depth d in a uniformly dense spherical Earth, the fractional reductions in g are equal to first order when`,L`$d=2h$`,[
    [L`$d=h$`,"The small-altitude reduction has coefficient two, whereas the depth reduction has coefficient one."],[L`$d=h/2$`,"This reverses the relation between the first-order reductions."],[L`$d=4h$`,"The altitude correction is linear in h/R at first order."]],
    L`For $h,d\ll R$, $g_h/g_0\approx1-2h/R$ and $g_d/g_0=1-d/R$. Equal reductions give $d=2h$.`,["Write the small-height approximation.","Compare with the uniform-density depth formula.","Equate reductions, not the distances themselves." ]),
  M("6.3",104,2,"Assertion (A): The formula for gravity decreasing linearly with depth is exact for any real planet. Reason (R): Its derivation assumes a spherically symmetric uniform density.","A is false, but R is true.",[
    ["Both A and R are true, and R explains A.","A uniform-density model is not exact for all real planets."],["Both A and R are true, but R does not explain A.","The assertion overstates the model's validity."],["A is true, but R is false.","Uniform density is the assumption behind the linear result."]],
    L`$g_d=g_0(1-d/R)$ follows from enclosed mass proportional to radius cubed. Real density profiles need not satisfy that relation, so the model is not universally exact.`,["Identify the density assumption used for enclosed mass.","Real planets can have layered density.","A model result must retain its conditions." ]),
  W("6.3",101,"vsaq",2,"In the uniform-density spherical-planet model, a body is placed at the planet's centre.",[
    {prompt:"What are its gravitational force and mass there?",answer:"Its net gravitational force is zero by spherical symmetry, while its mass remains unchanged.",marking:["Distinguishes zero net gravitational force from unchanged mass."]}],
    ["Opposite directions contribute equal attractions.","The field tends to zero at the centre.","Mass does not depend on local field strength."],["Calling the body massless when its weight vanishes."]),
  W("6.3",102,"saq",3,L`A uniform-density spherical planet has radius R and surface gravity $g_0$. Find the interior distance from the centre where gravity equals its value at an altitude 2R above the surface.`,[
    {prompt:"Calculate both the common gravity and the required interior radius.",answer:L`The outside centre distance is 3R, so gravity is $g_0/9$. Inside, $g(r)=g_0r/R$; equality gives $r=R/9$, corresponding to depth $8R/9$.`,marking:["Obtains outside gravity g0/9 using centre distance 3R.","Obtains interior radius R/9 rather than confusing it with depth."]}],
    ["Convert altitude to distance from centre.","Use the different interior and exterior formulae.","The requested interior coordinate is radius, not depth."],["Using the outside inverse-square rule inside the planet."]),
  W("6.3",103,"laq",3,L`For a spherical planet, consider altitude $h=0.10R$. Compare the exact gravity ratio with the first-order small-altitude approximation.`,[
    {prompt:"Calculate the two values of g at that altitude in units of surface gravity.",answer:L`Exact: $g_h/g_0=1/(1.10)^2=100/121\approx0.82645$. First-order: $1-2h/R=0.80$.`,marking:["Obtains exact ratio 100/121.","Obtains approximate ratio 0.80."]},
    {prompt:"Find the approximate formula's percentage error relative to the exact value, and state whether it overestimates or underestimates gravity.",answer:L`Relative error magnitude is $[(100/121)-0.80]/(100/121)=0.032=3.2\%$. The approximation underestimates g. Its neglected higher-order terms are no longer negligible at the desired precision.`,marking:["Uses exact value as the relative-error denominator.","Obtains 3.2%.","Identifies underestimation and the approximation's limited precision."]}],
    ["Do not round the exact fraction too early.","Relative error is difference divided by the exact value.","A first-order formula is not an exact identity."],["Applying the small-height approximation without checking its accuracy."]),
  W("6.3",104,"case",3,L`A uniform-density non-rotating planet has surface gravity $12\,\mathrm{m\,s^{-2}}$ and radius R. Station A is at depth R/3, and station B is at altitude R/2.`,[
    {prompt:"Calculate gravity at both stations and their ratio A:B.",answer:L`At A, $g_A=12(1-1/3)=8\,\mathrm{m\,s^{-2}}$. At B, $g_B=12/(1.5)^2=16/3\,\mathrm{m\,s^{-2}}$. The ratio is $3:2$.`,marking:["Obtains gravity 8 at A with the interior formula.","Obtains 16/3 at B and ratio 3:2."]},
    {prompt:"A 6 kg object is moved between the stations. Compare its weights and explain why its mass does not follow the same ratio.",answer:"Weights are 48 N at A and 32 N at B. Mass stays 6 kg; the weight difference comes from different gravitational field strengths, not a change in matter or inertia.",marking:["Obtains weights 48 N and 32 N.","Explains unchanged mass."]}],
    ["Keep altitude and depth distinct.","Use exact exterior gravity at this large altitude.","Multiply each local gravity by the same mass."],["Using 1-2h/R at h=R/2, where it is not a valid approximation."]),
  M("6.4",101,3,L`Two equal point masses M lie a distance 2a apart. Taking potential zero at infinity, the potential at their midpoint is`,L`$-2GM/a$`,[
    ["zero","Opposite fields cancel, but the two negative scalar potentials add."],[L`$-GM/(2a)$`,"Each source is a from the midpoint, not 2a, and there are two sources."],[L`$+2GM/a$`,"Gravitational potential with zero at infinity is negative."]],
    L`Each mass contributes $-GM/a$. Potential is a scalar, so $V=-GM/a-GM/a=-2GM/a$, even though the field there is zero.`,["Use the distance from the point to each source.","Add potentials as scalars.","Do not transfer the vector cancellation rule for fields to potentials." ]),
  M("6.4",102,2,L`A mass m moves from radius 2R to radius 3R outside a planet of mass M. The work done by gravity is`,L`$-GMm/(6R)$`,[
    [L`$+GMm/(6R)$`,"This is the potential-energy increase, not gravity's work."],[L`$-GMm/R$`,"Subtract reciprocal radii rather than radii."],["zero","Gravity does work during outward radial displacement."]],
    L`$W_g=GMm[1/(3R)-1/(2R)]=-GMm/(6R)$. Gravity opposes the outward motion.`,["Use the difference in gravitational potential energy.","Work by gravity is minus that change.","Check that outward motion gives negative gravity work." ]),
  M("6.4",103,2,L`Three equal point masses m occupy the vertices of an equilateral triangle of side a. With zero potential energy at infinite separation, the system's potential energy is`,L`$-3Gm^2/a$`,[
    [L`$-6Gm^2/a$`,"This counts every interacting pair twice."],[L`$-Gm^2/a$`,"There are three distinct pairs, not one."],[L`$+3Gm^2/a$`,"Gravitational pair energies are negative under the stated reference."]],
    L`There are three distinct pairs, each with energy $-Gm^2/a$. Their sum is $-3Gm^2/a$.`,["Count unordered pairs of the three masses.","Each separation equals a.","Do not double count reciprocal labels of the same pair." ]),
  M("6.4",104,2,"Assertion (A): Zero gravitational field at a point necessarily means zero gravitational potential there. Reason (R): Field is related to the spatial gradient of potential, not its absolute value.","A is false, but R is true.",[
    ["Both A and R are true, and R explains A.","A zero derivative can occur at a non-zero potential."],["Both A and R are true, but R does not explain A.","The assertion is false."],["A is true, but R is false.","The field-gradient relation is correct."]],
    "Equal masses give a counterexample at their midpoint: fields cancel, while the negative potentials add. A function's derivative can vanish without its value vanishing.",["Distinguish a value from its derivative.","Consider the midpoint between equal masses.","Potential is scalar; field is vector." ]),
  W("6.4",101,"vsaq",2,L`At a point the gravitational potential is $-5\times10^6\,\mathrm{J\,kg^{-1}}$.`,[
    {prompt:"Find the potential energy of a 3 kg object placed there under the same zero reference.",answer:L`$U=mV=3(-5\times10^6)=-1.5\times10^7\,\mathrm{J}$.`,marking:["Multiplies potential by mass and retains the negative sign."]}],
    ["Potential is energy per unit mass.","Multiply by the object's mass.","Do not drop the reference-dependent sign."],["Confusing potential in J/kg with potential energy in J."]),
  W("6.4",102,"saq",3,L`A body is slowly moved from the surface of a spherical planet of radius R to height R/2. The surface gravity is g and the body's mass is m.`,[
    {prompt:"Find the external work required, neglecting rotation and all losses.",answer:L`Final centre distance is $3R/2$. Thus $W_{\mathrm{ext}}=GMm(1/R-2/(3R))=GMm/(3R)=mgR/3$, since $GM=gR^2$.`,marking:["Uses final centre distance 3R/2 and the reciprocal-radius difference.","Obtains mgR/3, not the constant-g estimate mgR/2."]}],
    ["This altitude is not small compared with R.","Use the exact potential-energy difference.","Eliminate GM using surface gravity."],["Using mgh with surface g held constant over a large height."]),
  W("6.4",103,"laq",3,L`A small body is released from rest at distance 3R from the centre of a non-rotating spherical planet of mass M and radius R. It falls radially, with no atmosphere.`,[
    {prompt:"Find its speed when it reaches the surface using energy conservation.",answer:L`Initially $E=-GMm/(3R)$. At the surface, $\tfrac12mv^2-GMm/R=-GMm/(3R)$. Hence $v^2=4GM/(3R)$ and $v=\sqrt{4GM/(3R)}$.`,marking:["Writes initial and final mechanical energies with correct radii.","Obtains speed squared 4GM/(3R).",L`Obtains $v=\sqrt{4GM/(3R)}$.`]},
    {prompt:"Compare this with the surface escape speed and explain why the infall speed is smaller.",answer:L`With $v_e=\sqrt{2GM/R}$, $v/v_e=\sqrt{2/3}$. Starting at finite radius 3R releases less potential energy than falling from rest at infinity, which would reach the escape-speed magnitude at the surface.`,marking:[L`Obtains ratio $\sqrt{2/3}$.`,"Explains the smaller potential-energy drop from finite radius."]}],
    ["Use zero potential at infinity consistently.","Mass cancels in the energy equation.","Compare speed squares before taking the ratio's square root."],["Treating the fall as constant-g motion over a distance 2R."]),
  W("6.4",104,"case",3,L`Two fixed masses M are at x=-a and x=+a. A test body of mass m is moved very slowly from the midpoint to a point on the perpendicular bisector at distance $\sqrt3a$ from that midpoint.`,[
    {prompt:"Find gravitational potentials at the starting and finishing points.",answer:L`Initially each source is a away, so $V_i=-2GM/a$. Finally each is $\sqrt{a^2+3a^2}=2a$ away, so $V_f=-GM/a$.`,marking:["Obtains initial potential -2GM/a.","Finds final source distances 2a and potential -GM/a."]},
    {prompt:"Find external work and gravity's work, and state whether the work depends on the path taken between these points.",answer:L`$W_{\mathrm{ext}}=m(V_f-V_i)=+GMm/a$ for negligible kinetic-energy change. Gravity does $-GMm/a$. Gravity is conservative, so its work is independent of the path between the fixed endpoints.`,marking:["Gives the two equal opposite signed works.","States path independence for the gravitational work."]}],
    ["Calculate distances to both sources at both endpoints.","Add scalar potentials.","Slow motion removes net kinetic-energy change."],["Using field cancellation at the midpoint to set its potential to zero."]),
  M("6.5",101,2,L`Two satellites of masses m and 4m move in circular orbits of the same radius around a planet. Their orbital speeds are`,"equal",[
    ["in the ratio 1:2","Satellite mass cancels from the orbit equation."],["in the ratio 1:4","A larger gravitational force is accompanied by proportionally larger inertia."],["in the ratio 2:1","Orbital speed depends on the central mass and orbit radius, not satellite mass."]],
    L`$GMm/r^2=mv^2/r$ gives $v=\sqrt{GM/r}$, independent of satellite mass when the planet dominates the system.`,["Use gravity as the centripetal force.","Cancel the satellite mass.","The central planet's mass remains in the result." ]),
  M("6.5",102,2,L`A planet has twice Earth's radius and the same surface gravity. Its surface escape speed divided by Earth's is`,L`$\sqrt2$`,[
    ["2","At fixed g, escape speed is proportional to square root of radius."],["1","Equal surface gravity does not imply equal escape energy per unit mass."],[L`$1/\sqrt2$`,"At fixed surface gravity a larger radius increases escape speed."]],
    L`$v_e=\sqrt{2gR}$. Equal g and doubled R give the speed ratio $\sqrt2$.`,["Express escape speed in terms of surface gravity.","Hold g fixed, not planet mass.","Take the square root of the radius ratio." ]),
  M("6.5",103,2,L`A satellite in a circular orbit has total mechanical energy -E, where E is positive. Its kinetic energy and potential energy are respectively`,L`$E$ and $-2E$`,[
    [L`$2E$ and $-3E$`,"A gravitational circular orbit also requires U=-2K."],[L`$-E$ and $0$`,"Kinetic energy cannot be negative."],[L`$E/2$ and $-3E/2$`,"These sum correctly but do not satisfy the circular-orbit relation."]],
    L`For a circular orbit, $K=GMm/(2r)$ and $U=-GMm/r=-2K$. Thus total energy equals -K, so K=E and U=-2E.`,["Use both the energy sum and the circular-orbit condition.","Potential energy is minus twice kinetic energy.","The given E is a positive magnitude." ]),
  M("6.5",104,3,L`A body is launched radially outward from a spherical planet's surface at speed $v_e/2$, where $v_e$ is the surface escape speed. Ignore atmosphere and rotation. Its maximum distance from the centre is`,L`$4R/3$`,[
    [L`$R/3$`,"This is the maximum height above the surface, not centre distance."],[L`$2R$`,"Use total energy, not a linear relation between speed and height."],["infinity","The launch speed is below escape speed."]],
    L`Initial energy per unit mass is $v_e^2/8-GM/R=GM/(4R)-GM/R=-3GM/(4R)$. At the radial turning point it is $-GM/r_{\max}$, giving $r_{\max}=4R/3$.`,["Substitute escape speed squared as 2GM/R.","At maximum radial distance the speed is zero.","Keep centre distance separate from altitude." ]),
  W("6.5",101,"vsaq",2,"A satellite's circular orbit radius is increased by a factor of 9 around the same planet.",[
    {prompt:"By what factor does its orbital period increase?",answer:L`$T\propto r^{3/2}$, so the factor is $9^{3/2}=27$.`,marking:["Obtains factor 27 using the orbital-period radius dependence."]}],
    ["Use the period-radius law.","The exponent for period is three-halves.","Take square root of nine and then cube."],["Using inverse-square scaling for orbital period."]),
  W("6.5",102,"saq",3,L`A satellite moves in a circular orbit of radius r with speed v. A short tangential boost is applied at that point.`,[
    {prompt:"Find the minimum speed increment needed for escape, ignoring further propulsion and atmosphere.",answer:L`At radius r, local escape speed is $\sqrt{2GM/r}=\sqrt2v$. For a forward tangential boost, $\Delta v=(\sqrt2-1)v$.`,marking:["Relates local escape speed to circular speed at the same radius.",L`Obtains increment $(\sqrt2-1)v$, not total escape speed.`]}],
    ["Use the local radius, not the planet's surface radius.","The satellite already has speed v.","Subtract that initial speed from the required final speed."],["Reporting the full escape speed as the required increment."]),
  W("6.5",103,"laq",3,L`A satellite of mass m orbits a planet of mass M in a circle of radius r. Define $E_0=GMm/(2r)$. It is transferred to a circular orbit of radius 2r. Compare only the two endpoint states.`,[
    {prompt:"Express initial and final kinetic, potential and total energies in terms of E0.",answer:L`Initially $(K,U,E)=(E_0,-2E_0,-E_0)$. Finally they are $(E_0/2,-E_0,-E_0/2)$.`,marking:["Gives the initial energy triple.","Gives the final energy triple."]},
    {prompt:"Find the increase in mechanical energy and explain how the final speed can be lower even though the satellite receives energy.",answer:L`$\Delta E=+E_0/2$. Potential energy increases by $E_0$, while kinetic energy decreases by $E_0/2$. The positive net energy change raises the orbit, although the final circular speed is $v/\sqrt2$.`,marking:["Obtains positive energy change E0/2.","Accounts separately for potential-energy rise and kinetic-energy fall.",L`Gives final speed ratio $1/\sqrt2$ and explains the apparent paradox.`]}],
    ["Use the circular-orbit expressions at both radii.","Do not assume added total energy means added kinetic energy.","This comparison does not specify the transfer trajectory or burn history."],["Making kinetic energy increase because total energy increases."]),
  W("6.5",104,"case",3,L`A small non-rotating spherical planet has radius $2.0\times10^6\,\mathrm{m}$ and surface gravity $5.0\,\mathrm{m\,s^{-2}}$. A satellite is in a circular orbit at altitude equal to the planet's radius.`,[
    {prompt:"Find its orbital speed and period. You may leave the period in terms of pi.",answer:L`Orbit radius is $r=2R=4.0\times10^6\,\mathrm{m}$. Since $GM=gR^2$, $v=\sqrt{gR/2}=1000\sqrt5\,\mathrm{m\,s^{-1}}$. Then $T=2\pi r/v=8000\pi/\sqrt5\,\mathrm{s}$.`,marking:["Uses orbit radius 2R and obtains speed 1000 square root of 5 m/s.",L`Obtains period $8000\pi/\sqrt5\,\mathrm{s}$.`]},
    {prompt:"Find local escape speed from the orbit position and compare it with surface escape speed.",answer:L`At r=2R, $v_{e,r}=\sqrt{2GM/(2R)}=\sqrt{gR}=1000\sqrt{10}\,\mathrm{m\,s^{-1}}$. Surface escape speed is $\sqrt{2gR}=2000\sqrt5\,\mathrm{m\,s^{-1}}$, larger by $\sqrt2$.`,marking:["Obtains local escape speed 1000 square root of 10 m/s.","Obtains surface value and correct square-root-of-two comparison."]}],
    ["Convert altitude to centre distance first.","Replace GM using measured surface gravity.","Escape speed must be evaluated at its starting radius."],["Using surface radius in every orbit formula."]),
];
