import type { VideoSelection } from "@/lib/video-lessons";

// Original-creator lessons only. Older recordings are scoped to the matching
// content retained in the current 2026-27 registry.
export const CHEMISTRY_11_VIDEOS: VideoSelection[] = [
  {
    videoId: "rvqLff_eJR8",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u1-some-basic-concepts",
    topicCodes: ["1.1", "1.2", "1.3", "1.4", "1.5"],
    language: "en",
    focus: "Some basic concepts of chemistry",
    format: "lesson",
    coverage:
      "Animated full-chapter lesson covering measurement, mole calculations, formulae, stoichiometry and concentration. Use the current topic list to exclude any older-syllabus extras.",
  },
  {
    videoId: "wCunYTntVJo",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u1-some-basic-concepts",
    topicCodes: ["1.1", "1.2", "1.3", "1.4", "1.5"],
    language: "hi",
    focus: "Some basic concepts of chemistry",
    format: "revision",
    coverage:
      "Hinglish one-shot chapter revision in about 44 minutes; best after first study, with the current registry setting the assessed scope.",
  },
  {
    videoId: "-Qf8IdfFcvk",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u2-structure-of-atom",
    topicCodes: ["2.1", "2.2", "2.3"],
    language: "en",
    focus: "Atomic models, radiation and the Bohr model",
    format: "lesson",
    coverage:
      "Part 1 of the animated full-chapter sequence; use with Part 2 for orbitals, quantum numbers and electronic configuration.",
  },
  {
    videoId: "gWJeO6tTf9U",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u2-structure-of-atom",
    topicCodes: ["2.4", "2.5"],
    language: "en",
    focus: "Quantum model, orbitals and electronic configuration",
    format: "lesson",
    coverage:
      "Part 2 of the animated full-chapter sequence, supplementing the atomic-model and Bohr material in Part 1.",
  },
  {
    videoId: "TfppDsXOLlY",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u2-structure-of-atom",
    topicCodes: ["2.1", "2.2", "2.3", "2.4", "2.5"],
    language: "hi",
    focus: "Structure of atom",
    format: "revision",
    coverage:
      "Hinglish one-shot revision of the full chapter in about 44 minutes; concise exam review rather than a full first-teaching sequence.",
  },
  {
    videoId: "2_gEGKGDuDc",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u4-chemical-bonding-molecular-structure",
    topicCodes: ["4.1", "4.2", "4.3"],
    language: "en",
    focus: "Lewis bonding, bond parameters and molecular shapes",
    format: "lesson",
    coverage:
      "Part 1 of the animated full-chapter sequence; Part 2 continues with orbital-based bonding and hydrogen bonding.",
  },
  {
    videoId: "pGFd43BJGNc",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u4-chemical-bonding-molecular-structure",
    topicCodes: ["4.4", "4.5"],
    language: "en",
    focus: "Hybridisation, molecular orbitals and hydrogen bonding",
    format: "lesson",
    coverage:
      "Part 2 of the animated full-chapter sequence, to be used after the Lewis-structure and VSEPR foundations in Part 1.",
  },
  {
    videoId: "a0lFMwb6wms",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u4-chemical-bonding-molecular-structure",
    topicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    language: "hi",
    focus: "Chemical bonding and molecular structure",
    format: "lesson",
    coverage:
      "Current 2026-27 Hindi/Hinglish full-chapter lesson covering the Class 11 bonding unit. Its long one-shot format can be used selectively by topic.",
  },
  {
    videoId: "mibviwHOveM",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u5-chemical-thermodynamics",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "en",
    focus: "Chemical thermodynamics",
    format: "lesson",
    coverage:
      "Animated full-chapter lesson covering thermodynamic terms, first law, calorimetry, reaction enthalpy and spontaneity at chapter level.",
  },
  {
    videoId: "lSmIi-MSZgg",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u5-chemical-thermodynamics",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "hi",
    focus: "Chemical thermodynamics",
    format: "revision",
    coverage:
      "Hinglish one-shot chapter revision in about 44 minutes, with concepts and exam-oriented consolidation.",
  },
  {
    videoId: "qi6h6Regqak",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u5-chemical-thermodynamics",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "hi",
    focus: "Thermodynamics rapid recap",
    format: "revision",
    coverage:
      "Hinglish 15-minute rapid revision. It supplements, rather than replaces, sign-convention and calculation practice.",
  },
  {
    videoId: "xqUZTDkYUVI",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u6-equilibrium",
    topicCodes: ["6.1", "6.2"],
    language: "en",
    focus: "Chemical equilibrium and Le Chatelier principle",
    format: "lesson",
    coverage:
      "Part 1 of the animated full-chapter sequence, focused on dynamic equilibrium, constants and equilibrium shifts.",
  },
  {
    videoId: "NOO7mjlq-Xs",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u6-equilibrium",
    topicCodes: ["6.3", "6.4", "6.5"],
    language: "en",
    focus: "Ionic equilibrium, buffers and solubility",
    format: "lesson",
    coverage:
      "Part 2 of the animated full-chapter sequence, continuing into acid-base and solubility equilibria.",
  },
  {
    videoId: "0MY0ZfdUs5Q",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u6-equilibrium",
    topicCodes: ["6.1", "6.2", "6.3", "6.4", "6.5"],
    language: "hi",
    focus: "Equilibrium",
    format: "revision",
    coverage:
      "Hinglish one-shot chapter revision covering chemical and ionic equilibrium; numerical fluency needs separate practice.",
  },
  {
    videoId: "lp23KN03JrY",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u6-equilibrium",
    topicCodes: ["6.1", "6.2", "6.3", "6.4", "6.5"],
    language: "hi",
    focus: "Equilibrium rapid recap",
    format: "revision",
    coverage:
      "Hinglish 15-minute rapid revision of chemical and ionic equilibrium, intended for students who have already studied the chapter.",
  },
  {
    videoId: "thuIw8GLhzM",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u7-redox-reactions",
    topicCodes: ["7.1", "7.2", "7.3", "7.4"],
    language: "en",
    focus: "Redox concepts, oxidation numbers and balancing",
    format: "lesson",
    coverage:
      "Animated full-chapter lesson on redox definitions, agents, reaction types and balancing. Electrode-process coverage is not claimed.",
  },
  {
    videoId: "HN0xaDXCftg",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u7-redox-reactions",
    topicCodes: ["7.1", "7.2", "7.3", "7.4"],
    language: "hi",
    focus: "Redox reactions",
    format: "revision",
    coverage:
      "Hinglish one-shot chapter revision in about 44 minutes. No claim is made for the registry's separate electrode-process extension.",
  },
  {
    videoId: "soz-THA0luM",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u7-redox-reactions",
    topicCodes: ["7.1", "7.2", "7.3", "7.4"],
    language: "hi",
    focus: "Redox reactions rapid recap",
    format: "revision",
    coverage:
      "Hinglish 15-minute recap of standard redox chapter content; electrode half-reactions need a separate source.",
  },
  {
    videoId: "v-XxOyVPmlg",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u8-organic-chemistry-basic-principles-techniques",
    topicCodes: ["8.1", "8.2", "8.3"],
    language: "en",
    focus: "Organic structures, nomenclature and isomerism",
    format: "lesson",
    coverage:
      "Part 1 of the older animated Organic Chemistry chapter sequence. Use Part 2 for reaction concepts and purification or analysis.",
  },
  {
    videoId: "xXdvpmvFSfU",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u8-organic-chemistry-basic-principles-techniques",
    topicCodes: ["8.4", "8.5"],
    language: "en",
    focus: "Organic reaction concepts, purification and analysis",
    format: "lesson",
    coverage:
      "Part 2 of the older animated Organic Chemistry chapter sequence. This is theory support, not a substitute for supervised lab work.",
  },
  {
    videoId: "_x7ZtdYWnSE",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u8-organic-chemistry-basic-principles-techniques",
    topicCodes: ["8.1", "8.2", "8.3", "8.4", "8.5"],
    language: "hi",
    focus: "Organic chemistry basic principles and techniques",
    format: "revision",
    coverage:
      "Hinglish one-shot revision of the chapter. Purification and elemental-analysis procedures still require textbook and supervised practical study.",
  },
  {
    videoId: "CtDQxvp5mcw",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u8-organic-chemistry-basic-principles-techniques",
    topicCodes: ["8.1", "8.2", "8.3", "8.4", "8.5"],
    language: "hi",
    focus: "Organic chemistry rapid recap",
    format: "revision",
    coverage:
      "Hinglish 15-minute chapter recap; it is too compressed for first learning or practical technique preparation.",
  },
  {
    videoId: "VF-Lp6IpClM",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u9-hydrocarbons",
    topicCodes: ["9.1", "9.2", "9.3"],
    language: "en",
    focus: "Hydrocarbon classification, alkanes and alkenes",
    format: "lesson",
    coverage:
      "Part 1 of the animated full-chapter sequence, paired with Part 2 for alkynes and aromatic hydrocarbons.",
  },
  {
    videoId: "U2DzcHUgdwI",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u9-hydrocarbons",
    topicCodes: ["9.4", "9.5"],
    language: "en",
    focus: "Alkynes and aromatic hydrocarbons",
    format: "lesson",
    coverage:
      "Part 2 of the animated full-chapter sequence. Follow current NCERT scope for reaction detail and hazardous-hydrocarbon context.",
  },
  {
    videoId: "k7pqxuBK8Jo",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u9-hydrocarbons",
    topicCodes: ["9.1", "9.2", "9.3", "9.4", "9.5"],
    language: "hi",
    focus: "Hydrocarbons",
    format: "revision",
    coverage:
      "Hinglish one-shot full-chapter revision covering the main hydrocarbon families and reactions.",
  },
  {
    videoId: "w-7kM3xupl4",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u9-hydrocarbons",
    topicCodes: ["9.1", "9.2", "9.3", "9.4", "9.5"],
    language: "hi",
    focus: "Hydrocarbons rapid recap",
    format: "revision",
    coverage:
      "Hinglish 15-minute chapter recap; use after detailed study and reaction practice.",
  },
  {
    videoId: "aM0UMpyCnbo",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.1", "F.2"],
    language: "en",
    focus: "Gas laws, ideal gas equation and real gases",
    format: "lesson",
    coverage:
      "Older States of Matter chapter retained only for the current formative gas-law and real-gas topics; liquid-state material is outside this mapping.",
  },
  {
    videoId: "ABYNG_ZrXRU",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.3"],
    language: "en",
    focus: "s-block trends and first-element behaviour",
    format: "lesson",
    coverage:
      "Older s-block chapter used only for the retained formative trend and first-element material, not as a current standalone theory unit.",
  },
  {
    videoId: "UebSo5CvYDI",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.4"],
    language: "en",
    focus: "p-block trends and unique first elements",
    format: "lesson",
    coverage:
      "Older p-block chapter scoped only to the retained formative trends and first-element behaviour; group-specific detail may exceed current scope.",
  },
  {
    videoId: "FggvNDlkJxo",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.1"],
    language: "en",
    focus: "Purification of benzoic acid by crystallisation",
    format: "concept",
    coverage:
      "MeitY OLabs demonstration of crystallisation as a purification technique. It does not cover glass working, cork boring, melting point or boiling point, and it does not replace supervised lab work.",
  },
  {
    videoId: "1nqxPW9kL2M",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.3"],
    language: "en",
    focus: "Preparation of standard oxalic acid solution",
    format: "concept",
    coverage:
      "Original OLabs demonstration of preparing 250 mL of 0.1 M standard oxalic acid solution, matching the standard-solution portion of Lab.3. It does not replace supervised practical work.",
  },
  {
    videoId: "kc0Nc77t5Ig",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.3"],
    language: "en",
    focus: "Acid-base quantitative estimation",
    format: "concept",
    coverage:
      "MeitY OLabs demonstration of acid-base titration technique using standard sodium carbonate and hydrochloric acid. It supports volumetric procedure, while the authored Lab.3 calculation uses standard oxalic acid and sodium hydroxide.",
  },
  {
    videoId: "DboO6_eF5cE",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u3-classification-periodicity",
    topicCodes: ["3.1", "3.2", "3.3", "3.4", "3.5"],
    language: "en",
    focus: "Classification of elements and periodicity",
    format: "lesson",
    coverage:
      "English CBSE chapter lesson spanning periodic classification, table structure, electronic placement and periodic trends. Detailed exception practice remains separate.",
  },
  {
    videoId: "uRTLY3p1VUE",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u7-redox-reactions",
    topicCodes: ["7.5"],
    language: "en",
    focus: "Redox reactions and electrode processes",
    format: "concept",
    coverage:
      "Focused Class 11 treatment of oxidation and reduction at electrodes, including anode and cathode roles. It supplements the main redox chapter lessons.",
  },
  {
    videoId: "AXhOVhqXRXQ",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "u7-redox-reactions",
    topicCodes: ["7.5"],
    language: "hi",
    focus: "Galvanic-cell electrodes and voltage",
    format: "concept",
    coverage:
      "Khan Academy India Hindi explanation of galvanic-cell electrodes and voltage, supporting anode/cathode and electrode-process interpretation.",
  },
  {
    videoId: "AJiOL1ZgZng",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.1"],
    language: "hi",
    focus: "Gas laws and ideal gas equation",
    format: "lesson",
    coverage:
      "Hindi/Hinglish lesson on Boyle, Charles, Gay-Lussac and Avogadro laws and the ideal-gas equation. Real-gas deviation is covered separately.",
  },
  {
    videoId: "MKo0d51Udxs",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.2"],
    language: "hi",
    focus: "Ideal and real gases",
    format: "concept",
    coverage:
      "Hindi/Hinglish lesson on real-gas deviation and compressibility factor, scoped to the qualitative formative topic.",
  },
  {
    videoId: "1uJk4K_irP8",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.3"],
    language: "hi",
    focus: "s-block trends and first-element behaviour",
    format: "lesson",
    coverage:
      "Hindi/Hinglish older-chapter lesson used only for the retained s-block trends and first-element behaviour, not as a current standalone theory unit.",
  },
  {
    videoId: "6Ojqg1tzdRw",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.4"],
    language: "hi",
    focus: "Anomalous behaviour of boron",
    format: "concept",
    coverage:
      "Hindi/Hinglish concept lesson supporting the unique first-element behaviour portion of the formative p-block topic; it is not full p-block trend coverage.",
  },
  {
    videoId: "22ZB0ZwvOsQ",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.1"],
    language: "en",
    focus: "Basic laboratory techniques",
    format: "concept",
    coverage:
      "MeitY OLabs demonstration of basic glass-working and cork-boring techniques. Perform these operations only under teacher supervision.",
  },
  {
    videoId: "nQNaTfqXECk",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.1"],
    language: "en",
    focus: "Melting point of an organic compound",
    format: "concept",
    coverage:
      "MeitY OLabs melting-point demonstration. It supports apparatus recognition and procedure review, not unsupervised performance.",
  },
  {
    videoId: "J9Zmjs1EAWc",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.1"],
    language: "en",
    focus: "Boiling point of an organic compound",
    format: "concept",
    coverage:
      "MeitY OLabs boiling-point demonstration, scoped to the boiling-point portion of Lab.1 and subject to teacher supervision.",
  },
  {
    videoId: "c7g0c59ZxH4",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.2"],
    language: "en",
    focus: "pH determination",
    format: "concept",
    coverage:
      "MeitY OLabs demonstration of pH determination. Common-ion and equilibrium-shift experiments are separate selections.",
  },
  {
    videoId: "XqDchNzLNsY",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.2"],
    language: "en",
    focus: "Common-ion effect on pH",
    format: "concept",
    coverage:
      "LabInApp demonstration of pH variation from the common-ion effect in weak acids and bases; it does not cover every pH experiment in Lab.2.",
  },
  {
    videoId: "zCeciBrBhMU",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.2"],
    language: "en",
    focus: "Equilibrium shift with ferric and thiocyanate ions",
    format: "concept",
    coverage:
      "MeitY OLabs equilibrium-shift demonstration using ferric and thiocyanate ions. It supports observation review under teacher supervision.",
  },
  {
    videoId: "rZX_Hv2LNQg",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.2"],
    language: "hi",
    focus: "pH determination practical",
    format: "concept",
    coverage:
      "Hindi Class 11 practical explanation of pH determination. It is a scope-only supplement and does not claim common-ion or equilibrium-shift coverage.",
  },
  {
    videoId: "O3d_NKyhIwg",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.4"],
    language: "en",
    focus: "Confirmatory tests for chloride",
    format: "concept",
    coverage:
      "MeitY OLabs demonstration of chloride-ion tests, providing one anion example within systematic salt analysis.",
  },
  {
    videoId: "GTZBs3iZgg0",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.4"],
    language: "en",
    focus: "Confirmatory tests for ammonium ion",
    format: "concept",
    coverage:
      "MeitY OLabs demonstration of ammonium-ion tests, providing one cation example within systematic salt analysis.",
  },
  {
    videoId: "wI_X8xRnh9E",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.4"],
    language: "hi",
    focus: "Salt analysis theory and practical workflow",
    format: "lesson",
    coverage:
      "Hindi/Hinglish board-practical lesson on salt-analysis workflow. Use the school's prescribed ion list and confirmatory tests; teacher supervision remains essential.",
  },
  {
    videoId: "FUo428guKt0",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.5"],
    language: "en",
    focus: "Lassaigne test for extra elements",
    format: "concept",
    coverage:
      "MeitY OLabs overview of Lassaigne's test for extra elements in organic compounds. Investigatory-project design is not covered.",
  },
  {
    videoId: "slC3G0XVenU",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.5"],
    language: "hi",
    focus: "Lassaigne extract and element detection",
    format: "concept",
    coverage:
      "Hindi/Hinglish explanation of sodium-fusion extract and nitrogen, sulphur and halogen detection. It does not cover investigatory-project design.",
  },
  {
    videoId: "6oabC6KaUpQ",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.1"],
    language: "hi",
    focus: "Cutting, bending and drawing a glass jet",
    format: "concept",
    coverage:
      "Hindi/Hinglish Class 11 demonstration of selected glass-working techniques. Cork boring, physical-constant measurements and crystallisation require the other practical supports and teacher supervision.",
  },
  {
    videoId: "WXsji-QVacI",
    courseSlug: "cbse-chemistry-11",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.3"],
    language: "hi",
    focus: "Oxalic acid and sodium hydroxide titration",
    format: "concept",
    coverage:
      "Hindi/Hinglish Class 11 demonstration determining NaOH molarity against 0.05 M standard oxalic acid with phenolphthalein, matching the authored Lab.3 substances and endpoint.",
  },
];
