import type { VideoSelection } from "@/lib/video-lessons";

export const FOUNDATION_VIDEOS: VideoSelection[] = [
  {
    videoId: "snlKFX8_q1o",
    courseSlug: "cbse-math-9",
    unitSlug: "u1-number-system",
    topicCodes: ["1.1", "1.2", "1.3", "1.4", "1.5"],
    language: "en",
    focus: "Number systems",
    format: "lesson",
    coverage:
      "Full animated NCERT number-systems chapter, including real-number representation and irrational numbers.",
  },
  {
    videoId: "VQLWEVM0eWs",
    courseSlug: "cbse-math-9",
    unitSlug: "u2-algebra-ix",
    topicCodes: ["2.1", "2.3"],
    language: "en",
    focus: "Polynomials",
    format: "lesson",
    coverage:
      "Polynomials, identities and factorisation; not sequences or pairs of equations.",
  },
  {
    videoId: "qj9PGmoL6Mo",
    courseSlug: "cbse-math-9",
    unitSlug: "u3-coordinate-geometry-ix",
    topicCodes: ["3.1", "3.2"],
    language: "en",
    focus: "Cartesian coordinates",
    format: "lesson",
    coverage:
      "Cartesian-plane basics and plotting; not distance, midpoint or collinearity.",
  },
  {
    videoId: "B6rfaYAjrMU",
    courseSlug: "cbse-math-9",
    unitSlug: "u4-geometry",
    topicCodes: ["4.3"],
    language: "en",
    focus: "Triangles and congruence",
    format: "lesson",
    coverage:
      "Full animated triangles chapter with standard congruence results.",
  },
  {
    videoId: "JIsKAUERQyQ",
    courseSlug: "cbse-math-9",
    unitSlug: "u5-mensuration",
    topicCodes: ["5.3"],
    language: "en",
    focus: "Heron's formula",
    format: "lesson",
    coverage: "Heron's formula and standard triangle-area applications.",
  },
  {
    videoId: "35IP0ggmkjM",
    courseSlug: "cbse-math-9",
    unitSlug: "u6-statistics-probability",
    topicCodes: ["6.1", "6.2", "6.3", "6.4"],
    language: "hi",
    focus: "Statistics and probability",
    format: "revision",
    coverage:
      "Hindi/Hinglish full-course marathon, scoped to standard statistics and empirical probability; not tree diagrams.",
  },

  {
    videoId: "mwaL-T3-ITQ",
    courseSlug: "cbse-science-9",
    unitSlug: "u1-world-of-living",
    topicCodes: ["1.1"],
    language: "en",
    focus: "Cell structure",
    format: "lesson",
    coverage:
      "Fundamental Unit of Life chapter, including cell structures and organelles.",
  },
  {
    videoId: "PJ0Nl-kwHhA",
    courseSlug: "cbse-science-9",
    unitSlug: "u2-matter-nature-behaviour",
    topicCodes: ["2.1", "2.2"],
    language: "en",
    focus: "Mixtures and separation",
    format: "lesson",
    coverage: "Mixtures, solution types and standard separation ideas.",
  },
  {
    videoId: "rRsefE4xoNs",
    courseSlug: "cbse-science-9",
    unitSlug: "u2-matter-nature-behaviour",
    topicCodes: ["2.3", "2.4"],
    language: "en",
    focus: "Structure of the atom",
    format: "lesson",
    coverage:
      "Atomic models, electronic arrangement, atomic and mass numbers, isotopes and valency.",
  },
  {
    videoId: "7FHrda_i2m8",
    courseSlug: "cbse-science-9",
    unitSlug: "u3-motion-force-work-sound",
    topicCodes: ["3.1", "3.2"],
    language: "en",
    focus: "Motion and graphs",
    format: "lesson",
    coverage: "Kinematics, graphs and standard equations of motion.",
  },
  {
    videoId: "BeI58I7lftw",
    courseSlug: "cbse-science-9",
    unitSlug: "u2-matter-nature-behaviour",
    topicCodes: ["2.1", "2.2", "2.3", "2.4", "2.5"],
    language: "hi",
    focus: "Matter and atoms",
    format: "revision",
    coverage:
      "Hindi/Hinglish course marathon scoped to matter, mixtures, atoms and molecules; it does not establish the new Earth-systems unit.",
  },

  {
    videoId: "OqIsi_4IkO0",
    courseSlug: "cbse-science-10",
    unitSlug: "u1-chemical-substances-nature-behaviour",
    topicCodes: ["1.1"],
    language: "en",
    focus: "Chemical reactions",
    format: "lesson",
    coverage: "Full animated reactions-and-equations chapter.",
  },
  {
    videoId: "Q5rfzGmhVdQ",
    courseSlug: "cbse-science-10",
    unitSlug: "u2-world-of-living",
    topicCodes: ["2.1", "2.2"],
    language: "en",
    focus: "Life processes",
    format: "lesson",
    coverage: "Nutrition, respiration, transport and excretion.",
  },
  {
    videoId: "nSzg1FyjTBs",
    courseSlug: "cbse-science-10",
    unitSlug: "u3-natural-phenomena",
    topicCodes: ["3.1", "3.2", "3.3", "3.4"],
    language: "en",
    focus: "Reflection and refraction",
    format: "lesson",
    coverage: "Spherical mirrors, mirror formula, refraction and lenses.",
  },
  {
    videoId: "T8Mam6h_JY8",
    courseSlug: "cbse-science-10",
    unitSlug: "u4-effects-of-current",
    topicCodes: ["4.1", "4.2", "4.3"],
    language: "en",
    focus: "Electricity",
    format: "lesson",
    coverage:
      "Current, voltage, resistance, combinations, heating and electric power.",
  },
  {
    videoId: "KB3a2tNdJ8A",
    courseSlug: "cbse-science-10",
    unitSlug: "u5-natural-resources",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "en",
    focus: "Our environment",
    format: "lesson",
    coverage:
      "Ecosystems, food chains, wastes, biomagnification and ozone depletion.",
  },
  {
    videoId: "DigrHomWUkw",
    courseSlug: "cbse-science-10",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.1"],
    language: "en",
    focus: "Periodic classification",
    format: "lesson",
    coverage:
      "Periodic classification only; other formative topics need separate sources.",
  },
  {
    videoId: "HPphkPll7Wg",
    courseSlug: "cbse-science-10",
    unitSlug: "u1-chemical-substances-nature-behaviour",
    topicCodes: ["1.1", "1.2", "1.3", "1.4"],
    language: "hi",
    focus: "Class 10 chemistry",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT marathon scoped to the four standard chemistry chapters; practical work is not claimed.",
  },

  {
    videoId: "ByF2q7TENLE",
    courseSlug: "cbse-math-10",
    unitSlug: "u1-number-systems",
    topicCodes: ["1.1", "1.2", "1.3"],
    language: "en",
    focus: "Real numbers",
    format: "lesson",
    coverage:
      "Prime factorisation applications and irrationality in the full real-numbers chapter.",
  },
  {
    videoId: "5wx-307BDco",
    courseSlug: "cbse-math-10",
    unitSlug: "u2-algebra-x",
    topicCodes: ["2.1"],
    language: "en",
    focus: "Polynomials and zeroes",
    format: "lesson",
    coverage: "Full animated Class 10 polynomials chapter.",
  },
  {
    videoId: "n0YK4gJCLv0",
    courseSlug: "cbse-math-10",
    unitSlug: "u5-trigonometry",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "hi",
    focus: "Trigonometry",
    format: "revision",
    coverage:
      "Hindi/Hinglish full-NCERT revision scoped to ratios, identities and heights and distances.",
  },

  {
    videoId: "54_XRjHhZzI",
    courseSlug: "calc-ab",
    unitSlug: "u1-limits",
    topicCodes: ["1.1", "1.2", "1.3", "1.4"],
    language: "en",
    focus: "Introduction to limits",
    format: "lesson",
    coverage:
      "University Calculus I limit intuition; mathematically reusable but not AP-specific or a full Unit 1 treatment.",
  },
  {
    videoId: "RUS4mKo9tBk",
    courseSlug: "calc-ab",
    unitSlug: "u3-comp-implicit",
    topicCodes: ["3.2", "3.6"],
    language: "en",
    focus: "Implicit differentiation",
    format: "lesson",
    coverage:
      "Implicit differentiation with higher derivatives; reusable Calculus I teaching, not AP-specific.",
  },
  {
    videoId: "sB6ZVg-8uJE",
    courseSlug: "calc-ab",
    unitSlug: "u8-app-integration",
    topicCodes: ["8.4", "8.6"],
    language: "en",
    focus: "Area between curves",
    format: "lesson",
    coverage:
      "Calculus I area-between-curves lesson; not y-based regions or volumes.",
  },
  {
    videoId: "pUmXQ2926sQ",
    courseSlug: "calc-ab",
    unitSlug: "u5-analytical-app",
    topicCodes: [
      "5.1",
      "5.2",
      "5.3",
      "5.4",
      "5.5",
      "5.6",
      "5.7",
      "5.8",
      "5.9",
      "5.10",
      "5.11",
      "5.12",
    ],
    language: "en",
    focus: "AP Units 1-5 review",
    format: "revision",
    coverage:
      "AP AB/BC review scoped to analytical applications of derivatives; concise review, not first teaching.",
  },
  {
    videoId: "QWuqkiaw_UE",
    courseSlug: "calc-ab",
    unitSlug: "u6-integration",
    topicCodes: [
      "6.1",
      "6.2",
      "6.3",
      "6.4",
      "6.5",
      "6.6",
      "6.7",
      "6.8",
      "6.9",
      "6.10",
      "6.11",
    ],
    language: "en",
    focus: "AP integration review",
    format: "revision",
    coverage:
      "AP AB/BC Units 6-10 review scoped to integration; BC-only material elsewhere is outside this mapping.",
  },
  {
    videoId: "QWuqkiaw_UE",
    courseSlug: "calc-ab",
    unitSlug: "u7-diff-eqs",
    topicCodes: ["7.1", "7.2", "7.3", "7.4", "7.6", "7.7", "7.8"],
    language: "en",
    focus: "AP differential equations review",
    format: "revision",
    coverage:
      "Slope fields, separable equations and exponential models within an AP AB/BC review.",
  },

  // Current Hindi/Hinglish full-course marathons provide a second-language
  // revision path across the standard CBSE chapters. Coverage notes flag the
  // StudyLoop extensions that are not established by those source titles.
  {
    videoId: "35IP0ggmkjM",
    courseSlug: "cbse-math-9",
    unitSlug: "u1-number-system",
    topicCodes: ["1.1", "1.2", "1.3", "1.4", "1.5"],
    language: "hi",
    focus: "Number systems",
    format: "revision",
    coverage:
      "Hindi/Hinglish full-course marathon scoped to the Number Systems chapter.",
  },
  {
    videoId: "35IP0ggmkjM",
    courseSlug: "cbse-math-9",
    unitSlug: "u2-algebra-ix",
    topicCodes: ["2.1", "2.3", "2.4"],
    language: "hi",
    focus: "Class 9 algebra",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of standard polynomials, identities and linear equations; sequences and pairs-of-equations extensions are not claimed.",
  },
  {
    videoId: "35IP0ggmkjM",
    courseSlug: "cbse-math-9",
    unitSlug: "u3-coordinate-geometry-ix",
    topicCodes: ["3.1", "3.2"],
    language: "hi",
    focus: "Coordinate geometry",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of Cartesian-plane basics and plotting; advanced coordinate applications need separate teaching.",
  },
  {
    videoId: "35IP0ggmkjM",
    courseSlug: "cbse-math-9",
    unitSlug: "u4-geometry",
    topicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    language: "hi",
    focus: "Class 9 geometry",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision across the standard Euclid, lines, triangles, quadrilaterals and circles chapters.",
  },
  {
    videoId: "35IP0ggmkjM",
    courseSlug: "cbse-math-9",
    unitSlug: "u5-mensuration",
    topicCodes: ["5.3", "5.4", "5.5"],
    language: "hi",
    focus: "Mensuration",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of Heron's formula and standard surface-area and volume solids; arcs, sectors and pyramids are not claimed.",
  },

  {
    videoId: "n0YK4gJCLv0",
    courseSlug: "cbse-math-10",
    unitSlug: "u1-number-systems",
    topicCodes: ["1.1", "1.2", "1.3"],
    language: "hi",
    focus: "Real numbers",
    format: "revision",
    coverage: "Hindi/Hinglish full-NCERT revision scoped to Real Numbers.",
  },
  {
    videoId: "n0YK4gJCLv0",
    courseSlug: "cbse-math-10",
    unitSlug: "u2-algebra-x",
    topicCodes: ["2.1", "2.2", "2.3", "2.4"],
    language: "hi",
    focus: "Class 10 algebra",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of polynomials, linear pairs, quadratics and arithmetic progressions.",
  },
  {
    videoId: "n0YK4gJCLv0",
    courseSlug: "cbse-math-10",
    unitSlug: "u3-coordinate-geometry",
    topicCodes: ["3.1", "3.2", "3.3"],
    language: "hi",
    focus: "Coordinate geometry",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of distance, section formula and coordinate applications.",
  },
  {
    videoId: "n0YK4gJCLv0",
    courseSlug: "cbse-math-10",
    unitSlug: "u4-geometry",
    topicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    language: "hi",
    focus: "Triangles and circles",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of similarity, proportionality, Pythagoras and tangents.",
  },
  {
    videoId: "n0YK4gJCLv0",
    courseSlug: "cbse-math-10",
    unitSlug: "u6-mensuration",
    topicCodes: ["6.1", "6.2", "6.3", "6.4", "6.5"],
    language: "hi",
    focus: "Mensuration",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of circle measures and combined-solid surface area and volume.",
  },
  {
    videoId: "n0YK4gJCLv0",
    courseSlug: "cbse-math-10",
    unitSlug: "u7-statistics-probability",
    topicCodes: ["7.1", "7.2", "7.3", "7.4", "7.5"],
    language: "hi",
    focus: "Statistics and probability",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of grouped statistics and classical probability.",
  },

  {
    videoId: "sIqVmuNfG3I",
    courseSlug: "cbse-science-9",
    unitSlug: "u1-world-of-living",
    topicCodes: ["1.3"],
    language: "hi",
    focus: "Reproduction in plants and animals",
    format: "lesson",
    coverage:
      "Current Class 9 Hindi/Hinglish lesson dedicated to the registry's reproduction chapter.",
  },
  {
    videoId: "MBTB3_2VHyo",
    courseSlug: "cbse-science-9",
    unitSlug: "u1-world-of-living",
    topicCodes: ["1.1", "1.2", "1.3", "1.4", "1.5"],
    language: "hi",
    focus: "Class 9 biology",
    format: "revision",
    coverage:
      "Hindi/Hinglish biology marathon spanning cells, tissues, reproduction and classification, with cross-chapter revision useful for integrated reasoning; practical execution still requires the separate practical selections.",
  },
  {
    videoId: "BeI58I7lftw",
    courseSlug: "cbse-science-9",
    unitSlug: "u3-motion-force-work-sound",
    topicCodes: ["3.1", "3.2", "3.3", "3.4", "3.5"],
    language: "hi",
    focus: "Motion, force, work and sound",
    format: "revision",
    coverage:
      "Hindi/Hinglish full-course marathon scoped to the standard physics chapters; simple machines may receive only revision-level treatment.",
  },
  {
    videoId: "Z6alJFYLZ9I",
    courseSlug: "cbse-science-9",
    unitSlug: "u4-earth-as-a-system",
    topicCodes: ["4.1", "4.2", "4.3"],
    language: "en",
    focus: "Solar radiation and Earth heating",
    format: "concept",
    coverage:
      "English concept lesson on solar radiation, heat balance and temperature, useful for Earth-system interactions and differential heating; not the full unit.",
  },
  {
    videoId: "nCNjcmbf9Tc",
    courseSlug: "cbse-science-9",
    unitSlug: "u4-earth-as-a-system",
    topicCodes: ["4.4", "4.5"],
    language: "hi",
    focus: "Biogeochemical cycles",
    format: "concept",
    coverage:
      "Hindi ecology lesson on biogeochemical cycles and human influence; broader than the CBSE Class 9 framing.",
  },
  {
    videoId: "teERjw2A51M",
    courseSlug: "cbse-science-9",
    unitSlug: "u4-earth-as-a-system",
    topicCodes: ["4.4"],
    language: "en",
    focus: "Biogeochemical cycles",
    format: "concept",
    coverage:
      "English ecology lesson focused on global biogeochemical cycles; does not cover solar radiation or winds.",
  },
  {
    videoId: "4PP-bAlj2BU",
    courseSlug: "cbse-science-9",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["IA.1"],
    language: "hi",
    focus: "Mixture observations",
    format: "lesson",
    coverage:
      "Hindi practical demonstration of homogeneous and heterogeneous mixtures; not the full IA programme.",
  },
  {
    videoId: "AKJyrRNG3is",
    courseSlug: "cbse-science-9",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["IA.3"],
    language: "en",
    focus: "Onion-peel slide",
    format: "lesson",
    coverage:
      "Practical demonstration of preparing a stained onion-peel mount; supervised lab practice remains necessary.",
  },

  {
    videoId: "HPphkPll7Wg",
    courseSlug: "cbse-science-10",
    unitSlug: "u2-world-of-living",
    topicCodes: ["2.1", "2.2", "2.3", "2.4", "2.5"],
    language: "hi",
    focus: "Class 10 biology",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT marathon scoped to life processes, coordination, reproduction and heredity.",
  },
  {
    videoId: "HPphkPll7Wg",
    courseSlug: "cbse-science-10",
    unitSlug: "u3-natural-phenomena",
    topicCodes: ["3.1", "3.2", "3.3", "3.4", "3.5"],
    language: "hi",
    focus: "Light and the human eye",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT marathon scoped to reflection, refraction, lenses and the human eye.",
  },
  {
    videoId: "HPphkPll7Wg",
    courseSlug: "cbse-science-10",
    unitSlug: "u4-effects-of-current",
    topicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    language: "hi",
    focus: "Electricity and magnetism",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT marathon scoped to electricity, magnetic effects and domestic circuits.",
  },
  {
    videoId: "HPphkPll7Wg",
    courseSlug: "cbse-science-10",
    unitSlug: "u5-natural-resources",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "hi",
    focus: "Our environment",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of ecosystems, food chains, waste, biomagnification and ozone depletion.",
  },

  {
    videoId: "CHWhaAlo_ms",
    courseSlug: "calc-ab",
    unitSlug: "u1-limits",
    topicCodes: ["1.2", "1.5", "1.6", "1.7"],
    language: "hi",
    focus: "Limits and algebraic evaluation",
    format: "lesson",
    coverage:
      "Hindi/Hinglish Class 11 lesson reusable for basic limit notation and algebraic evaluation; not AP-specific and not continuity/asymptote coverage.",
  },
  {
    videoId: "KUu18_pkvbk",
    courseSlug: "calc-ab",
    unitSlug: "u2-differentiation",
    topicCodes: ["2.1", "2.2", "2.5", "2.6", "2.7", "2.8", "2.9", "2.10"],
    language: "hi",
    focus: "Differentiation from basics",
    format: "lesson",
    coverage:
      "Hindi/Hinglish differentiation course reusable for derivative meaning and standard rules; JEE-oriented rather than AP-specific.",
  },
  {
    videoId: "Kqmq47WOvdU",
    courseSlug: "calc-ab",
    unitSlug: "u7-diff-eqs",
    topicCodes: ["7.1", "7.2", "7.6", "7.7", "7.8"],
    language: "hi",
    focus: "Differential equations",
    format: "lesson",
    coverage:
      "Hindi/Hinglish JEE lesson reusable for modeling, verification and separable equations; slope fields are not claimed.",
  },
  {
    videoId: "oixVk-jA3vM",
    courseSlug: "calc-ab",
    unitSlug: "u6-integration",
    topicCodes: ["6.6", "6.7", "6.8", "6.9", "6.11"],
    language: "hi",
    focus: "Definite and indefinite integration",
    format: "revision",
    coverage:
      "Hindi/Hinglish JEE calculus revision reusable for integral properties, antiderivatives and substitution; not AP-specific.",
  },

  {
    videoId: "u9gWnGrWkVk",
    courseSlug: "cbse-math-9",
    unitSlug: "u2-algebra-ix",
    topicCodes: ["2.4"],
    language: "en",
    focus: "Linear equations in two variables",
    format: "lesson",
    coverage:
      "Full animated Class 9 linear-equations chapter; pairs of equations are outside its scope.",
  },
  {
    videoId: "6LBC2FnsGEw",
    courseSlug: "cbse-math-9",
    unitSlug: "u4-geometry",
    topicCodes: ["4.1"],
    language: "en",
    focus: "Euclid's geometry",
    format: "lesson",
    coverage: "Full animated introduction to Euclid's geometry.",
  },
  {
    videoId: "QS48hkxsOz4",
    courseSlug: "cbse-math-9",
    unitSlug: "u4-geometry",
    topicCodes: ["4.2"],
    language: "en",
    focus: "Lines and angles",
    format: "lesson",
    coverage: "Full animated lines-and-angles chapter.",
  },
  {
    videoId: "g0osHz73n34",
    courseSlug: "cbse-math-9",
    unitSlug: "u4-geometry",
    topicCodes: ["4.4"],
    language: "en",
    focus: "Quadrilaterals",
    format: "lesson",
    coverage: "Full animated quadrilaterals chapter.",
  },
  {
    videoId: "hsqLBpD7hMY",
    courseSlug: "cbse-math-9",
    unitSlug: "u4-geometry",
    topicCodes: ["4.5"],
    language: "en",
    focus: "Circles",
    format: "lesson",
    coverage:
      "Full animated Class 9 circles chapter covering the standard geometry results and constructions.",
  },
  {
    videoId: "QQx5EFJH08s",
    courseSlug: "cbse-math-9",
    unitSlug: "u5-mensuration",
    topicCodes: ["5.4", "5.5"],
    language: "en",
    focus: "Surface areas and volumes",
    format: "lesson",
    coverage:
      "Standard solids in the full animated chapter; pyramids and every composite extension are not claimed.",
  },
  {
    videoId: "Ol-y2HO18Kg",
    courseSlug: "cbse-math-9",
    unitSlug: "u6-statistics-probability",
    topicCodes: ["6.1", "6.2", "6.3"],
    language: "en",
    focus: "Statistics",
    format: "lesson",
    coverage:
      "English full-chapter lesson on data displays and central tendency.",
  },
  {
    videoId: "gaNXYPZXVAk",
    courseSlug: "cbse-math-9",
    unitSlug: "u6-statistics-probability",
    topicCodes: ["6.4", "6.5"],
    language: "hi",
    focus: "Introduction to probability",
    format: "lesson",
    coverage:
      "Hindi/Hinglish new-NCERT probability chapter covering experimental and introductory theoretical probability; advanced tree work may need StudyLoop practice.",
  },

  {
    videoId: "JNHjc1r-TJk",
    courseSlug: "cbse-science-9",
    unitSlug: "u1-world-of-living",
    topicCodes: ["1.2"],
    language: "en",
    focus: "Plant and animal tissues",
    format: "lesson",
    coverage:
      "Full animated Class 9 chapter on the structures and functions of plant and animal tissues.",
  },
  {
    videoId: "fsiLGhWACTw",
    courseSlug: "cbse-science-9",
    unitSlug: "u1-world-of-living",
    topicCodes: ["1.4"],
    language: "en",
    focus: "Diversity and classification",
    format: "lesson",
    coverage: "Full animated diversity-in-living-organisms chapter.",
  },
  {
    videoId: "YNNoQkw0-cA",
    courseSlug: "cbse-science-9",
    unitSlug: "u2-matter-nature-behaviour",
    topicCodes: ["2.5"],
    language: "en",
    focus: "Atoms, molecules and formulae",
    format: "lesson",
    coverage: "Formulae, molecular mass and laws of chemical combination.",
  },
  {
    videoId: "eIAne1UCz-E",
    courseSlug: "cbse-science-9",
    unitSlug: "u3-motion-force-work-sound",
    topicCodes: ["3.3"],
    language: "en",
    focus: "Force and Newton's laws",
    format: "lesson",
    coverage:
      "Full animated Force and Laws of Motion chapter; friction detail may need reinforcement.",
  },
  {
    videoId: "kS-wQsUSHsY",
    courseSlug: "cbse-science-9",
    unitSlug: "u3-motion-force-work-sound",
    topicCodes: ["3.4"],
    language: "en",
    focus: "Work and energy",
    format: "lesson",
    coverage: "Work, energy and power; not every simple-machine outcome.",
  },
  {
    videoId: "hWkxTtIOsYw",
    courseSlug: "cbse-science-9",
    unitSlug: "u3-motion-force-work-sound",
    topicCodes: ["3.5"],
    language: "en",
    focus: "Sound",
    format: "lesson",
    coverage: "Sound waves and standard applications.",
  },

  {
    videoId: "TPphmsPe4sc",
    courseSlug: "cbse-science-10",
    unitSlug: "u1-chemical-substances-nature-behaviour",
    topicCodes: ["1.2"],
    language: "en",
    focus: "Acids, bases and salts",
    format: "lesson",
    coverage: "Full animated acids, bases and salts chapter.",
  },
  {
    videoId: "3VsmMtQCaUw",
    courseSlug: "cbse-science-10",
    unitSlug: "u1-chemical-substances-nature-behaviour",
    topicCodes: ["1.3"],
    language: "en",
    focus: "Metals and non-metals",
    format: "lesson",
    coverage: "Full animated metals and non-metals chapter.",
  },
  {
    videoId: "y0NDtAjW6hc",
    courseSlug: "cbse-science-10",
    unitSlug: "u1-chemical-substances-nature-behaviour",
    topicCodes: ["1.4"],
    language: "en",
    focus: "Carbon compounds",
    format: "lesson",
    coverage: "Full animated carbon-and-its-compounds chapter.",
  },
  {
    videoId: "irzfDYMUhRY",
    courseSlug: "cbse-science-10",
    unitSlug: "u2-world-of-living",
    topicCodes: ["2.3"],
    language: "en",
    focus: "Control and coordination",
    format: "lesson",
    coverage: "Full animated control-and-coordination chapter.",
  },
  {
    videoId: "P-uHjiIiCCQ",
    courseSlug: "cbse-science-10",
    unitSlug: "u2-world-of-living",
    topicCodes: ["2.4"],
    language: "en",
    focus: "Reproduction",
    format: "lesson",
    coverage:
      "How Organisms Reproduce chapter, including standard reproductive-health concepts.",
  },
  {
    videoId: "u0QrwrR7vcw",
    courseSlug: "cbse-science-10",
    unitSlug: "u2-world-of-living",
    topicCodes: ["2.5"],
    language: "en",
    focus: "Heredity",
    format: "lesson",
    coverage:
      "Heredity and evolution chapter scoped to heredity and sex determination.",
  },
  {
    videoId: "j8JtL9yisT0",
    courseSlug: "cbse-science-10",
    unitSlug: "u3-natural-phenomena",
    topicCodes: ["3.5"],
    language: "en",
    focus: "Human eye",
    format: "lesson",
    coverage: "Human eye, prism and atmospheric colour effects.",
  },
  {
    videoId: "Ml-iZ_UNkwE",
    courseSlug: "cbse-science-10",
    unitSlug: "u4-effects-of-current",
    topicCodes: ["4.4", "4.5"],
    language: "en",
    focus: "Magnetic effects",
    format: "lesson",
    coverage:
      "Magnetic fields and standard domestic-current concepts; induction and generators are separate formative topics.",
  },
  {
    videoId: "FpzlZq_wDL4",
    courseSlug: "cbse-science-10",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.4", "F.5"],
    language: "hi",
    focus: "Electromagnetic induction and generators",
    format: "concept",
    coverage:
      "Hindi Khan Academy concept lesson on generator operation and electromagnetic induction.",
  },
  {
    videoId: "FRx5LPCmpaw",
    courseSlug: "cbse-science-10",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["Lab.1", "Lab.2", "Lab.3", "Lab.4", "Lab.5"],
    language: "hi",
    focus: "Class 10 science activities",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of important syllabus activities; use as preparation, not a replacement for supervised experiments or record work.",
  },

  {
    videoId: "pUmXQ2926sQ",
    courseSlug: "calc-ab",
    unitSlug: "u1-limits",
    topicCodes: [
      "1.1",
      "1.2",
      "1.3",
      "1.4",
      "1.5",
      "1.6",
      "1.7",
      "1.8",
      "1.9",
      "1.10",
      "1.11",
      "1.12",
      "1.13",
      "1.14",
      "1.15",
      "1.16",
    ],
    language: "en",
    focus: "AP limits and continuity review",
    format: "revision",
    coverage:
      "AP AB/BC Units 1-5 review scoped to Unit 1; concise review rather than first teaching.",
  },
  {
    videoId: "pUmXQ2926sQ",
    courseSlug: "calc-ab",
    unitSlug: "u2-differentiation",
    topicCodes: [
      "2.1",
      "2.2",
      "2.3",
      "2.4",
      "2.5",
      "2.6",
      "2.7",
      "2.8",
      "2.9",
      "2.10",
    ],
    language: "en",
    focus: "AP derivative rules review",
    format: "revision",
    coverage:
      "AP AB/BC Units 1-5 review scoped to derivative definitions and rules.",
  },
  {
    videoId: "pUmXQ2926sQ",
    courseSlug: "calc-ab",
    unitSlug: "u3-comp-implicit",
    topicCodes: ["3.1", "3.2", "3.3", "3.4", "3.5", "3.6"],
    language: "en",
    focus: "AP composite and implicit differentiation",
    format: "revision",
    coverage:
      "AP AB/BC Units 1-5 review scoped to chain, implicit, inverse and higher derivatives.",
  },
  {
    videoId: "pUmXQ2926sQ",
    courseSlug: "calc-ab",
    unitSlug: "u4-contextual-app",
    topicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5", "4.6", "4.7"],
    language: "en",
    focus: "AP contextual applications",
    format: "revision",
    coverage: "AP AB/BC Units 1-5 review scoped to Unit 4 applications.",
  },
  {
    videoId: "QWuqkiaw_UE",
    courseSlug: "calc-ab",
    unitSlug: "u8-app-integration",
    topicCodes: [
      "8.1",
      "8.2",
      "8.3",
      "8.4",
      "8.5",
      "8.6",
      "8.7",
      "8.8",
      "8.9",
      "8.10",
      "8.11",
      "8.12",
    ],
    language: "en",
    focus: "AP applications of integration",
    format: "revision",
    coverage:
      "AP AB/BC Units 6-10 review scoped to AB applications of integration; BC-only material elsewhere is outside this mapping.",
  },

  {
    videoId: "vwu8m0wI4Jw",
    courseSlug: "cbse-math-10",
    unitSlug: "u2-algebra-x",
    topicCodes: ["2.1", "2.2", "2.3", "2.4"],
    language: "en",
    focus: "Class 10 algebra summary",
    format: "revision",
    coverage:
      "English-medium all-chapter board review, scoped to polynomials, linear pairs, quadratics and arithmetic progressions.",
  },
  {
    videoId: "vwu8m0wI4Jw",
    courseSlug: "cbse-math-10",
    unitSlug: "u3-coordinate-geometry",
    topicCodes: ["3.1", "3.2", "3.3"],
    language: "en",
    focus: "Coordinate geometry summary",
    format: "revision",
    coverage:
      "English-medium board review of distance, section formula and coordinate applications.",
  },
  {
    videoId: "vwu8m0wI4Jw",
    courseSlug: "cbse-math-10",
    unitSlug: "u4-geometry",
    topicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    language: "en",
    focus: "Geometry summary",
    format: "revision",
    coverage:
      "English-medium board review of similarity, proportionality, Pythagoras and tangents.",
  },
  {
    videoId: "vwu8m0wI4Jw",
    courseSlug: "cbse-math-10",
    unitSlug: "u5-trigonometry",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "en",
    focus: "Trigonometry summary",
    format: "revision",
    coverage:
      "English-medium board review of ratios, standard values, identities and heights and distances.",
  },
  {
    videoId: "vwu8m0wI4Jw",
    courseSlug: "cbse-math-10",
    unitSlug: "u6-mensuration",
    topicCodes: ["6.1", "6.2", "6.3", "6.4", "6.5"],
    language: "en",
    focus: "Mensuration summary",
    format: "revision",
    coverage:
      "English-medium board review of circle measures and surface areas and volumes.",
  },
  {
    videoId: "vwu8m0wI4Jw",
    courseSlug: "cbse-math-10",
    unitSlug: "u7-statistics-probability",
    topicCodes: ["7.1", "7.2", "7.3", "7.4", "7.5"],
    language: "en",
    focus: "Statistics and probability summary",
    format: "revision",
    coverage:
      "English-medium board review of grouped statistics and classical probability.",
  },
  {
    videoId: "oixVk-jA3vM",
    courseSlug: "calc-ab",
    unitSlug: "u8-app-integration",
    topicCodes: ["8.4", "8.5", "8.6"],
    language: "hi",
    focus: "Areas using integration",
    format: "revision",
    coverage:
      "Hindi/Hinglish JEE calculus review reusable for areas between curves; cross-section and rotation volumes are not claimed.",
  },

  {
    videoId: "_0oeaaCKFy8",
    courseSlug: "cbse-math-9",
    unitSlug: "u2-algebra-ix",
    topicCodes: ["2.2"],
    language: "en",
    focus: "Sequences and progressions",
    format: "lesson",
    coverage:
      "Current Class 9 NCERT Explainer lesson dedicated to sequences and progressions.",
  },
  {
    videoId: "g3MbdXuTdR0",
    courseSlug: "cbse-math-9",
    unitSlug: "u2-algebra-ix",
    topicCodes: ["2.2"],
    language: "hi",
    focus: "Sequences and progressions",
    format: "lesson",
    coverage:
      "Hindi/Hinglish new-NCERT one-shot on sequences and progressions.",
  },
  {
    videoId: "6qJB9bfSMas",
    courseSlug: "cbse-math-9",
    unitSlug: "u2-algebra-ix",
    topicCodes: ["2.5"],
    language: "en",
    focus: "Pairs of linear equations",
    format: "concept",
    coverage:
      "Class 10 animated chapter reused for the pairs-of-linear-equations extension; broader and one grade above the core Class 9 chapter.",
  },
  {
    videoId: "3MIZUl6bWxY",
    courseSlug: "cbse-math-9",
    unitSlug: "u3-coordinate-geometry-ix",
    topicCodes: ["3.3", "3.4", "3.5"],
    language: "hi",
    focus: "Coordinate geometry applications",
    format: "revision",
    coverage:
      "Hindi/Hinglish complete-chapter revision useful for distance, midpoint, collinearity and mixed coordinate questions.",
  },
  {
    videoId: "R6o_TVU65sI",
    courseSlug: "cbse-math-9",
    unitSlug: "u3-coordinate-geometry-ix",
    topicCodes: ["3.3", "3.5"],
    language: "en",
    focus: "Distance formula",
    format: "concept",
    coverage:
      "English concept lesson on the distance formula and its coordinate-plane use; floor-plan modeling remains an application extension.",
  },
  {
    videoId: "WYVQjJsjhs8",
    courseSlug: "cbse-math-9",
    unitSlug: "u3-coordinate-geometry-ix",
    topicCodes: ["3.4"],
    language: "en",
    focus: "Collinearity with distance",
    format: "concept",
    coverage:
      "English worked concept lesson testing collinearity with the distance formula.",
  },
  {
    videoId: "g6SfGc9iKAc",
    courseSlug: "cbse-math-9",
    unitSlug: "u5-mensuration",
    topicCodes: ["5.1", "5.2"],
    language: "hi",
    focus: "Perimeter and area",
    format: "lesson",
    coverage:
      "Hindi/Hinglish new-NCERT chapter on perimeter and area, including circle measures.",
  },
  {
    videoId: "XcBHb3zPJxg",
    courseSlug: "cbse-math-9",
    unitSlug: "u5-mensuration",
    topicCodes: ["5.1", "5.2"],
    language: "en",
    focus: "Circle area and perimeter",
    format: "concept",
    coverage:
      "English circle-measure concept supplement; sector and arc extensions may require the worked practice in StudyLoop.",
  },
  {
    videoId: "casNoSzuma4",
    courseSlug: "cbse-science-9",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["IA.2"],
    language: "en",
    focus: "Conservation of mass practical",
    format: "lesson",
    coverage:
      "MeitY OLabs demonstration of conservation of mass; supervised lab practice and records remain necessary.",
  },
  {
    videoId: "xnh3GdKV7Pc",
    courseSlug: "cbse-science-9",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["IA.5"],
    language: "en",
    focus: "Newton's second law practical",
    format: "lesson",
    coverage:
      "MeitY OLabs verification of Newton's second law; motion-graph and IA record work are not covered.",
  },
  {
    videoId: "UW6PAdz5Ot8",
    courseSlug: "cbse-science-9",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["IA.4"],
    language: "hi",
    focus: "Energy and simple machines",
    format: "lesson",
    coverage:
      "Hindi/Hinglish chapter lesson useful for pendulum-energy and simple-machine preparation; pulse-speed practical work is separate.",
  },
  {
    videoId: "ife1FQtUrwU",
    courseSlug: "cbse-science-10",
    unitSlug: "u1-chemical-substances-nature-behaviour",
    topicCodes: ["1.5"],
    language: "en",
    focus: "pH practical",
    format: "lesson",
    coverage:
      "Grade 10 pH-paper practical demonstration; this is one component of integrated practical chemistry.",
  },
  {
    videoId: "u0QrwrR7vcw",
    courseSlug: "cbse-science-10",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.2"],
    language: "en",
    focus: "Evolution",
    format: "lesson",
    coverage:
      "The evolution portion of the original Shiksha House heredity-and-evolution chapter.",
  },
  {
    videoId: "ZgKAxgyvycE",
    courseSlug: "cbse-science-10",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.3"],
    language: "hi",
    focus: "Electric motor",
    format: "concept",
    coverage:
      "Hindi Khan Academy explanation of electric-motor principle and operation.",
  },

  {
    videoId: "n0YK4gJCLv0",
    courseSlug: "cbse-math-9",
    unitSlug: "u2-algebra-ix",
    topicCodes: ["2.5"],
    language: "hi",
    focus: "Pairs of linear equations",
    format: "revision",
    coverage:
      "Hindi/Hinglish Class 10 revision reused for the pairs-of-linear-equations extension; it is one grade above the core Class 9 material.",
  },
  {
    videoId: "lZSL7Tm5ViA",
    courseSlug: "cbse-math-9",
    unitSlug: "u6-statistics-probability",
    topicCodes: ["6.4", "6.5"],
    language: "en",
    focus: "Experimental and theoretical probability",
    format: "concept",
    coverage:
      "English probability lesson supporting experimental and theoretical probability ideas; StudyLoop supplies the table and tree applications.",
  },

  {
    videoId: "XTrxr2cxwsY",
    courseSlug: "cbse-science-9",
    unitSlug: "u1-world-of-living",
    topicCodes: ["1.3"],
    language: "en",
    focus: "Reproduction in plants and animals",
    format: "lesson",
    coverage:
      "PW Foundation English lesson on the current Class 9 reproduction chapter, including the main plant and animal processes.",
  },
  {
    videoId: "7Q4uQ15PuWE",
    courseSlug: "cbse-science-9",
    unitSlug: "u1-world-of-living",
    topicCodes: ["1.5"],
    language: "en",
    focus: "Integrated biology revision",
    format: "revision",
    coverage:
      "English full-course science marathon used only for cross-chapter biology revision across cells, tissues and diversity; practical execution remains separate.",
  },
  {
    videoId: "HTGJ58AcHYI",
    courseSlug: "cbse-science-9",
    unitSlug: "u4-earth-as-a-system",
    topicCodes: ["4.5"],
    language: "en",
    focus: "Human impact on natural cycles",
    format: "concept",
    coverage:
      "English concept lesson showing how human activity alters the nitrogen cycle; it supplements rather than completes all human-impact examples.",
  },
  {
    videoId: "WEhKjP4PUdE",
    courseSlug: "cbse-science-9",
    unitSlug: "u4-earth-as-a-system",
    topicCodes: ["4.1", "4.2", "4.3"],
    language: "hi",
    focus: "Solar radiation and differential heating",
    format: "concept",
    coverage:
      "Hindi animated lesson on solar radiation, Earth's heat balance and temperature, supporting system interactions and differential-heating concepts.",
  },
  {
    videoId: "jBCiDNwjlkM",
    courseSlug: "cbse-science-9",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["IA.1"],
    language: "en",
    focus: "Mixture separation",
    format: "lesson",
    coverage:
      "TicTacLearn English demonstration of separating mixture components; solution, suspension and colloid observations remain separate practical tasks.",
  },
  {
    videoId: "4sY1KoktMZo",
    courseSlug: "cbse-science-9",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["IA.4"],
    language: "en",
    focus: "Energy and simple machines",
    format: "lesson",
    coverage:
      "Deeksha Vedantu English chapter lesson useful for pendulum-energy and simple-machine preparation; pulse-speed measurement remains separate.",
  },
  {
    videoId: "kgjqMMj4V4g",
    courseSlug: "cbse-science-9",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["IA.2"],
    language: "hi",
    focus: "Conservation of mass",
    format: "lesson",
    coverage:
      "Hindi conservation-of-mass lesson supporting the required experiment; supervised chemical handling and laboratory records remain necessary.",
  },
  {
    videoId: "Jhtub_pPKEA",
    courseSlug: "cbse-science-9",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["IA.3"],
    language: "hi",
    focus: "Onion-peel slide",
    format: "lesson",
    coverage:
      "Hindi/Hinglish practical demonstration of preparing a stained onion-peel mount; tissue slides and specimen identification need separate practice.",
  },
  {
    videoId: "VgbDPfnUyRc",
    courseSlug: "cbse-science-9",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["IA.5"],
    language: "hi",
    focus: "Newton's second law activity",
    format: "lesson",
    coverage:
      "Hindi experiment demonstrating Newton's second law; motion-graph activities and internal-assessment record preparation remain separate.",
  },

  {
    videoId: "FRx5LPCmpaw",
    courseSlug: "cbse-science-10",
    unitSlug: "u1-chemical-substances-nature-behaviour",
    topicCodes: ["1.5"],
    language: "hi",
    focus: "Integrated practical chemistry",
    format: "revision",
    coverage:
      "Hindi/Hinglish revision of important Class 10 science activities, useful for chemistry observations but not a replacement for supervised practical work.",
  },
  {
    videoId: "kmmWoLIzv1o",
    courseSlug: "cbse-science-10",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.3"],
    language: "en",
    focus: "Electric motor",
    format: "concept",
    coverage:
      "English explanation of the electric motor's electromagnetic principle, construction and working.",
  },
  {
    videoId: "Ylgb8FFMgd4",
    courseSlug: "cbse-science-10",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.4", "F.5"],
    language: "en",
    focus: "Induction and electric generators",
    format: "concept",
    coverage:
      "Khan Academy India English explanation of electromagnetic induction and AC/DC generator operation.",
  },
  {
    videoId: "OhvoiOYsyN0",
    courseSlug: "cbse-science-10",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.1"],
    language: "hi",
    focus: "Periodic classification",
    format: "revision",
    coverage:
      "Hindi/Hinglish one-shot revision of periodic classification and the major periodic-table trends expected at Class 10 level.",
  },
  {
    videoId: "m1vfHJaaf4E",
    courseSlug: "cbse-science-10",
    unitSlug: "formative-reinforcement",
    topicCodes: ["F.2"],
    language: "hi",
    focus: "Evolution",
    format: "revision",
    coverage:
      "Hindi/Hinglish rapid revision of heredity and evolution, scoped here to the formative evolution topic.",
  },
  {
    videoId: "ife1FQtUrwU",
    courseSlug: "cbse-science-10",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["Lab.1"],
    language: "en",
    focus: "pH and indicator observations",
    format: "lesson",
    coverage:
      "English Grade 10 pH-paper practical demonstrating indicator observations; additional reaction observations require supervised laboratory work.",
  },
  {
    videoId: "2PHrJKbykVI",
    courseSlug: "cbse-science-10",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["Lab.2"],
    language: "en",
    focus: "Soap test and carbon compounds",
    format: "concept",
    coverage:
      "Khan Academy India English lesson on soaps and detergents, supplementing the soap-test component; metal and acetic-acid tests remain hands-on tasks.",
  },
  {
    videoId: "9WB82CvGIa8",
    courseSlug: "cbse-science-10",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["Lab.3"],
    language: "en",
    focus: "Ohm's law circuit",
    format: "lesson",
    coverage:
      "English board-practical demonstration of wiring an Ohm's-law circuit; series and parallel resistor trials still require supervised measurement.",
  },
  {
    videoId: "FOLDv1JLzeE",
    courseSlug: "cbse-science-10",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["Lab.4"],
    language: "en",
    focus: "Leaf-peel stomata slide",
    format: "lesson",
    coverage:
      "English practical demonstration of preparing a leaf-peel mount to observe stomata; respiration and dicot-embryo activities remain separate.",
  },
  {
    videoId: "qdN4y215c3c",
    courseSlug: "cbse-science-10",
    unitSlug: "internal-assessment-practicals",
    topicCodes: ["Lab.5"],
    language: "en",
    focus: "Focal-length practical",
    format: "lesson",
    coverage:
      "English Grade 10 focal-length experiment; glass-slab and prism tracing remain separate supervised optical practicals.",
  },
];
