import type { VideoSelection } from "@/lib/video-lessons";

// Scoped supplements for registry topics not already represented in the shared
// selection list. Chapter one-shots are labelled as revision, not first teaching.
export const MATH_SENIOR_VIDEOS: VideoSelection[] = [
  {
    videoId: "5ZhNmKb-dqk",
    courseSlug: "cbse-math-11",
    unitSlug: "u1-sets-functions",
    topicCodes: ["1.1"],
    language: "en",
    focus: "Sets, subsets and interval notation",
    format: "concept",
    coverage:
      "Set-theory foundation covering sets, subsets and notation. Use the separate set-operations clip for Venn-diagram operations.",
  },
  {
    videoId: "wbBY2tTqXDA",
    courseSlug: "cbse-math-11",
    unitSlug: "u1-sets-functions",
    topicCodes: ["1.3", "1.4"],
    language: "en",
    focus: "Relations and functions",
    format: "concept",
    coverage:
      "Introduces relations, functions, ordered-pair mappings and function notation. Detailed graph transformations and trigonometric functions are separate.",
  },
  {
    videoId: "KyOQhC8ctxc",
    courseSlug: "cbse-math-11",
    unitSlug: "u1-sets-functions",
    topicCodes: ["1.4", "1.5"],
    language: "en",
    focus: "Domains, ranges and real-valued function graphs",
    format: "lesson",
    coverage:
      "Domain and range from formulas and graphs for common real-valued function families. It is not a relations lesson.",
  },
  {
    videoId: "QPAbml1pQ0Q",
    courseSlug: "cbse-math-11",
    unitSlug: "u1-sets-functions",
    topicCodes: ["1.3", "1.4", "1.5"],
    language: "hi",
    focus: "Relations and functions",
    format: "lesson",
    coverage:
      "Current-NCERT chapter lesson on Cartesian products, relations, functions, domains, ranges and real-valued function graphs.",
  },
  {
    videoId: "m1OitPmkydY",
    courseSlug: "cbse-math-11",
    unitSlug: "u1-sets-functions",
    topicCodes: ["1.6"],
    language: "en",
    focus: "Trigonometric identities",
    format: "concept",
    coverage:
      "Core trigonometric identities and their algebraic use. Angle-sum and multiple-angle identities have separate selections.",
  },
  {
    videoId: "Vw-RwPBWS8g",
    courseSlug: "cbse-math-11",
    unitSlug: "u1-sets-functions",
    topicCodes: ["1.7"],
    language: "en",
    focus: "Graphs, periods, domains and ranges of sine and cosine",
    format: "lesson",
    coverage:
      "Graphs sine and cosine with periods, transformations, domains and ranges. The Hindi full chapter lesson supplies the broader six-function context.",
  },
  {
    videoId: "sU2pyMR8GZ4",
    courseSlug: "cbse-math-11",
    unitSlug: "u1-sets-functions",
    topicCodes: ["1.8"],
    language: "en",
    focus: "Compound-angle identities",
    format: "lesson",
    coverage:
      "Sum-and-difference identities for sine, cosine and tangent with worked examples. Product-sum manipulation is only a supporting consequence, not the sole focus.",
  },
  {
    videoId: "SE5SBTgrwH8",
    courseSlug: "cbse-math-11",
    unitSlug: "u1-sets-functions",
    topicCodes: ["1.9"],
    language: "en",
    focus: "Double-angle identities",
    format: "lesson",
    coverage:
      "Double-angle formulas for sine, cosine and tangent. Triple-angle practice remains limited and should be supplemented by the chapter lesson.",
  },
  {
    videoId: "FS3L1k6lHXQ",
    courseSlug: "cbse-math-11",
    unitSlug: "u1-sets-functions",
    topicCodes: ["1.6", "1.7", "1.8", "1.9"],
    language: "hi",
    focus: "Trigonometric functions and identities",
    format: "lesson",
    coverage:
      "Current-NCERT full chapter lesson covering trigonometric functions, graphs and ranges, and compound- and multiple-angle identities.",
  },
  {
    videoId: "1r6yLUKc8yc",
    courseSlug: "cbse-math-11",
    unitSlug: "u2-algebra-xi",
    topicCodes: ["2.2"],
    language: "hi",
    focus: "Linear inequalities",
    format: "lesson",
    coverage:
      "Full chapter lesson on solving and representing linear inequalities in one variable. It does not cover the other algebra chapters in this unit.",
  },
  {
    videoId: "DrZJKdXlZ3I",
    courseSlug: "cbse-math-11",
    unitSlug: "u2-algebra-xi",
    topicCodes: ["2.2"],
    language: "en",
    focus: "Linear inequalities",
    format: "lesson",
    coverage:
      "Solving linear inequalities and representing solutions algebraically and on a number line.",
  },
  {
    videoId: "XJnIdRXUi7A",
    courseSlug: "cbse-math-11",
    unitSlug: "u2-algebra-xi",
    topicCodes: ["2.3"],
    language: "en",
    focus: "Permutations and combinations",
    format: "lesson",
    coverage:
      "Counting, permutations and combinations with worked examples. Binomial expansion is covered separately.",
  },
  {
    videoId: "s19dWIHficY",
    courseSlug: "cbse-math-11",
    unitSlug: "u2-algebra-xi",
    topicCodes: ["2.4"],
    language: "en",
    focus: "Binomial theorem",
    format: "lesson",
    coverage:
      "Binomial expansion, Pascal's triangle, terms and coefficients with combinations-based examples.",
  },
  {
    videoId: "XZJdyPkCxuE",
    courseSlug: "cbse-math-11",
    unitSlug: "u2-algebra-xi",
    topicCodes: ["2.5"],
    language: "en",
    focus: "Arithmetic sequences and series",
    format: "lesson",
    coverage:
      "Arithmetic sequences and finite arithmetic series. Pair with the geometric-sequence portion of the Hindi chapter lesson for the complete registry topic.",
  },
  {
    videoId: "Tr-TVt5JAWY",
    courseSlug: "cbse-math-11",
    unitSlug: "u2-algebra-xi",
    topicCodes: ["2.3"],
    language: "hi",
    focus: "Permutations and combinations",
    format: "lesson",
    coverage:
      "Chapter lesson on counting principles, permutations and combinations with CBSE and JEE-oriented examples.",
  },
  {
    videoId: "j9GohkxkjGk",
    courseSlug: "cbse-math-11",
    unitSlug: "u2-algebra-xi",
    topicCodes: ["2.4"],
    language: "hi",
    focus: "Binomial theorem",
    format: "lesson",
    coverage:
      "Chapter lesson on binomial expansions and standard term-based questions. Sequences and series are not covered.",
  },
  {
    videoId: "CCWhTwyx-rc",
    courseSlug: "cbse-math-11",
    unitSlug: "u2-algebra-xi",
    topicCodes: ["2.5"],
    language: "hi",
    focus: "Sequences and series",
    format: "lesson",
    coverage:
      "Chapter lesson on sequences and series for the current Class 11 NCERT chapter. It is not mapped to permutations, combinations or binomial theorem.",
  },
  {
    videoId: "ceORkyzh6pA",
    courseSlug: "cbse-math-11",
    unitSlug: "u3-coordinate-geometry",
    topicCodes: ["3.3", "3.4"],
    language: "en",
    focus: "Geometric definitions of conic sections",
    format: "concept",
    coverage:
      "Geometric definitions and focal relationships for circles, parabolas, ellipses and hyperbolas. This is a conceptual foundation, not full CBSE equation practice.",
  },
  {
    videoId: "EzJP9uwV3ms",
    courseSlug: "cbse-math-11",
    unitSlug: "u3-coordinate-geometry",
    topicCodes: ["3.5"],
    language: "en",
    focus: "Three-dimensional coordinates",
    format: "concept",
    coverage:
      "Plots and interprets points in a three-dimensional coordinate system. This is the introductory Class 11 foundation, not Class 12 line geometry.",
  },
  {
    videoId: "5BDrdI3rdQY",
    courseSlug: "cbse-math-11",
    unitSlug: "u3-coordinate-geometry",
    topicCodes: ["3.2"],
    language: "en",
    focus: "Distance from a point to a line",
    format: "lesson",
    coverage:
      "Derives and applies point-to-line distance in coordinate geometry. The clip also mentions 3D, but this mapping is restricted to the Class 11 straight-line topic.",
  },
  {
    videoId: "kS2ydDhLaVw",
    courseSlug: "cbse-math-11",
    unitSlug: "u3-coordinate-geometry",
    topicCodes: ["3.3", "3.4"],
    language: "hi",
    focus: "Conic sections",
    format: "lesson",
    coverage:
      "Current-NCERT chapter lesson on circles, parabolas, ellipses and hyperbolas. Straight lines and introductory three-dimensional geometry are separate topics.",
  },
  {
    videoId: "bnah8aIb7CU",
    courseSlug: "cbse-math-11",
    unitSlug: "u3-coordinate-geometry",
    topicCodes: ["3.5"],
    language: "hi",
    focus: "Introduction to three-dimensional geometry",
    format: "lesson",
    coverage:
      "Class 11 introductory three-dimensional geometry chapter. Do not use it for the more advanced Class 12 line and shortest-distance topics.",
  },
  {
    videoId: "xGibYZiT5-U",
    courseSlug: "cbse-math-11",
    unitSlug: "u4-calculus-xi",
    topicCodes: ["4.1", "4.3"],
    language: "en",
    focus: "Limits and the derivative definition",
    format: "concept",
    coverage:
      "Connects limit evaluation to the standard and alternate limit definitions of a derivative. It does not cover the complete CBSE limits catalogue or all polynomial and trigonometric derivative rules.",
  },
  {
    videoId: "lvJUmabJhLE",
    courseSlug: "cbse-math-11",
    unitSlug: "u4-calculus-xi",
    topicCodes: ["4.3", "4.4"],
    language: "en",
    focus: "Derivative as tangent slope and rate of change",
    format: "concept",
    coverage:
      "Connects the limit definition of the derivative to secant and tangent slopes, instantaneous velocity and rates of change.",
  },
  {
    videoId: "HbtuSC_WOW0",
    courseSlug: "cbse-math-11",
    unitSlug: "u4-calculus-xi",
    topicCodes: ["4.2"],
    language: "en",
    focus: "Limits of trigonometric functions",
    format: "lesson",
    coverage:
      "Evaluates standard trigonometric limits. Exponential and logarithmic limit cases remain more fully covered by the Hindi chapter lesson.",
  },
  {
    videoId: "PEqCa0U77mc",
    courseSlug: "cbse-math-11",
    unitSlug: "u4-calculus-xi",
    topicCodes: ["4.5"],
    language: "en",
    focus: "Derivatives of trigonometric functions",
    format: "lesson",
    coverage:
      "Standard derivatives of trigonometric functions with worked examples. Polynomial power rules are assumed as a prerequisite.",
  },
  {
    videoId: "rXRN_8Wz5kk",
    courseSlug: "cbse-math-11",
    unitSlug: "u4-calculus-xi",
    topicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    language: "hi",
    focus: "Limits and derivatives",
    format: "lesson",
    coverage:
      "Current-NCERT chapter lesson spanning limits, the derivative definition, rate and tangent interpretations, and standard derivative rules. Use the chapter sections relevant to the current topic.",
  },
  {
    videoId: "xZELQc11ACY",
    courseSlug: "cbse-math-11",
    unitSlug: "challenge-practice",
    topicCodes: ["C11.1"],
    language: "en",
    focus: "Set-operation foundations for challenge practice",
    format: "concept",
    coverage:
      "Foundational union, intersection and Venn-diagram review for the set-algebra challenge topic. This elementary clip does not teach power-set arguments or challenge-level reasoning.",
  },
  {
    videoId: "bAHqiEESWgs",
    courseSlug: "cbse-math-11",
    unitSlug: "challenge-practice",
    topicCodes: ["C11.1"],
    language: "hi",
    focus: "Sets foundations for challenge practice",
    format: "revision",
    coverage:
      "Board-level sets recap supporting the vocabulary and operations used in the set-algebra challenge topic. It does not promise challenge-level power-set or proof practice.",
  },
  {
    videoId: "OQz1ydBcQSA",
    courseSlug: "cbse-math-11",
    unitSlug: "challenge-practice",
    topicCodes: ["C11.6"],
    language: "en",
    focus: "Complex-number foundations for challenge practice",
    format: "concept",
    coverage:
      "Complex arithmetic, standard form, conjugates and Argand-plane foundations. It supports the prerequisite layer only and does not teach challenge-level loci, roots of unity or mixed parameter reasoning.",
  },
  {
    videoId: "X6pqgXzfNDQ",
    courseSlug: "cbse-math-11",
    unitSlug: "challenge-practice",
    topicCodes: ["C11.6"],
    language: "hi",
    focus: "Complex-number revision for challenge practice",
    format: "revision",
    coverage:
      "Chapter recap supporting complex algebra, conjugates and modulus. It is foundational revision, not challenge-level instruction for loci, De Moivre powers or parameter problems.",
  },
  {
    videoId: "TePZBh0y9TI",
    courseSlug: "cbse-math-11",
    unitSlug: "challenge-practice",
    topicCodes: ["C11.1", "C11.2", "C11.3", "C11.4", "C11.5"],
    language: "en",
    focus: "JEE sets, relations and functions",
    format: "revision",
    coverage:
      "Pure-English JEE one-shot spanning set reasoning, relation properties, function domains and ranges, injectivity, composition and inverses. It supports mixed challenge practice but does not guarantee every StudyLoop question pattern.",
  },
  {
    videoId: "j9UeuYDob8Y",
    courseSlug: "cbse-math-11",
    unitSlug: "challenge-practice",
    topicCodes: ["C11.1", "C11.2", "C11.3", "C11.4", "C11.5"],
    language: "hi",
    focus: "JEE relations and functions",
    format: "revision",
    coverage:
      "JEE Main and Advanced relations-and-functions lesson supporting equivalence, domain/range, injectivity, composition, inverses and mixed reasoning. Set algebra is supporting prerequisite material rather than the sole focus.",
  },
  {
    videoId: "8EKy2Hxprrg",
    courseSlug: "cbse-math-11",
    unitSlug: "challenge-practice",
    topicCodes: ["C11.6", "C11.7", "C11.8"],
    language: "en",
    focus: "JEE complex numbers in English",
    format: "lesson",
    coverage:
      "English JEE complex-numbers one-shot supporting algebra, Argand and polar reasoning, loci, De Moivre's theorem and roots of unity. Mixed quadratic parameters are treated separately.",
  },
  {
    videoId: "sKwCHRS8zqA",
    courseSlug: "cbse-math-11",
    unitSlug: "challenge-practice",
    topicCodes: ["C11.6", "C11.7", "C11.8"],
    language: "hi",
    focus: "JEE complex numbers",
    format: "lesson",
    coverage:
      "JEE Main and Advanced complex-numbers lesson supporting algebra, Argand and polar forms, loci, De Moivre powers and roots of unity.",
  },
  {
    videoId: "reMEOAcJi7U",
    courseSlug: "cbse-math-11",
    unitSlug: "challenge-practice",
    topicCodes: ["C11.9", "C11.10"],
    language: "en",
    focus: "JEE quadratic equations in English",
    format: "lesson",
    coverage:
      "English JEE one-shot covering quadratic equations, root nature and higher-level equation reasoning. Mixed complex-quadratic questions may still require combining this with the complex-numbers selection.",
  },
  {
    videoId: "xMFg07mCutk",
    courseSlug: "cbse-math-11",
    unitSlug: "challenge-practice",
    topicCodes: ["C11.9", "C11.10"],
    language: "hi",
    focus: "JEE quadratic equations",
    format: "lesson",
    coverage:
      "JEE Main and Advanced quadratic-equations lesson supporting nature of roots, parameters and mixed reasoning. Combine with the complex-numbers lesson for questions crossing both strands.",
  },
  {
    videoId: "_dn3yUfNZKU",
    courseSlug: "cbse-math-11",
    unitSlug: "u5-statistics-probability",
    topicCodes: ["5.1", "5.2", "5.3"],
    language: "hi",
    focus: "Statistics: dispersion and standard deviation",
    format: "revision",
    coverage:
      "Chapter one-shot covering measures of dispersion, including mean deviation, variance and standard deviation for ungrouped and grouped data. Use it as revision after learning the definitions and formulas.",
  },
  {
    videoId: "Uk98hiMQgN0",
    courseSlug: "cbse-math-11",
    unitSlug: "u5-statistics-probability",
    topicCodes: ["5.1", "5.2"],
    language: "en",
    focus: "Variance and standard deviation",
    format: "lesson",
    coverage:
      "Mean, variance and standard-deviation formulas for ungrouped data. Mean deviation and grouped-data comparison receive only prerequisite support.",
  },
  {
    videoId: "x6Pnf57wRAs",
    courseSlug: "cbse-math-11",
    unitSlug: "u5-statistics-probability",
    topicCodes: ["5.3"],
    language: "en",
    focus: "Standard deviation of grouped data",
    format: "lesson",
    coverage:
      "Calculates standard deviation from grouped frequency data. Use the ungrouped-data lesson for the underlying variance formulas.",
  },
  {
    videoId: "0T-CaQCiSf4",
    courseSlug: "cbse-math-11",
    unitSlug: "u5-statistics-probability",
    topicCodes: ["5.4", "5.5"],
    language: "en",
    focus: "Sample spaces, complements and probability bounds",
    format: "concept",
    coverage:
      "Sample spaces, complementary events and probability values. Union/intersection rules are reinforced by the separate addition-rule lesson used in Class 12.",
  },
  {
    videoId: "qYqS5Ib7TxA",
    courseSlug: "cbse-math-11",
    unitSlug: "u5-statistics-probability",
    topicCodes: ["5.4", "5.5"],
    language: "hi",
    focus: "Events and axiomatic probability",
    format: "revision",
    coverage:
      "Chapter one-shot covering experiments, sample spaces, events and the axiomatic approach to probability. It is a recap, not a substitute for topic-by-topic first teaching.",
  },
  {
    videoId: "nf2id-6PrQY",
    courseSlug: "cbse-math-12",
    unitSlug: "u1-relations-functions",
    topicCodes: ["1.5", "1.6"],
    language: "hi",
    focus: "Inverse trigonometric functions",
    format: "lesson",
    coverage:
      "Current-NCERT chapter lesson on inverse trigonometric functions, principal values, identities and equations. Relations and general function properties are outside this selection.",
  },
  {
    videoId: "hrumNRQwTV8",
    courseSlug: "cbse-math-12",
    unitSlug: "u1-relations-functions",
    topicCodes: ["1.1", "1.2"],
    language: "en",
    focus: "Equivalence relations, classes and partitions",
    format: "concept",
    coverage:
      "Explains equivalence relations, equivalence classes and the induced partition of a set. Other relation properties should be reviewed from the existing chapter selection.",
  },
  {
    videoId: "jt7p-mCC0ng",
    courseSlug: "cbse-math-12",
    unitSlug: "u1-relations-functions",
    topicCodes: ["1.5"],
    language: "en",
    focus: "Inverse trigonometric functions and principal values",
    format: "lesson",
    coverage:
      "Evaluates inverse trigonometric functions using principal-value ranges and reference angles.",
  },
  {
    videoId: "waDbbpib9cM",
    courseSlug: "cbse-math-12",
    unitSlug: "u1-relations-functions",
    topicCodes: ["1.6"],
    language: "en",
    focus: "Inverse trigonometric identities",
    format: "lesson",
    coverage:
      "Uses inverse trigonometric functions with double- and half-angle identities. It supplements, rather than replaces, principal-value instruction.",
  },
  {
    videoId: "hyhktV5pxrE",
    courseSlug: "cbse-math-12",
    unitSlug: "u2-algebra",
    topicCodes: ["2.1", "2.2", "2.3", "2.4"],
    language: "hi",
    focus: "Matrices",
    format: "lesson",
    coverage:
      "Current-NCERT full chapter lesson on matrix notation, types, operations, transpose and invertible matrices. Determinants and their applications are treated separately.",
  },
  {
    videoId: "5zIK-D1DVgo",
    courseSlug: "cbse-math-12",
    unitSlug: "u2-algebra",
    topicCodes: ["2.3"],
    language: "en",
    focus: "Symmetric and skew-symmetric matrices",
    format: "concept",
    coverage:
      "Transpose-based definitions and examples of symmetric and skew-symmetric matrices.",
  },
  {
    videoId: "UHhvcj0doaA",
    courseSlug: "cbse-math-12",
    unitSlug: "u2-algebra",
    topicCodes: ["2.4", "2.7"],
    language: "en",
    focus: "Matrix equations",
    format: "lesson",
    coverage:
      "Solves matrix equations using matrix operations and inverses. Determinant-based consistency tests are outside this clip.",
  },
  {
    videoId: "3ROzG6n4yMc",
    courseSlug: "cbse-math-12",
    unitSlug: "u2-algebra",
    topicCodes: ["2.5"],
    language: "en",
    focus: "Evaluating determinants",
    format: "lesson",
    coverage:
      "Evaluation of second- and third-order determinants. Minors, cofactors and inverse applications are covered separately.",
  },
  {
    videoId: "_jHGxcX0C10",
    courseSlug: "cbse-math-12",
    unitSlug: "u2-algebra",
    topicCodes: ["2.5", "2.6"],
    language: "en",
    focus: "Minors, cofactors and determinant expansion",
    format: "lesson",
    coverage:
      "Minors, cofactors and cofactor expansion, providing the prerequisite for adjoint and inverse calculations.",
  },
  {
    videoId: "Fg7_mv3izR0",
    courseSlug: "cbse-math-12",
    unitSlug: "u2-algebra",
    topicCodes: ["2.6", "2.7"],
    language: "en",
    focus: "Inverse matrices and linear systems",
    format: "lesson",
    coverage:
      "Finds a three-by-three inverse and uses inverse-matrix reasoning. Area applications and determinant consistency cases need their chapter selections.",
  },
  {
    videoId: "6Nk8YoHgnss",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.4", "3.5"],
    language: "hi",
    focus: "Applications of derivatives",
    format: "lesson",
    coverage:
      "Chapter lesson on rate of change, increasing and decreasing functions, and maxima and minima. It assumes the core differentiation rules have already been studied.",
  },
  {
    videoId: "PEqCa0U77mc",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.2"],
    language: "en",
    focus: "Trigonometric derivative rules",
    format: "lesson",
    coverage:
      "Standard trigonometric derivatives with rule-based examples. Use the existing continuity selection and the implicit/parametric selection for adjacent topics.",
  },
  {
    videoId: "A9CR6XOuQkk",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.3"],
    language: "en",
    focus: "Implicit and second derivatives",
    format: "lesson",
    coverage:
      "Implicit differentiation through first and second derivatives, including trigonometric examples. Parametric differentiation is not the primary focus.",
  },
  {
    videoId: "WiOdQQYLMU4",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.4", "3.5"],
    language: "en",
    focus: "Applications of derivatives",
    format: "revision",
    coverage:
      "Study-guide review of derivative applications, including rates, monotonicity and extrema. It is revision rather than first teaching.",
  },
  {
    videoId: "o75AqTInKDU",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.6"],
    language: "en",
    focus: "Indefinite integrals and standard rules",
    format: "lesson",
    coverage:
      "Basic indefinite-integration rules, formulas and trigonometric antiderivatives. Advanced methods have separate clips.",
  },
  {
    videoId: "6rXByMcuAyI",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.7"],
    language: "en",
    focus: "Integration by partial fractions",
    format: "lesson",
    coverage:
      "Worked integration by partial fractions. Pair with the chapter lesson for integration by parts.",
  },
  {
    videoId: "aeB5BWY0RlE",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.8"],
    language: "en",
    focus: "Fundamental theorem of calculus",
    format: "concept",
    coverage:
      "Connects accumulation, antiderivatives and definite integrals through the fundamental theorem of calculus.",
  },
  {
    videoId: "kgg5Rspf1Js",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.9"],
    language: "en",
    focus: "Area between curves",
    format: "lesson",
    coverage:
      "Sets up and evaluates definite integrals for area between two curves with worked examples.",
  },
  {
    videoId: "C7nuJcJriWM",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.10"],
    language: "en",
    focus: "Separable differential equations",
    format: "lesson",
    coverage:
      "Introduces first-order separable differential equations and their solutions. Formation, order and degree remain supported by the Hindi full chapter lesson.",
  },
  {
    videoId: "hXOrQ0Ao4UE",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.6", "3.7", "3.8"],
    language: "hi",
    focus: "Indefinite and definite integration",
    format: "lesson",
    coverage:
      "Class 12 integration chapter lesson covering standard indefinite methods and definite integrals. Applications of integrals and differential equations have separate selections.",
  },
  {
    videoId: "qEU2oKUNosA",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.9"],
    language: "hi",
    focus: "Applications of integrals",
    format: "lesson",
    coverage:
      "Chapter lesson on using definite integrals to find areas. It does not replace the preceding integration-method lessons.",
  },
  {
    videoId: "HzUPPCfcw64",
    courseSlug: "cbse-math-12",
    unitSlug: "u3-calculus",
    topicCodes: ["3.10"],
    language: "hi",
    focus: "Differential equations",
    format: "lesson",
    coverage:
      "Class 12 chapter lesson on order and degree, forming differential equations and standard solution methods in the NCERT scope.",
  },
  {
    videoId: "uZHMmMeNySo",
    courseSlug: "cbse-math-12",
    unitSlug: "u4-vectors-3d",
    topicCodes: ["4.1", "4.2", "4.3", "4.4"],
    language: "hi",
    focus: "Vector algebra",
    format: "lesson",
    coverage:
      "Vector basics, components, direction cosines, addition, section formula, scalar product, projections, vector product and area. Three-dimensional line geometry is not covered by this selection.",
  },
  {
    videoId: "QgBLda_lXhU",
    courseSlug: "cbse-math-12",
    unitSlug: "u4-vectors-3d",
    topicCodes: ["4.5", "4.6", "4.7"],
    language: "en",
    focus: "Three-dimensional line geometry",
    format: "revision",
    coverage:
      "A compact Class 12 recap with simple problems on three-dimensional geometry. Use it to refresh line forms and standard methods; it does not teach vector algebra or promise exhaustive shortest-distance practice.",
  },
  {
    videoId: "NEj70xMyRIk",
    courseSlug: "cbse-math-12",
    unitSlug: "u4-vectors-3d",
    topicCodes: ["4.1", "4.2", "4.3", "4.4"],
    language: "hi",
    focus: "Vector algebra",
    format: "lesson",
    coverage:
      "NCERT vector algebra chapter lesson covering components and direction cosines, vector operations, section formula, scalar product, vector product and area.",
  },
  {
    videoId: "ZoCxUV893fo",
    courseSlug: "cbse-math-12",
    unitSlug: "u4-vectors-3d",
    topicCodes: ["4.1"],
    language: "en",
    focus: "Direction cosines and direction angles",
    format: "concept",
    coverage:
      "Direction cosines and angles of a vector, supporting the component and magnitude foundations in this topic.",
  },
  {
    videoId: "xS-gdFgZel0",
    courseSlug: "cbse-math-12",
    unitSlug: "u4-vectors-3d",
    topicCodes: ["4.2"],
    language: "en",
    focus: "Vector addition by components",
    format: "concept",
    coverage:
      "Adds vectors by components. Section-formula practice is not the main focus and is covered more fully in the Hindi chapter lesson.",
  },
  {
    videoId: "VzX8KJKFhlM",
    courseSlug: "cbse-math-12",
    unitSlug: "u4-vectors-3d",
    topicCodes: ["4.3"],
    language: "en",
    focus: "Dot products, projections and angles",
    format: "lesson",
    coverage:
      "Dot product calculations and their angle interpretation, with projection foundations.",
  },
  {
    videoId: "pWbOisq1MJU",
    courseSlug: "cbse-math-12",
    unitSlug: "u4-vectors-3d",
    topicCodes: ["4.4"],
    language: "en",
    focus: "Cross products and area",
    format: "lesson",
    coverage:
      "Cross-product computation and geometric interpretation. Triangle and parallelogram area follow from the magnitude interpretation.",
  },
  {
    videoId: "jCluGlqH70M",
    courseSlug: "cbse-math-12",
    unitSlug: "u4-vectors-3d",
    topicCodes: ["4.5", "4.6", "4.7"],
    language: "hi",
    focus: "Three-dimensional line geometry",
    format: "lesson",
    coverage:
      "NCERT three-dimensional geometry chapter lesson on line forms, angles, skew lines and shortest distance. Vector algebra foundations are covered separately.",
  },
  {
    videoId: "wEkEihCorHw",
    courseSlug: "cbse-math-12",
    unitSlug: "u5-linear-programming",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "hi",
    focus: "Linear programming",
    format: "lesson",
    coverage:
      "Chapter one-shot on objectives and constraints, graphical feasible regions, corner-point optimisation, solution cases and standard applications.",
  },
  {
    videoId: "Bzzqx1F23a8",
    courseSlug: "cbse-math-12",
    unitSlug: "u5-linear-programming",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "en",
    focus: "Linear programming by the graphical method",
    format: "lesson",
    coverage:
      "Introduces objectives and constraints, graphical feasible regions and corner-point optimisation with applications. Use the chapter lesson for the full range of bounded, unbounded and multiple-optimum cases.",
  },
  {
    videoId: "OByl4RJxnKA",
    courseSlug: "cbse-math-12",
    unitSlug: "u6-probability",
    topicCodes: ["6.1", "6.4", "6.5"],
    language: "en",
    focus: "Bayes' theorem with tree and Venn diagrams",
    format: "concept",
    coverage:
      "Introduces Bayes' theorem through conditional probability examples, tree diagrams and Venn diagrams. Multiplication rules and independence need separate study.",
  },
  {
    videoId: "94AmzeR9n2w",
    courseSlug: "cbse-math-12",
    unitSlug: "u6-probability",
    topicCodes: ["6.2", "6.3"],
    language: "en",
    focus: "Multiplication rules and independent events",
    format: "lesson",
    coverage:
      "Addition and multiplication rules with mutually exclusive and independent events. Conditional probability and Bayes' theorem have separate selections.",
  },
  {
    videoId: "vO9zVl0fXZA",
    courseSlug: "cbse-math-12",
    unitSlug: "u6-probability",
    topicCodes: ["6.1", "6.2", "6.3", "6.4", "6.5"],
    language: "hi",
    focus: "Conditional probability and Bayes' theorem",
    format: "lesson",
    coverage:
      "Class 12 probability chapter lesson spanning conditional probability, multiplication theorem, independent events, total probability and Bayes' theorem.",
  },
  {
    videoId: "U4j8Pw4hV5U",
    courseSlug: "cbse-math-12",
    unitSlug: "u2-algebra",
    topicCodes: ["2.5", "2.6", "2.7"],
    language: "hi",
    focus: "Determinants and matrix applications",
    format: "revision",
    coverage:
      "Determinant evaluation and properties, area of a triangle, minors and cofactors, adjoint and inverse, and solving linear systems. Basic matrix notation and operations are outside this selection.",
  },
  {
    videoId: "U4j8Pw4hV5U",
    courseSlug: "cbse-math-12",
    unitSlug: "challenge-practice",
    topicCodes: ["C12.2", "C12.3", "C12.4", "C12.5"],
    language: "hi",
    focus: "Determinant foundations for challenge practice",
    format: "revision",
    coverage:
      "Foundational determinant, adjoint, inverse and linear-system revision that supports these challenge topics. The clip is not challenge-level teaching and does not cover the full difficulty or parameter reasoning of StudyLoop challenge questions.",
  },
  {
    videoId: "vzt9c7iWPxs",
    courseSlug: "cbse-math-12",
    unitSlug: "challenge-practice",
    topicCodes: ["C12.1"],
    language: "en",
    focus: "Matrix-operation foundations for challenge practice",
    format: "concept",
    coverage:
      "Foundational matrix order and multiplication practice for the matrix-algebra challenge topic. It does not cover matrix powers or challenge-level deductions.",
  },
  {
    videoId: "4e4xqoYdylo",
    courseSlug: "cbse-math-12",
    unitSlug: "challenge-practice",
    topicCodes: ["C12.1"],
    language: "hi",
    focus: "Matrices revision for challenge practice",
    format: "revision",
    coverage:
      "Board-level matrices recap supporting types and operations in the challenge unit. It does not promise challenge-level matrix powers or mixed reasoning.",
  },
  {
    videoId: "K-thBCPDqaY",
    courseSlug: "cbse-math-12",
    unitSlug: "challenge-practice",
    topicCodes: ["C12.1"],
    language: "en",
    focus: "JEE matrices in pure English",
    format: "lesson",
    coverage:
      "Pure-English JEE matrices one-shot supporting matrix types, algebra and powers. Determinant properties and system consistency are covered separately.",
  },
  {
    videoId: "fsmiRRcj_nw",
    courseSlug: "cbse-math-12",
    unitSlug: "challenge-practice",
    topicCodes: ["C12.2", "C12.3", "C12.4", "C12.5"],
    language: "en",
    focus: "JEE determinants in pure English",
    format: "lesson",
    coverage:
      "Pure-English JEE determinants one-shot supporting determinant properties, adjoint and inverse, linear-system consistency and parameter-based applications. It supplements the matrix-algebra selection.",
  },
  {
    videoId: "jr_DqbNC_dI",
    courseSlug: "cbse-math-12",
    unitSlug: "challenge-practice",
    topicCodes: ["C12.1", "C12.2", "C12.3", "C12.4", "C12.5"],
    language: "hi",
    focus: "JEE matrices and determinants",
    format: "revision",
    coverage:
      "JEE Main revision spanning matrix algebra and powers, determinant properties, adjoint and inverse, systems and mixed applications. It does not imply complete coverage of every advanced parameter pattern.",
  },
];
