import type { VideoSelection } from "@/lib/video-lessons";

// Optional chapter supplements from original creator uploads. Practical videos,
// when present, are demonstrations only and do not replace supervised lab work.
export const PHYSICS_SENIOR_VIDEOS: VideoSelection[] = [
  {
    videoId: "v1_PvRIykCs",
    courseSlug: "cbse-physics-11",
    unitSlug: "u1-physical-world-measurement",
    topicCodes: ["1.1", "1.2", "1.3", "1.4", "1.5"],
    language: "en",
    focus: "Units and measurements",
    format: "lesson",
    coverage:
      "Shiksha House chapter lesson on units, errors, significant figures and dimensions; use current StudyLoop scope for assessed details.",
  },
  {
    videoId: "hzIP3ECrGJo",
    courseSlug: "cbse-physics-11",
    unitSlug: "u2-kinematics",
    topicCodes: ["2.1", "2.2"],
    language: "en",
    focus: "Motion in a straight line",
    format: "lesson",
    coverage:
      "Position, displacement, velocity, acceleration, equations of motion and motion graphs; plane motion is covered separately.",
  },
  {
    videoId: "DLjgka69URU",
    courseSlug: "cbse-physics-11",
    unitSlug: "u2-kinematics",
    topicCodes: ["2.3", "2.4", "2.5"],
    language: "en",
    focus: "Motion in a plane",
    format: "lesson",
    coverage:
      "Vectors, projectile motion and uniform circular motion in the NCERT motion-in-a-plane chapter.",
  },
  {
    videoId: "RX1B67J88NQ",
    courseSlug: "cbse-physics-11",
    unitSlug: "u3-laws-of-motion",
    topicCodes: ["3.1", "3.2", "3.3", "3.4", "3.5"],
    language: "en",
    focus: "Laws of motion",
    format: "lesson",
    coverage:
      "Newton's laws, momentum, equilibrium, friction and circular-motion applications in one chapter lesson.",
  },
  {
    videoId: "vqVAOthL8f0",
    courseSlug: "cbse-physics-11",
    unitSlug: "u4-work-energy-power",
    topicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    language: "en",
    focus: "Work, energy and power",
    format: "lesson",
    coverage:
      "Work-energy theorem, power, potential energy, conservation and collisions in the NCERT chapter sequence.",
  },
  {
    videoId: "mR_6KPV2Zjk",
    courseSlug: "cbse-physics-11",
    unitSlug: "u5-system-particles-rigid-body",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "en",
    focus: "Systems of particles and rotational motion",
    format: "lesson",
    coverage:
      "Centre of mass, torque, angular momentum, rotational dynamics and moment of inertia as a chapter lesson.",
  },
  {
    videoId: "J2-PpzuaacE",
    courseSlug: "cbse-physics-11",
    unitSlug: "u6-gravitation",
    topicCodes: ["6.1", "6.2", "6.3", "6.4", "6.5"],
    language: "en",
    focus: "Gravitation",
    format: "lesson",
    coverage:
      "Gravitation, variation of g, potential, satellites and escape speed in the NCERT chapter sequence.",
  },
  {
    videoId: "5wHjxNSPouQ",
    courseSlug: "cbse-physics-11",
    unitSlug: "u7-properties-bulk-matter",
    topicCodes: ["7.1"],
    language: "en",
    focus: "Mechanical properties of solids",
    format: "lesson",
    coverage:
      "Stress, strain, elastic moduli and stress-strain behaviour; fluid and thermal properties are separate lessons.",
  },
  {
    videoId: "Tdn_NkQFF3M",
    courseSlug: "cbse-physics-11",
    unitSlug: "u7-properties-bulk-matter",
    topicCodes: ["7.2", "7.3", "7.4"],
    language: "en",
    focus: "Mechanical properties of fluids",
    format: "lesson",
    coverage:
      "Fluid pressure, buoyancy, continuity, Bernoulli's principle, viscosity and surface tension; thermal properties are separate.",
  },
  {
    videoId: "hz22apRERW0",
    courseSlug: "cbse-physics-11",
    unitSlug: "u7-properties-bulk-matter",
    topicCodes: ["7.5"],
    language: "en",
    focus: "Thermal properties of matter",
    format: "lesson",
    coverage:
      "Thermal expansion, calorimetry, phase change and heat transfer in the NCERT chapter sequence.",
  },
  {
    videoId: "Wg6kTB3yYjM",
    courseSlug: "cbse-physics-11",
    unitSlug: "u8-thermodynamics",
    topicCodes: ["8.1", "8.2", "8.3", "8.4", "8.5"],
    language: "en",
    focus: "Thermodynamics",
    format: "lesson",
    coverage:
      "Thermal equilibrium, thermodynamic processes, P-V work and the first and second laws in one chapter lesson.",
  },
  {
    videoId: "3yTCXDYGSpI",
    courseSlug: "cbse-physics-11",
    unitSlug: "u9-kinetic-theory",
    topicCodes: ["9.1", "9.2", "9.3", "9.4", "9.5"],
    language: "en",
    focus: "Kinetic theory of gases",
    format: "lesson",
    coverage:
      "Perfect-gas equation, molecular model, rms speed, equipartition and mean free path in the NCERT chapter sequence.",
  },
  {
    videoId: "JH7kBhlHNoE",
    courseSlug: "cbse-physics-11",
    unitSlug: "u10-oscillations-waves",
    topicCodes: ["10.1", "10.2"],
    language: "en",
    focus: "Oscillations",
    format: "lesson",
    coverage:
      "Periodic motion, SHM, spring and pendulum oscillations and SHM energy; travelling and standing waves are not covered.",
  },
  {
    videoId: "8F4c62h4Xkg",
    courseSlug: "cbse-physics-12",
    unitSlug: "u1-electrostatics",
    topicCodes: ["1.1", "1.2"],
    language: "en",
    focus: "Electric charges and fields, part 1",
    format: "lesson",
    coverage:
      "Charge, Coulomb's law, superposition and the introductory electric-field material; continue with part 2 for flux and Gauss's law.",
  },
  {
    videoId: "UEXEHi42_kg",
    courseSlug: "cbse-physics-12",
    unitSlug: "u1-electrostatics",
    topicCodes: ["1.2", "1.3"],
    language: "en",
    focus: "Electric charges and fields, part 2",
    format: "lesson",
    coverage:
      "Continuation covering electric-field applications, dipoles, flux and Gauss's law; potential and capacitance are separate lessons.",
  },
  {
    videoId: "Bfl7sfmNYeo",
    courseSlug: "cbse-physics-12",
    unitSlug: "u1-electrostatics",
    topicCodes: ["1.4", "1.5"],
    language: "en",
    focus: "Electrostatic potential and capacitance, part 1",
    format: "lesson",
    coverage:
      "Electrostatic potential, potential energy, equipotentials and the beginning of capacitance; continue with part 2 for capacitor applications.",
  },
  {
    videoId: "qz5RRFT23Qk",
    courseSlug: "cbse-physics-12",
    unitSlug: "u1-electrostatics",
    topicCodes: ["1.5"],
    language: "en",
    focus: "Electrostatic potential and capacitance, part 2",
    format: "lesson",
    coverage:
      "Continuation of capacitance, capacitor combinations, dielectric effects and stored energy.",
  },
  {
    videoId: "m4N8CPjHN3Q",
    courseSlug: "cbse-physics-12",
    unitSlug: "u2-current-electricity",
    topicCodes: ["2.1", "2.2", "2.3", "2.4", "2.5"],
    language: "en",
    focus: "Current electricity",
    format: "lesson",
    coverage:
      "Drift, Ohm's law, resistivity, cells, Kirchhoff's rules and bridge circuits in one NCERT chapter lesson.",
  },
  {
    videoId: "K2OYkQqZ01Q",
    courseSlug: "cbse-physics-12",
    unitSlug: "u3-magnetic-effects-current-magnetism",
    topicCodes: ["3.1", "3.2", "3.3", "3.4"],
    language: "en",
    focus: "Moving charges and magnetism",
    format: "lesson",
    coverage:
      "Fields due to currents, Lorentz force, force on conductors, current loops and galvanometer applications; magnetic materials are separate.",
  },
  {
    videoId: "RL0p9vXbdYI",
    courseSlug: "cbse-physics-12",
    unitSlug: "u3-magnetic-effects-current-magnetism",
    topicCodes: ["3.5"],
    language: "en",
    focus: "Magnetism and matter",
    format: "lesson",
    coverage:
      "Bar magnets, magnetic field lines, magnetisation and magnetic materials in the NCERT chapter sequence.",
  },
  {
    videoId: "LlUqU81NnIs",
    courseSlug: "cbse-physics-12",
    unitSlug: "u4-electromagnetic-induction-alternating-currents",
    topicCodes: ["4.1", "4.2", "4.3"],
    language: "en",
    focus: "Electromagnetic induction",
    format: "lesson",
    coverage:
      "Flux, Faraday's and Lenz's laws, motional emf, eddy currents and induction; alternating-current circuits are separate.",
  },
  {
    videoId: "PnnFhvjJ7Xw",
    courseSlug: "cbse-physics-12",
    unitSlug: "u4-electromagnetic-induction-alternating-currents",
    topicCodes: ["4.4", "4.5"],
    language: "en",
    focus: "Alternating current",
    format: "lesson",
    coverage:
      "RMS values, reactance, impedance, LCR resonance, AC power, generator and transformer topics.",
  },
  {
    videoId: "PDRKP4b7tJE",
    courseSlug: "cbse-physics-12",
    unitSlug: "u5-electromagnetic-waves",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "en",
    focus: "Electromagnetic waves",
    format: "lesson",
    coverage:
      "Displacement current, production and nature of electromagnetic waves, spectrum order and common uses.",
  },
  {
    videoId: "ALC0WDdbnsk",
    courseSlug: "cbse-physics-12",
    unitSlug: "u6-optics",
    topicCodes: ["6.1", "6.2"],
    language: "en",
    focus: "Ray optics, part 1",
    format: "lesson",
    coverage:
      "Reflection, refraction and lens foundations; continue with part 2 for prism and optical instruments.",
  },
  {
    videoId: "RNgPpwfVYM4",
    courseSlug: "cbse-physics-12",
    unitSlug: "u6-optics",
    topicCodes: ["6.2", "6.3", "6.4"],
    language: "en",
    focus: "Ray optics, part 2",
    format: "lesson",
    coverage:
      "Continuation of lenses plus prism, total internal reflection and optical instruments; wave optics is separate.",
  },
  {
    videoId: "u30W5ipiQL8",
    courseSlug: "cbse-physics-12",
    unitSlug: "u6-optics",
    topicCodes: ["6.5"],
    language: "en",
    focus: "Wave optics",
    format: "lesson",
    coverage:
      "Huygens' principle, interference, Young's double-slit experiment and qualitative diffraction.",
  },
  {
    videoId: "3RoTS5DM-fk",
    courseSlug: "cbse-physics-12",
    unitSlug: "u7-dual-nature-radiation-matter",
    topicCodes: ["7.1", "7.2", "7.3", "7.4", "7.5"],
    language: "en",
    focus: "Dual nature of radiation and matter",
    format: "lesson",
    coverage:
      "Photon energy, photoelectric observations and equation, graphs and de Broglie matter waves.",
  },
  {
    videoId: "mIqlLELb_dA",
    courseSlug: "cbse-physics-12",
    unitSlug: "u8-atoms-nuclei",
    topicCodes: ["8.1", "8.2", "8.3"],
    language: "en",
    focus: "Atoms",
    format: "lesson",
    coverage:
      "Rutherford scattering, Bohr's hydrogen model and energy-level spectra; nuclear physics is separate.",
  },
  {
    videoId: "H_1Au9yVl1M",
    courseSlug: "cbse-physics-12",
    unitSlug: "u8-atoms-nuclei",
    topicCodes: ["8.4", "8.5"],
    language: "en",
    focus: "Nuclei",
    format: "lesson",
    coverage:
      "Nuclear composition and size, mass defect, binding energy, fission and fusion.",
  },
  {
    videoId: "FdjTjiKiGkE",
    courseSlug: "cbse-physics-12",
    unitSlug: "u9-electronic-devices",
    topicCodes: ["9.1", "9.2", "9.3"],
    language: "en",
    focus: "Semiconductor electronics, part 1",
    format: "lesson",
    coverage:
      "Energy bands, intrinsic and extrinsic semiconductors and p-n junction foundations; continue with part 2 for diode applications.",
  },
  {
    videoId: "2C0WLYlYxmA",
    courseSlug: "cbse-physics-12",
    unitSlug: "u9-electronic-devices",
    topicCodes: ["9.3", "9.4", "9.5"],
    language: "en",
    focus: "Semiconductor electronics, part 2",
    format: "lesson",
    coverage:
      "Continuation of p-n junction behaviour, diode I-V characteristics and rectifier action; follow the current syllabus scope.",
  },
  {
    videoId: "-t7wCNnJATc",
    courseSlug: "cbse-physics-11",
    unitSlug: "u3-laws-of-motion",
    topicCodes: ["3.1", "3.2", "3.3", "3.4", "3.5"],
    language: "hi",
    focus: "Laws of motion full-chapter practice",
    format: "revision",
    coverage:
      "Hindi/Hinglish full-chapter one-shot with concepts and practice across Newton's laws, momentum conservation, equilibrium, friction and circular dynamics.",
  },
  {
    videoId: "_Yp0Jq_b3kM",
    courseSlug: "cbse-physics-11",
    unitSlug: "u8-thermodynamics",
    topicCodes: ["8.1", "8.2", "8.3", "8.4", "8.5"],
    language: "hi",
    focus: "Thermodynamics",
    format: "lesson",
    coverage:
      "Hindi/Hinglish board lesson with chapters for state variables, zeroth and first laws, P-V work, thermodynamic processes and the second law.",
  },
  {
    videoId: "5ppdT-dsC4Y",
    courseSlug: "cbse-physics-12",
    unitSlug: "u1-electrostatics",
    topicCodes: ["1.4", "1.5"],
    language: "hi",
    focus: "Potential and capacitance",
    format: "revision",
    coverage:
      "Ten-minute Hindi/Hinglish formula recap of potential, capacitance, parallel-plate factors and stored energy; use after first teaching.",
  },
  {
    videoId: "j5wR8pfqyh4",
    courseSlug: "cbse-physics-12",
    unitSlug: "u4-electromagnetic-induction-alternating-currents",
    topicCodes: ["4.4", "4.5"],
    language: "hi",
    focus: "Alternating current",
    format: "revision",
    coverage:
      "Hindi/Hinglish board one-shot covering RMS values, phase, LCR circuits, resonance and AC power; electromagnetic induction is separate.",
  },
  {
    videoId: "V3JXWwBXv-4",
    courseSlug: "cbse-physics-12",
    unitSlug: "u6-optics",
    topicCodes: ["6.1", "6.2", "6.3", "6.4"],
    language: "hi",
    focus: "Ray optics and optical instruments",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT revision of reflection, refraction, mirrors, lenses, prisms, total internal reflection and optical instruments.",
  },
  {
    videoId: "yY6ChKn7thM",
    courseSlug: "cbse-physics-12",
    unitSlug: "u6-optics",
    topicCodes: ["6.5"],
    language: "hi",
    focus: "Wave optics",
    format: "revision",
    coverage:
      "Hindi/Hinglish board one-shot on Huygens' principle, YDSE, interference and diffraction; it may discuss polarisation beyond current StudyLoop scope.",
  },
  {
    videoId: "7naR68Z6xEs",
    courseSlug: "cbse-physics-12",
    unitSlug: "u7-dual-nature-radiation-matter",
    topicCodes: ["7.1", "7.2", "7.3", "7.4", "7.5"],
    language: "hi",
    focus: "Dual nature of radiation and matter",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT revision of the photoelectric effect, Einstein's equation, graphs and de Broglie wavelength.",
  },
  {
    videoId: "v16hdgJ9rag",
    courseSlug: "cbse-physics-11",
    unitSlug: "practicals-activities",
    topicCodes: ["Lab.4"],
    language: "en",
    focus: "Resonance tube demonstration",
    format: "concept",
    coverage:
      "Demonstrates resonance positions and speed-of-sound reasoning. Watch as preparation only; perform apparatus setup and readings under lab supervision.",
  },
  {
    videoId: "0WeXmbdYsyY",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.1", "Lab.6"],
    language: "hi",
    focus: "Meter bridge experiment and viva",
    format: "lesson",
    coverage:
      "Hindi/Hinglish step-by-step meter-bridge demonstration covering circuit checks, readings, calculations, errors and viva. Perform the experiment only under lab supervision.",
  },
  {
    videoId: "FXF1iW7ntig",
    courseSlug: "cbse-physics-11",
    unitSlug: "u10-oscillations-waves",
    topicCodes: ["10.3", "10.4", "10.5"],
    language: "en",
    focus: "Travelling waves, standing waves and beats",
    format: "lesson",
    coverage:
      "English-medium foundation lesson on the Class 11 Waves chapter, including progressive waves, superposition, standing waves, harmonics and beats.",
  },
  {
    videoId: "dhNhg9t3Lhw",
    courseSlug: "cbse-physics-11",
    unitSlug: "u4-work-energy-power",
    topicCodes: ["4.1", "4.2", "4.3", "4.4", "4.5"],
    language: "hi",
    focus: "Work, energy and power",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT one-shot with derivations and board practice across work, energy, power, conservation, vertical circular motion and collisions.",
  },
  {
    videoId: "nwV_ADaD1Dk",
    courseSlug: "cbse-physics-11",
    unitSlug: "u5-system-particles-rigid-body",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "hi",
    focus: "System of particles and rotational motion",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT one-shot with derivations and board practice on centre of mass, torque, angular momentum, rotational dynamics and moment of inertia.",
  },
  {
    videoId: "-jJgjcF3TVI",
    courseSlug: "cbse-physics-11",
    unitSlug: "u6-gravitation",
    topicCodes: ["6.1", "6.2", "6.3", "6.4", "6.5"],
    language: "hi",
    focus: "Gravitation",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT one-shot with derivations and board practice on gravitation, variation of g, potential, escape speed and satellites.",
  },
  {
    videoId: "ZwD4CoXKEUk",
    courseSlug: "cbse-physics-11",
    unitSlug: "u7-properties-bulk-matter",
    topicCodes: ["7.1"],
    language: "hi",
    focus: "Mechanical properties of solids",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT one-shot on elasticity, stress, strain, elastic moduli and stress-strain behaviour; fluids and thermal properties are separate.",
  },
  {
    videoId: "6aS6LcLU8hM",
    courseSlug: "cbse-physics-11",
    unitSlug: "u7-properties-bulk-matter",
    topicCodes: ["7.2", "7.3", "7.4"],
    language: "hi",
    focus: "Mechanical properties of fluids",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT one-shot on pressure, buoyancy, continuity, Bernoulli's principle, viscosity and surface tension.",
  },
  {
    videoId: "43KARHMMW_w",
    courseSlug: "cbse-physics-11",
    unitSlug: "u7-properties-bulk-matter",
    topicCodes: ["7.5"],
    language: "hi",
    focus: "Thermal properties of matter",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT one-shot on thermal expansion, calorimetry, phase change and heat transfer.",
  },
  {
    videoId: "k4FvOpHU0jo",
    courseSlug: "cbse-physics-11",
    unitSlug: "u9-kinetic-theory",
    topicCodes: ["9.1", "9.2", "9.3", "9.4", "9.5"],
    language: "hi",
    focus: "Kinetic theory of gases",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT one-shot with derivations on the perfect-gas model, pressure, rms speed, equipartition and mean free path.",
  },
  {
    videoId: "n0cEcXWPFCU",
    courseSlug: "cbse-physics-11",
    unitSlug: "u10-oscillations-waves",
    topicCodes: ["10.1", "10.2"],
    language: "hi",
    focus: "Oscillations",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT one-shot on periodic motion, SHM, phase, spring and pendulum oscillations and SHM energy.",
  },
  {
    videoId: "p3vMfyGjfcM",
    courseSlug: "cbse-physics-11",
    unitSlug: "u10-oscillations-waves",
    topicCodes: ["10.3", "10.4", "10.5"],
    language: "hi",
    focus: "Waves",
    format: "revision",
    coverage:
      "Hindi/Hinglish full-chapter one-shot on progressive waves, superposition, reflection, standing waves, harmonics and beats.",
  },
  {
    videoId: "lWbUXCr3FOk",
    courseSlug: "cbse-physics-12",
    unitSlug: "u3-magnetic-effects-current-magnetism",
    topicCodes: ["3.5"],
    language: "hi",
    focus: "Magnetism and matter",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT revision of bar magnets, field lines, magnetic materials, magnetisation and temperature effects.",
  },
  {
    videoId: "GaLQhuyaUNg",
    courseSlug: "cbse-physics-12",
    unitSlug: "u4-electromagnetic-induction-alternating-currents",
    topicCodes: ["4.1", "4.2", "4.3"],
    language: "hi",
    focus: "Electromagnetic induction",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT revision of flux, Faraday's and Lenz's laws, motional emf, eddy currents, self-induction and mutual induction.",
  },
  {
    videoId: "NsO6M28xPTs",
    courseSlug: "cbse-physics-12",
    unitSlug: "u5-electromagnetic-waves",
    topicCodes: ["5.1", "5.2", "5.3", "5.4", "5.5"],
    language: "hi",
    focus: "Electromagnetic waves",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT revision of displacement current, origin and transverse nature of electromagnetic waves, the spectrum and uses.",
  },
  {
    videoId: "YuU3gaY34dI",
    courseSlug: "cbse-physics-12",
    unitSlug: "u8-atoms-nuclei",
    topicCodes: ["8.1", "8.2", "8.3", "8.4", "8.5"],
    language: "hi",
    focus: "Atoms and nuclei",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT revision of Rutherford and Bohr models, hydrogen spectra, nuclear composition, binding energy, fission and fusion.",
  },
  {
    videoId: "XGc2OCsjIdk",
    courseSlug: "cbse-physics-12",
    unitSlug: "u9-electronic-devices",
    topicCodes: ["9.1", "9.2", "9.3", "9.4", "9.5"],
    language: "hi",
    focus: "Semiconductor electronics",
    format: "revision",
    coverage:
      "Hindi/Hinglish NCERT revision of energy bands, intrinsic and extrinsic semiconductors, p-n junction biasing, diode characteristics and rectifiers.",
  },
  {
    videoId: "11EM0nZUdqE",
    courseSlug: "cbse-physics-11",
    unitSlug: "practicals-activities",
    topicCodes: ["Lab.1"],
    language: "en",
    focus: "Screw gauge principle and apparatus",
    format: "concept",
    coverage:
      "English apparatus introduction to screw-gauge pitch and least count. It supplements, but does not replace, supervised readings, zero correction and uncertainty work.",
  },
  {
    videoId: "fowRMegIFvw",
    courseSlug: "cbse-physics-11",
    unitSlug: "practicals-activities",
    topicCodes: ["Lab.2"],
    language: "en",
    focus: "Parallelogram law of vectors",
    format: "concept",
    coverage:
      "MeitY OLabs demonstration of one mechanics experiment in this cluster. Set up weights and verify equilibrium only under lab supervision.",
  },
  {
    videoId: "WMQZWBi7fbE",
    courseSlug: "cbse-physics-11",
    unitSlug: "practicals-activities",
    topicCodes: ["Lab.3"],
    language: "en",
    focus: "Young's modulus experiment",
    format: "concept",
    coverage:
      "MeitY OLabs demonstration of Young's modulus as one elasticity experiment; fluid and thermal experiments in this cluster need separate supervised practice.",
  },
  {
    videoId: "pH-72pQDsWA",
    courseSlug: "cbse-physics-11",
    unitSlug: "practicals-activities",
    topicCodes: ["Lab.5"],
    language: "en",
    focus: "Class 11 practical exam and viva orientation",
    format: "revision",
    coverage:
      "English-titled practical and viva orientation for apparatus familiarity and exam communication; follow the current school record and project requirements.",
  },
  {
    videoId: "2_KrtHaqw-w",
    courseSlug: "cbse-physics-11",
    unitSlug: "practicals-activities",
    topicCodes: ["Lab.1"],
    language: "hi",
    focus: "Vernier calipers",
    format: "concept",
    coverage:
      "Hindi/Hinglish apparatus lesson on reading a vernier scale. Take measurements, determine zero correction and handle apparatus only under lab supervision.",
  },
  {
    videoId: "4nt6cYjJkzE",
    courseSlug: "cbse-physics-11",
    unitSlug: "practicals-activities",
    topicCodes: ["Lab.2"],
    language: "hi",
    focus: "Parallelogram law practical",
    format: "concept",
    coverage:
      "Hindi/Hinglish demonstration of one mechanics practical. It does not cover pendulum, friction, projectile or rolling-ball activities in the same cluster.",
  },
  {
    videoId: "50VYcOryCXo",
    courseSlug: "cbse-physics-11",
    unitSlug: "practicals-activities",
    topicCodes: ["Lab.3"],
    language: "hi",
    focus: "Young's modulus experiment",
    format: "concept",
    coverage:
      "Hindi MeitY OLabs demonstration of one elasticity experiment; fluids and thermal activities require separate supervised preparation.",
  },
  {
    videoId: "cfRbAfOCkR4",
    courseSlug: "cbse-physics-11",
    unitSlug: "practicals-activities",
    topicCodes: ["Lab.4"],
    language: "hi",
    focus: "Sonometer and resonance-tube calculations",
    format: "concept",
    coverage:
      "Hindi explanation of sonometer and resonance-tube calculations. Use it before supervised apparatus work; it is not a substitute for taking resonance readings.",
  },
  {
    videoId: "tbTjRlLIilo",
    courseSlug: "cbse-physics-11",
    unitSlug: "practicals-activities",
    topicCodes: ["Lab.5"],
    language: "hi",
    focus: "Practical file, exam and viva orientation",
    format: "revision",
    coverage:
      "Hindi/Hinglish orientation to the Class 11 practical file, experiment allocation and viva; follow current school record and project requirements.",
  },
  {
    videoId: "JTvzP7HrMxU",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.1", "Lab.6"],
    language: "en",
    focus: "Meter bridge and resistance of a wire",
    format: "concept",
    coverage:
      "MeitY OLabs demonstration of meter-bridge balance and resistance measurement, relevant to the electrical-measurement and resistivity clusters. Perform connections under supervision.",
  },
  {
    videoId: "pPQVH8s_UDU",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.2"],
    language: "en",
    focus: "Galvanometer to voltmeter conversion",
    format: "concept",
    coverage:
      "MeitY OLabs demonstration of one galvanometer-conversion activity; sonometer and transformer activities in this cluster need separate supervised practice.",
  },
  {
    videoId: "V6TaA1iLl9U",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.3"],
    language: "en",
    focus: "Convex-lens focal length graph",
    format: "concept",
    coverage:
      "English demonstration of finding convex-lens focal length from a u-v graph, representing one optics experiment in this cluster. Use supervised optical-bench alignment.",
  },
  {
    videoId: "h88jDycWFTk",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.4"],
    language: "en",
    focus: "Diode I-V characteristics",
    format: "concept",
    coverage:
      "MeitY OLabs diode-characteristics demonstration. Component identification, multimeter and LDR activities still require supervised hands-on practice.",
  },
  {
    videoId: "aQ0DLteewhM",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.5", "Lab.8"],
    language: "en",
    focus: "Practical exam and viva preparation",
    format: "revision",
    coverage:
      "English practical-exam guide for viva preparation and presentation. Verify file-completion, project and evaluation requirements with the current school instructions.",
  },
  {
    videoId: "IxjeH_svHak",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.7"],
    language: "en",
    focus: "Refractive index of a liquid",
    format: "concept",
    coverage:
      "English demonstration of a liquid refractive-index method using a lens and mirror, representing one auxiliary-optics activity. Perform alignment and readings under supervision.",
  },
  {
    videoId: "zHLqPRYQomY",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.2"],
    language: "hi",
    focus: "Galvanometer to voltmeter apparatus",
    format: "concept",
    coverage:
      "Hindi/Hinglish apparatus demonstration for galvanometer conversion. It does not cover the sonometer and transformer activities in the same cluster.",
  },
  {
    videoId: "Kk2Q6TM1JT8",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.3"],
    language: "hi",
    focus: "Concave-mirror focal length",
    format: "concept",
    coverage:
      "Hindi demonstration of one focal-length experiment in the optics cluster. Perform optical-bench alignment and readings under lab supervision.",
  },
  {
    videoId: "b3QY47NGwHw",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.4"],
    language: "hi",
    focus: "p-n junction diode practical viva",
    format: "revision",
    coverage:
      "Hindi/Hinglish viva preparation for the p-n junction diode experiment; circuit assembly, graph readings, components, multimeter and LDR work remain supervised tasks.",
  },
  {
    videoId: "StBdeErCQlc",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.5", "Lab.8"],
    language: "hi",
    focus: "Practical list, file and viva preparation",
    format: "revision",
    coverage:
      "Hindi/Hinglish overview of current practical experiments and viva preparation. Confirm file-completion, project and evaluation requirements with the school.",
  },
  {
    videoId: "lQFxbiQd6QE",
    courseSlug: "cbse-physics-12",
    unitSlug: "practicals-projects",
    topicCodes: ["Lab.7"],
    language: "hi",
    focus: "Concave-lens focal length using a convex lens",
    format: "concept",
    coverage:
      "Hindi demonstration of one auxiliary-lens experiment. Perform object, lens and screen alignment and readings only under lab supervision.",
  },
];
